### ISSUE TITLE
1-Pager (Better together story)

### ISSUE THREAD

**Issue by amyleeland** [kata-containers/runtime#1]
We need to add the differentiating features being contributed by each project to tell a better together story. 

Please add these features here- https://docs.google.com/a/intel.com/document/d/1RXfzgYWrN3SrI6pw_oazSWeHDfQTApY1VzQNdRZhUb0/edit?usp=sharing

**Comment by jellonek** [comment]
Sorry, but linked file requires additional rights.

**Comment by egernst** [comment]
@amyleeland this has been finished already; please reopen if I'm mistaken...

**Comment by kfox1111** [comment]
Nope. Still requires access.

**Comment by egernst** [comment]
@kfox1111 - see https://katacontainers.io/docs/kata-containers-1pager.pdf

**Comment by kfox1111** [comment]
Perfect. Thanks.
