### ISSUE TITLE
9P: doesn't support renameat2(2) syscall

### ISSUE THREAD

**Issue by eryugey** [kata-containers/runtime#1001]
# Description of problem
LTP test renameat20[12] failed as

```bash
# docker run -t --runtime=kata-runtime -v /opt:/opt --rm centos /opt/ltp/testcases/bin/renameat201
renameat201    1  TPASS  :  renameat2() returned the expected value: TEST_ERRNO=EEXIST(17): File exists
renameat201    2  TFAIL  :  renameat201.c:154: renameat2() failed unexpectedly: TEST_ERRNO=EINVAL(22): Invalid argument
renameat201    3  TPASS  :  renameat2() returned the expected value: TEST_ERRNO=ENOENT(2): No such file or directory
renameat201    4  TFAIL  :  renameat201.c:154: renameat2() failed unexpectedly: TEST_ERRNO=EINVAL(22): Invalid argument
renameat201    5  TPASS  :  renameat2() returned the expected value: TEST_ERRNO=EINVAL(22): Invalid argument
renameat201    6  TPASS  :  renameat2() returned the expected value: TEST_ERRNO=EINVAL(22): Invalid argument
# docker run -t --runtime=kata-runtime -v /opt:/opt --rm centos /opt/ltp/testcases/bin/renameat202
renameat202    1  TFAIL  :  renameat202.c:133: renameat2() failed unexpectedly: TEST_ERRNO=EINVAL(22): Invalid argument
```

And it turns out that currently 9P doesn't support renameat2(2) syscall, see v9fs_vfs_rename() in fs/9p/vfs_inode.c
```c
v9fs_vfs_rename(...)
{
...
        if (flags)
                return -EINVAL;
...
}
```
# Steps to reproduce
1. download & build LTP, assume it's installed to /opt/ltp here
2.  docker run -t --runtime=kata-runtime -v /opt:/opt --rm centos /opt/ltp/testcases/bin/renameat201
     docker run -t --runtime=kata-runtime -v /opt:/opt --rm centos /opt/ltp/testcases/bin/renameat202

# Expected result
9P supports renameat2(2) syscall and passes the test.

# Actual result
Test failed as described above.

# Additional info
The problem itself should be a 9P bug in the kernel, but I think it is an issue of the kata solution as a whole. So I open this issue to track it.

**Comment by sboeuf** [comment]
Hi @eryugey, thanks for your interest in Kata!
I can see that you're opening a bunch of issues all related to 9p. As you mentioned it in the __Additional info__ section, those are POSIX compatibility issues that are directly tied to 9p, and Kata is a simple user of that.
I don't think having one Github issue on Kata per compatibility issue is a bit too much. I think having a single issue listing all the compatibility issues makes more sense, and will help track this in a centralized place.
