### ISSUE TITLE
sudo make install fail

### ISSUE THREAD

**Issue by teawater** [kata-containers/runtime#1008]
sudo make install
INFO: yq was not found, installing it
make: /bin/yq: Command not found
golang.mk:20: *** "ERROR: cannot determine minimum golang version".  Stop.

**Comment by grahamwhaley** [comment]
hi @teawater This might be because your `GOPATH` is not set?
If so, we should check that it is (even though technically now `golang` itself does not need a `GOPATH` to be set), as we rely on the value of `GOPATH` in many of our files and scripts to build and test kata containers.

**Comment by jodh-intel** [comment]
Yep - I tend to install using the following (as do the CI scripts):

```sh
$  make clean && make && sudo -E PATH=$PATH make install
```
