### ISSUE TITLE
Create container failed when Guest OS boot slowly

### ISSUE THREAD

**Issue by BetaXOi** [kata-containers/runtime#1020]
# Description of problem
I got error message below when use my custom Qemu version
``` bash
$ docker run --rm --name test -ti alpine uname -a                
docker: Error response from daemon: oci runtime error: Failed to check if grpc server is working: rpc error: code = Unavailabl
e desc = transport is closing.
```
There is a similar issue #979, but i replace qemu instead of kernel.

It's easy to reproduce even use original qemu-lite:
- modify `kernel_params = "boot_delay=100"` in `configuration.toml`
- create container again

# Reason
The `runtime` does not wait Guest OS kernel prepare `agent.channel.0`(the frontend of virtserialport for kata-agent).
[the correct sequence](https://www.plantuml.com/plantuml/svg/pLTDRniX43sNNp5o3fLMsYZjqOgiA5RJGnF5IQHUeXxmxiH6jc7Digdpxmlx1GkiRULKJglvU0oFny3Ub8fALUssX7mjDumNLD8TBBIDPQoWN2redZE-WkzNnFflnQ6pVxiYP2aECFb55ONdYYksmma1FGgB0kzCganmHHb7MGRkal9SemHskaAk0ciXnU4ZiAu_2fJlh1IIO8Fc5BOmAM5PaursfaNZ76GzuQuAu_VQEepxMM6f9d1nprPhTRkjCCXvV25VmZdhbTLpGWr6o6iwysYQGYQHAdnfsBcJOZSN_8sj2CqKUzSUdrT2XWOuXJcAP5OHOjLL-n0cj8UnE-PbNwTfD1romHlISlHG7CCPwsmrD8LQqhyVxD9STRNV9i4Afis9BiYH5RJ3cY1DPw9MnHJkQSMpjT5D7zY3x5rhLu9XPAo6A2kHKleFCmEahnSIyp-pjg92eXOUGc8KTrcAR9FqyLnem2s-gTvYHf9OSIQ9vrhIRAFrwjYDUWsGLyLCQtwgPIsKwH3r2GafqSV2XNzywV9g6c23akDs4EAamiNTtQqU0_yGfX4P9FLQBhCrvHhlyYe9Kk9CdC683NcJMeb3QaOfEaM46SwUUzvnJxDojxdqLFOcA8r-CepJEcXCndFimFobx5FdfTFcZmDcbSAdXyMS5dJ9jamnB6CfvfWqEH9L9Jde7FrP5eANUF9GENMUSwR6EfVVN1ei1wVhCR7ErBQzGO-9DCncYxpuHN_NHJ86MVKjrcQ5nytUcTseBKq3Sw_1hf61jHsJIs4lrc55XZMtf2DzFYBkS5upt2cjshkwSqQtqLuNJTVr-SV5Q0MagEgs9N4_Q5pTY6vLjiPiSyOkXMINka4yunxc1k4vCkUfee_Lsymgp5PuL7LxCKfxT9FYCkrMuDxgxae-JSaOu7zBpVYJ9xpR0vHZhQEvpERs0UJd7djicJ2REZhxwtKQl1NzsE0PHcxqPkdVXty0)

[the incorrent sequence](https://www.plantuml.com/plantuml/svg/xLTDRniX43sNNu6SWwMLDabxj28hZTNqq4Hn4gcNg0UyEx6Hrx1csTJ-zuNzWWNMTfCUEwVLCFCOXiU3lIua4RBSP0YDYpLbEH5aW-VAHnEQ4oRd94qfM-8lbyYCt_1Tw_zyYT22x_3e1v44FvLCqWsC45QM6nJyHeLCE9E4CX25DrmGbYeKpq-MmAJdpGNVxJtlQf-3UAC55mXgDAkmkKxnongjrM2SruEzh4VOb7xyLddxSTzBAEG8dztHvKhUP2LuEG_Fw9C_PxMoQavSWI7q4a-TDarm8e18UAwxSoluPiRPArqYaaZwfaRSlYBKT-1Zc8D8UXK-LbMr2w53EnYpOqxsLHm7qt7AMTsq51mKot72EXiEJN15wP_tPcaskvfldM08q-G45sJH2ZTcN3YEfxnYnGJVaP8bAysRBh03sThUjWJTaQ4QWbq9bD9zw1bm_78c8FqrRIhA1IZY0OuquyuBdgoZBfvn1PZ1g-mysgB8a3EAdA45ITQAhvPVirS3ELLC5USdYjPSQeMeJeZV4dKiRFY7vpQlQWDUWs2GzKAiL7nsUtkZh3UkxM9iW6gQuQXQpNco8amXdbz6NbAu5oVqn8Iy2iN5VdC6c_Gtwx5stsdOy4ZT0LjckgPsBbne9YKGRh2TExweOWuTdj-4lklij3pzjeEabF1uFv-Hd2neHYM58fIYZqoT8q2MWc6LepwBdBC2ZXumgyvJpjUGYhb2KsDPEAtUX5IgaS2UtWJ4izua9txUtNk1Z5vMTQCrMVxHC_TdQvMd5ZFxIcn53HlV8SBavfBjLwIxPfTqGFC3zFRdrMPFQVZUrfrIaWLrBvYkwdCFZEOA5hoi94p0jYTYhGMtAbb1iZvXb_nc5qegdc2BPnhXAJ3diQ8FrTk9dDQQhygyrIWL8pI3a8RP6eWFQDsA57eYl01WZVwcU0_zIeA2M4DppHHd9rkgQ0koOXmaKQeQ8FZUyWpSD_-lYNznJPWEUzBLijf-zTdiVlSn6G9ixIF7vGDy3DBno9FOV_jvA8Ukavh3C_D0TdCFFSPrc4aTdFtbAlR-9TnOxvcEhjLcgT_BFm00)

Maybe we need add event notify for `kata-agent`, and `runtime` wait the event passively instead of send `CheckRequest` actively。

**Comment by devimc** [comment]
container managers (docker, k8s, etc) defines timeouts for each container operation (create, start, kill, etc) even if kata-runtime waits for ever to the kata-agent and it never finishes the container, the container manager will finish it because of timeouts.

**Comment by jodh-intel** [comment]
Yes, as we were saying on #979, I think it's important to understand why your custom setup is taking so long to boot - it suggests a problem somewhere.

**Comment by BetaXOi** [comment]
I think you do not get point.

The point is the frontend of virtserialport is not ready when send `grpc.CheckRequest` to backend.
The boot time of GuestOS is slower 1 second on my custom QEMU then QEMU-lite.

The reproducible method i gived is just to be used explain the issue easily, the boot time of GuestOS use my custom QEMU is actually quite short still.

**Comment by devimc** [comment]
@BetaXOi I understand your point, the problem I see with custom components (kernel, qemu, etc) is that we don't know what change was made, hence it's really hard for us to identify the real issue. The solution that I have in mind is to add a loop with delays in each iteration here https://github.com/kata-containers/runtime/blob/master/virtcontainers/kata_agent.go#L1362, but the solution that you propose sounds interesting, it would be nice if you could implement it and raise a pull request, I'd be glad to review it. what do you think?

**Comment by BetaXOi** [comment]
@devimc please help review PR #1047

**Comment by devimc** [comment]
@BetaXOi thanks, I'll take a look
