### ISSUE TITLE
cgroup name and path are not honoured

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#1021]
# Description of problem

cgroup name and path are not honoured causing problems in some implementations for resource governance, since they expect the cgroup in a specific directory, but kata-runtime creates it in `/sys/fs/cgroup/cpu,cpuacct/kata/$CONTAINERID/vcpu` , this issue was introduced here https://github.com/kata-containers/runtime/commit/34fe3b9d6d69d9fd7b1b5cfbc3c6fced7f17bc38

# Expected result
```
$ docker run --cpus=4 -dti --runtime=kata-runtime --cgroup-parent=hello debian bash
```

cpu cgroup path for this container should be `/sys/fs/cgroup/cpu,cpuacct/system.slice/docker.service/hello/$CONTAINERID`

# Actual result

```
$ docker run --cpus=4 -dti --runtime=kata-runtime --cgroup-parent=hello debian bash
```

`--cgroup-parent` option is not honoured and  cpu cgroup path is `/sys/fs/cgroup/cpu,cpuacct/kata/$CONTAINERID/vcpu`

cc @WeiZhang555 @egernst

**Comment by WeiZhang555** [comment]
@devimc This is a real issue. I mentioned some worries and a feasible(maybe) solution: https://github.com/kata-containers/runtime/pull/734#discussion_r224051455

For a POD, my suggestion is we honor ONLY the cgroup parent of first container of pod, in case containers in one POD has different cgroup parent(which is invalid).

e.g.

c1 has cgroups parent: mycontainer
c2 has cgroups parent: hello
c3 has cgroups parent: world
We only honor cgroupPath of c1 and ignores c2 and c3.

Final cgroup path:
/sys/fs/cgroup/cpu
|--mycontainer
     |--vcpu
     |--c1
     |--c2
     |--c3

Regards to this:

```
/sys/fs/cgroup/cpu,cpuacct/system.slice/docker.service/hello/$CONTAINERID
```

This part requires systemd cgroup support.

**Comment by mocolic** [comment]
Tested with this versions:
- sudo ./crictl --version crictl version  => 1.0.0-alpha
- kata-runtime version => 1.4.0

Service Fabric creates its own cgroup, pass the cgroup name to kata-runtime, while expecting that containers will be created under specified cgroup. This is breaking change for Service Fabric, resulting in Service Fabric resource governance not to work with kata 1.4.0 - where new _'kata'_ cgroup has been introduced. Service Fabric supports several container technologies and all of them are working in the same way (supporting the user specified cgroup), except for the Kata with this recent change.

**Comment by devimc** [comment]
@mocolic how did you pass the cgroup name to kata runtime?

**Comment by mocolic** [comment]
@devimc 
It is passed through CRI api, using set_cgroup_parent() function for LinuxPodSandboxConfig structure when starting pod sandbox.

**Comment by devimc** [comment]
@mocolic can you take a look to https://github.com/kata-containers/runtime/issues/1125?
does this solution work for you?
