### ISSUE TITLE
Bump kernel version to 4.19.20

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#1029]
We need to bump the kernel version now that the kernel config bumped from 4.14.x to 4.19.x

**Comment by jcvenegas** [comment]
@sboeuf this was reverted given we found some issues in the CI and not proper testing on PRs for the kernel, could you reopen a PR.
We expect this fail on 
- ARM CI ( @chavafg  seems that this is on runtime repo)
- Mertrics CI ( @grahamwhaley  for the boot time format change)

Even if this fail would be good to reopen the PR before the issues are fixed, so we can see that now the kernel is begin tested again.

**Comment by sboeuf** [comment]
@jcvenegas so you suggest I re-submit the same PR, but we tag it `do-not-merge` while both metrics and ARM CI are not fixed?
