### ISSUE TITLE
Update collect script for throttler

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#103]
Update https://github.com/kata-containers/runtime/blob/master/data/kata-collect-data.sh.in to also collect [throttler](https://github.com/kata-containers/ksm-throttler) details.

**Comment by gabibeyer** [comment]
Based on [6fc13e95](https://github.com/kata-containers/runtime/commit/6fc13e9548b6eea65175a47e01b937566bdc92f8), looks like this has been implemented and this issue can be closed

**Comment by amshinde** [comment]
Yes, we can close this.
