### ISSUE TITLE
Add support for firecracker in addition to QEMU as a supported hypervisor in Kata.

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1031]
# Add support for firecracker in addition to QEMU as a supported hypervisor in Kata.

This will require a few changes and additions to Kata components

## Runtime
 - [x] Making multiqueue optional for network interfaces  kata-containers/runtime#1027
- [ ]  Supporting gRPC based copy of files from host to VM - https://github.com/kata-containers/runtime/pull/1041
- [ ] actual implementation of the hypervisor interface (fc.go) https://github.com/kata-containers/runtime/pull/1044
- [ ] Adding support to boot from disk (vs nvdimm or initramfs)
- [ ] Adding support for virtio-mmio type devices https://github.com/kata-containers/runtime/pull/1045
- [ ]  Add hypervisor configuration table for Firecracker - https://github.com/kata-containers/runtime/issues/1042

## Kernel

- [x] Updating the Kata kernel configuration
   https://github.com/kata-containers/packaging/pull/272

## Packaging

- [ ] Packaging of the rootfs as a disk in a firecracker friendly format
       This is no longer needed. https://github.com/kata-containers/runtime/issues/1031#issuecomment-448295267
- [ ] Supporting a debug console over vsock (to aid debugging) 

## Agent

- [ ] Adding support for virtio-mmio type devices in the runtime https://github.com/kata-containers/agent/pull/437
- [ ] Supporting gRPC based copy of files from host to VM
   https://github.com/kata-containers/agent/pull/433

**Comment by WeiZhang555** [comment]
+1 !

**Comment by egernst** [comment]
@Weichen81 - this would be adding an additional hypervisor (firecracker) to Kata; we'd still keep and definitely maintain QEMU/NEMU support.  So, we'd remain compatible, and depending on the type of workload and infrastructure you're running on, you'd pick the appropriate hypervisor.

**Comment by Weichen81** [comment]
@egernst Hi Eric, I meant should we have firecracker_amd64.go and firecracker_aarch64.go at the same time in this issue, or we just start from firecracker_amd64.go first : )

**Comment by mcastelino** [comment]
Firecracker currently supports Intel CPUs, with planned AMD and Arm support. Once we have support for other architectures we should add them.

On Dec 17, 2018, at 8:58 PM, Wei Chen <notifications@github.com<mailto:notifications@github.com>> wrote:


@egernst<https://github.com/egernst> Hi Eric, I meant should we have firecracker_amd64.go and firecracker_aarch64.go at the same time in this issue, or we just start from firecracker_amd64.go first : )

**Comment by Pennyzct** [comment]
Very happy to offer any help when we have support for aarch64. ;)

**Comment by mcastelino** [comment]
> Packaging of the rootfs as a disk in a firecracker friendly format

This work item is no longer needed. The rootfs can be added as a regular block device. The root can be explicitly specified vs implicitly added by firecracker itself.

https://github.com/mcastelino/fireclient/blob/noroot/instance.go#L126

https://github.com/mcastelino/fireclient/blob/noroot/instance.go#L92

This will allow us to use the same "partitioned" rootfs we use in the case of NVDIMM.

This means we can use the same image for both cases. All we need is the updated agent that supports virtio-mmio.

/cc @sboeuf @egernst
