### ISSUE TITLE
vsock: Close vsock fd before returning context

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1053]
# Description of problem

The vsock fd opened when trying to find a free CID prevents firecracker from opening that vsock fd when launching the VM. QEMU can consume the vhost fd directly. By holding on to the vhost fd we prevent any race condition.

For firecracker we need to find a race free way to hold on to the CID without holding on to the vsock.

**Comment by mcastelino** [comment]
@bergwolf @devimc moving the conversation here from https://github.com/kata-containers/runtime/pull/1054 to the issue.

One way to fix this issue is for kata to have some sort of systemlevel lock when we manage CIDs.

i.e. if we hold on to the lock till the VM consumes the CID. 

The CID lookup code should wait on the system level lock before it allocates new CIDs.
The lock is taken by the runtime in the small window between the runtime closing the fd and the firecracker VMM latching on to the CID.

**Comment by devimc** [comment]
> One way to fix this issue is for kata to have some sort of systemlevel lock when we manage CIDs.

you won't see race conditions between kata-runtime processes, but there are  other processes running in the host (i.e xpra) that can request CIDs

**Comment by bergwolf** [comment]
@mcastelino Another way is to extend FC API to accept an fd option when configuring vsock. We can launch FC similar to how we launch qemu and pass the vsock vhost fd to it. Then we tell FC which vhost fd owns the cid and it can just reuse it instead of opening the vsock vhost device again.

Then the current workflow works for FC as well as QEMU.

**Comment by bergwolf** [comment]
> Another way is to extend FC API to accept an fd option when configuring vsock. 

@mcastelino Let's see how FC responds it -- https://github.com/firecracker-microvm/firecracker/issues/782
