### ISSUE TITLE
Documentation: Describe how to setup Kata with Firecracker support

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1067]
# Description of problem

Kata supports firecracker VMM. Add documentation on how to setup the system to support firecracker.

- [ ] Describe how to build firecracker with experimental vsock support (which is required for Kata)
Note: We will need to build firecracker till the released firecracker binary includes support for vsock
- [ ] Describe configuration.toml setup for firecracker
     - [ ] The Hypervisor stanza (firecracker binary and kernel)
     - [ ] vsock enable
     - [ ] tcFilter enable
- [ ] Ensure vsock kernel module is loaded
- [ ] Setup docker with device mapper graph driver
- [ ] Setup crio with device mapper graph driver
- [ ] Describe how to launch docker with runtime set to use firecracker
- [ ] Describe how to launch a Kubernetes pod with the runtime class feature set to use firecracker
- [ ] Document current limitations and feature gaps
       
Note: This issue itself will be used to generate the document and then moved into the main Kata documentation

**Comment by jodh-intel** [comment]
Related to https://github.com/kata-containers/tests/issues/1015, since the CI will need a `.ci/install_firecracker.sh` setup script.

**Comment by mcastelino** [comment]
Assuming all the binaries and artifacts that are firecracker related are stored at `/firecracker`. The artifacts include
- firecracker  (binary with built with vsock support
- kata-containers.img  (which has the updated agent with virtio-mmio support)
- kata-runtime  (with firecracker support)
- vmlinux (uncompressed kernel with virtio-mmio enabled)


# crio setup

Delta only. Where /dev/vdb needs to replaced by a free disk/partition available to you with size 10GB 

```
...
[crio]

storage_driver = "devicemapper"

storage_option = [
  "dm.basesize=8G",
  "dm.directlvm_device=/dev/vdb",
  "dm.directlvm_device_force=true",
  "dm.fs=ext4"
]

[crio.runtime.runtimes.katafire]
runtime_path="/firecracker/kata-runtime"
...

```

# Docker Setup  `/etc/docker/daemon.json`
```
{
  "storage-driver": "devicemapper",
  "runtimes": {
    "firecracker": {
      "path": "/firecracker/kata-runtime"
    }
  }
}
```

# Kata Setup `/etc/kata-containers/configuration.toml`

```
[hypervisor.firecracker]
path = "/firecracker/firecracker"
kernel = "/firecracker/vmlinux"
image = "/firecracker/kata-containers.img"
kernel_params = ""
default_vcpus = 1
default_memory = 4096
default_maxvcpus = 0
default_bridges = 1
block_device_driver = "virtio-mmio"
disable_block_device_use = false
enable_debug = true
use_vsock = true

..
[runtime]
internetworking_model="tcfilter"
```

# Simple Kubernetes POD definition

```
apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-pod
spec:
  runtimeClassName: katafire
  containers:
  - name: ubuntu
    image: "ubuntu:14.04"
    command: ["top"]
    stdin: true
    tty: true
```

**Comment by egernst** [comment]
Example documentation is currently at: https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support

I think we want a more formal version of this to be added to the documentation repository.

**Comment by mcastelino** [comment]
https://github.com/clearlinux/cloud-native-setup/issues/23

**Comment by asaintsever** [comment]
It seems trying to use devicemapper storage driver with cri-o 1.14.1 on **Minikube** does not work at all.

SSH into Minikube, then edit `/etc/crio/crio.conf`:

```
[crio]

storage_driver = "devicemapper"

storage_option = [
  "dm.basesize=8G",
  "dm.directlvm_device=/dev/vdb",
  "dm.directlvm_device_force=true",
  "dm.fs=ext4"
]
```

and restarting crio service (sudo systemctl restart crio) fails with error:
```
crio.service - Open Container Initiative Daemon
   Loaded: loaded (/usr/lib/systemd/system/crio.service; disabled; vendor preset: enabled)
   Active: failed (Result: exit-code) since Wed 2019-06-19 08:56:55 UTC; 9min ago
     Docs: https://github.com/kubernetes-sigs/cri-o
  Process: 9719 ExecStart=/usr/bin/crio $CRIO_OPTIONS $CRIO_MINIKUBE_OPTIONS (code=exited, status=1/FAILURE)
 Main PID: 9719 (code=exited, status=1/FAILURE)

Jun 19 08:56:55 minikube-crio-kata crio[9719]: time="2019-06-19 08:56:55.073907552Z" level=debug msg="found valid runtime 'kata-nemu' for runtime_path '/opt/kata/bin/kata-nemu'
Jun 19 08:56:55 minikube-crio-kata crio[9719]: "
Jun 19 08:56:55 minikube-crio-kata crio[9719]: time="2019-06-19 08:56:55.073917247Z" level=debug msg="found valid runtime 'kata-fc' for runtime_path '/opt/kata/bin/kata-fc'
Jun 19 08:56:55 minikube-crio-kata crio[9719]: "
Jun 19 08:56:55 minikube-crio-kata crio[9719]: time="2019-06-19 08:56:55.074168506Z" level=debug msg="[graphdriver] trying provided driver "devicemapper""
Jun 19 08:56:55 minikube-crio-kata crio[9719]: time="2019-06-19 08:56:55.074178698Z" level=error msg="Failed to GetDriver graph devicemapper /var/lib/containers/storage"
Jun 19 08:56:55 minikube-crio-kata crio[9719]: time="2019-06-19 08:56:55.074216694Z" level=fatal msg="failed to GetDriver graph devicemapper /var/lib/containers/storage: driver not supported"
Jun 19 08:56:55 minikube-crio-kata systemd[1]: crio.service: Main process exited, code=exited, status=1/FAILURE
Jun 19 08:56:55 minikube-crio-kata systemd[1]: crio.service: Failed with result 'exit-code'.
Jun 19 08:56:55 minikube-crio-kata systemd[1]: Failed to start Open Container Initiative Daemon.
```

**Comment by grahamwhaley** [comment]
@asaintsever - I don't think anybody has ever tried this under `minikube`. I presume you set up an available `/dev/vdb` under `minikube` for the crio storage to use?
I suspect this might be more of a minikube problem than a kata one. Maybe you can try setting up `minikube` with `crio` and a devicemapper storage *without* having kata in the loop, and see if that works?

**Comment by asaintsever** [comment]
@grahamwhaley thanks for your quick answer. Yes I do create a "fake" device (using part of this script: https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/setup_kata_firecracker.sh).
And yes, I only tried to make crio happy with devicemapper without involving kata, just modifying crio.conf and restarting crio service. So this is a Minikube or crio issue in the end, not a kata one for sure.
