### ISSUE TITLE
Why the kata TPS testing result so low? Any suggestion?

### ISSUE THREAD

**Issue by clarklee92** [kata-containers/runtime#1073]
# Testing result tables

env |   | CRI-Containerd(kata) | CRI-Containerd(runc) | docker
-- | -- | -- | -- | --
deploy ten nginx | time(seconds) | 27 | 23 | 10
one nginx pod | tps(Transactions Per Second) | 227.28 | 13149.24 | 13234.52
disk io | write | 36.1 MB/s | 41.9 MB/s | 41.1 MB/s
disk io |read | 39.7 MB/s | 41.9 MB/s | 41.9 MB/s
---
# Kata-runtime ENV
[Meta]
  Version = "1.0.19"

[Runtime]
  Debug = false
  DisableNewNetNs = false
  Path = "/usr/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.4.1"
    Commit = "45ea48e"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-lite-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = false
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.4.1_agent_3cf32a0a6b0.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.14.67.19-4.1.container"
  Parameters = ""

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.4.1-6553b83"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.4.1-6346110"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"

[Host]
  Kernel = "3.10.0-957.1.3.el7.x86_64"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "CentOS Linux"
    Version = "7"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) Gold 6148 CPU @ 2.40GHz"

[Netmon]
  Version = "kata-netmon version 1.4.1"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
# configuration.toml keeps default

**Comment by egernst** [comment]
What’s your storage driver?

Default config if nginx places index.html in the rootfs, which is slow if you use 9p.

**Comment by clarklee92** [comment]
I use overlay with `containerd`.  As I known, `containerd` didn't support "devicemapper", how could I solved this problem if  containerd used?

**Comment by lifupan** [comment]
How many vCPUs specified for kata? Is there any cpu limits for docker and runc?

**Comment by grahamwhaley** [comment]
Hi @clarklee92 - I suspect @egernst suggestion is the most likely, that the test page is being served up off of 9p. There is a related issue over at https://github.com/kata-containers/runtime/issues/551 which is worth a read I think. You may have to configure your container to serve the data up another way for the test.
Also, I think @lifupan question is relevant - how many vcpu's you give the container affects how many parallel network processing threads are generated on the host, so can also effect performance.

If you need more input, you will need to supply us details of which container you ran and how (command line, config file), and how you ran the test (`ab`, `hey` etc. and command line).

**Comment by clarklee92** [comment]
> Hi @clarklee92 - I suspect @egernst suggestion is the most likely, that the test page is being served up off of 9p. There is a related issue over at #551 which is worth a read I think. You may have to configure your container to serve the data up another way for the test.
> Also, I think @lifupan question is relevant - how many vcpu's you give the container affects how many parallel network processing threads are generated on the host, so can also effect performance.
> 
> If you need more input, you will need to supply us details of which container you ran and how (command line, config file), and how you ran the test (`ab`, `hey` etc. and command line).

Thank you very much, I read that #551 &c#717 and tried crio + devicemapper with `ab -c 10 -n 10000 <EXTERNAL-IP>` yesterday. The result becomes about five times better. 
9P cache is inconsiderable and `devicemapper` is unusable under `containerd`.  maybe we can only get the nginx container setup to move the index.html into a tmpfs/ramfs. That's really an uncomfortable solution. ~.~

**Comment by zhiminghufighting** [comment]
@egernst @grahamwhaley, is there a possible to located the container rootfs into a memory-backed file and use DAX to improve the file access in this case?
