### ISSUE TITLE
Kata can't handle the exception when qemu exit abnormally

### ISSUE THREAD

**Issue by zhiminghufighting** [kata-containers/runtime#1074]
# Description of problem

When qemu(or qemu-lite) exits abnormally or be forcedly killed after kata container is launched, 
1) if kata is launched by docker, the docker-containerd-shim will never exit as qemu(or qemu-lite) exit;
2)if kata is launched by k8s + cri-containerd, the docker-containerd-shim will never exit as qemu(or qemu-lite) exit;

comparison vs docker runc:
if a container is launched by docker runc and the container process is forcedly killed, docker-containerd-shim will exit as the container process exit;

# Expected result
docker-containerd-shim will exit as qemu(or qemu-lite) exit or qemu is  forced killed;

# Actual result
the docker-containerd-shim will never exit as qemu(or qemu-lite) exit or qemu is forcedly killed

---
This issue can be observed on every Linux environment whatever the OS version or hardware config or kata config;

**Comment by zhiminghufighting** [comment]
This issue is found by exception test scenario. Please confirm if it is an real issue or not and what's the right behavior vs docker runc under that extremely condition.

**Comment by egernst** [comment]
I think this is a bug, @zhiminghufighting.

To clarify, you can reproduce this with both shim and CLI impl of Kata?

**Comment by zhiminghufighting** [comment]
@egernst sorry to miss your info, it can be reproduced on kata 1.5/1.6 based on docker.
cmd : docker run --rm -ti -d centos
then kill qemu process and use 'ps' to show running process, you can see docker-containerd-shim still there. It should exit with qemu exit.
