### ISSUE TITLE
[Feature Request] Make Runtime support Kernel + Initrd VM configuration instead of requiring miniOS

### ISSUE THREAD

**Issue by sr229** [kata-containers/runtime#1087]
# Description of problem

Based from the documentation, you need a rootfs, kernel, and the agent. However, in a related work by HyperHQ, their runtime only requires initrd and the kernel - hence their immutable VM design. The init system also resides within the VM. All in all, this looks like this:

![image](https://trello-attachments.s3.amazonaws.com/554c998a4c9dacc5c143ec99/1083x635/c8748abc93dbc18e70f7a09d2963e8ff/hyper.png)

This usually results in a equally-functionable VM Kata Containers provides, albeit in a more economical fashion.

There is advantages of using just initrd and kernel:

- Size reduction: I'm not quite certain how large Kata is when installed, but in practice, a Hyper Containers package only costs about 12MB of space for the package itself excluding the installed package.

- We remove the requirement of an agent since the Docker daemon will control the lifecycle (via `kata-shim` and `kata-proxy`).

**Comment by gnawux** [comment]
Hi @sr229 

This is Xu from hyper.sh, and Thanks for mention our work. And we are now member of the Kata Containers project.

For Kata Containers

> Kata Containers supports both an initrd and rootfs based minimal guest image.

We could use the initrd image without a standalone rootfs in Kata.

And on

> We remove the requirement of an agent since the Docker daemon will control the lifecycle

Actually, the `kata-agent` may stand in the same position as `hyperstart`. The difference is the `kata-agent` is written in go with `libcontainer` imported.

**Comment by sr229** [comment]
Ah. Thanks for clarifying hyperstart. However, it seems the default distribution has the miniOS preincluded. I think a kernel + initrd combination would do for most cases since:

- Some people who wants to use Kata may have considered the package sizes. Hyper Containers maintained that 12MB size which allowed it to be used when storage is prime estate.

And regarding Kata supporting Kernel+Initrd:

- I think it wasn't stated clearly in the docs. It was worded that the three was worded as a requirement IMHO, might be a oversight from me.

That's my input for now.

**Comment by xiaoxubeii** [comment]
I think the doc is very clear:
https://github.com/kata-containers/documentation/blob/master/architecture.md#guest-image

```
Guest image
Kata Containers supports both an initrd and rootfs based minimal guest image.

Root filesystem image
The default packaged root filesystem image, sometimes referred to as the "mini O/S", is a highly optimized container bootstrap system based on Clear Linux. It provides an extremely minimal environment and has a highly optimized boot path.

The only services running in the context of the mini O/S are the init daemon (systemd) and the Agent. The real workload the user wishes to run is created using libcontainer, creating a container in the same manner that is done by runc.

For example, when docker run -ti ubuntu date is run:

The hypervisor will boot the mini-OS image using the guest kernel.
systemd, running inside the mini-OS context, will launch the kata-agent in the same context.
The agent will create a new confined context to run the specified command in (date in this example).
The agent will then execute the command (date in this example) inside this new context, first setting the root filesystem to the expected Ubuntu* root filesystem.
```

And I think you can also pack the extra binaries, such as init daemon and agent, which is hyperstart in HyperHQ, into initrd that named hyper-initrd.img. There are almost the same thing.

**Comment by sr229** [comment]
Can confirm its just a oversight from me, will mark this closed.
