### ISSUE TITLE
pass the kata conf file from env KATA_CONF_FILE

### ISSUE THREAD

**Issue by lifupan** [kata-containers/runtime#1091]
# Description of problem
we can pass a specific conf file using env KATA_CONF_FILE to shimv2 to select the proper hypervisor such as qemu or firecracker.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by caoruidong** [comment]
Maybe we have some options already. It will look /opt/kata first
