### ISSUE TITLE
Replace the resourceStorage implementation

### ISSUE THREAD

**Issue by sameo** [kata-containers/runtime#1099]
# Description of problem

The `resourceStorage` implementation is a wide spread dependency and prevents several key components (e.g. hypervisors) to be moved into their own package.

# Expected result

Create a new `store` package that provides a storage implementation for virtcontainers, with the following features:

- Simplicity: The API should be short and simple.
- Transparency: The core virtcontainers code should not care about
  the storage backend details.
- Extensibility: It should be easily extensible to add non local and in
  memory backends.

**Comment by jodh-intel** [comment]
Related to the following PRs:

- https://github.com/kata-containers/runtime/pull/883
- https://github.com/kata-containers/runtime/pull/874
