### ISSUE TITLE
Re-add bash completion script

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#110]
We should add https://github.com/clearcontainers/runtime/blob/master/data/completions/bash/runtime.in into this repo as `./data/completions/bash/runtime.in` with suitable adjustments.

**Comment by raravena80** [comment]
@jodh-intel looking at this. Are there any docs on how the cc bash completion works? Looks like this is run through a substitution in where the expressions in between @xxxx@ are substituted.

**Comment by jodh-intel** [comment]
Hi @raravena80 - you are right - in the latter days of Clear Containers we "built" the completions shell script. That change was made on https://github.com/clearcontainers/runtime/pull/933 to allow the CC runtime to be built for CC or for Kata.

However, that is now unnecessary complexity so something like the following (untested ;) might be sufficient for Kata:

```
$ go get -d github.com/clearcontainers/runtime
$ cd $GOPATH/src/github.com/clearcontainers/runtime
$ git show ae68143b6909cd99abcf0b7ce6b7dd7cf7f04b02:data/completions/bash/cc-runtime|sed 's/cc/kata/g'
```

Note that you'll need to add in the 1-line change to `main.go` to enable the bash completion flag in the runtime (see https://github.com/clearcontainers/runtime/pull/563).

**Comment by raravena80** [comment]
Thanks, @jodh-intel. Looks like it's already enabled here:  https://github.com/kata-containers/runtime/blob/dd2bf15ebc7691322117d79c7a004f01267aca13/cli/main.go#L338

Sounds like we just need to add the file.

**Comment by jodh-intel** [comment]
@raravena80 - nice! ;)

**Comment by raravena80** [comment]
Seems like this works. I'll go ahead and create a PR.

```
# source <file>
# kata-runtime <tab>
create      events      h           kata-check  kill        pause       resume      spec        state       version
delete      exec        help        kata-env    list        ps          run         start       update
```

@jodh-intel how does the file get sourced when you install the package?

**Comment by raravena80** [comment]
Oh, I see there's an install-completion target in the `Makefile`

**Comment by jodh-intel** [comment]
Right. Note that this will need to happen next: https://github.com/kata-containers/packaging/issues/59.
