### ISSUE TITLE
[RFC] Creating a new Kata repo and dockerhub organization for Kata with a sample Kata admission controller

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1102]
# Description of problem

## New Kata Example Webhook repo
Given that crio no longer has support for default workload trust (and containerd) never had the notion of default workload trust, an user will need to explicitly tag workloads with a runtime class for them to be deployed with Kata. This is something most users will not do (or for that matter should be able to choose).

A cluster operator normally defines policy based on RBAC and namespaces.

To show how Kata can be setup seamlessly by a cluster operator it makes sense to publish a simple policy implementation using an admission controller.

I am proposing we create a new repo under Kata containers with contents from the initial implementation from
https://github.com/mcastelino/kata-webhook

## New Kata Dockerhub organization

We should also create a dockerhub organization to publish the container image corresponding to this webhook.

This dockerhub organization can also host kata-deploy artifacts for example.

## Kata Admission controller webhook

Based on
https://github.com/clearlinux/cloud-native-setup/tree/master/clr-k8s-examples#running-kata-workloads

Implement a simple admission controller webhook to annotate pods with the kata runtime class.

### How to use the admission controller

```
docker build -t mcastelino/kubewebhook-pod-annotate-example:latest
./create_certs.sh
```

Note: The docker image location can be changed and the image needs to be
published if the webhook needs to work.

On a single machine cluster change the `imagePullPolicy` to use the locally 
built image.

### Making Kata the default runtime

Today in `crio.conf` runc is the default runtime when a user does not specify
`runtimeClass` in the pod spec. If you want to run a cluster where kata is used
by default, except for workloads we know for sure will not work with kata, use
the [admission webhook](https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#admission-webhooks)
and sample admission controller we created by running -

`kubectl apply -f deploy/`

The [admission webhook](deploy/webhook-registration.yaml)
is setup to exclude certian namespaces from being run with Kata using filters on namespace labels.

```yaml
    namespaceSelector:
      matchExpressions:
        -  {key: "kata", operator: NotIn, values: ["false"]}
```

The rook operators for example are marked as such

```yaml
apiVersion: v1
kind: Namespace
metadata:
  name: rook-ceph-system
  labels:
    kata: "false"
```

Pods not explicitly excluded by the namespace filter are dynamically tagged to
run with Kata with some [exceptions](https://github.com/mcastelino/kata-webhook/main.go#L25) -

* `hostNetwork: true`
* `rook-ceph` and `rook-ceph-system` namespaces (buggy)

Other pod properties will be added as exceptions in future.

**Comment by egernst** [comment]
“We should also create a dockerhub organization to publish the container image corresponding to this webhook.”

There is one today already: https://cloud.docker.com/u/katadocker/repository/list

**Comment by mcastelino** [comment]
@egernst this should also include supporting multiple runtime classes and picking firecracker based on namespace or other constraints.

**Comment by grahamwhaley** [comment]
I think we generally try not to blossom our repo count too much - is there a possibility to have a repo such as 'support files' or even 'kata-k8s' or similar, so we can use the repo for other related items in the future?

Question - is the docker hub free, or a paid or limited-volume service or? Just curious, and want to ensure we either don't run into any surprises later and/or ensure if it is paid the right group of folks own that...

**Comment by chavafg** [comment]
I agree we should have the admission controller somwhere inside the kata organization. 
I am currently working on enabling the k8s e2e tests and the admission controller is the way I plan to run them, so currently I am referencing to @mcastelino repo, but should be here. 
As @mcastelino said, this can be in a new repository or we can add it to the `tests` repository inside the `integration/kubernetes` directory. 

About the dockerhub org, who is the one we can contact to upload an image?

**Comment by mcastelino** [comment]
@grahamwhaley I will move this to the tests repo. Also we can make Dockerhub autobuild this container.

**Comment by chavafg** [comment]
@egernst I see a 404 when trying to get into `https://cloud.docker.com/u/katadocker`, maybe this is private?

**Comment by krsna1729** [comment]
@chavafg https://hub.docker.com/u/katadocker this is the public link

**Comment by chavafg** [comment]
@krsna1729 thanks

**Comment by grahamwhaley** [comment]
wrt to ownership of that dockerhub org - imo the details of that (login, password etc.) need to be lodged with the OSF and architecture committee - otherwise we need to debate having the kata project relying on something that would nominally be a little outside of its control...
