### ISSUE TITLE
CI to integrate with k8s e2e

### ISSUE THREAD

**Issue by wenlxie** [kata-containers/runtime#1108]
# Description of problem

Don't have CI job to have integration test with k8s

# Expected result

Have k8s e2e integration test  CI , so that every change should have been e2e tested

**Comment by grahamwhaley** [comment]
Hi @wenlxie . Indeed, having the k8s e2e tests running in the CI would be great.
Is that something you are offering to implement?
I happened to be looking at the e2e tests yesterday. I had a look at the docs for the [Ubuntu juju based runs](https://kubernetes.io/docs/getting-started-guides/ubuntu/validation/), but was then pointed to the [Heptio sonobouy](https://github.com/heptio/sonobuoy) code, that looks like it might be an easier way to run.

**Comment by egernst** [comment]
I think this would be a great candidate for a nightly?

**Comment by krsna1729** [comment]
/cc @mcastelino 
@grahamwhaley in order to run the sonobouy tests automatically in kata was one of the reasons we needed this IIRC https://github.com/mcastelino/kata-webhook

**Comment by mcastelino** [comment]
> @grahamwhaley in order to run the sonobouy tests automatically in kata was one of the reasons we needed this IIRC https://github.com/mcastelino/kata-webhook

We did run sonobuoy against kata using the admission controller, but ran into failures. This was a bit surprising given that we do run the same set as part of CRI-O e2e testing.

@sboeuf we do run e2e tests with kata+crio as part of CRI-O CI right?

**Comment by chavafg** [comment]
I remember that @gnawux mentioned that he was able to run the e2e tests successfully using vshim2. @gnawux do you have the steps to make the e2e tests work with kata?

**Comment by zhiminghufighting** [comment]
There are so much PRC key customers expecting the e2e test on k8s.
@egernst @gnawux, do we have the schedule for it?

**Comment by gnawux** [comment]
@chavafg yes, we did the node e2e conformance test set. 

@lifupan has the script here: https://github.com/lifupan/kata-benchmark/blob/master/scripts/kata-e2e-node-test.sh
