### ISSUE TITLE
Can I set the path of bios in the qemu using the kata-static-*.tar.xz

### ISSUE THREAD

**Issue by sofat1989** [kata-containers/runtime#1116]
# Description of problem

1. Change the configuration like this
```
-bash-4.2# cat /etc/kata-containers/configuration.toml
[hypervisor.qemu]
path = "/usr/local/kata/opt/kata/bin/qemu-system-x86_64"
kernel = "/usr/local/kata/opt/kata/share/kata-containers/vmlinuz.container"
image = "/usr/local/kata/opt/kata/share/kata-containers/kata-containers.img"
machine_type = "pc"
```
The whole opt directory is located in /usr/local/kata/

2. Create the pod to start a kata container
The error message:
```
Failed create pod sandbox: rpc error: code = Unknown desc = "/run/containerd/containerd.sock": rpc error: code = 2 desc = failed to start sandbox container: failed to create containerd task: OCI runtime create failed: qemu: could not load PC BIOS 'bios-256k.bin': unknown
```
3. I put the bios into /usr/share directory, the error still happened.
4. Put the all the kata-qemu directory in the dir /opt/kata/share/. The it works. 

Only putting the bios in the /opt/kata/share/kata-qemu will work

# Expected result
1. We can set the path via configuration

# Actual result
1. only /opt/kata/share/kata-qemu will work
---

extra  questions:
1. Why here is the path fixed to /opt/kata/share/kata-qemu. How can i change?

**Comment by devimc** [comment]
cc @egernst @mcastelino

**Comment by egernst** [comment]
Hi @sofat1989 - this is set within the build itself for QEMU to check in this path for the requisite binaries.  This static configuration was done to help facilitate an easy way to install the kata binaries in a cloud native way (ie, see https://github.com/kata-containers/packaging/tree/master/kata-deploy)

What distribution are you on?   You can always use the distro pacakges we have described here, [1], which will utilize more standard path.

[1] https://github.com/kata-containers/documentation/blob/master/install/

**Comment by sofat1989** [comment]
@egernst Thank you for your reply. We want to use the kata-static-* packages to install the kata binaries in a cloud-native way.  Just unzip the package and put the binary in one fixed location. It is not needed to install these packages when the host os image is building out. But for our images, directory `/` is read-only. So we hope all the packages can be found in /usr/local/kata/.  We are using v1.4.0. 

> this is set within the build itself for QEMU to check in this path for the requisite binaries. 
Could you tell how to change this set? We can try to build out the qemu which can read the bios in other location, for example, /usr/local/kata?
