### ISSUE TITLE
containerd-shim-v2: Use UnmarshalAny to properly retrieve resources

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#1130]
Here https://github.com/kata-containers/runtime/blob/master/containerd-shim-v2/service.go#L703-L706, we assume the type being unmarshalled has been serialized through JSON encoding, and also we assume it is of type `specs.LinuxResources`.
Instead, we should use `UnmarshalAny()` function from `github.com/containerd/typeurl` package, which is the right way to proceed on a type `protobuf.Any`.

**Comment by lifupan** [comment]
Hi @sboeuf, for the update request to kata shimv2, we are sure that this protobuf.Any is a json Marshaled specs.LinuxResources, so I think it's ok for this assume here.  Please see 
https://github.com/containerd/containerd/blob/96f306ee4cb2b3e881408658602c5d831995c7ad/task_opts.go#L205.

**Comment by sboeuf** [comment]
@lifupan I agree it's not a huge deal, but it would be cleaner not to take containerd implementation as reference here. Since the API uses a protobuf.Any, I think we should use `typeurl.UnmarshalAny()`.
You could imagine that CRI-O and containerd use different structures to define resources, and our implementation should be able to handle both IMO (even if that's not the case in practice).

**Comment by lifupan** [comment]
@sboeuf I agree it'll be much more clear to use typeurl.UnmarshalAny() here. I'll send a PR later to address it.

**Comment by sboeuf** [comment]
Great, and while you're at it, you should also fix the `Exec()` here: https://github.com/kata-containers/runtime/blob/master/containerd-shim-v2/exec.go#L74-L78
