### ISSUE TITLE
Copy Files: Allow all hypervisor implementations to support copyfiles

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1147]
# Description of problem

Today copy files feature is not visible to the user. The hypervisor registers this as a built in capability

https://github.com/kata-containers/runtime/pull/1041

It would be good to expose this as a user tuneable. This will allow an end user to setup a 9p free environment even with QEMU.

**Comment by devimc** [comment]
sounds like a good feature, but who is going to monitor changes in the files (therefore copy files again) :thinking:

**Comment by egernst** [comment]
I think if we document this well, it is reasonable to show this as a tradeoff of security versus functionality.
