### ISSUE TITLE
s390x: virtio-blk-ccw support

### ISSUE THREAD

**Issue by alicefr** [kata-containers/runtime#1153]
IBM Z uses ccw devices and the case for 'virtio-blk-ccw' with devicemapper doesn't properly work. It requires a special handling. That probably requires changes in govmm, the agent and the runtime. I saw from https://github.com/kata-containers/runtime/issues/1113 that you might plan to drop the 'virtio-blk'' option. Therefore, I don't know if it's worthy to implement this functionality. The option 'virtio-scsi' works.

**Comment by caoruidong** [comment]
Wrong `fixes` ...

**Comment by alicefr** [comment]
:) thanks to re-open it! @tuan-hoang1 is working on this part

**Comment by alicefr** [comment]
I extended kata to support virtio-blk-ccw devices for s390x. Differently to pci devices, ccw devices can be identified by the param `devno`(device_bus_id). The devices information during the hotplug are updated under'/sys/devices/css0/', and the disk name can be found under '/sys/bus/ccw/devices'
This requires several modifications:
- `govmm` add devno parameters and virtio-blk-ccw. 
- `agent`: add virtio-blk-ccw support.
- `runtime`
     - vendor the govmm modifications
     - abstract pci bridge variable as bridge to be able to add other bus type (like ccw)
     - add ccw bus type
     - add devno param
     - add virtio-blk-ccw 

There're several modifications to the code and I'm not sure how to split the various modification to ease the review. I was thinking to open 2 PRs:
1- with the abstraction of pcibridge and the support of ccw
2- addition of devno param and virtio-blk-ccw

**Comment by alicefr** [comment]
The vendoring of govmm can be done together with this PR https://github.com/kata-containers/runtime/pull/1843 or I'll do on top. I need in any case the updated signature for 2 functions

**Comment by alicefr** [comment]
Can I open a PR with the rest of my changes for the virtio-blk-ccw with the do-not-merge tag? I'd really appreciate any suggestion how to split it and also if you like my changes in the common code. Currently my code can be found [here](https://github.com/alicefr/runtime/tree/virtio-blk-ccw).

**Comment by alicefr** [comment]
hi, thanks to merging the agent part. Now, the missing part is the runtime. @jschintag and I we noticed today that you revendor govmm. The new version inlcuded the [devno support](https://github.com/intel/govmm/pull/99/commits/9cf98da0be6ba09161259910f9d9a4ec0428b476). However, the runtime part is missing and the qemu cmd line is broken (for s390x). It has an empty value for `devno`. Something like `qemu-system-s390x: -device virtio-serial-ccw,id=serial0,devno=`. So no wonder if now the runtime for s390x is not working properly. I've already prepared the code. But it's complicate because I extended the PCI bridge and this requires some code review.

**Comment by alicefr** [comment]
I'd suggest that I open a PR with the code with a dont-merge tag, is it ok for you?

**Comment by grahamwhaley** [comment]
@alicefr - opening a PR for just code review is fine - there is/should even be a RequestForComments(RFC) label/subject identifier to mark it as such, as well as DNM.
/cc @devimc @amshinde for the whole devnode/qemu side etc.

**Comment by alicefr** [comment]
thanks, we're going to open the PR in the next days
