### ISSUE TITLE
shimv2: optionally plug rootfs block storage instead of mounting it

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#1158]
containerd snapshotter is sending a slice of mounts to runtime to construct the rootfs. For kata, instead of mounting it on the host, if there is only one mount and it is a block storage, we can plug it to the guest directly. It would allow us to bypass 9pfs for container rootfs.

Ref: container rootfs mount structure
```go
type Mount struct {
        // Type defines the nature of the mount.
        Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
        // Source specifies the name of the mount. Depending on mount type, this
        // may be a volume name or a host path, or even ignored.
        Source string `protobuf:"bytes,2,opt,name=source,proto3" json:"source,omitempty"`
        // Target path in container
        Target string `protobuf:"bytes,3,opt,name=target,proto3" json:"target,omitempty"`
        // Options specifies zero or more fstab style mount options.
        Options []string `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
}
```

**Comment by bergwolf** [comment]
To properly support it, we need to change virtcontainers ContainerConfig to use `Mount` to describe a container rootfs.

**Comment by gnawux** [comment]
Yes, this what I discussed with @lifupan when we began the shimv2 development and stated in the KubeCon Seattle session. As the shimv2 patch set has been merged, we should move forward.

**Comment by sboeuf** [comment]
@bergwolf containerd makes the difference between mounts related to the rootfs versus regular mounts. We need to make sure we don't introduce any confusion with those mounts.
Also, what's the strategy regarding the behavior of virtcontainers? Are we still gonna use what's provided by the config.json for the rootfs?

One more comment, the way devicemapper is currently handled by the kata-runtime does not involve extra mounts, we use directly the device available on the rootfs path. But I agree it'd be nice to support both v1 and v2 properly.

**Comment by sameo** [comment]
@bergwolf Is the `Type` field the one differentiating the rootfs path from regular mounts?

**Comment by bergwolf** [comment]
@sameo `Type` is the file system type, ext4/xfs or bind etc. Rootfs is just another mountpoint for containers. The `mount` structure can be the same for rootfs path and regular mounts(volumes). What is different here for containerd snapshotters is rootfs can be a slice of mounts that runtime needs to mount one by one in order to construct the rootfs of a container.

Here we can optimize for a special case, -- when there is only one element in the rootfs mount slice, and that one is a block based volume.

**Comment by lifupan** [comment]
> Here we can optimize for a special case, -- when there is only one element in the rootfs mount slice, and that one is a block based volume.

Hi @bergwolf , is there a general logic to confirm that a mount is a block based volume?

**Comment by gnawux** [comment]
At least the `Options` field:

```
        // Options specifies zero or more fstab style mount options.
        Options []string `protobuf:"bytes,4,rep,name=options" json:"options,omitempty"`
```

will show how to mount the `Source`.

**Comment by bergwolf** [comment]
@lifupan We have at least two ways:
1. check the `Source` filed to see if it is a block device or a file volume
2. check the `Type` field to see if it a block file system type
