### ISSUE TITLE
kata+firecracker: boot of agent takes 3.5 seconds

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#1160]
Boot time to the Kata-Agent is around 3.5 seconds, per open-tracing  tracing output.

Taking a looking at the kernel boot, nothing is notable with respect to boot.  It seems that the latency is in userspace as we await for the gRPC server to come up and respond to kata-runtime on the host.

**Comment by jodh-intel** [comment]
It would be worth enabling full debug and looking to see when the agents `announce` message appears.

**Comment by egernst** [comment]
Manohar is betting money this is an entropy issue.  Need to find someone to confirm so he can collect his winnings.

/cc @mcastelino

**Comment by sboeuf** [comment]
@mcastelino if this is confirmed, what would be the plan to fix it? `virtio-rng` would need to be added to the FC device model, right?
