### ISSUE TITLE
Issues with release of Firecracker

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#1172]
Following the steps from https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support, after installing the static binaries from https://github.com/kata-containers/runtime/releases/download/1.5.0/kata-static-1.5.0-x86_64.tar.xz and then configuring docker and trying to run a container, I have the following error:
```
$ docker run -ti --runtime kata-fc busybox sh
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/2f3844afcb77f6b5a855dfdbb10303a6ddb7c444f46e055e1a1adb4edff59d27/log.json: no such file or directory): fork/exec /opt/kata/bin/kata-fc: no such file or directory: : unknown.
```
Here are the files at `/opt/kata/bin`
```
$ ls /opt/kata/bin/
containerd-shim-kata-v2  kata-collect-data.sh  kata-runtime  qemu-ga  qemu-pr-helper  qemu-system-x86_64  virtfs-proxy-helper
```
What exists is `kata-runtime` but not `kata-fc` so should we re-name the runtime?
Then what I try to do was re-name the runtime and try again to run a container but now I am getting the following error
```
$ docker run -ti --runtime kata-fc busybox sh
docker: Error response from daemon: OCI runtime create failed: Cannot find usable config file (config file "/etc/kata-containers/configuration.toml" unresolvable: file /etc/kata-containers/configuration.toml does not exist, config file "/opt/kata/share/defaults/kata-containers/configuration.toml" unresolvable: file /opt/kata/share/defaults/kata-containers/configuration.toml does not exist): unknown.
```
The configuration.toml that exists is `/opt/kata/share/defaults/kata-containers/configuration-fc.toml` which again my question this should be rename?
Then, I did the rename of the `configuration.toml` however I am getting this issue
```
docker: Error response from daemon: OCI runtime create failed: /opt/kata/share/defaults/kata-containers/configuration.toml: file /opt/kata/bin/firecracker does not exist: unknown.
```

**Comment by GabyCT** [comment]
@jcvenegas and @egernst as we want to enable a jenkins CI for firecracker, should we use `firecracker` binary from the tar?

**Comment by jcvenegas** [comment]
The configuration toml seems that is not there because the make install is broken in kata-runtime

**Comment by jcvenegas** [comment]
I fixed the tarball script until destdir work again.

**Comment by egernst** [comment]
@jcvenegas did we push a new tarballs?

This worked yester-morning I thought? I tested tues night...

**Comment by egernst** [comment]
I pushed 0.12 firecracker binary as well as the runtimes to be used (kata-fc, kata-qemu)

**Comment by GabyCT** [comment]
@jcvenegas and @egernst thanks for the changes, now I can see the `firecracker`, `kata-fc`, and `kata-qemu` binaries.
