### ISSUE TITLE
You got firecracker support, great, what about image repo for it ?

### ISSUE THREAD

**Issue by sokoow** [kata-containers/runtime#1176]
# Description of problem

Sorry for my ignorance here, but everybody keeps going on about how wonderful firecracker is. Fair play for implementing its support, but I think the whole solution is quite early and it's missing its killer feature - a firecracked image repo.

# Expected result

In a similar fashion like docker, it'd be really useful to have an image repository - that'd greatly improve portability and image building process. Are there any efforts to address this yet, even from anybody else ?

**Comment by grahamwhaley** [comment]
Hi @sokoow - thanks for raising the question.
/cc @egernst - from the Kata pov, afaik, you run existing OCI images (such as docker images from the docker hub) - so there is no real difference between an OCI image and an FC image - as long as the image doesn't try to use features that FC doesn't support. But, I think others will have a much better idea than me :-)

**Comment by mcastelino** [comment]
@sokoow you can run any docker image using firecracker + kata. You can do this via the docker CLI or use it within kubernetes.

For more detail
https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support

**Comment by mcastelino** [comment]
@sokoow yes there are limitations given the security profile and feature set current provided with firecracker. We have documented them in some detail here.
Note: No need for annotations. Just use the runtime class.

https://github.com/kata-containers/documentation/issues/351

If you have vagrant setup on your machine, you can try this to see how things come together
https://github.com/clearlinux/cloud-native-setup/tree/master/clr-k8s-examples

**Comment by egernst** [comment]
@sokoow dito to what Manohar and Graham already highlighted.  The beauty is that nothing changes, with respect to images.  Give it a try and let us know how it goes.  Keep in mind the (many) limitations that exist today for k8s+Firecracker

**Comment by mcastelino** [comment]
@sokoow closing this issue. Please reopen if the details provided were insufficient.
