### ISSUE TITLE
The virtcontainers network interface is not needed

### ISSUE THREAD

**Issue by sameo** [kata-containers/runtime#1179]
# Description of problem

The following network interface:

```Go
type network interface {
	// run runs a callback function in a specified network namespace.
	run(networkNSPath string, cb func() error) error

	// add adds all needed interfaces inside the network namespace.
	add(sandbox *Sandbox, hotplug bool) error

	// remove unbridges and deletes TAP interfaces. It also removes virtual network
	// interfaces and deletes the network namespace.
	remove(sandbox *Sandbox, hotunplug bool) error
}
```

is only implemented by the default network implementation and the noop one. The noop one is only there for testing purposes and at the same time there is no known need for another network model implementation.

# Expected result

Remove the network interface and only use what's currently the default network interface implementation.

**Comment by sameo** [comment]
cc @mcastelino @sboeuf @egernst @bergwolf

**Comment by sboeuf** [comment]
@sameo I'm not against the removal of the Go interface since, as you mentioned it, we're only using one single implementation. But I'm concerned about the unit tests, because the noop implementation is pretty convenient to test a bunch of code that would be complex to test if we had to mimic the real network behavior. WDYT?

**Comment by mcastelino** [comment]
> @sameo I'm not against the removal of the Go interface since, as you mentioned it, we're only using one single implementation. But I'm concerned about the unit tests, because the noop implementation is pretty convenient to test a bunch of code that would be complex to test if we had to mimic the real network behavior. WDYT?

@sboeuf could you not test it with the equivalent of net==none? With the noop you were actually not exercising any real code paths right. It was just there to satisfy the interface?

**Comment by sboeuf** [comment]
@mcastelino 
>@sboeuf could you not test it with the equivalent of net==none?

That's a good idea, and I didn't think about this as it's been introduced fairly recently. This might be enough for some cases.

>With the noop you were actually not exercising any real code paths right. It was just there to satisfy the interface?

Yes, exactly.

**Comment by egernst** [comment]
Great!  I think we should remove, no reason to have an interface in case, and we can fix the tests.

**Comment by sameo** [comment]
> What will this mean with respect to semantic versioning?

This is purely an internal interface, there is no reason to bump version for this kind of change.
