### ISSUE TITLE
Use minimal memory memory size between host and kata default memory

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#1182]
# Description of problem

Kata by default uses 2G for memory , when it is used on systems with less memory this fails with an error from qemu.

# Expected result

Detect the host system memory and just this before create container VM.

# Actual result

```
docker: Error response from daemon: OCI runtime create failed: qemu-system-x86_64: -m 2048M,slots=10,maxmem=1505M: invalid value of -m option maxmem: maximum memory size (0x5e100000) must be at least the initial memory size (0x80000000): unknown.
```
---
(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by jcvenegas** [comment]
\cc @krsna1729

**Comment by krsna1729** [comment]
This seems to be qemu specific since firecracker did not have any issues, when trying the wiki. If this can be confirmed by someone else too, we may want to document or open an issue to reconcile the behavior?
