### ISSUE TITLE
Ability to use prometheus node_exporter on the Kata VM

### ISSUE THREAD

**Issue by raravena80** [kata-containers/runtime#1183]
# Description of problem

Currently, running the node_exporter in a Kata container would probably not yield any metrics for the Kata VM since it's very minimal.   Some people may want to get some metrics about specific CPU, Mem usage of the Kata VM (Obviously, knowing that there's a performance penalty)

# Expected Result

Ability to export metrics using the node_exporter

# Actual result

We haven't tested it yet, but probably would not yield metrics since the Kata VM/Kernel footprint are minimal

---

More information on the Prometheus node_exporter: https://github.com/prometheus/node_exporter

**Comment by mcastelino** [comment]
@krsna1729 @ganeshmaharaj let us add it to https://github.com/clearlinux/cloud-native-setup That way we have test bed ready for this.

**Comment by krsna1729** [comment]
@mcastelino we already have node exported as part of kube-prometheus install today in our setup
https://github.com/clearlinux/cloud-native-setup/blob/master/clr-k8s-examples/4-kube-prometheus/node-exporter-daemonset.yaml

What I dont understand is why would we install it inside the kata VM? I though they need look and feel like containers.

**Comment by raravena80** [comment]
@krsna1729 yes, that's the idea to feel like containers, but I think it's more about 'optionally' gathering metrics.
