### ISSUE TITLE
Question: Running all containers in a single sandbox with docker

### ISSUE THREAD

**Issue by dcflachs** [kata-containers/runtime#1196]
I am aware from the documentation and #390 that due to Docker's lack of the Pod abstraction all containers launched with Kata are launched in their own sandbox VM. I am also aware of the effort to upstream changes to docker to allow the possibility. What i am wondering is if in the interim an alternative might be possible for my use case, and where would be the place to begin for developing such? Specifically I have a use case where I would like to have multiple containers running in a single VM/POD/Sandbox but i need only a single sandbox per host. Essentially i have the need to provide strong isolation for a single group of containers from the rest of the containers on a system. My thought was that it might be possible to modify the kata runtime such that the container level abstractions in docker aligned with those in kata and hardcode a single sandbox instance for all containers launched with the runtime. Does anyone have any thoughts on this idea and if/where I might begin to approach it?

**Comment by caoruidong** [comment]
Kata is a runtime component. It gets information only fro config.json. Which field do you want to use?

**Comment by caoruidong** [comment]
I think you can try and modify https://github.com/moby/moby/pull/37262 metioned in #390 first. Kata now can get from annotations in spec and deal with it well. So I think it's better to add a patch in upper component like docker and containerd than kata itself.
