### ISSUE TITLE
Not able to disable network with firecracker

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#1197]
It is not possible to run a container with the flag of `--net=none` using Firecracker. To do this at the `configuration.toml` we modify the `disable_new_netns=true` and `internetworking_model=none`.

**Comment by GabyCT** [comment]
The test that we ran is https://github.com/kata-containers/tests/blob/master/integration/network/disable_net/net_none.bats

**Comment by mcastelino** [comment]
@GabyCT --net=none is different from disable_net_netns=true + model=none

Normal --net=none should work with tcfilter model. Is it not working.

**Comment by GabyCT** [comment]
@mcastelino , sorry if I do not explain well. These are the scenarios where it is failing
1. We are setting `disable_new_netns=false` and  then we run a container with no network `docker run -d ... --net=none ...` then we check the namespaces of host init daemon with no  network and then we check the namespaces of the processes and we compare the namespace of host init daemon that
should not be equal to namespace of the process. Currently this scenario is failing.
