### ISSUE TITLE
Move runV docs/readme to kata-containers/runtime

### ISSUE THREAD

**Issue by navidshaikh** [kata-containers/runtime#12]
Presently there is no landing readme/document at https://github.com/kata-containers/runtime/ , how about moving readme from runV [page](https://github.com/hyperhq/runv/blob/299f4e6493050173c0bd30a48fde31b3a34b0f24/README.md) ?

**Comment by sameo** [comment]
@navidshaikh I'd prefer if we have a Kata specific readme, and this is what we'll have once we have `cc-runtime` as a submodule there.

**Comment by egernst** [comment]
Hey @navidshaikh, I think we can close this, based on sameo's feedback.  Please reopen if you  feel I'm mistaken!
