### ISSUE TITLE
expect ip a to show link in up state

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#1201]
When executing sudo docker run --runtime=kata-runtime alpine sh -c " ip a", I would expect to see the link state to be up. This is not the case. If you add a sleep 1 before executing ip a, ex: sudo docker run --runtime=kata-runtime alpine sh -c " sleep 1; ip a", the link is up as expected. Similarly, if I start an interactive terminal for a clear container, the link is in up state as expected.

Original issue, which can still be reproduced:
https://github.com/clearcontainers/runtime/issues/885

**Comment by egernst** [comment]
@mcastelino @sboeuf @amshinde - FYI - this is still an issue...

**Comment by caoruidong** [comment]
I can't fully understand this issue and reproduce it.

**Comment by jodh-intel** [comment]
Edited description ( s/cc-runtime/kata-runtime/ ;)

**Comment by amshinde** [comment]
Taking another look at this.

**Comment by amshinde** [comment]
@egernst This does not really break anything, so closing this.
