### ISSUE TITLE
fc: does not show fc version in kata-env if not `root`

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#1207]
# Description of problem

Running `/opt/kata/bin/kata-fc kata-env` as non-root fails to extract the `firecracker` version info. You get `<<unknown>>` in the Hypervisor.Version entry.

# Expected result

It would be nice if you got the `fc` version - which on my system is `0.12.0`.

The root issue (pun intended) is I think that `/opt/kata/bin/firecracker` is root owned and only user executable - so, as a normal user `kata-fc` cannot run `firecracker` to extract the info.

I'm also guessing that is a deliberate `firecracker` security model decision.

So, maybe we cannot do anything about this, as I doubt we will try a `sudo` from inside `kata-env`. But, let's detail it here and discuss at least.

(this was using the 1.5.0 static tarball installation btw).

**Comment by jodh-intel** [comment]
Could you paste the `ls -l` here? Also, if we're packaging this, did we change any defaults ourselves to make this more restrictive?

Seems pretty amazing to me that you aren't even allowed to run `--version` though ;(

**Comment by grahamwhaley** [comment]
Sure - would have done originally, but was on different machine ;-)

```bash
$ ls -la /opt/kata/bin
total 82832
drwxr-xr-x 2 gwhaley gwhaley      226 Jan 25 00:19 .
drwxr-xr-x 6 gwhaley gwhaley       56 Dec  4 18:42 ..
-rwxr-xr-x 1 gwhaley gwhaley 27312544 Jan 25 00:18 containerd-shim-kata-v2
-rwxr--r-- 1 root    root     6195952 Jan 25 00:19 firecracker
-rwxr-xr-x 1 gwhaley gwhaley    13600 Jan 25 00:18 kata-collect-data.sh
-rwxr-xr-x 1 root    root         121 Jan 25 00:19 kata-fc
-rwxr-xr-x 1 root    root         123 Jan 25 00:19 kata-qemu
-rwxr-xr-x 1 gwhaley gwhaley 32989896 Jan 25 00:18 kata-runtime
-rwxr-xr-x 1 gwhaley gwhaley  2177024 Dec  4 18:42 qemu-ga
-rwxr-xr-x 1 gwhaley gwhaley  2278248 Dec  4 18:42 qemu-pr-helper
-rwxr-xr-x 1 gwhaley gwhaley 12297952 Dec  4 18:42 qemu-system-x86_64
-rwxr-xr-x 1 gwhaley gwhaley  1527704 Dec  4 18:42 virtfs-proxy-helper

$ /opt/kata/bin/firecracker -V
-bash: /opt/kata/bin/firecracker: Permission denied
$ sudo /opt/kata/bin/firecracker -V
firecracker 0.12.0


$ /opt/kata/bin/kata-fc kata-env
...
[Hypervisor]
  MachineType = ""
  Version = "<<unknown>>"
  Path = "/opt/kata/bin/firecracker"

$ sudo /opt/kata/bin/kata-fc kata-env
...
[Hypervisor]
  MachineType = ""
  Version = "firecracker 0.12.0"
  Path = "/opt/kata/bin/firecracker"
```
