### ISSUE TITLE
sandbox creation fails when enable_hugepages = true

### ISSUE THREAD

**Issue by mythi** [kata-containers/runtime#1210]
# Description of problem

pod creation fails after ```kata-runtime``` is configured with

```$ sudo sed -i -e 's/^# *\(enable_hugepages\).*=.*$/\1 = true/g' /usr/share/defaults/kata-containers/configuration.toml```

# Expected result

the sandbox is created with hugepages enabled

# Actual result

An error occurs:

```
  Warning  FailedCreatePodSandBox  8s (x2 over 20s)  kubelet, r630-6    Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: OCI runtime create failed: qemu-lite-system-x86_64: -object memory-backend-file,id=dimm1,size=2048M,mem-path=/dev/hugepages,share=on,prealloc=on: unable to map backing store for guest RAM: Cannot allocate memory: unknown
```

---

kata-runtime 1.3.0, containerd 1.2.0

```
Output of "`rpm -qa|egrep "(cc-oci-runtimecc-runtimerunv|kata-proxy|kata-runtime|kata-shim|kata-ksm-throttler|kata-containers-image|linux-container|qemu-)"`":
qemu-vanilla-data-2.11.2+git.0982a56a55-12.1.x86_64
kata-runtime-1.3.0+git.a786643-14.1.x86_64
kata-ksm-throttler-1.3.0.git+6e903fb-11.1.x86_64
kata-containers-image-1.3.0-9.1.x86_64
kata-shim-bin-1.3.0+git.5fbf1f0-8.1.x86_64
kata-shim-1.3.0+git.5fbf1f0-8.1.x86_64
qemu-vanilla-2.11.2+git.0982a56a55-12.1.x86_64
kata-proxy-bin-1.3.0+git.6ddb006-9.1.x86_64
kata-proxy-1.3.0+git.6ddb006-9.1.x86_64
qemu-lite-bin-2.11.0+git.f886228056-12.1.x86_64
kata-linux-container-4.14.67.12-10.1.x86_64
qemu-vanilla-bin-2.11.2+git.0982a56a55-12.1.x86_64
qemu-lite-data-2.11.0+git.f886228056-12.1.x86_64
qemu-lite-2.11.0+git.f886228056-12.1.x86_64

mylinen@r630-6:~> grep -i Huge /proc/meminfo
AnonHugePages:    395264 kB
ShmemHugePages:        0 kB
HugePages_Total:     512
HugePages_Free:      512
HugePages_Rsvd:        0
HugePages_Surp:        0
Hugepagesize:       2048 kB
mylinen@r630-6:~> mount|grep -i huge
cgroup on /sys/fs/cgroup/hugetlb type cgroup (rw,nosuid,nodev,noexec,relatime,hugetlb)
hugetlbfs on /dev/hugepages type hugetlbfs (rw,relatime)

```

**Comment by jodh-intel** [comment]
Thanks for raising @mythi! I can confirm this behaviour.

Feature was added in Clear Containers under https://github.com/clearcontainers/runtime/pull/627.

I've raised a test issue so we can add tests to avoid breaking this again once we've fixed it:

- https://github.com/kata-containers/tests/issues/1128

/cc @mcastelino.

**Comment by mythi** [comment]
@jodh-intel I have it working and it sort of was a config issue on my side.

```enable_hugepages``` takes all of VM memory from hosts hugepages. By default the VM mem size is 2048M which means the host needs 2048/```Hugepagesize``` amount of ```HugePages_Free```.

With, e.g., ```sudo sysctl -w vm.nr_hugepages=4096``` I get to run my pods.

**Comment by jodh-intel** [comment]
Great news @mythi! We should capture this in the userguide, so I've added a label to remind us to update https://github.com/kata-containers/documentation/wiki/UserGuide (feel free to do that if you wish ;)
