### ISSUE TITLE
Firecracker docker integration tests failing

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#1221]
We know that we have some limitations right now with Firecracker, however, here it is the list of all the docker integration tests that are not working properly
https://github.com/kata-containers/tests/blob/master/.ci/hypervisors/firecracker/configuration_firecracker.yaml

**Comment by teawater** [comment]
Does this issue have relation with jenkins-ci-ubuntu-16-04-firecracker fail in these 2 prs?

**Comment by GabyCT** [comment]
@teawater right now the CI of firecracker is not working https://github.com/kata-containers/runtime/issues/1222
