### ISSUE TITLE
Add hypervisor package

### ISSUE THREAD

**Issue by sameo** [kata-containers/runtime#1229]
# Description of problem

In order to simplify and make the virtcontainers logic more logically separated (#1059), we want to move the hypervisor specific code into its own package. The end goal is to keep only the pure virtcontainers logic under the virtcontainers package.

**Comment by egernst** [comment]
Adding needs help label -- could use someone else in community to help drive this forward.

**Comment by Zyqsempai** [comment]
I can help with that, if it's still actual.

**Comment by devimc** [comment]
@Zyqsempai yes please
