### ISSUE TITLE
Devicemapper storage with no /rootfs prefix

### ISSUE THREAD

**Issue by linxiulei** [kata-containers/runtime#1248]
# Description of problem

Now, kata-runtime respects docker implement that a block device to store image contents has a 'rootfs' prefix within FS. However, containerd's new coming devicemapper implement may not do it that way. See https://github.com/containerd/containerd/pull/3022

It's time to consider how kata to use block based image and still got a way compatible with docker  (eventually, docker would adopt containerd completely https://github.com/moby/moby/pull/38738#pullrequestreview-204497769)

**Comment by bergwolf** [comment]
On kata side, we can implement kata shimv2 to handle block based image better by insert it as a block device to the guest.

For block based image + docker, we need to push docker(moby) to adopt containerd shimv2.

**Comment by mcastelino** [comment]
@linxiulei This is actually a bug in Kata which made an assumption. We will break this
https://github.com/kata-containers/runtime/issues/1248

**Comment by mcastelino** [comment]
/cc @ganeshmaharaj @egernst @amshinde @sboeuf @bergwolf 

With this change we can support all variants of graph drivers and snapshotters.

We should also make one more change longer term

https://github.com/kata-containers/runtime/blob/master/containerd-shim-v2/service.go#L327

This always mounts the block device on the host even though in the case of Kata this is no longer desired. In the case of block based snapshotters we should skip mounting on the hostside. This will be safer even though we may break some docker functionality.
