### ISSUE TITLE
containerd-shim-v2: new shim comes

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#1273]
Hey, maintainers. Containerd support a new kind shim v2, `io.containerd.runc.v2` which support one shim to control multiple containers, here is a simple graph
```
                                         | ----- kata-container
containerd-shim-kata -----|----- kata-container
                                         |----- kata-container
```
details in https://github.com/containerd/containerd/pull/3004, /cc @lifupan , would you like to check if it suit for kata container, if this issue got repeated, just close it.

**Comment by lifupan** [comment]
Hi @Ace-Tang, I had noticed that, and I think for runc, that's a good  feature which can group the containers in the same pod into one runc-shim,  actually for kata-shimv2, it  had already supported this at birth, and all of the containers in the same pod share the same kata-shimv2.

**Comment by Ace-Tang** [comment]
Oh, Good to know that
