### ISSUE TITLE
add support for intelRDT at pod granularity

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#1275]
The OCI runtime spec includes an optional field for intelRDT support, see [1].

While this is specified on a container granularity, in the case of orchestrators that utilize a pod concept, without virtualized RDT support, the restrictions would only be feasible at a pod granularity.

As a first step, we should add support for intelRDT at a pod granularity.  Based on this, we would constrain the hypervisor itself, so this should b applicable to all hypervisor configurations of Kata Containers.

[1] - https://github.com/opencontainers/runtime-spec/blob/1722abf79c2f8f2675f47367f827c6491472cf27/config-linux.md#intelrdt

**Comment by sboeuf** [comment]
That sounds good and feasible. It would be very similar to the way we handle cgroups today, since we would need to make sure that we apply an RDT superset to the hypervisor, based on the union of all RDT info from every container of this same pod.
