### ISSUE TITLE
Cannot run kata-container with containerd and kubenetes

### ISSUE THREAD

**Issue by jimmyshen007** [kata-containers/runtime#1276]
Hi experts,

I am keep getting the following error so that kubelet cannot start up.
the main cause is "Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
F". Thanks in advance for your help.

kubenetes: 1.13.3
kata-container: 1.5
cri-containerd: 1.24

:40:08.066990 2760 server.go:407] Version: v1.13.3
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.067201 2760 plugins.go:103] No cloud provider specified.
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.069600 2760 certificate_store.go:130] Loading cert/key pair from "/var/lib/kubelet/pki/kubelet-client-current.pem".
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.074563 2760 server.go:666] --cgroups-per-qos enabled, but --cgroup-root was not specified. defaulting to /
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.074814 2760 container_manager_linux.go:248] container manager verified user specified cgroup-root exists: []
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.074838 2760 container_manager_linux.go:253] Creating Container Manager object based on Node Config: {RuntimeCgroupsName: SystemCgroupsName: KubeletCgroupsName: ContainerRuntime:remote CgroupsPerQO
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.074956 2760 container_manager_linux.go:272] Creating device plugin manager: true
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.074988 2760 state_mem.go:36] [cpumanager] initializing new in-memory state store
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.075104 2760 state_mem.go:84] [cpumanager] updated default cpuset: ""
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.075115 2760 state_mem.go:92] [cpumanager] updated cpuset assignments: "map[]"
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.075201 2760 kubelet.go:281] Adding pod path: /etc/kubernetes/manifests
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: I0224 14:40:08.075224 2760 kubelet.go:306] Watching apiserver
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: E0224 14:40:08.094351 2760 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:444: Failed to list *v1.Service: Get https://172.31.54.125:6443/api/v1/services?limit=500&resourceVersion=0: dial tcp 172.31.
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: E0224 14:40:08.094755 2760 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/kubelet.go:453: Failed to list *v1.Node: Get https://172.31.54.125:6443/api/v1/nodes?fieldSelector=metadata.name%3Dizj6cfbzerrv6p79qpdzs
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: E0224 14:40:08.095345 2760 reflector.go:134] k8s.io/kubernetes/pkg/kubelet/config/apiserver.go:47: Failed to list *v1.Pod: Get https://172.31.54.125:6443/api/v1/pods?fieldSelector=spec.nodeName%3Dizj6cfbzerrv6p7
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: W0224 14:40:08.095648 2760 util_unix.go:77] Using "/run/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/containerd/containerd.sock".
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: W0224 14:40:08.095706 2760 util_unix.go:77] Using "/run/containerd/containerd.sock" as endpoint is deprecated, please consider using full url format "unix:///run/containerd/containerd.sock".
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: E0224 14:40:08.096846 2760 remote_runtime.go:72] Version from runtime service failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: E0224 14:40:08.096910 2760 kuberuntime_manager.go:184] Get runtime version failed: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService
Feb 24 14:40:08 iZj6cfbzerrv6p79qpdzsaZ kubelet[2760]: F0224 14:40:08.096929 2760 server.go:261] failed to run Kubelet: failed to create kubelet: rpc error: code = Unimplemented desc = unknown service runtime.v1alpha2.RuntimeService

**Comment by egernst** [comment]
can you share your containerd configuration and how you are starting the cluster?

**Comment by jimmyshen007** [comment]
@egernst Thanks! I first tried 

```
disabled_plugins = ["cri"]
[plugins]
  [plugins.cri]
    [plugins.cri.containerd]
      no_pivot = false
    [plugins.cri.containerd.runtimes]
      [plugins.cri.containerd.runtimes.runc]
         runtime_type = "io.containerd.runc.v1"
         [plugins.cri.containerd.runtimes.runc.options]
           NoPivotRoot = false
           NoNewKeyring = false
           ShimCgroup = ""
           IoUid = 0
           IoGid = 0
           BinaryName = "runc"
           Root = ""
           CriuPath = ""
           SystemdCgroup = false
      [plugins.cri.containerd.runtimes.kata]
         runtime_type = "io.containerd.kata.v2"
      [plugins.cri.containerd.runtimes.katacli]
         runtime_type = "io.containerd.runc.v1"
         [plugins.cri.containerd.runtimes.katacli.options]
           NoPivotRoot = false
           NoNewKeyring = false
           ShimCgroup = ""
           IoUid = 0
           IoGid = 0
           BinaryName = "/usr/bin/kata-runtime"
           Root = ""
           CriuPath = ""
           SystemdCgroup = false
      [plugins.cri.containerd.default_runtime]
        runtime_type = "io.containerd.kata.v2"
      [plugins.cri.cni]
        # conf_dir is the directory in which the admin places a CNI conf.
        conf_dir = "/etc/cni/net.d"
```

Then:
```
disabled_plugins = ["cri"]
[plugins]
  [plugins.cri]
    [plugins.cri.containerd]
    [plugins.cri.containerd.default_runtime]
      runtime_type = "io.containerd.runtime.v1.linux"
      runtime_engine = "/usr/bin/kata-runtime"      
    [plugins.cri.containerd.untrusted_workload_runtime]
         runtime_type = "io.containerd.kata.v2"
    [plugins.cri.cni]
      # conf_dir is the directory in which the admin places a CNI conf.
      conf_dir = "/etc/cni/net.d"
```

In both cases, containerd was running ok. It is just the kubelet service always showing the error as in the last thread.

My OS is Debian 9.2 64bit. I tried:
 \# systemctl daemon-reload
 \# systemctl restart kubelet

I saw the same warning appeared when I init kubernetes:
\# sudo kubeadm init --ignore-preflight-errors --cri-socket /run/containerd/containerd.sock --pod-network-cidr=10.244.0.0/16

**Comment by jodh-intel** [comment]
Aside: @egernst, @chavafg - it sounds like we might need to improve the data collection performed by https://github.com/kata-containers/runtime/blob/master/data/kata-collect-data.sh.in to help understand issues like this maybe? If so, feel free to PR changes as you guys are prolly best placed for these sorts of updates.
