### ISSUE TITLE
unit-tests: add tests for resource requests for pods

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#1296]
We had an issue where vCPUs weren't being accounted correctly, [1].  I noticed we don't have unit tests -- let's make sure we add some to cover the potential scenarios!

[1] - https://github.com/kata-containers/runtime/issues/1292

**Comment by grahamwhaley** [comment]
I've assigned to @devimc , who I think has the most history and knowledge of that bit of code etc.
