### ISSUE TITLE
memory footprint increase ~30 MB

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#1302]
# Description of problem

### Kernel 4.14.x

Rootfs image: 184.5 MB
initrd image: 161 MB

### Kernel 4.19.x

Rootfs image: 216 MB
initrd image: 164 MB

This increment was introduced in the version 4.16, the last kernel version with a "normal" memory footprint was 4.15.18

**Comment by grahamwhaley** [comment]
I'm guessing directly related to what we saw when we landed the 4.19.2x update. See [this comment](https://github.com/kata-containers/runtime/pull/1111#issuecomment-454365193) for some measures way back when we started that update cycle on metrics changes.
Good luck if you are hunting this - and do update here, as that might fold back into the pending [kernel fragment PR](https://github.com/kata-containers/packaging/pull/314)

**Comment by egernst** [comment]
@devimc I know you've been spending some time looking at changes in DAX support when migrating to 4.19.  I'm assigning this to you (and if you can dump the latest status/findings it may be helpful for others). Let me know if this doesn't make sense.

**Comment by devimc** [comment]
see https://github.com/kata-containers/packaging/issues/378
