### ISSUE TITLE
RFC: Create new repo under kata for the kata-containerd-lvm-snapshotter

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1303]
# Create new repo under kata for the kata-containerd-lvm-snapshotter

We are creating a lvm based snapshotter to provide a block based snapshotter for Kata to be used with containerd. This is required as containerd will no longer support an in-tree in process block based snapshotter.

This repo will be used to hold a lvm-snapshotter that can be used along with kata (or runc) when using containerd.

**Comment by sboeuf** [comment]
Sounds relevant to me! :+1:

**Comment by mcastelino** [comment]
/cc @ganeshmaharaj @egernst @sboeuf @kata-containers/architecture-committee @nalind

@ganeshmaharaj has an initial working version of the same. We will attempt to converge this implementation across https://github.com/containers/storage/pull/261 implemented by @nalind for CRI-O

This can also be used with firecracker.

**Comment by mcastelino** [comment]
https://github.com/kata-containers/runtime/issues/943

**Comment by mcastelino** [comment]
https://github.com/docker/for-linux/issues/452

**Comment by mcastelino** [comment]
https://github.com/containers/storage/pull/285

**Comment by mcastelino** [comment]
https://github.com/firecracker-microvm/firecracker-containerd/tree/master/snapshotter/devmapper

**Comment by egernst** [comment]
I think it would make sense to put this in a "third party" location. Naming wise, github.com/containers/storage makes a lot of sense.

/cc @nmeyerhans

**Comment by mcastelino** [comment]
@egernst yes a project neutral location would be ideal. As it will work for for any runtime implementation conformant to containerd.

**Comment by mcastelino** [comment]
Pointer to the existing early implementation by 
@ganeshmahara jhttps://github.com/ganeshmaharaj/lvm-snapshotter 

This is functional. We will continue development on that repo until the final location is chosen.

**Comment by mcastelino** [comment]
We now have a block based snapshotter from the firecracker team in containerd. @ganeshmaharaj also has a PR pending to add LVM based snapshotter to containerd. Closing this as we do not need our own repo for this.
