### ISSUE TITLE
Are kata-shim and kata-proxy needed when using with containerd

### ISSUE THREAD

**Issue by zhsj** [kata-containers/runtime#1314]
# Description of problem

This seems a newbie question, I try to run kata with containerd(with v2 shim) and k8s.

I didn't see any kata-proxy and kata-shim process running, and it works just fine.

So I removed the kata-proxy and kata-shim binary, and set

```
[shim.kata]
#path = "/opt/kata/libexec/kata-containers/kata-shim"
path = "/"
[proxy.kata]
#path = "/opt/kata/libexec/kata-containers/kata-proxy"
path = "/"
```

And I started the kata container successfully, with command

```
sudo ctr run --runtime io.containerd.runtime.kata.v2 -t docker.io/library/debian:buster-slim test1 bash
```

So I guest for containerd, the kata-proxy and kata-shim are not needed.

But if I unset `[proxy.kata] path` and `[shim.kata] path`, it will failed to run.

```
ctr: io.containerd.kata.v2: /usr/share/defaults/kata-containers/configuration.toml: file /usr/libexec/kata-containers/kata-shim does not exist
: exit status 1: unknown
```

It failed at the reading configuration phase.

# Expected result

containerd could start kata container without kata-shim and kata-proxy binaries.

# Actual result

```
ctr: io.containerd.kata.v2: /usr/share/defaults/kata-containers/configuration.toml: file /usr/libexec/kata-containers/kata-shim does not exist
: exit status 1: unknown
```

**Comment by gnawux** [comment]
@zhsj you don't need `kata-shim` and `kata-proxy` when working with shimv2. But I guess there's a configuration validation issue. 

@lifupan, could you check it?
