### ISSUE TITLE
Is GPU device supported by Kata Containers?

### ISSUE THREAD

**Issue by bluetune** [kata-containers/runtime#1315]
# Description of problem
Can gpu device be added into guest vm ?  and by which way?
(1)  coldplugging
(2) hotplug
then, what about the support for vgpu?

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by jodh-intel** [comment]
Hi @bluetune - please see https://github.com/kata-containers/documentation/blob/master/use-cases/GPU-passthrough-and-Kata.md.

Can this issue now be closed/
