### ISSUE TITLE
Can't connect to qmp/console's unix socket if created by shimv2

### ISSUE THREAD

**Issue by zhsj** [kata-containers/runtime#1318]
# Description of problem

I want to debug the VM, and I follow the developer guide, to start a shell in the VM.
Now with container created by docker(via `docker run  --runtime kata-runtime`), I've successfully entered the VM, with command `socat "stdin,raw,echo=0,escape=0x11" "unix-connect:${console}"`

But for the container created by shimv2 (via `ctr run --runtime io.containerd.run.kata.v2`), the unix socket doesn't response, neither console.sock nor qmp.sock.

This looks like that other process is using these socket files. (I just observe that these unix socket files can only response to one client.) But I use `fuser` to search, there's only qemu process using the socket file.

I'm using the default kata configuration(debug is false), default containerd configuration.

kata version is 1.5.0 and containerd is 1.2.4.

# Expected result

The qmp/console unix socket files can response.

# Actual result

The socket files of container created by shimv2 can't response.

**Comment by amshinde** [comment]
@sboeuf Any idea about this beheaviour?

**Comment by sboeuf** [comment]
@zhsj can you check if the QEMU process that has been started by `containerd-shim-kata-v2` has a `console.sock` socket being created?
I'm not entirely sure in case of `containerd-shim-kata-v2`, if you're not using `vsock`, the runtime might be the one connecting to the `console.sock`, even if `enable_debug=false` (that would be a bug obviously). Or the other possibility would be that in this case the `console.sock` is not created (check by looking at qemu process `ps -ef | grep qemu`).

**Comment by egernst** [comment]
@lifupan @gnawux ptal?

**Comment by zhsj** [comment]
> I'm not entirely sure in case of containerd-shim-kata-v2, if you're not using vsock, the runtime might be the one connecting to the console.sock, even if enable_debug=false (that would be a bug obviously).

So I tried the vsock. Although I failed to run (not sure if #1319 is related), I can connect to the qmp and console socket.
> Or the other possibility would be that in this case the console.sock is not created (check by looking at qemu process ps -ef | grep qemu).

It's created, I can see it's opened by qemu process.
```
$ sudo lsof -n -p 9765|grep sock
qemu-syst 9765 root   11u     sock                0,9      0t0 20218250 protocol: UNIX
qemu-syst 9765 root   12u     sock                0,9      0t0 20218252 protocol: UNIX
qemu-syst 9765 root   13u     sock                0,9      0t0 20218254 protocol: UNIX
qemu-syst 9765 root   18u     unix 0x00000000316096da      0t0 20219221 /run/vc/vm/test1/console.sock type=STREAM
qemu-syst 9765 root   19u     unix 0x00000000e37c7e77      0t0 20219222 /run/vc/vm/test1/kata.sock type=STREAM
qemu-syst 9765 root   91u     unix 0x0000000075d1a32f      0t0 20217508 /run/vc/vm/test1/qmp.sock type=STREAM
```

**Comment by lifupan** [comment]
Hi @zhsj, 
For console.sock, there is a difference between docker cli and shimv2, in shimv2 case, it ignored the proxy "debug" option and watched the console always, that's why you cannot reattach onto it using socat. I will fix it and make it keep align with docker cli case. 

For qmp.sock, since kata runtime will exit once  kata container started using docker cli method, that's why you can dial into it; but for shimv2, it will run as a daemon and connected on qpm.sock, thus you cannot reattach onto it again. 

 BTW, what's your usecase for this sock connect? Is there any special demands to connect those sock files outside of kata?

**Comment by zhsj** [comment]
@lifupan thanks for the clarification.

I was debuging the VM, as I've added a private device to it... My case when developing can be migrated to use the docker cli. But I'm not sure if it goes to the k8s cluster(it will use containerd and shimv2), how can I debug it.

**Comment by lifupan** [comment]
> @lifupan thanks for the clarification.
> 
> I was debuging the VM, as I've added a private device to it... My case when developing can be migrated to use the docker cli. But I'm not sure if it goes to the k8s cluster(it will use containerd and shimv2), how can I debug it.

shimv2 will forward the qemu's console output into containerd's logger, thus you can catch qemu's console output from containerd's log.

**Comment by zhsj** [comment]
> Is there's a strong demand for this debug in product env(using shimv2)?

I'm not sure, since there's no prod env yet...
