### ISSUE TITLE
Running from ramdisk not supported.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#134]
On setting 'DOCKER_RAMDISK=true' in docker service file and starting a container, runtime will fail and give an error " docker: Error response from daemon: OCI runtime create failed: flag provided but not defined: -no-pivot: unknown".

**Comment by amshinde** [comment]
This is seen with cc-runtime, but applicable with kata-runtime. We indeed do not support the `-no-pivot` flag that runc supports. I would like to get input on this to see if this feature can be supported with Kata-containers with the fact that we are running  a containers inside a virtual machine.

**Comment by grahamwhaley** [comment]
Can we tie this into the limitations doc Issue over at https://github.com/kata-containers/documentation/issues/31 somehow as well pls.

**Comment by jodh-intel** [comment]
Yep - I'll add it.

**Comment by amshinde** [comment]
@jodh-intel Thanks.

**Comment by amshinde** [comment]
@sameo @laijs @bergwolf Do you have any input on this, if this is att possible to do with Kata containers.

**Comment by laijs** [comment]
I think kata-runtime can just ignore the `-no-pivot` argument.
I don't think it would break anything.

**Comment by jodh-intel** [comment]
ftr, `cc-oci-runtime` used to support the option but make it a nop:

- https://github.com/intel/cc-oci-runtime/blob/master/src/commands/create.c#L43..L48

**Comment by WeiZhang555** [comment]
Agree. This flag can be ignored then the error will be gone.

**Comment by jodh-intel** [comment]
Responding to @grahamwhaley's request, I should point out that I added this limitation to the doc:

- https://github.com/kata-containers/documentation/pull/48

If anyone feels like reviewing, we need one more ack before that can land...

**Comment by caoruidong** [comment]
Close this by #423
