### ISSUE TITLE
dmesg errors while running a container

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#1345]
While running a container with kernel version 4.19.24, we are getting dmesg errors

```
$ docker run -ti --runtime=kata-runtime debian dmesg -l err
[    1.038971] EXT4-fs (pmem0p1): DAX unsupported by block device. Turning off DAX.
[    1.155322] systemd[75]: tmp.mount: Failed to execute command: No such file or directory
```
Running a container with kernel version 4.14.67 , we are getting

```
$ docker run -ti --runtime=kata-runtime debian dmesg -l err
[    1.155322] systemd[75]: tmp.mount: Failed to execute command: No such file or directory
```

No errors should be there.

**Comment by jcvenegas** [comment]
[    1.038971] EXT4-fs (pmem0p1): DAX unsupported by block device. Turning off DAX.
Probably is because the issue that @devimc  is traking

**Comment by jcvenegas** [comment]
the systemd issues are probably because the new image what image version are you using ?

**Comment by devimc** [comment]
I'm taking both issues :nerd_face:

**Comment by GabyCT** [comment]
@jcvenegas 
```
Path = "/usr/share/kata-containers/kata-containers-clearlinux-28210-osbuilder-da9f541-agent-a2037c0.img"
```

**Comment by devimc** [comment]
fixed https://github.com/kata-containers/runtime/pull/1340 and https://github.com/kata-containers/osbuilder/pull/264

**Comment by grahamwhaley** [comment]
Weird, I am seeing this (`DAX unsupported by block device`) error on both:
- a fresh `tests/.ci/setup.sh` install in a `ccloudvm` Ubuntu 18.04.2 LTS VM instance
  - image `kata-containers-clearlinux-29400-osbuilder-edd7d9c-agent-7720b93.img`
- a fresh v1.6.3 static binary `/opt/kata` install on a freshly installed Ubuntu 18.04.2 LTS bare metal NUC
  - image `kata-containers-image_clearlinux_1.6.3_agent_22bbb821b6.img`

odd. I checked a recent 18.04 CI run, and it definitely looks like it is working there...
I'll probably re-produce in the morning.

/cc @devimc @jcvenegas

**Comment by grahamwhaley** [comment]
If anybody has a moment to try this on a local machine, just:

```bash
$ docker run -ti --rm --runtime=kata-runtime debian dmesg -l err
```

and see if you get any output?

Oh, I lied - I see the `DAX` error on the ccloudvm instance, I see some systemd errors on the static install... using the `kata-qemu` runtime.

**Comment by devimc** [comment]
@grahamwhaley I ran the command that you mention, and the output is empty. Also there is a test in the CI to check the dmesg errors, https://github.com/kata-containers/tests/blob/master/integration/docker/run_test.go#L295

**Comment by grahamwhaley** [comment]
@devimc - thanks. Yeah, I know there is a test - that is what first triggered for me in a local CI run :-)
I was trying to run the CI locally with `kata-fc`, but so far it has failed with different test cases each time :-(
