### ISSUE TITLE
Bind cpu is not working with Numactl

### ISSUE THREAD

**Issue by tiejun2sh** [kata-containers/runtime#1348]
# Description of problem

I am using the Docker image to do some AI related benchmarking. 
The PC hardware has two CPU sockets, and in my test, I try to bind the test to the CPU0.

So I am passing numactl --cpunodebind=0 --membind=0 when I run following command. 

`sudo docker run it --runtime kata-runtime -m=96g --cpus=63  --rm $IMAGE bash -ci 'source /.bashrc && numactl --cpunodebind=0 --membind=0 python program…’`

# Expected result

expect the CPU bind with Numactl can work well with Kata runtime.

# Actual result

Error which is telling 

`numactl: This system does not support NUMA policy
`
If changing container runtime to RunC, there is no such error.

---
# PC hardware information
NUMA node0 CPU(s):   0-17,36-53
NUMA node1 CPU(s):   18-35,54-71

# kata-env

`[Meta]
  Version = "1.0.20"

[Runtime]
  Debug = false
  Trace = false
  DisableNewNetNs = false
  Path = "/usr/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.5.0-rc2"
    Commit = ""
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.11.0\nCopyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/kata-qemu-lite-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = false
  UseVSock = false

[Image]
  Path = "xxxxx.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.14.90-8.container"
  Parameters = ""

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.5.0-rc2"
  Path = "/usr//libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.5.0-rc2"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.19.13-679.native"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "xxxxx"
    Version = "xxxxx"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = " xxxxx@ 2.30GHz"

[Netmon]
  Version = "kata-netmon version 1.5.0-rc2"
  Path = "/usr//libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
`

**Comment by egernst** [comment]
@devimc @jcvenegas - can you PTAL?  AFAIU we don't have numa support yet?  Is this bug actually a missing feature?

**Comment by egernst** [comment]
Ah, it looks lik you are running numactl in the guest itself?  In the runc case you are running this on the host itself (I would assume privs are needed).  Could you do the same with cpu-sets in docker itself?

You could rebuild the rootfs to include numactl, but you'd just be restricting vCPUs inside the virtual machine.  I think you effectively want to bind the hypervisor to the physical CPUs, right?

You'd do this through the docker CLI.

**Comment by jcvenegas** [comment]
hi @tiejun2sh we dont emulate the numa organization of the host, the guest is not a numa node, I think you want to do numa affinity in the guest as are using  most of the cpus in your host?

the most similar think we have in mind is to pin vcpus to cpus but this wont be numa aware in the case of the allocations.  \cc  @mcastelino  what do you think of add this as feature request ?

**Comment by tiejun2sh** [comment]
> Ah, it looks like you are running numactl in the guest itself (in the container)? In the runc case you are running this on the host (I would assume privs are needed to do this from inside container). Could you do the same with cpu-sets in docker itself?
> 
> You could rebuild the rootfs to include numactl, but you'd just be restricting vCPUs inside the virtual machine when utilizing Kata. I think you effectively want to bind the hypervisor to the physical CPUs, right?
> 
> You'd do this through the docker CLI.

Yes, I am running numactl inside the docker instance. In the docker file image, it has numactl installed. We pass the cpu set (numactl --cpunodebind=0 --membind=0) with the bash command when calling docker run. So I expect when the docker instance get running, the one workload thread can bind to each CPU cores in case numactl command executed successfully. 
In the RunC case, it is using the same way as illustrated above, and it works perfect fine. I see the workload thread is binded to the physical CPU cores with top command.  
In contrast, for Kata, becauseof the failure of numactl command, workload thread rescheduled frequently among different CPU cores. This causes relative lower performance compared to RunC case.
And thanks for suggestion that binding the hypervisor to the physical CPUs, can this avoid using numactl in my case? I will also try and study this.

**Comment by tiejun2sh** [comment]
> hi @tiejun2sh we dont emulate the numa organization of the host, the guest is not a numa node, I think you want to do numa affinity in the guest as are using most of the cpus in your host?
> [Tiejun] Yes, workload will be running inside the docker instance. the hardware has 2CPU sockets. 72 CPU cores. The test expects to maximize the performance with 1/4 CPU cores(so we create 18 inter thread, and expect each thread can bind to each cpu core)

> the most similar think we have in mind is to pin vcpus to cpus but this wont be numa aware in the case of the allocations. \cc @mcastelino what do you think of add this as feature request ?

**Comment by egernst** [comment]
@tiejun2sh - yeah, you should "tell" Docker to do this via cpu-set.  if you do this, then the hypervisor will be bound to those specific CPUs.  Right @jcvenegas ?
