### ISSUE TITLE
Verify/Optimize Raw Block storage support

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1354]
# Ensure Raw block storage is exposed via block devices (SCSI/IDE) 

Kubernetes v1.13 moves raw block volume support to beta. This feature allows persistent volumes to be exposed inside containers as a block device instead of as a mounted file system.

https://kubernetes.io/blog/2019/03/07/raw-block-volume-support-to-beta/

# Expected result

We need to ensure that
- Add tests to ensure that we support it
- Ensure Raw block storage is exposed via block devices (SCSI/IDE) instead of 9p/virtio-fs

**Comment by amshinde** [comment]
Will take a look @mcastelino.

**Comment by amshinde** [comment]
@mcastelino I verified this using a local Persistent volume backed by a loop-mounted block device.
I have created a gist here:
https://gist.github.com/amshinde/2ab9b5a2f2e91694a7421b1e2b787b58

I suppose we can duplicate the same in our tests. What do you think?

cc @chavafg @GabyCT

**Comment by amshinde** [comment]
@chavafg Lets add a test for this in our CI then leveraging the `sdb` device.

**Comment by amshinde** [comment]
Closed with https://github.com/kata-containers/tests/issues/1358
