### ISSUE TITLE
Fail to stop kata container

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#1368]
# Description of problem

When parallel run kata containers more than thousands times, will get some case cannot stop container, error is 
```
124 time="2019-03-13T11:34:04+08:00" level=info msg="{\"execute\":\"quit\"}" arch=amd64 command=kill container=d5f325b8ca2f83dd876aa7061f90f989bb58d221fb79063a610217a674376a7e name=kata-runtime pid=75093 sandbox=d5f325b8ca2f83dd876aa7061f90f989bb58d221fb79063a610217a674376a7e source=virtcontainers subsystem=qmp
125 time="2019-03-13T11:34:04+08:00" level=info msg="{\"timestamp\": {\"seconds\": 1552448044, \"microseconds\": 291115}, \"event\": \"SHUTDOWN\", \"data\": {\"guest\": true}}" arch=amd64 command=kill container=d5f325b8ca2f83dd876aa7061f90f989bb58d221fb79063a610217a674376a7e name=kata-runtime pid=75093 sandbox=d5f325b8ca2f83dd876aa7061f90f989bb58d221fb79063a610217a674376a7e     source=virtcontainers subsystem=qmp
126 time="2019-03-13T11:34:04+08:00" level=error msg="Fail to execute qmp QUIT" arch=amd64 command=kill container=d5f325b8ca2f83dd876aa7061f90f989bb58d221fb79063a610217a674376a7e error="unable to write command to qmp socket write unix @->/run/vc/vm/d5f325b8ca2f83dd876aa7061f90f989bb58d221fb79063a610217a674376a7e/qmp.sock: write: broken pipe" name=kata-runtime pid=75093 sand    box=d5f325b8ca2f83dd876aa7061f90f989bb58d221fb79063a610217a674376a7e source=virtcontainers subsystem=qemu
```

I assume if is qemu shutdown first than give response to `quit` request. (Just guess)

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by jodh-intel** [comment]
The container paths are unique so it seems unlikely this is directly related to running in parallel, but maybe more that you've managed to run a lot of containers and hit some sort of condition not normally seen.

What state is the qemu instance in (if it's still running)? Can you login with a debug console or get a stack trace of the qemu process?

Have you ever seen this behaviour before @markdryan?

**Comment by Ace-Tang** [comment]
Yes, I agree that it is not related with running in parallel, it occurs with a low probability, only run thousands time, and sometimes occurs. Actually when this error occurs, qemu has already shutdown, so it hard to get the stack

**Comment by markdryan** [comment]
@jodh-intel I haven't seen this before but looking at the error message it seems that the VM has already quit.  Could the code be asking the same VM to shut down twice?  What does the shutdown code in kata look like?

**Comment by jodh-intel** [comment]
@markdryan - Here is where the QMP QUIT gets called:

https://github.com/kata-containers/runtime/blob/master/virtcontainers/qemu.go#L647..L666

**Comment by sboeuf** [comment]
@Ace-Tang are you hitting this issue when running with `vsock` or not? Do you have a `kata-proxy` or not?

**Comment by sboeuf** [comment]
I'm thinking there might be some cases where the agent will terminate, and this would cause the VM to shutdown before the QMP QUIT is being called. If that's the case, this [patch](https://github.com/kata-containers/agent/pull/415/commits/272f273961e70096938ac7a3fe6477023c8f715a) from PR https://github.com/kata-containers/agent/pull/415 will fix things for you.
Could you manually modify your kata image to try this out locally?

**Comment by Ace-Tang** [comment]
@sboeuf , I run without vsock, have kata-proxy, I will add the patch for kata-agent, and run test to see if happen again. But I also get another guess that if vm load is high, does this cause qemu shutdown before qmp returns.  BTW, it's so late, I will try tomorrow

**Comment by sboeuf** [comment]
@Ace-Tang That's a good point, if the load is high, we might have something failing in the agent because we reach a timeout, and that might cause the VM to shutdown. So this patch should help, but also it would not fix the issue that might be about timeouts.

**Comment by Ace-Tang** [comment]
also get another error , probably one thousandth probability, like error `unable to write command to qmp socket write`
```
time="2019-03-14T19:40:25+08:00" level=info msg="{\"execute\":\"quit\"}" arch=amd64 command=kill container=4eaa9fbfbdc0e79c1a878b970e3fe01cb70369dac27139eab2b0a8fe8d68ec46 name=kata-runtime pid=95781 sandbox=4eaa9fbfbdc0e79c1a878b970e3fe01cb70369dac27139eab2b0a8fe8d68ec46 source=virtcontainers subsystem=qmp
time="2019-03-14T19:40:25+08:00" level=info msg="{\"timestamp\": {\"seconds\": 1552563625, \"microseconds\": 861079}, \"event\": \"VSERPORT_CHANGE\", \"data\": {\"open\": false, \"id\": \"channel0\"}}" arch=amd64 command=kill container=4eaa9fbfbdc0e79c1a878b970e3fe01cb70369dac27139eab2b0a8fe8d68ec46 name=kata-runtime pid=95781 sandbox=4eaa9fbfbdc0e79c1a878b970e3fe01cb70369dac27139eab2b0a8fe8d68ec46 source=virtcontainers subsystem=qmp
time="2019-03-14T19:40:25+08:00" level=info msg="{\"timestamp\": {\"seconds\": 1552563625, \"microseconds\": 905028}, \"event\": \"SHUTDOWN\", \"data\": {\"guest\": true}}" arch=amd64 command=kill container=4eaa9fbfbdc0e79c1a878b970e3fe01cb70369dac27139eab2b0a8fe8d68ec46 name=kata-runtime pid=95781 sandbox=4eaa9fbfbdc0e79c1a878b970e3fe01cb70369dac27139eab2b0a8fe8d68ec46 source=virtcontainers subsystem=qmp
time="2019-03-14T19:40:26+08:00" level=error msg="Fail to execute qmp QUIT" arch=amd64 command=kill container=4eaa9fbfbdc0e79c1a878b970e3fe01cb70369dac27139eab2b0a8fe8d68ec46 error="exitting QMP loop, command cancelled" name=kata-runtime pid=95781 sandbox=4eaa9fbfbdc0e79c1a878b970e3fe01cb70369dac27139eab2b0a8fe8d68ec46 source=virtcontainers subsystem=qemu
```
that also show vm has shutdown, so set all qmp response `exitting QMP loop, command cancelled`

**Comment by jodh-intel** [comment]
One other point - you don't appear to have enabled [full debug](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug). If you can recreate with that enabled it might give us more of a clue as to what is happening.

**Comment by markdryan** [comment]
> exitting QMP loop, command cancelled

You are likely to see this error if you issue a whole pile of commands to the VM, but the VM shuts down before they are all executed.  This error indicates that there's no point in sending the queued command to the VM as it either isn't there any more or its no longer being monitored.

**Comment by grahamwhaley** [comment]
Just a note - if you are enabling full debug and running many containers in parallel, watch out for the journald dropping entries - see https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#journald-rate-limiting
iirc, I found that whilst running 1000 containers for instance ;-)

**Comment by Ace-Tang** [comment]
Why vm shutdown before qmp response return I still not know, but I wonder if we can monitor the qmp event, and check if we get shutdown but qmp response is false, then we can think the vm is shutdown successful ?
