### ISSUE TITLE
[RFC] Simplify CPU hotplug

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#1384]
This proposal is based out of the pending PR https://github.com/kata-containers/agent/pull/478. The idea is explained pretty well by @justin-he [here](https://github.com/kata-containers/agent/pull/478#discussion_r266300970) but let me extend it in more details.

Kata supports CPU hotplug, that's a fact, but if we look into details, it only supports it for specific hypervisors (QEMU does, but Firecracker doesn't), and for specific architectures (QEMU x86 does, but QEMU aarch64 doesn't).

Now if we look into the details and reasons why this is not supported, we have several answers:
- In case of hypervisor, this might be a simple choice from the hypervisor to keep the code simple and not have the hardware hotplug mechanism being emulated.
- In case of architecture, this might be a pure lack of support from the hardware definition itself.

No matter the reasons, we want to make sure we deliver the same level of support across all architectures and hypervisors to simplify Kata for our users.
Moreover, we want to simplify the Kata codebase whenever it is possible, since less code introduces less maintenance and less bugs.

That's why I'd like to propose we approach CPU hotplug with a consistent mechanism across hypervisors and architectures. This would involve to start the VM with a large number of vCPUs (let's say 8 for this example), but limit the amount of __online__ ones by using the kernel to do so.
This means that from a guest perspective, the amount of hardware CPUs would be 8, but by default only 1 (or more, depending what's needed when VM is started) would be __online__, hence __usable__.
On the host side, this results into a higher memory footprint since we would end up having some idle vCPUs (threads) that would not be used.
If I'm not mistaken, each of these threads would consume 8k of memory, which is pretty negligible compared to the memory footprint implied by all other Kata Containers component (we're talking about `MiB` order here).
If we can accept this very small bump, we would simplify the entire model since we would not need to use some specific ACPI capabilities provided by QEMU for x86 architecture only, but instead we would have a unified way of having CPU hotplug.

/cc @sameo @egernst @mcastelino @amshinde @bergwolf @jodh-intel @WeiZhang555 @gnawux @devimc @jcvenegas @grahamwhaley @jon PTAL

**Comment by amshinde** [comment]
@sboeuf I like the simplified approach, especially if it does not impact memory consumption too much.
It will help us to step away from all the complexities associated with CPU hotplug and related issues.

**Comment by sboeuf** [comment]
@amshinde 
>if it does not impact memory consumption too much

Agreed, and I mentioned `8k` but this needs to be confirmed before we decide to move forward with this approach.
@devimc I believe you did such measurement before, do you have more accurate numbers regarding what it would cost?

>If we decide to go with this approach, question is what to pick as the default CPU number

That's the part we need to figure out. The default behavior is to rely on the `configuration.toml`, but from a cluster perspective, having this information through CRI/OCI annotations would be very useful indeed.

**Comment by ganeshmaharaj** [comment]
A very dumb question and I will apologize for my ignorance ahead of time.  What happens if for some reason we allocate more than 8 CPUs for a container/pod?

**Comment by sboeuf** [comment]
@ganeshmaharaj 
>A very dumb question and I will apologize for my ignorance ahead of time

There is no dumb questions ;)

>What happens if for some reason we allocate more than 8 CPUs for a container/pod?

We need to know at VM creation what would be the maximum CPUs our containers might need. If for some reason, we started a VM with 8 CPUs and a container needs 16, I guess we have two choices, either we return an error saying that something has been misconfigured since we cannot honor the request, or we decide to treat this as a simple warning and instead give the maximum of CPUs available.
That's the question we have to solve. But I'd say that it is going to depend on the extra memory consumed by those extra vCPU threads. If it's really `8k`, we could afford 100 CPUs as the default and online only what we need.

One thing to consider with a very high number of CPUs is the boot time of our VM.
/cc @grahamwhaley ^

**Comment by justin-he** [comment]
Hi all, another open point I should raise here about the simplified cpu hotplug is:
Whether --privileged will be supported in Kata in the future?
If no, the sysfs in container will be mounted as readonly and the user can't set the cpu as online/offline.
If yes, the sysfs will be mounted as rw, so the vcpu is out of control

I noticed that [1] announced this point, just double confirm whether in the future Kata will change the limitations or not?
[1] [previleged limitations](https://github.com/kata-containers/documentation/blob/ab214c137859cdf54c1fca3e441b3120839b808f/Limitations.md#docker-run---privileged)

**Comment by bergwolf** [comment]
Hi @sboeuf, IMO the biggest drawback of the proposed approach is security. It relies on the guest kernel for how much vCPU a guest can actually use. And in general we would not **trust** the guest even if user apps are actually inside their own namespaces. If any user hacks into the guest kernel and gains root access there, they would be able use as many vCPU as there are. IWO there is only one defense line for guest vCPU usage. And we do not seem to trust it from the very beginning.

**Comment by dadux** [comment]
Starting the VM with more vCPU would actually be a problem for our use case. 

We've had the case where we started seeing containers OOMing after going to a bigger AWS instance type. After a bit of investigation we realised that a lot of applications use the number of cores to determine how many threads to start by default (NodeJS for example), thus consuming more memory.

Having the number of visible vCPU == CPU limit in the pod definition is actually something we really like about Kata.

**Comment by grahamwhaley** [comment]
@sboeuf - ack, if we start to look at adding 'offline vCPUs' to kata by default at startup, then (whoever writes the patch...) we should run  up the metrics and measure both the boot time and memory footprint overheads. waaay back in the history of Kata we did allocate as many vCPU slots as the host had physical cores for instance, and this added a substantial penalty on large machines (like 88 or 128 cores for the ones I measured on). We need to ensure folks are happy with any overhead/costs and look at the cost/benefit ratio etc.

@dadux - good point. Kata itself suffered something similar on the host side at one point where the golang runtime would get rescheduled and keep allocating new thread/processes for its garbage collector, until it ran the host out of process ID slots, at which point things started to get killed off.

**Comment by WeiZhang555** [comment]
> Hi @sboeuf, IMO the biggest drawback of the proposed approach is security. 

I agree with @bergwolf , it's more about security.  We never trust guest apps in any cases, besides a priviledged container can have root access in Guest and online the CPUs easily.

> We could make this as a pod level configuration(pod annotations passed to the OCI layer?) rather than a host wide configuration.

I think this is the best approach. If K8s can calculate the POD resource and passed it to OCI runtime, then we can always know exact number of vCPUs the qemu requires. The drawback is it's not friendly to "kata-runtime update" resource command, K8s doesn't support updating  container resources IIRC so it's not a big problem so far.

**Comment by sboeuf** [comment]
Thanks for the feedback so far. I have to admit I forgot about the part where we would be relying on the guest to do the _offline_ part.

Then the only solution I can think of would be a dedicated paravirtualized solution such as `virtio-cpu`. It would be responsible for onlining/offlining the CPUs on the guest side, but the hypervisor would really be in charge. Every time you need a new CPU, the hypervisor would spin a new vCPU thread and it would inform the guest driver that a new CPU has been created, hence the driver would simply online it.
This is the most generic approach I can think of, that would work for any hypervisor/architecture without giving the possibility to the guest to mess things up.

What do you all think?

**Comment by amshinde** [comment]
> I think this is the best approach. If K8s can calculate the POD resource and passed it to OCI runtime, then we can always know exact number of vCPUs the qemu requires. The drawback is it's not friendly to "kata-runtime update" resource command, K8s doesn't support updating container resources IIRC so it's not a big problem so far.

I suppose we could do this with an admission controller that could annotate the pod with the number of cpus actually required. cc @egernst 
If no cpu limits are present, we could pick a sane default.
I dont think we need to worry about `kata-runtime update` command for k8s atleast.

@sboeuf The hypervisor handling the onlining of CPUs seems like a sane approach to me. Lets see what others have to say about it.

**Comment by sboeuf** [comment]
And to be clear, with a PV approach like `virtio-cpu`, we would not have to know about the number of needed CPUs at the time the VM is started.

**Comment by justin-he** [comment]
> Thanks for the feedback so far. I have to admit I forgot about the part where we would be relying on the guest to do the _offline_ part.
> 
> Then the only solution I can think of would be a dedicated paravirtualized solution such as `virtio-cpu`. It would be responsible for onlining/offlining the CPUs on the guest side, but the hypervisor would really be in charge. Every time you need a new CPU, the hypervisor would spin a new vCPU thread and it would

Could you elaborate more about "the hypervisor would spin a new vCPU thread"? Does it mean hypervisor will pick an readly spawned vCPU thread and do sth afterwards? Or create a vcpu thread ?
The it is the latter one, there is a limitation on arm64 at the kvm side:
All vcpu threads are needed to be created at initialization stage. The gic resource management limits that.

> inform the guest driver that a new CPU has been created, hence the driver would simply online it.
> This is the most generic approach I can think of, that would work for any hypervisor/architecture without giving the possibility to the guest to mess things up.
> 
> What do you all think?

**Comment by devimc** [comment]
@sboeuf `virtio-cpu` is something new? I haven't heard about it , another solution that I have in mind is to enable the kernel option that online the resources (mem and cpu) automatically and asynchronously the agent should only the cgroups once all resources are connected

**Comment by justin-he** [comment]
virtio-cpu needs to change the codes on both guest and qemu side. Need we push it to qemu/kernel community firstly and pull back to kata？ IMHO，it is hard to persuade upstream accept this

**Comment by sboeuf** [comment]
@justin-he 
>Could you elaborate more about "the hypervisor would spin a new vCPU thread"? Does it mean hypervisor will pick an alreadly spawned vCPU thread and do sth afterwards? Or create a vcpu thread ?
The it is the latter one, there is a limitation on arm64 at the kvm side:
All vcpu threads are needed to be created at initialization stage. The gic resource management limits that.

Yes I was thinking about the latter one. I thought we could create a new vCPU thread after the VM has already been created. I didn't know about the ARM64 limitation that was tied to the GIC. This is really a problem as this solution would not work... Is this limitation part of KVM, or is it because of the ARM GIC design that makes it impossible to create a new CPU later on?

>virtio-cpu needs to change the codes on both guest and qemu side. Should we push it to qemu/kernel community firstly and pull back to kata？ IMHO，it is hard to persuade upstream accept this

It is just an idea since we've recently seen some work related to memory hotplug called `virtio-mem`. I thought that we could have applied the same concept for CPU in order to be architecture agnostic. I don't know what would be the opinion of the virtio/QEMU community on this, but would be interesting to ask since they might have done some work/research in this field already.

**Comment by sboeuf** [comment]
@devimc 
>`virtio-cpu` is something new? I haven't heard about it 

It's just an idea about how we could solve some of the complexity around CPU hotplug, but does not exist. It might be a wrong idea though.

>another solution that I have in mind is to enable the kernel option that online the resources (mem and cpu) automatically and asynchronously the agent should only the cgroups once all resources are connected

By having the kernel onlining CPUs automatically, I think you fallback onto the first issue about having a VM that is going to use all the CPUs that have been created with it. And because we cannot know in advance the number of CPUs needed for this pod, we might end up assigning a lot of CPUs.

**Comment by sboeuf** [comment]
@mcastelino 
> there is a limitation on arm64 at the kvm side:
All vcpu threads are needed to be created at initialization stage. The gic resource management limits that.

Do you think that's something we can fix/patch?

**Comment by justin-he** [comment]
> @justin-he
> 
> > Could you elaborate more about "the hypervisor would spin a new vCPU thread"? Does it mean hypervisor will pick an alreadly spawned vCPU thread and do sth afterwards? Or create a vcpu thread ?
> > The it is the latter one, there is a limitation on arm64 at the kvm side:
> > All vcpu threads are needed to be created at initialization stage. The gic resource management limits that.
> 
> Yes I was thinking about the latter one. I thought we could create a new vCPU thread after the VM has already been created. I didn't know about the ARM64 limitation that was tied to the GIC. This is really a problem as this solution would not work... Is this limitation part of KVM, or is it because of the ARM GIC design that makes it impossible to create a new CPU later on?
From what Mark Rutland (maintainer) told:
"We'd need something along those lines. Each CPU has a notional point to point link to the interrupt controller (to the redistributor, to be precise), and this entity must pre-exist."

So, currently kvm code:
```
	if (irqchip_in_kernel(kvm) && vgic_initialized(kvm)) {
		err = -EBUSY;
		goto out;
	}
```
https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/tree/virt/kvm/arm/arm.c#n277
> 
> > virtio-cpu needs to change the codes on both guest and qemu side. Should we push it to qemu/kernel community firstly and pull back to kata？ IMHO，it is hard to persuade upstream accept this
> 
> It is just an idea since we've recently seen some work related to memory hotplug called `virtio-mem`. I thought that we could have applied the same concept for CPU in order to be architecture agnostic. I don't know what would be the opinion of the virtio/QEMU community on this, but would be interesting to ask since they might have done some work/research in this field already.

**Comment by justin-he** [comment]
> @mcastelino
> 
> > there is a limitation on arm64 at the kvm side:
> > All vcpu threads are needed to be created at initialization stage. The gic resource management limits that.
> 
> Do you think that's something we can fix/patch?

Hi @sboeuf , I don't think it is easy, it is by designing.
Besides, even we had fixed it at kernel/kvm side, currently the guest firmware can't dynamically get informed that "I need to create N vcpus, and let M (M<=N) online."

Of course, I thought qemu can take this, such as setting the hotpluggable cpu node in guest's device tree. Guest need to parse that nodes. But guest kernel need to be changed.

**Comment by sboeuf** [comment]
@justin-he 
>Of course, I thought qemu can take this, such as setting the hotpluggable cpu node in guest's device tree. Guest need to parse that nodes. But guest kernel need to be changed.

Yes of course, if the KVM side could be fixed, we would still need a paravirtualized solution to handle CPU discovery and onlining from the guest kernel.
