### ISSUE TITLE
Allow data collection script output to be hidden

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#1386]
The output of the [data collection script](https://github.com/kata-containers/runtime/blob/master/data/kata-collect-data.sh.in) is designed to be pasted directly into a github issue.

That results in a *lot* of output so using a cute trick which @dylanzr introduced us to, allow the output of the script to be hidden / unhidden by clicking on a "twistie". See the example at the top of https://github.com/kata-containers/runtime/issues/1347.

**Comment by grahamwhaley** [comment]
argh, embedded HTML ?? :-/ - but, yes, given it hides the huge volume of data... that will help with the PR readability. And, as we cannot (en)force the data being added as an attachment rather than a paste... this is probably a step in a good direction...
