### ISSUE TITLE
Move to qemu vanilla

### ISSUE THREAD

**Issue by chavafg** [kata-containers/runtime#1397]
In recent days we have talk about moving our default hypervisor from the 2.11 `qemu-lite` to a newer version of the qemu, which could be qemu vanilla 3.1.0 or 4.0.0 (which is still in rc).

Opening this issue to discuss further.

**Comment by chavafg** [comment]
btw, I have already took the task to test qemu 3.1.0 locally and all QA tests seem pretty stable.

**Comment by jcvenegas** [comment]
+1
The benefits related with this: 
- Updated qemu: Bugfixes,  security issues fixed from upstream. 
- Better testing for multiples architectures
- New features: #790 depends on this to provide a good support for VFIO cases.

Some items to fix to consider this complete are:
-[ ] Static binaires provide the latest qemu version.
-[ ] Packaging already provides qemu-vanilla package but need to deprecate qemu-lite and move qemu-vanilla as default 
-[ ] Deprecate qemu-lite 
-[ ] Move CI to test qemu vanilla 
-[ ] @bergwolf talk about a minimal qemu  version for people dont want to move qemu in a long time.
-[ ] Performance as we are moving from qemu-lite we may seen some regressions @grahamwhaley

**Comment by jcvenegas** [comment]
@sameo @sboeuf   nemu following stable qemu releases?  If yes would be great both qemu vanilla and nemu are based on the same qemu version to reduce differences that qemu and nemu for easier testing.

**Comment by sboeuf** [comment]
@jcvenegas yes for now NEMU relies on 3.1, but there is some ongoing work to rebase NEMU on top of 4.0.

**Comment by grahamwhaley** [comment]
@jcvenegas et. al. I opened a similar issue and did some metrics measures last month ;-) - over at https://github.com/kata-containers/runtime/issues/1253
Reference that for the metrics impacts, but I think let this Issue be the place for the current discussion.

**Comment by mcastelino** [comment]
@jcvenegas can you have a list of out of tree QEMU patches we carry today?

**Comment by mcastelino** [comment]
https://github.com/kata-containers/qemu/issues/6

**Comment by mcastelino** [comment]
WIP: DNM: qemu: update qemu vanilla version #1407
https://github.com/kata-containers/runtime/pull/1407

**Comment by mcastelino** [comment]
Metrics Data from @grahamwhaley 
 https://github.com/kata-containers/runtime/issues/1253#issuecomment-465685511
