### ISSUE TITLE
continuous-integration/travis-ci/pr always fail in linux/ppc64le but not in amd64

### ISSUE THREAD

**Issue by teawater** [kata-containers/runtime#1411]
https://github.com/kata-containers/runtime/pull/1409
https://github.com/kata-containers/runtime/pull/1410

$ travis_setup_go
go version go1.10.8 linux/ppc64le
$ export GOPATH="/home/travis/gopath"
$ export PATH="/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.10.8.linux.ppc64le/bin:/home/travis/bin:/home/travis/bin:/home/travis/.local/bin:/opt/pyenv/shims:/home/travis/perl5/perlbrew/bin:/home/travis/.rvm/gems/ruby-2.4.1/bin:/home/travis/.rvm/gems/ruby-2.4.1@global/bin:/home/travis/.rvm/rubies/ruby-2.4.1/bin:/home/travis/gopath/bin:/home/travis/.gimme/versions/go1.8.3.linux.ppc64le/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/home/travis/.rvm/bin:/opt/pyenv/bin"
$ export GO111MODULE="auto"
$ gimme version
v1.5.3
$ go version
go version go1.10.8 linux/ppc64le
go.env
$ go env
GOARCH="ppc64le"
GOBIN=""
GOCACHE="/home/travis/.cache/go-build"
GOEXE=""
GOHOSTARCH="ppc64le"
GOHOSTOS="linux"
GOOS="linux"
GOPATH="/home/travis/gopath"
GORACE=""
GOROOT="/home/travis/.gimme/versions/go1.10.8.linux.ppc64le"
GOTMPDIR=""
GOTOOLDIR="/home/travis/.gimme/versions/go1.10.8.linux.ppc64le/pkg/tool/linux_ppc64le"
GCCGO="gccgo"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build545902971=/tmp/go-build -gno-record-gcc-switches"
before_install.1
22.12s$ sudo apt update -y -qq
243 packages can be upgraded. Run 'apt list --upgradable' to see them.
before_install.2
$ sudo apt install -y -qq curl
The following additional packages will be installed:
  libcurl3-gnutls libcurl4-gnutls-dev
Suggested packages:
  libcurl4-doc libcurl3-dbg libgnutls-dev libidn11-dev librtmp-dev
The following packages will be upgraded:
  curl libcurl3-gnutls libcurl4-gnutls-dev
3 upgraded, 0 newly installed, 0 to remove and 240 not upgraded.
Need to get 575 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 74958 files and directories currently installed.)
Preparing to unpack .../curl_7.47.0-1ubuntu2.12_ppc64el.deb ...
7Progress: [  0%] [..........................................................] 87Progress: [  6%] [####......................................................] 8Unpacking curl (7.47.0-1ubuntu2.12) over (7.47.0-1ubuntu2.8) ...
7Progress: [ 12%] [########..................................................] 87Progress: [ 18%] [###########...............................................] 8Preparing to unpack .../libcurl4-gnutls-dev_7.47.0-1ubuntu2.12_ppc64el.deb ...
7Progress: [ 25%] [###############...........................................] 8Unpacking libcurl4-gnutls-dev:ppc64el (7.47.0-1ubuntu2.12) over (7.47.0-1ubuntu2.8) ...
7Progress: [ 31%] [###################.......................................] 87Progress: [ 37%] [######################....................................] 8Preparing to unpack .../libcurl3-gnutls_7.47.0-1ubuntu2.12_ppc64el.deb ...
7Progress: [ 43%] [##########################................................] 8Unpacking libcurl3-gnutls:ppc64el (7.47.0-1ubuntu2.12) over (7.47.0-1ubuntu2.8) ...
7Progress: [ 50%] [#############################.............................] 87Progress: [ 56%] [#################################.........................] 8Processing triggers for man-db (2.7.5-1) ...
Processing triggers for libc-bin (2.23-0ubuntu10) ...
Setting up libcurl3-gnutls:ppc64el (7.47.0-1ubuntu2.12) ...
7Progress: [ 62%] [#####################################.....................] 87Progress: [ 68%] [########################################..................] 8Setting up curl (7.47.0-1ubuntu2.12) ...
7Progress: [ 75%] [############################################..............] 87Progress: [ 81%] [################################################..........] 8Setting up libcurl4-gnutls-dev:ppc64el (7.47.0-1ubuntu2.12) ...
7Progress: [ 87%] [###################################################.......] 87Progress: [ 93%] [#######################################################...] 8Processing triggers for libc-bin (2.23-0ubuntu10) ...
install.1
0.01s$ cd ${TRAVIS_BUILD_DIR}
install.2
0.97s$ .ci/install-yq.sh
0.06s$ make
/home/travis/gopath/bin/yq: 1: /home/travis/gopath/bin/yq: Not: not found
golang.mk:33: *** "ERROR: cannot determine minimum golang version".  Stop.
The command "make" failed and exited with 2 during .
Your build has been stopped.

**Comment by devimc** [comment]
cc @nitkon

**Comment by nitkon** [comment]
@devimc : I had raised an issue [here](https://github.com/mikefarah/yq/issues/224) which I think has now got fixed.
