### ISSUE TITLE
qemu leak if container failed to start 

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#1426]
# Description of problem

https://github.com/kata-containers/runtime/blob/c6804c8e2bc9e2d290970ff39d982ffffe291146/virtcontainers/api.go#L100-L109

kata do cleanup after startVm(), but in startVM, function may return error but vm already start  , kata-agent failed to start server and return error, 
```
failed to create task for container(3a13403c6e5b13c6e2db5274b5e0b9882f37d82f5b61b1a8da84e08e7236f962): OCI runtime create failed: create error: unknown"
```

The error found in test I mention in https://github.com/kata-containers/runtime/issues/1368, maybe hundreds qemu run on the host make host load high, and kata-agent can not work.

The qemu version is `QEMU emulator version 2.11.0`, I think it should be a bug if use other qemu version

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by egernst** [comment]
@Ace-Tang do you have a simple example for reproducing this bug?

**Comment by Ace-Tang** [comment]
@egernst ， run many container parallel may reproduce, but it also simple to reproduce if you created an error in `startVM()`, the qemu will leak

**Comment by grahamwhaley** [comment]
@egernst - afaik, the only parallel launch test code we have is in the [fast footprint density test](https://github.com/kata-containers/tests/blob/master/metrics/density/fast_footprint.sh#L484) - maybe you can use that as a test case?
