### ISSUE TITLE
Pass correct mount type to agent for ephemeral volumes

### ISSUE THREAD

**Issue by YongjiXie** [kata-containers/runtime#1438]
Now we set volume's mount type to "ephemeral" to indicate ephemeral volumes. And this type will be passed to agent later. It's incorrect. Instead, "bind" should be the correct mount type to be passed.

**Comment by mcastelino** [comment]
@YongjiXie @amshinde a question. We do want ephemeral `memory` volumes to be created within the VM. Not on the host. Will this continue to be the case after this change.

**Comment by YongjiXie** [comment]
> 
> 
> @YongjiXie @amshinde a question. We do want ephemeral `memory` volumes to be created within the VM. Not on the host. Will this continue to be the case after this change.

Sure. We have passed storages like: storages:<driver:\"ephemeral\" source:\"tmpfs\" fstype:\"tmpfs\" mount_point:\"/run/kata-containers/sandbox/ephemeral/xxx\" > to agent. This will make agent mount tmpfs to the mount point. Then IIUC, we need a bind mount between container path and this mountpoint.

Thanks,
Yongji

**Comment by amshinde** [comment]
@YongjiXie What you described is how it is currently working in Kata.
