### ISSUE TITLE
revert #1405

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#1443]
rever https://github.com/kata-containers/runtime/pull/1405, since now the image has 2 MBRs and losetup can mount it without an offset 

cc @jodh-intel

**Comment by jodh-intel** [comment]
I *guess* this makes sense since we added the DAX/NVDIMM header but then removed it between releases. But there are images "out there" (such as `1.6.0~rc2-18`) containing the header, so maybe we should leave it in until we release `1.7.0`?

**Comment by devimc** [comment]
ooh I see, I didn't know that
