### ISSUE TITLE
Should add CNI and CNM tests

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#145]
_From @egernst on December 12, 2017 19:0_

Should introduce cni_tests and cnm_tests to virtcontainers.

_Copied from original issue: containers/virtcontainers#508_

**Comment by gabibeyer** [comment]
There is no longer a cni.go and cnm.go. It looks like cni is being done in the CRI layer: [commit](https://github.com/kata-containers/runtime/commit/99fa75842358ec1cc1f428edecb704349ac8478d), and the networking.go and networking_test.go handle the default cnm implementation: [commit](https://github.com/kata-containers/runtime/commit/44d2ec757c5c74eb5718cfb686a6537bf3584bd0)

@egernst Do you agree we can close this issue?
