### ISSUE TITLE
Does kata plan to support checkpoint/restore?

### ISSUE THREAD

**Issue by yyyeerbo** [kata-containers/runtime#1473]
Maybe we can use snapshot to achieve better checkpoint/restore than criu?

**Comment by devimc** [comment]
cc @gnawux @egernst

**Comment by soolaugust** [comment]
also want to know, 👍

**Comment by devimc** [comment]
@soolaugust I don't see this in the [kata 2.0 roadmap][1]. 

[1]: https://github.com/kata-containers/kata-containers/projects/2

**Comment by soolaugust** [comment]
I see. very excited if this could be supported.

**Comment by chris13524** [comment]
Can't this runtime just plug into [QEMU's checkpointing feature](https://wiki.qemu.org/Features/MicroCheckpointing)?

Also noting that this issue appears to be a duplicate of #184

**Comment by devimc** [comment]
@chris13524 yeah, QEMU micro checkpoints looks good, [CRIU](https://criu.org/Main_Page) should work too, maybe we can support both and let user choose the best
