### ISSUE TITLE
Missing runtime Makefile

### ISSUE THREAD

**Issue by sameo** [kata-containers/runtime#15]
The runtime repository is missing a top level Makefile for building and (at least for now) selecting one of the 2 runtimes to be installed.

The Makefile installation step should also always create a symbolic link from `kata-runtime` to the runtime of choice binary name.

For example, in the cc-runtime case:

```sh
$ export KATA_RUNTIME=cc
$ make # Calls into make -C cc-runtime build-kata-system
$ make install # Calls into make -C cc-runtime install-kata-system and creates a link from kata-runtime to the cc binary

```

**Comment by sameo** [comment]
cc @jodh-intel @bergwolf @gnawux @grahamwhaley

**Comment by grahamwhaley** [comment]
I think, as an interim measure (that is, until we have one unified runtime), this is the right thing to do, as it will install the one true name of `kata-runtime` and save us having to change it again in the future (will all the confusion that would bring to end users and testers).

Hopefully we will avoid any confusion on bug reports as to which `kata-runtime` binary is being used, as a `kata-runtime --version` or similar should end up in the reports and thus differentiate clearly.

**Comment by jodh-intel** [comment]
@sameo - sounds good to me.

@grahamwhaley - good point. I wonder if both runtimes should add some extra output to `--version` to make it clear which "source" runtime they were built from. That will allow users to avoid having to look for commits to work out which is which ;)
