### ISSUE TITLE
Split virtcontainers into smaller packages

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#150]
_From @sameo on February 21, 2018 14:40_

Currently all the virtcontainers code lives under the `virtcontainers` package, making code documentation not clear and all mixed together. See https://godoc.org/github.com/containers/virtcontainers

We should start splitting the code into different logical packages. For example:

- `api` for gathering the https://github.com/containers/virtcontainers/blob/master/documentation/api/1.0/api.md
- `utils` for the externally reachable utilities (things like `RunningOnVMM()` or `SerializeParams()`
- `agent` for adding all agent related structures and interfaces

_Copied from original issue: containers/virtcontainers#631_

**Comment by egernst** [comment]
_From @sboeuf on February 21, 2018 15:37_

This will certainly add some complexity into the code since we won't be able to access everything as easily as we do today, due to the fact that everything is from the same package `main`. Seems like a pretty big change for the purpose of clearer documentation.

**Comment by WeiZhang555** [comment]
Agree. This is necessary.

I am doing some refactoring, but it's not easy, I'll try to upstream some codes piece by piece.

**Comment by sboeuf** [comment]
An issue was already opened here: https://github.com/kata-containers/runtime/issues/66
Closing this one as this is a duplicate.

@WeiZhang555 I am fine if you want to work on this but we have higher priority tasks at the moment. And this one is not part of the 1.0 release.
