### ISSUE TITLE
Allow pod stop to be called several times

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#151]
_From @sboeuf on February 7, 2018 17:15_

We should  be able to call several times into pod stop, the call being a no-op if the pod has already been stopped.

_Copied from original issue: containers/virtcontainers#600_

**Comment by sboeuf** [comment]
The same way the container stop is idempotent, I think the pod stop should be idempotent too. This has to be implemented inside virtcontainers. This is a one line change, but the question is, do we think this is a good idea ?

**Comment by caoruidong** [comment]
I think it's a good idea. Is there any way to call sandbox stop multiple times? Sandbox stop() is called in delete, and then the pod is gone.
