### ISSUE TITLE
support-vsock: load vhost_vsock module if it isn't built-in

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/runtime#1512]
# Description of problem
In a few host machines, when vhost_vsock isn't built-in, but could be loadable, value `SupportVoscks` from `kata-env` still outputs false.
We add `modprobe -i vhost_vsock` in func `SupportsVsocks` to try to avoid above scenario.

# Expected result
```
[Host]
  Kernel = "5.0.7"
  Architecture = "arm64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "18.04"
  [Host.CPU]
    Vendor = "3rd Party Limited"
    Model = "v8"
```

# Actual result
```
[Host]
  Kernel = "5.0.7"
  Architecture = "arm64"
  VMContainerCapable = true
  SupportVSocks = false
  [Host.Distro]
    Name = "Ubuntu"
    Version = "18.04"
  [Host.CPU]
    Vendor = "3rd Party Limited"
    Model = "v8"
```
Related: #1195 #581

**Comment by stefanha** [comment]
@devimc This happens because /dev/vsock only exists after vhost_vsock.ko has been loaded.  QEMU opens /dev/vhost-vsock and this causes vhost_vsock.ko to be loaded.  Therefore SupportsVsocks() shouldn't call os.Stat(VSockDevicePath), just checking os.Stat(VHostVSockDevicePath) is enough.

**Comment by Pennyzct** [comment]
Hi~ @stefanha I'm Penny. ;). Correct me if I'm wrong, So as you say, even the vhost_vsock.ko hasn't been loaded at host firstly, we don't need to use`modprobe -i vhost_vsock` to load vhost_vsock.ko before using them, it will be automatically loaded when QEMU opens /dev/vhost-vosck.

**Comment by stefanha** [comment]
@Pennyzct Hi Penny!  Yes, that's correct since Linux 4.13.  Earlier Linux versions required manual loading of vhost_vsock.ko.
