### ISSUE TITLE
Incorrect implementation of burstable and best effort pods

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1534]
# Incorrect implementation of burstable pods

Today Kata containers starts a pod with 1 vCPU. 
We then ramp up the number of vCPUs based on the cpu.shares or cpu requests we see come in for the containers.

In the case of burstable pods with upper limits the upper limit is indicated by the quota and not the shares.

So to exhibit correct behavior we should scale up the CPUs based on shares and quota.

However we will still not have the right behavior for unbounded pods.

However at the very least we should do the right vCPU setup for all bounded pods.

If you see below the quota is available for bounded burstable CPU pods. Hence we should use the vCPUs based on that value.

**However unbounded pods will continue to be an issue for Kata and documented as a limitation**.

Here is how the shares are setup when using runc

```
/sys/fs/cgroup/cpu/kubepods/besteffort/cpu.shares
2
/sys/fs/cgroup/cpu/kubepods/besteffort/pod55148103-5666-11e9-9de2-525400123456/02f5cf17015d31beb2462857e1773754221712389d17df5a3a1e636bc04daaac/cpu.shares
2
/sys/fs/cgroup/cpu/kubepods/besteffort/pod55148103-5666-11e9-9de2-525400123456/1dad0913e3a373e1742ef9dbc707fbcaab65fa1d394d5dc5c7df6c6d36569db7/cpu.shares
2
/sys/fs/cgroup/cpu/kubepods/besteffort/pod55148103-5666-11e9-9de2-525400123456/6d50e7ca6b84fbd4195155e812e04e7b5976666818fe69e6d28832e63fae639f/cpu.shares
2
/sys/fs/cgroup/cpu/kubepods/besteffort/pod55148103-5666-11e9-9de2-525400123456/cpu.shares
2
```

```
/sys/fs/cgroup/cpu/kubepods/burstable/cpu.shares
1075
/sys/fs/cgroup/cpu/kubepods/burstable/pod41a37c57-5665-11e9-9de2-525400123456/31e7f4b8bfe5a23919d507c8d683ea97a83698f3e5f4abc13e4f5b401a26f3f1/cpu.shares
256
/sys/fs/cgroup/cpu/kubepods/burstable/pod41a37c57-5665-11e9-9de2-525400123456/62c5bf39f9bbd6dacb93b0a34e78f6c8db2ff0962bb90ad9ee564fb50b9c5554/cpu.shares
51
/sys/fs/cgroup/cpu/kubepods/burstable/pod41a37c57-5665-11e9-9de2-525400123456/cpu.shares
307
```

```
/sys/fs/cgroup/cpu/kubepods/besteffort/cpu.cfs_quota_us
-1
/sys/fs/cgroup/cpu/kubepods/besteffort/pod55148103-5666-11e9-9de2-525400123456/02f5cf17015d31beb2462857e1773754221712389d17df5a3a1e636bc04daaac/cpu.cfs_quota_us
-1
/sys/fs/cgroup/cpu/kubepods/besteffort/pod55148103-5666-11e9-9de2-525400123456/1dad0913e3a373e1742ef9dbc707fbcaab65fa1d394d5dc5c7df6c6d36569db7/cpu.cfs_quota_us
-1
/sys/fs/cgroup/cpu/kubepods/besteffort/pod55148103-5666-11e9-9de2-525400123456/6d50e7ca6b84fbd4195155e812e04e7b5976666818fe69e6d28832e63fae639f/cpu.cfs_quota_us
-1
/sys/fs/cgroup/cpu/kubepods/besteffort/pod55148103-5666-11e9-9de2-525400123456/cpu.cfs_quota_us
-1
```

```
/sys/fs/cgroup/cpu/kubepods/burstable/cpu.cfs_quota_us
-1
/sys/fs/cgroup/cpu/kubepods/burstable/pod41a37c57-5665-11e9-9de2-525400123456/31e7f4b8bfe5a23919d507c8d683ea97a83698f3e5f4abc13e4f5b401a26f3f1/cpu.cfs_quota_us
50000
/sys/fs/cgroup/cpu/kubepods/burstable/pod41a37c57-5665-11e9-9de2-525400123456/62c5bf39f9bbd6dacb93b0a34e78f6c8db2ff0962bb90ad9ee564fb50b9c5554/cpu.cfs_quota_us
10000
/sys/fs/cgroup/cpu/kubepods/burstable/pod41a37c57-5665-11e9-9de2-525400123456/cpu.cfs_quota_us
60000
/sys/fs/cgroup/cpu/kubepods/burstable/pod41a37c57-5665-11e9-9de2-525400123456/f876aa7433c71aec840afc385a39e1f3c1541c4521e148c3771e8679f040b788/cpu.cfs_quota_us
-1
/sys/fs/cgroup/cpu/kubepods/burstable/pod439651677ca7971bec7b2a9a0df5a512/1c3e8063c7bba7cf0e4b6e777704e56e5bdcbb15a794d36423a4734e6d5cb751/cpu.cfs_quota_us
-1
/sys/fs/cgroup/cpu/kubepods/burstable/pod439651677ca7971bec7b2a9a0df5a512/a0ff4137e61acf00ed6dc94212dbfba5161a7cb5fe20217e2cfaa1ba91474ae8/cpu.cfs_quota_us
-1
/sys/fs/cgroup/cpu/kubepods/burstable/pod439651677ca7971bec7b2a9a0df5a512/cpu.cfs_quota_us
-1
```

**Comment by mcastelino** [comment]
A potential fix for this can be
- unbounded pods continue to get the number of vCPUs as setup by the cluster admin in the kata toml file
   - That way the cluster admin control the behavior of unbounded pods
    - Setting it to -1 will give you **all** CPUs i.e. approximate the runc behaviour

- For bounded pods use quota if quota is higher than shares rounded up to the next higher CPU count

- Within the VM we enforce both the quota and the shares at container level, so we will get correct behavior within the VM


There is a related issue upstream in kubernetes which we also need to track https://github.com/kubernetes/kubernetes/issues/70585

**Comment by devimc** [comment]
@mcastelino you also need the period to calculate the number of vcpus

**Comment by mcastelino** [comment]
> @mcastelino you also need the period to calculate the number of vcpus

@devimc agree

**Comment by devimc** [comment]
> So to exhibit correct behavior we should scale up the CPUs based on shares and quota.

you mean period and not shares, right?  because I don't understand how shares can affect the number of vcpus 


> cpu.shares
    contains an integer value that specifies a relative share of CPU time available to the tasks in a cgroup. For example, tasks in two cgroups that have cpu.shares set to 100 will receive equal CPU time, but tasks in a cgroup that has cpu.shares set to 200 receive twice the CPU time of tasks in a cgroup where cpu.shares is set to 100. The value specified in the cpu.shares file must be 2 or higher.

**Comment by egernst** [comment]
@devimc @mcastelino  - actually, today we size *just* based off of limits:

https://github.com/kata-containers/runtime/blob/master/virtcontainers/sandbox.go#L1703-L1714:

```
func (s *Sandbox) calculateSandboxCPUs() uint32 {
	mCPU := uint32(0)

	for _, c := range s.config.Containers {
		if cpu := c.Resources.CPU; cpu != nil {
			if cpu.Period != nil && cpu.Quota != nil {
				mCPU += utils.CalculateMilliCPUs(*cpu.Quota, *cpu.Period)
			}

		}
	}
	return utils.CalculateVCpusFromMilliCpus(mCPU)
```

**Comment by egernst** [comment]
@mcastelino @jcvenegas @devimc -- I'm not sure if there are any changes required.  We already size according to limits, and don't have a real capability to scale shares, AFAIU.  

@mcastelino - agreed?

**Comment by jcvenegas** [comment]
Given this pod:
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test-cpumanager-burstable-integer-limit-runc
spec:
  restartPolicy: Never
  containers:
  - name: busy
    image: busybox
    command: [ "top" ]
    resources:
      requests:
        cpu: 2
        memory: 100Mi
```


Looking to the cgroups cpu limits for that pod we can see at pod level (set by containerd/kubelet):
A pod with two containers is created (top and pause), the sum of cpu requested by the pod is 2 
```bash
#Pod period and quota
/sys/fs/cgroup/cpu/kubepods/burstable/podeb10e69e-8e49-11e9-ba74-525400123456$ cat cpu.cfs_period_us
100000
/sys/fs/cgroup/cpu/kubepods/burstable/podeb10e69e-8e49-11e9-ba74-525400123456$ cat cpu.cfs_quota_us
-1
#Containers period and quota
/sys/fs/cgroup/cpu/kubepods/burstable/podeb10e69e-8e49-11e9-ba74-525400123456$ cat */cpu.cfs_period_us
100000
100000
/sys/fs/cgroup/cpu/kubepods/burstable/podeb10e69e-8e49-11e9-ba74-525400123456$ cat */cpu.cfs_quota_us
-1
-1
```
With that information we use today we are not able to calculate the vcpus needed for the VM

But if we look to shares of pod we see:
```
sys/fs/cgroup/cpu/kubepods/burstable/podeb10e69e-8e49-11e9-ba74-525400123456$ cat cpu.shares
2048
```

And for its containers we see:

/sys/fs/cgroup/cpu/kubepods/burstable/podeb10e69e-8e49-11e9-ba74-525400123456$ cat */cpu.shares
2048
2
```

Where `2048` should be the 2 cpus requested and `2` is just an small number for the pause container.

Now my question is what should be the formula to calculate this?

`( shares /1024  )`

**Comment by egernst** [comment]
@jcvenegas  - it depends -- its relative to what the parent cgroup provides and what the siblings request: 
```
 cpu.shares: The weight of each group living in the same hierarchy, that translates into the amount of CPU it is expected to get. Upon cgroup creation, each group gets assigned a default of 1024. The percentage of CPU assigned to the cgroup is the value of shares divided by the sum of all shares in all cgroups in the same level.
```

**Comment by jcvenegas** [comment]
Oh, true, so to achive that it is needed to calculate the cpus for all levels
/fs/cgroups/cpu/ - all cpus
kubepods  - shares/(sum(siblings)) 
... 
until we reach the container level  

does it worth  to do this calculation for this cases? by doing a recursive calculation

**Comment by jcvenegas** [comment]
Well this calculation will work while threre is not cpu overcommit  -  If there are many   burstable pods 
this calculation based in a global parent and siblings data is going to be  not reliable - right ? @mcastelino @egernst @devimc
