### ISSUE TITLE
cri-containerd fails removing cni network using cc-runtime

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#154]
_From @jcvenegas on December 15, 2017 4:38_

Using cc-runtime 3.0.10 cri-containerd fails when ModelMacVtap is used.

I changed cri-containerd to delete the network after the pod is destroyed, the pod is destroyed without errors but when cri-runtieme tries to remove the network thorugh the cni plugin it fails
The runtime calls done for this are:
craete network
cc-runtime create (a pod)
...
cc-runtime delete pod
delete network

deleten network fails when calling:
https://github.com/kubernetes-incubator/cri-containerd/blob/v1.0.0-alpha.1/pkg/server/sandbox_stop.go#L65

Returning  the following error:
running [/sbin/iptables -t nat -D POSTROUTING -s fe80::ccd:49ff:fed1:4f24/64 -j CNI-ec2256ee84ff75fb9ea71d56 -m comment --comment name: "containerd-net" id: "f204e2899981201fb06ea427d077c74d6c041d60b07262ff631594d8d2291180" --wait]: exit status 2: iptables v1.6.0: invalid mask `64' specified

I followed @mcastelino suggestion to try with ModelBridged and the error does not happen.

The CNI configuration is default used by cri-containerd:
https://github.com/kubernetes-incubator/cri-containerd/blob/v1.0.0-alpha.1/hack/install-deps.sh#L106

_Copied from original issue: containers/virtcontainers#517_

**Comment by egernst** [comment]
@jcvenegas you have suggested next steps on this?

**Comment by egernst** [comment]
@jcvenegas -- any updates here?  @mcastelino - I'd like to get the root-cause understood and documented.

**Comment by jcvenegas** [comment]
This is already fixed using latest cri-containerd versions.
