### ISSUE TITLE
Dockerfile volumes using 9p

### ISSUE THREAD

**Issue by awprice** [kata-containers/runtime#1561]
When running a Docker image on Kata that has a volume specified in the Dockerfile, for example:
```Dockerfile
FROM ubuntu

VOLUME ["/test-vol-123"]
```
The volume in the Dockerfile is created using 9p. Any data read/written to that volume whilst the container is running is slow (because it is using 9p).

This becomes a massive issue when running database containers such as Mysql, Postgres, Mongo etc. as they setup a volume for data to be stored in their Dockerfile. See the following example Dockerfiles:

Mysql: [Dockerfile#L67](https://github.com/docker-library/mysql/blob/a7a737f1eb44db467c85c8229df9d886dd63460e/8.0/Dockerfile#L67)
Postgres: [Dockerfile#L168](https://github.com/docker-library/postgres/blob/7e80419825e4bab4e749bc61334570ffc261ea5e/11/Dockerfile#L168)

Operation of the above databases become very slow inside Kata, even though for us the rootfs of the container inside the Kata VM is using device mapper.

This issue is very similar to https://github.com/kata-containers/runtime/issues/1429, but we cannot use emptyDir and override the volume, as we will be running Docker images with different volumes specified in the Dockerfile.

**Comment by bergwolf** [comment]
Duplicates with #198. We do not pass a dm based volume as a block device to the guest, because it is mounted on the host as well. Dual mounting the same device on two operating systems (host + guest) is problematic and can cause unexpected results.

That said, we already do it for dm based container rootfs, toggled by the `disable_block_device_use` config flag. Maybe we should do the same for volumes as well, just to be sane in our own logics.

**Comment by grahamwhaley** [comment]
@bergwolf Indeed. Double mounting is bad :-) If we can guarantee one of the mounts is readonly (which I guess is sort of what we do with the rootfs?), then maybe it is safe. Do we think we can make the host-side mount point (dynamically) RO, and things on the host side will be OK?
And, watch out for RO - iirc, for some filesystem types (journaled), we need to ensure they will not read the journal and try to replay anything or try to modify the superblock.

**Comment by grahamwhaley** [comment]
Just to note, I would **love** us to find a solution to have non-9p mounted volumes...

**Comment by amshinde** [comment]
@bergwolf Afaiu, docker volumes are always created as a directory under /var/lib/docker/volumes. 
Adding this for ref: https://github.com/moby/moby/issues/27215
As per the issue, if one wanted to use devicemapper for volumes, a separate volume driver would need to be used.(Something like https://github.com/containers/docker-lvm-plugin)

Using this and having support mentioned in #198 to pass dm-based volumes could be a possible solution for this issue.

If the user can provide a raw block device, this PR addresses the issue about auto-mounting it at the desired directory inside the container:
https://github.com/kata-containers/runtime/pull/882
I was initially not inclined towards this as this moves away from runc behaviour, but I think this could be a useful (configurable)solution for Kata. Wdyt @bergwolf ?

**Comment by bergwolf** [comment]
@amshinde Yes, I agree that we can make `-v /dev/sdc:/data` mount in the guest and it is useful for users who need block device based volumes, despite that it breaks runc compatibility. However, it does not solve @awprice's issue because the volume is created in the docker file and it gets passed to runc/kata-runtime as a mounted directory in the OCI spec IIUC.

**Comment by awprice** [comment]
Yep @bergwolf is absolutely right, this is an issue with volumes in the OCI spec in the Docker image. 

We are using Containerd + CRI for provisioning our Kata containers, so the paths of the volumes on the host side look something like: `/var/lib/containerd/io.containerd.grpc.v1.cri/containers/3357af71d81dff37f4df9a6b2f93b871e07f5cb7256aeae66433d8255205a6c6/volumes/8e0a2be7fa920c67dc4dd76893dc3527d353397319a59dc6796497ae0bada99c`.

CRI extracts the volumes from the OCI image spec and appends them to the volumes in the runtime spec. Maybe this could be a CRI modification?

I don't think we can do anything fancy like in https://github.com/kata-containers/runtime/pull/1485, where we moved emptyDir's to being provisioned in the sandbox container.
