### ISSUE TITLE
consider vendoring cni plugins

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#157]
_From @jodh-intel on May 26, 2017 16:27_

virtcontainers has a dependency on CNI (maintained using the `dep` tool.

The CI scripts also make use of CNI by building the network plugins (see  `utils/virtcontainers-setup.sh`).

However, that script pulls the tip of the CNI repository whereas virtcontainers is using a specific commit.

Recently, the CNI plugins used by the CI scripts where moved to a new repository (see #271). This broke our CI build as `utils/virtcontainers-setup.sh` was still `git clone`-ing from the old repository.

Rather than pulling from the tip of the containernetworking repository, we should consider vendoring (or using something like `versions.txt` in https://github.com/01org/clr-oci-runtime) to ensure that the CI scripts are in sync with the version of containernetworking code used by virtcontainers itself.

_Copied from original issue: containers/virtcontainers#273_

**Comment by egernst** [comment]
@jodh-intel this sounds reasonable (still), though I'd want to make sure that we continue to test against HEAD and move forward with CNI.  @chavafg - can we track updates to this repository much like how we do for k8s/crio?

**Comment by egernst** [comment]
_From @jodh-intel on February 15, 2018 16:56_

/cc @mcastelino, @sboeuf.

**Comment by gabibeyer** [comment]
@egernst @amshinde Doing some clean-up. Looks like we can close this issue and possibly delete virtcontainers/utils/virtcontainers-setup.sh, thoughts?
