### ISSUE TITLE
/usr/bin/qemu-lite-system-x86_64 meet Wrong!!!

### ISSUE THREAD

**Issue by xiaoding945** [kata-containers/runtime#1576]
# Description of problem
I follow steps as :
https://github.com/kata-containers/documentation/blob/master/install/docker/centos-docker-install.md

# Expected result

when I run command "docker run busybox uname -a".
Results as follows:
![image](https://user-images.githubusercontent.com/19324666/56562197-7f548700-65db-11e9-8c40-680bdcce6a27.png)

# Actual result
when I don't use kata setting ,just use docker ,i can run command successful

**Comment by xiaoding945** [comment]
docker info :
![image](https://user-images.githubusercontent.com/19324666/56562965-41586280-65dd-11e9-9eb8-b99b30575d65.png)

**Comment by xiaoding945** [comment]
I have solved this problem ,because i use librbd.so file is tooooo old. ummm ，so sorry

**Comment by grahamwhaley** [comment]
@xiaoding945 - no problem! - thanks for reporting, and letting us know what you found. It is good to have the history recorded here on github so others can search if they hit a similar problem!
