### ISSUE TITLE
Support Memory constrains

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#158]
_From @devimc on January 22, 2018 15:1_

- [x] hot add/remove memory
    issue https://github.com/kata-containers/runtime/issues/625
    pull request https://github.com/kata-containers/runtime/pull/624
- [x] apply memory cgroups in the guest
    issue https://github.com/kata-containers/runtime/issues/653
    pull request https://github.com/kata-containers/runtime/pull/654
- [x] track how much memory is being used for all containers and decide if a new chunk of memory must be added or not
https://github.com/kata-containers/runtime/pull/624
- [x] check if the maximum number of memory slots impacts container memory footprint
https://github.com/kata-containers/runtime/pull/580#issuecomment-418219019

Notes:
* on x86 only chucks/multiples of 128mb can be added
* memory hot remove is not possible

_Copied from original issue: containers/virtcontainers#578_

**Comment by jcvenegas** [comment]
WIP: https://github.com/jcvenegas/runtime-1/tree/memory-hotplug

**Comment by linzichang** [comment]
@jcvenegas @bergwolf Hi, I have seen cpu-hotplug support for "docker update" is done.  About "memory-hotplug", I find there is already some implementations like "hotplugMemory", but they haven't combined with kata-runtime update yet. What is the plan for this?
