### ISSUE TITLE
Hooks should be a per container resource

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#159]
_From @sameo on January 31, 2017 11:34_

Hooks are specifically designed for OCI containers, and there could be a set of hooks per container, not per pod.

_Copied from original issue: containers/virtcontainers#104_

**Comment by gabibeyer** [comment]
@egernst @amshinde Was this resolved by moving the OCI hooks out of virtcontainers and into the CLI?

**Comment by bpradipt** [comment]
Current OCI hook implementation in Kata is per container. However as per my understanding the hooks will run for all the containers in a pod.
@egernst @jodh-intel can this issue be closed ?
