### ISSUE TITLE
Enable mount namespace

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#160]
_From @amshinde on May 6, 2017 1:47_

A new mount namespace needs to be created before performing mounts

_Copied from original issue: containers/virtcontainers#236_

**Comment by devimc** [comment]
@amshinde @egernst  I'll be working on this

**Comment by bpradipt** [comment]
@jodh-intel @devimc this issue is stale and going through the past discussions it appears to be a big change with no easy solution. Should we close this issue to keep the backlog numbers saner ?

**Comment by devimc** [comment]
@bpradipt  thanks, I agree, I'll close it
