### ISSUE TITLE
some question about kata shim v1/v2

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#1602]
# Description of problem

Here are some question I see in my test, not sure should be fixed

# shim v1 interface
 use shim v1 interface,  after kill a task use ctr, container state pid should be -1
```
# ctr run -d docker.io/library/busybox:latest kk1 top
# kata-runtime list | grep kk1
kk1                                                                4992        running     /home/t4/pouch/containerd/state/io.containerd.runtime.v1.linux/default/kk1                                                                2019-04-28T15:01:51.342150578Z   #0
ctr t kill kk1
[root@daishu-test ~]# ./kata-runtime list | grep kk1
kk1                                                                4992        stopped     /home/t4/pouch/containerd/state/io.containerd.runtime.v1.linux/default/kk1                                                                2019-04-28T15:01:51.342150578Z   #1184 
```

# shim v1 interface
With shim v2,  after called kill , container status not changed, but task alreay stop, but kata-runtime list shows the container is still running
```
# ctr run --runtime kata.v2 -d docker.io/library/busybox:latest v2-k2 top
# ctr t ls | grep v2-k2
v2-k2                                                               5412     RUNNING
# ctr t kill v2-k2
# ctr t ls | grep v2-k2
v2-k2                                                               5412     STOPPED
# kata-runtime list | grep v2-k2
v2-k2                                                              -1          running     /home/t4/pouch/containerd/state/io.containerd.runtime.v2.task/default/v2-k2                                                               2019-04-28T15:20:46.735636968Z   #0

```

containerd-shim-v2 not set container status to stop when container exit in wait() goroutine, and in Cleanup interface, it will trigger one more signal to process, I think it can be avoid
```
    if oci.StateToOCIState(status.State) != oci.StateStopped {
        err := sandbox.KillContainer(cid, syscall.SIGKILL, true)
        if err != nil {
            logrus.WithError(err).WithField("container", cid).Warn("failed to kill container")
            return err 
        }   
    }   
```
The logic will not cause error but I think it is not correct

**Comment by lifupan** [comment]
@Ace-Tang  Yes, I think we can improve it by moving the stop container logic into wait section, in which to stop the specific container once shimv2 monitored the process exited.

**Comment by lifupan** [comment]
Hi @Ace-Tang , I think this issue can be fixed by pr https://github.com/kata-containers/runtime/pull/1723, can you have a test and close this issue?

**Comment by lifupan** [comment]
@Ace-Tang Can you have a check is this issue still existed?
