### ISSUE TITLE
Upgrade firecracker to 0.16.0

### ISSUE THREAD

**Issue by mcastelino** [kata-containers/runtime#1626]
# Description of problem

Upgrade firecracker to the latest 0.16.0

**Comment by mcastelino** [comment]
Firecracker has made certain machine-config fields mandatory. However the go-swagger generated code will omit boolean fields with value false. The swagger definition needs to be updated to reflect that the fields need to be mandatory to fix this issue.

We can upgrade to firecracker once this PR gets merged and the go-sdk regenerates the code. https://github.com/firecracker-microvm/firecracker/pull/1083

**Comment by acatangiu** [comment]
firecracker-microvm/firecracker#1083 was merged

**Comment by acatangiu** [comment]
Are you using `latest` Firecracker version in `master` or are you using the latest released version (`0.16.0`)?

The released version does not have this problem. The `machine-config` related changes have not been released yet (they came after the release).

**Comment by grahamwhaley** [comment]
Hi @acatangiu - so far we have been tracking released versions, and not the `master/HEAD`. Normally I think we'd track a version to ensure some stability, as we use it in our CI to check `kata` is stable against `fc` (that is, we are testing `kata` in our CI, not the leading edge changes in `fc` iyswim).
The version we test against is held in our versions file in this repo at https://github.com/kata-containers/runtime/blob/master/versions.yaml#L73
Currently `v0.15.2`.

**Comment by mcastelino** [comment]
@acatangiu I pulled master. I will retest with the actual release.
