### ISSUE TITLE
kata_agent: Fix kata channel name (virtio)

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#165]
_From @sboeuf on January 12, 2018 21:31_

The name of the virtio channel referring to the agent should not be defined inside `kata_agent.go`, but instead should be imported from `github.com/kata-containers/agent/api` package.

_Copied from original issue: containers/virtcontainers#558_

**Comment by bpradipt** [comment]
From the code this issue still remains.
https://github.com/kata-containers/runtime/blob/master/virtcontainers/hypervisor.go#L68
https://github.com/kata-containers/agent/blob/master/api.go#L15

However this issue becomes irrelevant for Kata 2.0 given the migration to rust agent.

Closing this issue. @devimc @jodh-intel hope this is fine.
