### ISSUE TITLE
Add kernel_params as K8s annotation in addition to hypervisor, kernel, and image.

### ISSUE THREAD

**Issue by eadamsintel** [kata-containers/runtime#1655]
At https://github.com/kata-containers/runtime/blob/master/virtcontainers/pkg/annotations/annotations.go there is no annotation to customize the kernel boot parameters.  For an Intel(r) QuickAssist card there are multiple versions out there each with their own kernel modules. It would be convenient to build one kata rootfs with all the QAT modules but use a kubernetes yaml file to specify which kernel modules to load on boot that is dependent on which QAT card is used. This could be done with a kermel_params value where the modules to load are specified.

**Comment by mythi** [comment]
@eadamsintel thanks for reporting this. I noticed this gap too but did not yet check what it needs to have implemented (I was thinking I could help getting this done)

**Comment by jodh-intel** [comment]
Thanks! That sounds like an offer @mythi! Feel free to assign the issue to yourself :smile:

The place to start looking at this is [`HypervisorConfig.assetPath()`](https://github.com/kata-containers/runtime/blob/master/virtcontainers/hypervisor.go#L398). However, I think this could be slightly more involved than the other assets. The reason being we need to decide how to handle user-specific kernel params set in the config file with [`kernel_params=`](https://github.com/kata-containers/runtime/blob/master/cli/config/configuration-qemu.toml.in#L30) when a `KernelParams` annotation is found.

If you look, there are unit tests to ensure the correct behaviour for `kernel_params=` currently (user params always take priority (get appended to the kernel cli) over any params the runtime currently specifies. That is the least surprising approach for users so we should continue with that if at all possible. Whatever is decided though, we will need:

- new unit tests for the new `KernelParams` annotation

  These will need to explicitly test `kernel_params=` behaviour too.

- documentation explaining the priority ordering of kernel params.

**Comment by mythi** [comment]
>  Feel free to assign the issue to yourself

Looks like I cannot do this myself. Anyway, I started working on this.

> user params always take priority (get appended to the kernel cli)

I think this how parameters from the annotation should be handled too. Just append them to what is already configured.

My biggest open right now is `Asset` that seems to assume annotations contain paths only. and `KernelParams` easily becomes a "special case" among other assets. I'm thinking of abusing `.path` for storing a raw string...

**Comment by grahamwhaley** [comment]
@mythi yeah, github will only allow it to be assigned if you are a member of the project....
@jodh-intel - is this related to the on-going discussion on adding the ability to modify any config file param via an annotation? If so, I'll /cc @mcastelino here then - and maybe we can assign this to him in the meantime..

**Comment by jodh-intel** [comment]
Yep, I think so - assigned.

**Comment by mythi** [comment]
Is the conversation available somewhere? I wonder what is included in `any config file param`. Just the hypervisor specific?

**Comment by jodh-intel** [comment]
@mythi - see: https://github.com/kata-containers/runtime/pull/1695.
