### ISSUE TITLE
Enable file based memory backend 

### ISSUE THREAD

**Issue by ganeshmaharaj** [kata-containers/runtime#1656]
Enable file based memory backing at `/dev/shm` on the host which will be used primarily (as of this writing) to be virtio-fs cache.

**Comment by renzhengeek** [comment]
Hi,

Currently, I can only start kata container with virtiofs by setting "enable_hugepages = true" in /etc/kata-containers/configuration.toml. Otherwise, kata will fail to create container using virtiofs.

Do you think it's the same issue here?

**Comment by egernst** [comment]
Yes @renzhengeek - that’s what Ganesh is working on resolving.
