### ISSUE TITLE
containerd-shim-kata-v2 process hangs when open stdin fifo

### ISSUE THREAD

**Issue by xs3c** [kata-containers/runtime#1659]
# Description of problem

When doing some benchmark testings, we encountered the containerd-shim-kata-v2 process hangs when open stdin fifo

# Expected result

the container is successfully started

# Actual result

the ctr run command would hang, the containerd-shim-kata-v2 process is blocked by open stdin fifo

---

**Comment by bergwolf** [comment]
So it is caused by ctr bug, right?

**Comment by xs3c** [comment]
> So it is caused by ctr bug, right?

Yes, but I did not dig it why the client does not open it, but it seems also reasonable that make stdin opened with O_NONBLOCK  in kata, at least the starting process of container is not blocked.
