### ISSUE TITLE
Generate an execID for every processes

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#166]
_From @sboeuf on December 22, 2017 20:32_

Virtcontainers should provide an ID to every processes started on every containers. The easy thing is for container's processes, we only need to use the `containerID` as the `execID`, and for the other case, that is `EnterContainer()`, we will generate a new unique ID.
It's important to get this ID generated from the runtime, so that we can provide it both to the shim and the agent. Indeed, the agent will expect such ID to spawn processes on behalf of the runtime, and those IDs have to match the ID from the shim.
This will be pretty straightforward to implement since we already have a `Token` field inside the `Process` structure.

_Copied from original issue: containers/virtcontainers#535_

**Comment by sboeuf** [comment]
This can be closed as it's handled through the `Process.Token`.
