### ISSUE TITLE
qemu-lite failed to enable vga when launching Kata container

### ISSUE THREAD

**Issue by zhiminghufighting** [kata-containers/runtime#1661]
# Description of problem
     When I reconfigure Qemu-lite launch parameter from “-vga none” to “-vga std” to enable vga in Kata runtime, it reports PCI unavailable error as below.
     Is there any dependence to enable vga? I ask some people and there is no dependence in kvm +qemu to launch an centos VM.

# Expected result

Launch Kata container successfully.

# Actual result

May 10 06:31:21 localhost.localdomain kata-runtime[28005]: time="2019-05-10T06:31:21.574044938-04:00" level=info msg="launching /usr/bin/qemu-lite-system-x86_64 with: [-name sandbox-c522a66fa441bb1eb5be1b2fcba79b7829e8922c09d2f51d077a5dba7732987b -uuid 3e6695d3-d12f-4bfe-b1e5-2369c0b96df2 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/c522a66fa441bb1eb5be1b2fcba79b7829e8922c09d2f51d077a5dba7732987b/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=8752M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/c522a66fa441bb1eb5
be1b2fcba79b7829e8922c09d2f51d077a5dba7732987b/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/usr/share/kata-containers/kata-containers-image_clearlinux_1.5.0_agent_a581aebf473.img,size=536870912 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/c522a66fa441bb1eb5be1b2fcba79b7829e8922c09d2
f51d077a5dba7732987b/kata.sock,server,nowait -device virtio-9p-pci,disable-modern=false,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/ru
n/kata-containers/shared/sandboxes/c522a66fa441bb1eb5be1b2fcba79b7829e8922c09d2f51d077a5dba7732987b,security_model=none -netdev tap,id=network-0,vhost=on,vhostfds=3,fds=4 -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:12:00:02,disable-modern=false,mq=on,vectors=4,romfile= -global kvm-pit.lost_tick_policy=discard -vga std -no-user-config -nodefaults -nographic -
daemonize -kernel /usr/share/kata-containers/vmlinuz-4.14.67.22-143.1.container -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootf
stype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=8 init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket -smp 1,cores=1,threads=1,sockets=1,maxcpus=8]" arch=amd64 clicreate container=c522a66fa441bb1eb5be1b2fcba79b7829e8922c09d2f51d077a5dba7732987b command=
create name=kata-runtime pid=28005 source=virtcontainers subsystem=qmp

level=error msg="Unable to launch /usr/bin/qemu-lite-system-x86_64: exit status 1" arc
h=amd64 clicreate container=c522a66fa441bb1eb5be1b2fcba79b7829e8922c09d2f51d077a5dba7732987b command=create name=kata-runtime pid=28005 source=virtcontainers subsystem=qmp
May 10 06:31:21 localhost.localdomain kata-runtime[28005]: time="2019-05-10T06:31:21.633469001-04:00" level=error msg="qemu-lite-system-x86_64: -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile=: PCI: slot 2 function 0 not available for pci-bridge, in use by VGA\n" arch=amd64 clicreate container=c522a66fa441bb1eb5be1b2fcba79b7829e8922c09d2f51d
077a5dba7732987b command=create name=kata-runtime pid=28005 source=virtcontainers subsystem=qmp

**Comment by grahamwhaley** [comment]
Hi @zhiminghufighting - what are you trying to achieve? Were you hoping that the container would then gain access to the hosts VGA controller, or? It might help us understand your goal and how to achieve it :-)

For reference, in case it helps, there is a guide on how to pass GPU in/out of Kata at https://github.com/kata-containers/documentation/blob/master/use-cases/GPU-passthrough-and-Kata.md
And there is a link to a container that can help get X11 working in a container (including a kata container) at https://github.com/kata-containers/documentation/wiki/UserGuide#x11-containers

**Comment by jodh-intel** [comment]
@zhiminghufighting - qemu-lite is extremely minimal (by design), so doesn't have graphical support enabled. We disable all graphics at build time - see:

- https://github.com/kata-containers/packaging/blob/master/scripts/configure-hypervisor.sh#L206

**Comment by zhiminghufighting** [comment]
@grahamwhaley  The background is here: i want to launch android based container image in Kata which is used to support cloud gaming. As you know, lots of gaming is running on billion mobile devices with Android OS in China. there is a big request to enable android container in Kata. After i launch Kata container with android based image with our OTC android in container team and found there is an android key process --surface finger can't be started normally caused by wrong framer buffer size. But if i need to get the framer buffer size, i need to enable vga in qemu-lite to support right framer buffer to start software render. Here android container needs a software render and framer buffer & virtual VGA is a mandatory option. The android container doesn't care about if there is a real VGA or GPU in host because it depends on software render library --opengl in android container image.
In above scenario, there is no need of hardware render in android container, so it doesn't depend on GPU GVT-g or GVT-d. I know and check all the related doc of enabling GPUs for kata in your link.
Thanks for your quick response.
Is there any other options for me to use vga?

**Comment by zhiminghufighting** [comment]
@jodh-intel please see the detail background and root cause of this requirement in above answer to Graham's question. 
I think you already answer the root cause of why the error log is reported by qemu-lite.
1. Can i enable gpu support by rebuild qemu-lite? If yes, is there any guide doc?
2. And if there is any other ways? I think even i enable gpu support to solve this issue, it will cause qemu-lite being heavy and increase the memory footprint and resource consumption.
thanks for your quick response!

**Comment by zhiminghufighting** [comment]
By the way, there would be a huge potential user scenario for Kata beside cloud is mentioned by me in above comment : gaming in cloud and cloud gaming based on android image container in chine.
Billions of android mobile device and thousands of gaming based on android OS.

**Comment by jodh-intel** [comment]
@zhiminghufighting - `qemu-lite` is a highly optimised version of qemu designed for "standard" sorts of container use-cases so doesn't include graphical support.

To just prove the concept, you could of course simply change your config to use the distro-packaged version of qemu which should contain graphics support:

```toml
path = "/usr/bin/qemu-system-x86_64"
```

Although you *could* rebuild `qemu-lite` to include graphic support, I don't think that is the best approach. Depending on the architecture, either [NEMU](https://github.com/intel/nemu) or `qemu-vanilla` would be better I think.

However, both those options are also built without graphical support so you would have to rebuild them with some of the graphical options we disable using https://github.com/kata-containers/packaging/blob/master/scripts/configure-hypervisor.sh.

However, you *may* need to make changes to the guest kernel configuration as that too is as minimal as possible for "normal" sorts of workloads.

We don't have documentation for this sort of scenario currently.

# Next steps

This is an interesting scenario but since it is going to require changes specifically for graphical support and since those may adversely affect memory density and boot speed, we'd need to study the idea carefully. We would also need additional tests, extra testing infrastructure and documentation.

As such, I suggest you raise an RFC issue using the main project repo (which we tend to use to discuss large features that potentially affect lots of different repos):

- https://github.com/kata-containers/kata-containers/issues/new

Then, send a mail to the mailing list referring to the issue and ideally present your idea at the Architecture Committee meeting so we can get more input from the entire community.

**Comment by zhiminghufighting** [comment]
@jodh-intel Good suggestion!I will collect the detail background and estimate the potential business impact for android image in kata container firstly and then prepare some material for the this user scenario.  thanks for your inputs!

**Comment by zhiminghufighting** [comment]
I will try the ways provided by you to make sure the feasibility of android in Kata container in next days.

**Comment by jodh-intel** [comment]
Thanks @zhiminghufighting.

**Comment by egernst** [comment]
@zhiminghufighting - I realize this is pretty stale now, but was pretty curious about the Android in Kata use case.  

Have you made more progress here, or have an end-to-end demo in this space?
