### ISSUE TITLE
network: arp conflict when use veth and bridge internetworking model

### ISSUE THREAD

**Issue by zhabinecho** [kata-containers/runtime#1673]
# Description of problem

The network configuration is veth onto physical interface eth0 and  bridge internetworking model. There are arp conflicts when ping the nic in guest from physical  interface eth0 on host. The veth response the arp request which is not expected.  

We use the network which like the aws.  https://github.com/aws/amazon-vpc-cni-k8s/blob/master/docs/cni-proposal.md

ip addr

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo

2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 00:16:3e:02:18:2f brd ff:ff:ff:ff:ff:ff
    inet 192.168.2.198/24 brd 192.168.2.255 scope global dynamic eth0

5: aws8db0408c9a8@if3: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether c2:3e:75:e2:ac:61 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 169.254.1.1/32 brd 169.254.1.1 scope global aws8db0408c9a8

 ip route

10.0.97.30 dev aws8db0408c9a8  scope link   <---------which is Pod ip

# Expected result

# Actual result

---

**Comment by zhabinecho** [comment]
I have pushed one patch to delete the veth IPs which can work fine :-)

**Comment by grahamwhaley** [comment]
Thanks @zhabinecho - are you intending to make a formal Pull Request with that patch? Details at:
https://github.com/kata-containers/community/blob/master/CONTRIBUTING.md#pull-requests

@amshinde , if you want to review in the meantime, patch is at https://github.com/zhabinecho/runtime/commit/f011e706db35f27a310b40c7719139c68f0f7077 I believe.
