### ISSUE TITLE
Fix NEMU machine_type back to 'virt' after virtio-fs issues are resolved.

### ISSUE THREAD

**Issue by ganeshmaharaj** [kata-containers/runtime#1713]
currently enabling virtio-fs with NEMU causes an issue with network access. Given that we are building static nemu for kata and shipping it with our tarball, switching the `machine_type` to `pc` for now to unblock use with virtio-fs. Once that network issue is resolved, we can revert back to using `virt` machine_type.

**Comment by egernst** [comment]
I see this is resolved by the following:
https://github.com/kata-containers/runtime/commit/6be5e5f1824fd9dde1e6775e91a4623d6ffe6c51

virt is the default, now.  Please re-open if I am mistaken!
