### ISSUE TITLE
Check if docker swarm works

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#174]
- Check to see if this limitation still exists: https://github.com/clearcontainers/runtime/issues/771.
- Identify the newest version of docker that the Kata runtime and components can work with.
  The ideal being that swam is supported with the same version of docker the other features are (in other words, no [`swarm-version` meta tag in the versions database](https://github.com/kata-containers/runtime/blob/master/versions.yaml#L106)).

**Comment by egernst** [comment]
it still doesn't work. Any custom network for docker will fail...

**Comment by egernst** [comment]
Tracking this failure in https://github.com/kata-containers/runtime/issues/175

**Comment by egernst** [comment]
Since this is defined as not-supported at this current time, I think we can close this issue (ie we cannot identify which version of docker we can support for swarm/compose test).
