### ISSUE TITLE
Kata debug console show the shell of android container wrongly instead of the shell of kata guest VM

### ISSUE THREAD

**Issue by zhiminghufighting** [kata-containers/runtime#1749]
# Description of problem

I enable kata image debug console by rebuild image and verify it works in centos/Ubuntu/busybox container images and i can enter Kata guest VM shell to view kata guest VM info.
But i connect the debug console of a running android container, the debug console will show the android container shell view instead of an kata guest VM shell view.

https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#create-a-custom-image-containing-a-shell 

# Expected result

the debug console will show the kata guest VM shell view.

# Actual result
1) error view of debug console based on a running android container:

[root@localhost ~]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
31bc2e1d785a        android:NAe000032   "/android-entry -c 0…"   18 hours ago        Up 18 hours         0.0.0.0:5555->5555/tcp   android0
5ceff5ce0746        centos              "/bin/bash"              18 hours ago        Up 18 hours                                  cocky_easley
[root@localhost ~]#
[root@localhost ~]#
[root@localhost ~]#
[root@localhost ~]# id=$(sudo docker ps -q --no-trunc)
[root@localhost ~]# echo $id
31bc2e1d785a7e1b3bcdca2e967c9284b632941bb29d2fd2a0aed92bb343410a 5ceff5ce074653bbb62902a9cfbc2c57d2e2106935a92d14a72e6942d4ad0515
[root@localhost ~]# console="/var/run/vc/vm/31bc2e1d785a7e1b3bcdca2e967c9284b632941bb29d2fd2a0aed92bb343410a/console.sock"
[root@localhost ~]# sudo socat "stdin,raw,echo=0,escape=0x11" "unix-connect:${console}"
[63414.771188] init: couldn't write 11297 to /dev/cpuset/camera-daemon/tasks: No such file or directory

bash-4.2# ls
bash-4.2# [63419.859353] init: couldn't write 11330 to /dev/cpuset/camera-daemon/tasks: No such file or directory

acct                   init.environ.rc              property_contexts
android-entry          init.houdini.rc              root
bugreports             init.logs.rc                 sbin
cache                  init.multidroid.rc           sdcard
charger                init.multidroid_cloud.rc     seapp_contexts
config                 init.multidroid_cloud.usb.rc selinux_version
d                      init.rc                      sepolicy
data                   init.usb.configfs.rc         service_contexts
default.prop           init.usb.rc                  storage
dev                    init.zygote32.rc             sys
etc                    init.zygote64_32.rc          system
file_contexts.bin      ipc                          ueventd.multidroid_cloud.rc
fstab.multidroid_cloud mnt                          ueventd.rc
init                   oem                          vendor
init.crashlogd.rc      proc
cloud:/ $ [63429.085860] init: couldn't write 11393 to /dev/cpuset/camera-daemon/tasks: No such file or directory

2)right view of debug console based on a running centos container:

[root@localhost ~]# docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS                    NAMES
31bc2e1d785a        android:NAe000032   "/android-entry -c 0…"   18 hours ago        Up 18 hours         0.0.0.0:5555->5555/tcp   android0
5ceff5ce0746        centos              "/bin/bash"              18 hours ago        Up 18 hours                                  cocky_easley
[root@localhost ~]#
[root@localhost ~]#
[root@localhost ~]# id=$(sudo docker ps -q --no-trunc)
[root@localhost ~]# echo $id
31bc2e1d785a7e1b3bcdca2e967c9284b632941bb29d2fd2a0aed92bb343410a 5ceff5ce074653bbb62902a9cfbc2c57d2e2106935a92d14a72e6942d4ad0515
[root@localhost ~]# console="/var/run/vc/vm/5ceff5ce074653bbb62902a9cfbc2c57d2e2106935a92d14a72e6942d4ad0515/console.sock"
[root@localhost ~]# sudo socat "stdin,raw,echo=0,escape=0x11" "unix-connect:${console}"

bash-4.2# ls
5ceff5ce074653bbb62902a9cfbc2c57d2e2106935a92d14a72e6942d4ad0515
5ceff5ce074653bbb62902a9cfbc2c57d2e2106935a92d14a72e6942d4ad0515-a4149e9ec4401367-resolv.conf
5ceff5ce074653bbb62902a9cfbc2c57d2e2106935a92d14a72e6942d4ad0515-c5d6b647daabcbfb-hostname
5ceff5ce074653bbb62902a9cfbc2c57d2e2106935a92d14a72e6942d4ad0515-d39b253b36397f78-hosts
bash-4.2# pwd
/run/kata-containers/shared/containers
bash-4.2# cd ..
bash-4.2# cd ..
bash-4.2# cd ..
bash-4.2# ls
dbus  kata-containers  libcontainer  mount  sandbox-ns  systemd
bash-4.2# cd ..
bash-4.2# ls
bin   dev  home  lib64       media  opt   root  sbin  sys  usr
boot  etc  lib   lost+found  mnt    proc  run   srv   tmp  var
bash-4.2#

--------------------------

Kata version: 1.7.0

**Comment by grahamwhaley** [comment]
/cc @devimc 
@zhiminghufighting - it would be really helpful if we could have some way to reproduce an android image run here to help debug - or, even something similar that had the same sort of docker run command, mount points, and permissions etc.

**Comment by devimc** [comment]
@zhiminghufighting thanks for raising this, some questions and comments:

* are you using initrd or rootfs image?
* how was the initrd/image generated?
* don't create the debug-console.service, try with `agent.debug_console` in the kernel command line https://github.com/kata-containers/agent/#enable-debug-console

**Comment by zhiminghufighting** [comment]
@devimc 
1. i use rootfs image;
2. according to this link to generate debug console;
https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#create-a-custom-image-containing-a-shell
3. by creating debug-console.service and maybe i use the wrong way, i will follow the way you mentioned.
Thanks a lot!

**Comment by zhiminghufighting** [comment]
@grahamwhaley @devimc  i will update the status of next action provide by @devimc  thanks in advance!

**Comment by egernst** [comment]
@zhiminghufighting -- what'd you find?

**Comment by egernst** [comment]
Hey @zhiminghufighting -- any updates here?

**Comment by zhiminghufighting** [comment]
@egernst Sorry for delay update! Currently mainly focusing on fix android container in kata issue and ignore this issue recently.

**Comment by zhiminghufighting** [comment]
@egernst new update for it. I enable kata VM console by setting agent.debug_console in the kernel command line. And here is the new logs:

init I 06-14 06:43:35  2002  2002 util.cpp:151] Created socket '/dev/socket/zygote_secondary', mode 660, user 0, group 1000
init I 06-14 06:43:35     1     1 service.cpp:791] starting service 'audioserver'...
init I 06-14 06:43:35     1     1 service.cpp:791] starting service 'cameraserver'...
init E 06-14 06:43:35  2004  2004 service.cpp:855] couldn't write 2004 to /dev/cpuset/camera-daemon/tasks: No such file or directory
init I 06-14 06:43:35     1     1 service.cpp:791] starting service 'media'...
init I 06-14 06:43:35     1     1 service.cpp:791] starting service 'netd'...
init I 06-14 06:43:35  2006  2006 util.cpp:151] Created socket '/dev/socket/netd', mode 660, user 0, group 1000
init I 06-14 06:43:35  2006  2006 util.cpp:151] Created socket '/dev/socket/dnsproxyd', mode 660, user 0, group 3003
init I 06-14 06:43:35  2006  2006 util.cpp:151] Created socket '/dev/socket/mdns', mode 660, user 0, group 1000
init I 06-14 06:43:35  2006  2006 util.cpp:151] Created socket '/dev/socket/fwmarkd', mode 660, user 0, group 3003
init I 06-14 06:43:35     1     1 service.cpp:791] starting service 'wificond'...
init I 06-14 06:43:35     1     1 service.cpp:791] starting service 'vendor.audio-hal-2-0'...
init I 06-14 06:43:42     1     1 action_manager.cpp:78] processing action (sys.sysctl.extra_free_kbytes=*) from (/init.rc:730)
init I 06-14 06:43:46     1     1 init.cpp:271] Received control message 'start' for 'wpa_supplicant' from pid: 2007 (/system/bin/wificond)
init E 06-14 06:43:46     1     1 init.cpp:279] No such service 'wpa_supplicant' for ctl.start
init I 06-14 06:44:16     1     1 action_manager.cpp:78] processing action (sys.boot_completed=1) from (/init.rc:724)
init I 06-14 06:44:16     1     1 action_manager.cpp:78] processing action (sys.boot_completed=1) from (/vendor/etc/init/hw/init.tenc.rc:8)
init I 06-14 06:44:16     1     1 service.cpp:791] starting service 'tenc_net'...
init I 06-14 06:44:16     1     1 action_manager.cpp:78] processing action (sys.boot_completed=1 && sys.logbootcomplete=1) from (/system/etc/init/bootstat.rc:70)
init I 06-14 06:44:16     1     1 service.cpp:791] starting service 'exec 4 (/system/bin/bootstat --set_system_boot_reason --record_boot_complete --record_boot_reason --record_time_since_factory_reset -l)'...
init I 06-14 06:44:16     1     1 sigchld_handler.cpp:88] Async property child exited with status 0
init I 06-14 06:44:16     1     1 sigchld_handler.cpp:88] Async property child exited with status 0
init I 06-14 06:44:16     1     1 sigchld_handler.cpp:88] Service 'exec 4 (/system/bin/bootstat --set_system_boot_reason --record_boot_complete --record_boot_reason --record_time_since_factory_reset -l)' (pid 2502) exited with status 0
init I 06-14 06:44:17     1     1 sigchld_handler.cpp:88] Service 'tenc_net' (pid 2501) exited with status 0

console:/ $
console:/ $ ls
aapt bugreports config default.prop init            init.usb.configfs.rc init.zygote32_64.rc metadata oem     sbin    sys        vendor
acct cache      d      dev          init.environ.rc init.usb.rc          init.zygote64_32.rc mnt      proc    sdcard  system
bin  charger    data   etc          init.rc         init.zygote32.rc     lost+found          odm      product storage ueventd.rc
console:/ $

**Comment by zhiminghufighting** [comment]
There is still android container rootfs view and logs being printed out. It may be a wrong action. Per my understanding, this 'console" should print out logs of kata VM and the view of kata vm rootfs instead of android container rootfs and logs.

**Comment by egernst** [comment]
Debug working now @zhiminghufighting ?
