### ISSUE TITLE
Support CRI metrics in Kata Containers

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#176]
Gathering container metrics is generally a non-standard process for the various tools in the container ecosystem.  We should support the base list of core-metrics.  Today there is a definition for these in CRI:
https://github.com/kubernetes/kubernetes/blob/master/pkg/kubelet/apis/cri/runtime/v1alpha2/api.proto#L83-L87

Kata Containers should make the necessary changes in the agent and runtime to support retrieval of these.

**Comment by devimc** [comment]
closing, shimv2 supports metrics
