### ISSUE TITLE
Hotplugged CPUs are not rounded up

### ISSUE THREAD

**Issue by gkhanna79** [kata-containers/runtime#1767]
# Description of problem

Assume we use the following values of _cpu_quota_ and _cpu_period_ to influence hotplugged vCPU count for a POD:

```
cpu_quota = 170000
cpu_period = 100000
```

Using the formula described [here](https://github.com/kata-containers/documentation/blob/master/design/cpu-constraints.md#container-with-cpu-constraint), the computed value is 2.69. Per [this](https://github.com/kata-containers/documentation/wiki/UserGuide#cpus), the computed value will be rounded up to 3.

However, the documentation [here ](https://github.com/kata-containers/documentation/blob/master/design/cpu-constraints.md#container-with-cpu-constraint)does not make a reference to the rounding up.

# Expected result

If a POD contains 1 container, it would be expected that 3 vCPUs will be hotplugged (excluding the default 1 vCPU). 
        
If a POD contains two containers, it would be expected 3 vCPUs to be hotplugged (excluding the default 1 vCPU) for each container. 

# Actual result

In each POD, we observe 2 vCPUs to be hotplugged per Container though, per documentation, POD1 should have gotten 4 (including the 1 default vCPU) and POD2 should have gotten 7 (also including the 1 default vCPU).

It appears that this behavior maybe due to uint casting done [here](https://github.com/kata-containers/runtime/blob/576b8a510c9cf8aa0656a34f1a562ffd2c246209/virtcontainers/utils/utils.go#L136).

**Comment by gkhanna79** [comment]
@egernst Filing per our offline discussion.

**Comment by egernst** [comment]
Thanks @gkhanna79 

@devimc - any chance you can take a look?  We have unit tests for this flow, but it is specific to Kubernetes based resource requests. I'd like to be able to

**Comment by egernst** [comment]
Hey @gkhanna79 - the logic is correct.  The document is wrong:
vCPU = Quota/Period.  mCPU = Quota/Period * 1000

I'll open an issue in the docs repo to get this fixed...

**Comment by gkhanna79** [comment]
Thanks for the confirmation @egernst. It makes everything sound reasonable now :)

**Comment by egernst** [comment]
@gkennedy12 -- closing this issue - let's track in error in vCPU calculation documentation #489

Thanks,
Eric
