### ISSUE TITLE
HV: Add kata-runtime support for ACRN hypervisor

### ISSUE THREAD

**Issue by vijaydhanraj** [kata-containers/runtime#1778]
Add ACRN as a supported hypervisor in kata-runtime

**Comment by gvancuts** [comment]
This definitely picked my curiosity...! I was trying to understand what this really means as my understanding of Kata is that it starts containers in QEMU-based VM (type-2 hypervisors), whereas ACRN is a type-1 hypervisor and runs bare-metal. Does this patch somehow turn ACRN into a type-2 hypervisor for this use-case or is this about being able to run Kata Containers inside Linux VMs that are already running as ACRN VMs (using nested virtualization)?
