### ISSUE TITLE
share file not ignore after copy to guest

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#1786]
# Description of problem

share file should be ignored after copy to guest successfully

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by egernst** [comment]
@Ace-Tang @bergwolf is this still an issue? Saw the PR closed, should we close this as well as it works as expected?

**Comment by Ace-Tang** [comment]
Yes, sorry to close the issue
