### ISSUE TITLE
Shim v2 CPU usage high when qemu exit

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#1824]
# Description of problem

There is a easy way to re-produce this issue.

```
1.  ctr run -d --runtime=kata.v2  docker.io/library/busybox:latest k-v2-test-30 top

2. ctr t kill k-v2-test-30
```

The shim CPU will get high, almost occupy one cpu, after some check, I think it is the grpc who alway trying to connect the down server.

```
/usr/local/go/src/syscall/asm_linux_amd64.s:18 +0x5\nsyscall.connect(0x3, 0xc0002dc110, 0x1e, 0x0, 0x0)
/usr/local/go/src/syscall/zsyscall_linux_amd64.go:1535 +0x50\nsyscall.Connect(0x3, 0xedc2c0, 0xc0002dc100, 0x0, 0xc0003ca000)
/usr/local/go/src/syscall/syscall_unix.go:240 +0x62\nnet.(*netFD).connect(0xc0002dc000, 0xee7e20, 0xc00053e480, 0x0, 0x0, 0xedc2c0, 0xc0002dc100, 0x0, 0x0, 0x0, ...)
/usr/local/go/src/net/fd_unix.go:70 +0x78\nnet.(*netFD).dial(0xc0002dc000, 0xee7e20, 0xc00053e480, 0x0, 0x0, 0xeea600, 0xc0004c1cc0, 0x0, 0xedc100, 0xc0004c1ca0)
/usr/local/go/src/net/sock_posix.go:149 +0xff\nnet.socket(0xee7e20, 0xc00053e480, 0xde70e9, 0x4, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, ...)
/usr/local/go/src/net/sock_posix.go:70 +0x1ab\nnet.unixSocket(0xee7e20, 0xc00053e480, 0xde70e9, 0x4, 0xeea600, 0x0, 0xeea600, 0xc0004c1cc0, 0xde6c7d, 0x4, ...)
/usr/local/go/src/net/unixsock_posix.go:45 +0x128\nnet.(*sysDialer).dialUnix(0xc00053d780, 0xee7e20, 0xc00053e480, 0x0, 0xc0004c1cc0, 0xc000066bb0, 0x517868, 0xbf3a98cf78d52cdc)
/usr/local/go/src/net/unixsock_posix.go:154 +0xa5\nnet.(*sysDialer).dialSingle(0xc00053d780, 0xee7e20, 0xc00053e480, 0xedfbe0, 0xc0004c1cc0, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/net/dial.go:565 +0x120\nnet.(*sysDialer).dialSerial(0xc00053d780, 0xee7e20, 0xc00053e480, 0xc0002f5df0, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0)
/usr/local/go/src/net/dial.go:524 +0x227\nnet.(*Dialer).DialContext(0xc000066ea8, 0xee7de0, 0xc000036088, 0xde70e9, 0x4, 0xc00046c025, 0x1b, 0x0, 0x0, 0x0, ...)
/usr/local/go/src/net/dial.go:406 +0x639\nnet.(*Dialer).Dial(0xc000066ea8, 0xde70e9, 0x4, 0xc00046c025, 0x1b, 0x0, 0x0, 0xedbcc0, 0xc0004d3e50)
/usr/local/go/src/net/dial.go:329 +0x75\nnet.DialTimeout(0xde70e9, 0x4, 0xc00046c025, 0x1b, 0x1cbac14c4f, 0xc0002ba7e0, 0x0, 0xedbc00, 0xc0004d0000)
/usr/local/go/src/net/dial.go:315 +0x9d\ngithub.com/kata-containers/runtime/vendor/github.com/kata-containers/agent/protocols/client.unixDialer.func1(0x0, 0xc0002ba7e0, 0xedbc00, 0xc0004d3e50)
```

![image](https://user-images.githubusercontent.com/10334997/59993546-34aac600-9683-11e9-841f-439a48072361.png)

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by grahamwhaley** [comment]
Good find @Ace-Tang - just to check, which version of Kata is this on - HEAD or ??
I think we had something similar not long ago that @lifupan fixed iirc. I have seen similar situations - high CPU consumption, but only after container exits. I suspect when customers have reported 'high CPU load', it has been caused by containers that have exited, not containers that are actively running.

**Comment by awprice** [comment]
@Ace-Tang @grahamwhaley Might be related to https://github.com/kata-containers/runtime/issues/1672?

**Comment by Ace-Tang** [comment]
@grahamwhaley ， the current master branch has this question

**Comment by Ace-Tang** [comment]
@awprice , I think it is caused by same problem, the grpc trying connect.

**Comment by lifupan** [comment]
As I has said in https://github.com/kata-containers/runtime/issues/1672#issuecomment-494267448, that issue was related with two issues: the first one was that qemu process would be killed by kubelet by accident, and the other  one was the same as this one. For the PR https://github.com/kata-containers/runtime/pull/1723 , it was just fixed the first issue.

**Comment by Ace-Tang** [comment]
@lifupan , yes, it fix the first one
