### ISSUE TITLE
Move CI to k8s 1.15

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#1836]
**Which feature do you think can be improved?**

K8s 1.15 is out

**How can it be improved?**

Move versions.yaml

**Additional Information**

Anything else to add?

We need to wait for cri-o to release an official 1.15 version, and check if the last containerd release is compatible with it or we should wait for one more release.

**Comment by GabyCT** [comment]
Closing this issue as we already enabled k8s 1.16
