### ISSUE TITLE
borken url: Clear Linux staless docs

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#1846]
# Description of problem

https://clearlinux.org/features/stateless is not longer working, lets update the docs

# Expected result

Point to as probably a more stable URL.
 https://github.com/clearlinux/clr-man-pages/blob/master/stateless.7.rst

**Comment by jodh-intel** [comment]
:heart:  it - borken is my favourite word of the week! :laughing:

**Comment by gnawux** [comment]
🤔 why did people change their URLs in this week together?

**Comment by jodh-intel** [comment]
I have no idea :smile: It's good to know the URL checker is actually working though.

Ideally, we'd have a daily / weekly CI run on `master` to identify these sorts of issues faster as it would be checking all the docs in a repo, not just those that a PR changed.

Related: https://github.com/kata-containers/ci/issues/101.
