### ISSUE TITLE
Implement the spec command

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#188]
The runtime does not implement the `runc spec` command that generates a basic `config.json`.

**Comment by caoruidong** [comment]
Can we just port runc's spec command here? Maybe we need to modify some comments. I can do this.

**Comment by grahamwhaley** [comment]
Hi @caoruidong 
There is a pending docs PR over at https://github.com/kata-containers/documentation/pull/48
I think if you check the `spec` section (potentially transient view at https://github.com/jodh-intel/documentation/blob/fa74ec5733dccf2a9bba3f7a9e91679562e59876/Limitations.md#spec-command), you'll find:

```
### spec command

The runtime does not implement the `spec` command. `runc` provides such
a command that generates a JSON-format template specification file that
is usable by the Kata Containers runtime. The addition of a `spec`
command to the Kata Containers runtime would just be duplication that
would likely always be playing catchup with `runc`.

See issue https://github.com/kata-containers/runtime/issues/188 for more information.
```

So, yeah, we could just call through to `runc` - the only downside I can think of is that our runtime would grow a tiny bit to handle that case.

Open to opinions here @sboeuf @egernst @jodh-intel
