### ISSUE TITLE
support x-pci-vendor-id and x-pci-device-id pass to qemu

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#1894]
**Which feature do you think can be improved?**

Support x-pci-vendor-id and x-pci-device-id pass to qemu when add vfio device.

**How can it be improved?**

As I have raised in https://github.com/intel/govmm/issues/97, in our production environment, some vendor id like 1ded can not be identified by virtio-pci driver, so I have to determine a specified vendor id pass to qemu

**Additional Information**

Anything else to add?

**Comment by devimc** [comment]
@Ace-Tang sounds good to me,  btw do you have enabled KSM in your production environment?
