### ISSUE TITLE
kata runtime library APIs

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#19]
Currently, both runv and cc-runtime imports the real runtime implementation from other orgs/repos (runv from `hyperhq/runv` and cc-runtime from `containers/virtcontainers`), to provide command line interfaces for kata runtime.

However, there are needs for runtime library APIs as well, e.g., hyperd and frakti make use of the runv library APIs directly rather than jump through command line APIs, which gives hyperd/frakti more functionality and better flexibility.

For kata, we should also define a set of kata runtime library APIs and provide them to users. In the meantime, the real runtime implementations should go in as well. The issue can work as a tracker for such discussions.

cc @gnawux @laijs @sameo @sboeuf @WeiZhang555

**Comment by sboeuf** [comment]
Well that's a good question ? Do we expect kata to provide such API ? If you look at CRI-O and CRI-containerd, they both rely on the runtime binary directly, assuming the runtime is compliant with OCI. Shouldn't frakti try to do the same ?
IMO, we taking the problem upside down here.

**Comment by bergwolf** [comment]
@sboeuf Both virtcontainers and runv already have the library APIs. My proposal is to consolidate them to provide kata library APIs, which aligns with the goal of merging cc and runv. Given that we want to represent kata rather than either virtcontainers or runv to consumers, it makes sense to converge the libraries as well. Once we merge the libraries, we would have kata library APIs. And the issue is to define such APIs. It is next step now that we have both cc and runv cli in place.

And IMO we should not decide consumer architectures. The discussion among CRI-O/CRI-containerd/frakti is others' fight. As an OCI runtime implementation, it is better for kata to stand neutral.

**Comment by laijs** [comment]
@sboeuf IIRC, fratki is not a yet another CRI-tool, nor a yet another CRI-O/CRI-containerd.
 It is the first implementation of the CRI which was originated born for fratki. It aims to leverage the best of vm containers to k8s. The aim will not be unchanged.

**Comment by sboeuf** [comment]
You're both right, we can have a library defining a high level API. I just want to make sure we try to define such a thing without relying on existing things like frakti so that we make this API convenient for an already exiting application. It would be more the other way around, which means we would define an API, and existing projects like frakti should adapt themselves to the newly defined API.

**Comment by bergwolf** [comment]
yes @sboeuf, frakti should be changed to use the new kata library API not the other way around.

**Comment by egernst** [comment]
I see this as addressed by https://github.com/kata-containers/documentation/blob/master/design/kata-api-design.md

Please re-open if I am mistaken.
