### ISSUE TITLE
tty output: May contain 'more data' than cc-runtime

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#20]
Running:
```
 docker run -ti --runtime=cc-runtime ubuntu dmesg | wc
   1445   11185  110388
```

gives a significantly different answer than:
```
docker run -ti --runtime=kata-runtime ubuntu dmesg | wc
   1364   10516  917504
```

The line and word counts look similar enough, but the byte count is very different.
Now, it may be that `kata` is passing some of the control characters out from the `dmesg` more verbosely or similar, but I've not figured out why yet. If anybody has any ideas, please chip in.

Found this when running https://github.com/clearcontainers/tests/blob/master/metrics/time/launch_times.sh#L101, which failed to find the 'end' of the kernel boot - I suspect as the output is so much larger we may have simply run out of buffer space somewhere in the script/shell.

**Comment by jodh-intel** [comment]
Confirmed - I'm seeing a lot of nul bytes and what appears to be occasional corruption in the output.

/cc @sboeuf.

**Comment by jodh-intel** [comment]
Actually, no corruption - just lots of nul byte padding ;)

**Comment by sboeuf** [comment]
Nothing obvious come to my mind but I'll take a look.

**Comment by sboeuf** [comment]
@grahamwhaley here is the fix: https://github.com/kata-containers/agent/pull/124

**Comment by grahamwhaley** [comment]
Just confirming this does look fixed with https://github.com/kata-containers/agent/pull/124, but now I see the possibly related https://github.com/kata-containers/agent/issues/125
