### ISSUE TITLE
Allow running unit tests with podman

### ISSUE THREAD

**Issue by marcov** [kata-containers/runtime#2006]
**Which feature do you think can be improved?**
 `make test`

**How can it be improved?**
docker in unit tests is basically used to: pull an image, create, export and rm a container.

It should be possible to run unit tests using podman, if the Docker daemon is not installed / running.

**Comment by grahamwhaley** [comment]
ack @marcov - I think this has vaguely been thought about before, but nobody has had time to look into it.

**Comment by marcov** [comment]
Adding it is some trivial, just try to use `podman` if `docker version` returns an error. I'll have a look at this.
