### ISSUE TITLE
is kata support virtualbox vm ?

### ISSUE THREAD

**Issue by damozhiying** [kata-containers/runtime#2018]
my physics host machine as below
 lsb_release -a
 are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.2 LTS
Release:	18.04
Codename:	bionic

use virtualbox  install ubuntu as below
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

host enabled cpu virtual  and virtualbox enable virtual as below
![2019-09-02 14-02-41屏幕截图](https://user-images.githubusercontent.com/10277950/64093356-99248880-cd8a-11e9-90e3-5415e0939be6.png)
![2019-09-02 14-05-31屏幕截图](https://user-images.githubusercontent.com/10277950/64093398-bce7ce80-cd8a-11e9-9075-9fc836884344.png)

**Comment by WeiZhang555** [comment]
As I know, virtualbox doesn't support nested virtualization, which mean you can't run another KVM virtual machine inside virtualbox.

So as the `kata-runtime check` showed, kata containers can't be run inside VirtualBox, it's not bug.

**Comment by cooltux008** [comment]
![image](https://user-images.githubusercontent.com/7871324/112786602-35a72d80-9089-11eb-9e35-8b59a6c4d9a8.png)

![image](https://user-images.githubusercontent.com/7871324/112786895-dac20600-9089-11eb-8bfe-387c6582af0c.png)

![image](https://user-images.githubusercontent.com/7871324/112786995-19f05700-908a-11eb-9a50-c414fd52c6c9.png)

When enabling the "nested virtualization"  in VirtualBox6.1,  the ```kata-runtime check``` is passed. 
But when the kata pod has been created, the node, which kata pod does run on,  becomes to be dormant. I think the component in wrong status is virtualbox

And I have also tested that on crio with kata, the node would be dormant too.

**Comment by fidencio** [comment]
Do I understand correct your VM has 2GB of RAM? That's way too low to run k8s on.
Try with at least 8GB and 4vCPUs.
