### ISSUE TITLE
Busybox container entrypoint started in abnormal state

### ISSUE THREAD

**Issue by clarklee92** [kata-containers/runtime#2032]
# Description of problem

Another issue, I started a busybox container with no command (which must be crash in runc pod) with kata.
But It turned running, I could login. `sh` as its No.1
```
/ # ps -ef
PID   USER     TIME  COMMAND
    1 root      0:00 sh
    9 root      0:00 sh
   17 root      0:00 ps -ef
```

**Comment by jodh-intel** [comment]
Hi @clarklee92 - could you provide more details please, ideally:

- The exact commands you ran with `runc` and Kata (with the output of each).
- Full versions details of all elements (or just the output of `sudo kata-collect-data.sh` pasted into a comment here).

**Comment by clarklee92** [comment]
@jodh-intel There is no command in my pod yaml. 
```
spec:
      containers:
      - image: busybox:latest
        imagePullPolicy: IfNotPresent
```
https://github.com/docker-library/busybox/blob/master/musl/Dockerfile  , the command `sh` should be exited if no args(like `sleep`) offered. But kata makes that container running, which is strange.

The output of `kata-collect-data.sh` list in #2031

**Comment by caoruidong** [comment]
I think default entrypoint is 'sh'. And if you give the container a tty, sh will not quit.
