### ISSUE TITLE
Add support for cloud hypervisor

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#2046]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

[ ] virtiofs support
[ ] Block device support
[ ] vsock support
[ ] [openapi client support](https://github.com/kata-containers/runtime/issues/2165)
[ ] [ci testing enabled ](https://github.com/kata-containers/tests/issues/2054)
[ ] [Provide as part kata containers release tarball](https://github.com/kata-containers/packaging/issues/792)
[ ] Unit testing

**Describe alternatives you've considered**

**Additional context**

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by ericooper** [comment]
As mentioned earlier I've got a working prototype so I'll use this issue as a reference for a WIP pull request for the cloud hypervisor prototype done so far.

**Comment by jcvenegas** [comment]
@jodh-intel thank you, we already sync in summary.

We are going to take @ericooper as base to then move to use cloud hypervisor http API. He already that is just move how we boot the VM today the rest of config launching of virtiofsd configurations not need any change at all.
