### ISSUE TITLE
config: some variables in configuration-qemu-virtiofs.toml are not replaced with actual values

### ISSUE THREAD

**Issue by chavafg** [kata-containers/runtime#2079]
# Description of problem
```
# XXX: Source file: "@CONFIG_QEMU_VIRTIOFS_IN@"

.
.
.

shared_fs = "@DEFSHAREDFS_QEMU_VIRTIOFS@"

```

**Comment by GabyCT** [comment]
@chavafg that was replaced with this PR https://github.com/kata-containers/runtime/commit/4134571e86ac7736f722a6937ce54fdced85ce11#diff-ebce02844da8831ba833219d9a0d0d36 , it seems that you are missing something in the MAKEFILE
