### ISSUE TITLE
Issues: we should add an 'issue template' for reporting

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#21]
We should discuss adding an 'issue template' to our repos, so we can request as much relevant information from end users at the time of Issue submission, rather than having to repeatedly ask them for one piece at a time etc.

**Comment by caoruidong** [comment]
we can close this since https://github.com/kata-containers/runtime/pull/93 is merged

**Comment by jodh-intel** [comment]
Good point @caoruidong - closing!
