### ISSUE TITLE
Can we support one pod with multiple containers that with GPU extended resource configured?

### ISSUE THREAD

**Issue by monstercy** [kata-containers/runtime#2120]
# Description of problem

Can we support one pod with multiple containers that with GPU extended resource configured?

Take GPU pass-through as an example:
```shell
docker run -it --runtime=kata-runtime --rm --device /dev/vfio/1 -v /dev:/dev debian /bin/bash
```
It need map the whole vm /dev path to container. If in K8S environments, we have one pod with two containers, each of container requests one GPU card,  one Pod is running on one VM, so the pod  has two GPU cards, but both of the two containers share the same vm /dev path. Both of the two cards are visible to every container.

I would like to know if my question is valid and is there any solution to this case?

Looking forward to your answer and support.

**Comment by devimc** [comment]
@monstercy your question is valid, to fix this "bug" we need to add support for devices cgroup, unfortunately we need to map the vfio device to the final device (the device created by the driver, ie /dev/dri/renderD128). For example in the host the device is `/dev/vfio/1` but in the guest we don't know what kind of device was hot plugged, hence we don't know what device path (ie /dev/dri/renderD128) we have to put in the devices cgroup.

**Comment by monstercy** [comment]
@devimc  thank you for your insightful answer. 
If the device name is fixed. Could you give me a guide on how to modify code to resolve the issue?

**Comment by devimc** [comment]
@monstercy more details about the complexity of this issue https://github.com/kata-containers/runtime/pull/701#issuecomment-419443916 , let me check the code to see what we can do
