### ISSUE TITLE
Fix running rootless

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#2132]
Issue colllecting what needs to be done to fix running rootless with podman for example:

- https://github.com/kata-containers/documentation/pull/565

# Tasks

- Fix range index

  https://github.com/kata-containers/runtime/blob/master/pkg/rootless/rootless.go#L93

  This should be `ids[2]` fwics.

**Comment by devimc** [comment]
# Tasks

make [`VCStoreUUIDPath`](https://github.com/kata-containers/runtime/blob/master/virtcontainers/store/vc.go#L273) rootless. uuid file shouldn't be created at `/var/` if `rootless`

patch #2134

**Comment by egernst** [comment]
@alicefr - FYI

**Comment by amshinde** [comment]
Related issue: https://github.com/kata-containers/runtime/issues/2177

**Comment by amshinde** [comment]
@jodh-intel I have raised https://github.com/kata-containers/runtime/pull/2178 to fix an issue with rootless. 
With this in place and using the latest podman(1.6.2-dev), I was able to run rootless containers on Ubuntu.

**Comment by c3d** [comment]
Tracked in Fedora as https://bugzilla.redhat.com/show_bug.cgi?id=1775164

**Comment by amshinde** [comment]
# Tasks

Fix running rootless with net=none
Issue: https://github.com/kata-containers/runtime/issues/2319
