### ISSUE TITLE
kata-qemu-virtiofs fails to launch container

### ISSUE THREAD

**Issue by brtknr** [kata-containers/runtime#2137]
# Description of problem

I built a kata-deploy container using 1.9.0-rc0 tag and deployed kata-deploy daemon-set on a kubernetes cluster. The kata-deploy part worked.  However, I am unable to launch containers with `kata-qemu-virtiofs` runtime class.

# Expected result

Run.

# Actual result

Failed create pod sandbox: rpc error: code = Unknown desc = failed to get sandbox runtime: no runtime for "kata-qemu-virtiofs" is configured

**Comment by devimc** [comment]
cc @GabyCT @egernst

**Comment by brtknr** [comment]
Aha, when I look inside /etc/containerd/config.toml, there is no entry for qemu-virtiofsd.

**Comment by brtknr** [comment]
I placed this config:

```
     [plugins.cri.containerd.runtimes.kata-qemu-virtiofs]
        runtime_type = "io.containerd.kata-qemu-virtiofs.v2"
        [plugins.cri.containerd.runtimes.kata-qemu-virtiofs.options]
              ConfigPath = "/opt/kata/share/defaults/kata-containers/configuration-qemu-virtiofs.toml"

```

And getting somewhat further as a result:

     Failed create pod sandbox: rpc error: code = Unknown desc = failed to start sandbox container: failed to create containerd task: runtime "io.containerd.kata-qemu-virtiofs.v2" binary not installed "containerd-shim-kata-qemu-virtiofs-v2": file does not exist: unknown

**Comment by GabyCT** [comment]
This https://github.com/kata-containers/packaging/commit/dab80870e2ff8a6271b0287cee625ad4d1068c31 tries to fix this issue

**Comment by egernst** [comment]
@brtknr - please try with latest release?  Thanks!

**Comment by jcvenegas** [comment]
No update in a long time - and 1.0 not supported anymore, closing this issue.
