### ISSUE TITLE
nofw can't use in kata-1.9

### ISSUE THREAD

**Issue by liangxianlong** [kata-containers/runtime#2151]
# Description of problem
Hello,I test ```nofw``` in kata-1.9,but i get an error
kernel and qemu config:
```shell
[hypervisor.qemu]
path = "/usr/bin/qemu-vanilla-system-x86_64"
kernel = "/usr/share/kata-containers/vmlinux.container"
image = "/usr/share/kata-containers/kata-containers.img"
machine_type = "pc"
```
machine_accelerators config:
```shell
machine_accelerators="nofw"
```
Then i start a container:
```shell
[root@host-69 1.9.0-stable]# docker run -ti --rm --runtime=kata-runtime busybox sh
docker: Error response from daemon: OCI runtime create failed: failed to launch qemu: exit status 1, error messages from qemu log: qemu-vanilla-system-x86_64: Property '.fw' not found: unknown.
[root@host-69 1.9.0-stable]#
```
# Expected result
But when i use qemu-lite,i can start the container
```shell
[hypervisor.qemu]
#path = "/usr/bin/qemu-vanilla-system-x86_64"
path = "/usr/bin/qemu-lite-system-x86_64"
kernel = "/usr/share/kata-containers/vmlinux.container"
image = "/usr/share/kata-containers/kata-containers.img"
machine_type = "pc"

# Optional space-separated list of options to pass to the guest kernel.
# For example, use `kernel_params = "vsyscall=emulate"` if you are having
# trouble running pre-2.15 glibc.
#
# WARNING: - any parameter specified here will take priority over the default
# parameter value of the same name used to start the virtual machine.
# Do not set values here unless you understand the impact of doing so as you
# may stop the virtual machine from booting.
# To see the list of default parameters, enable hypervisor debug, create a
# container and look for 'default-kernel-parameters' log entries.
kernel_params = ""

# Path to the firmware.
# If you want that qemu uses the default firmware leave this option empty
firmware = ""

# Machine accelerators
# comma-separated list of machine accelerators to pass to the hypervisor.
# For example, `machine_accelerators = "nosmm,nosmbus,nosata,nopit,static-prt,nofw"`
machine_accelerators="nofw"
```
```shell
[root@host-69 1.9.0-stable]# docker run -ti --rm --runtime=kata-runtime busybox sh      
/ #
```
kata-runtime version:
```shell
[root@host-69 ~]# kata-runtime --version
kata-runtime  : 1.9.0
   commit   : c772b3e15b403745be4ec51e32d9a58f0d65e499
   OCI specs: 1.0.1-dev
[root@host-69 ~]#
```
So, should we drive update to qemu  to modify this bug?

**Comment by devimc** [comment]
@liangxianlong `nofw` is a qemu-lite specific feature, but there are other alternatives if you want to boot uncompressed kernels, see https://stefano-garzarella.github.io/posts/2019-08-23-qemu-linux-kernel-pvh/

**Comment by liangxianlong** [comment]
@devimc  I see [https://stefano-garzarella.github.io/posts/2019-08-23-qemu-linux-kernel-pvh/](url).Another quesition,can we use ```nofw```and```template```at the same time accoding to [https://stefano-garzarella.github.io/posts/2019-08-23-qemu-linux-kernel-pvh/](url)

**Comment by devimc** [comment]
@liangxianlong I guess you meant `nofw` and `vmtemplating` ?  afaik  for `vmtemplating` you need qemu > 4.0 but these versions don't include support for `nofw`

**Comment by liangxianlong** [comment]
@devimc tks,i get it

**Comment by nixun** [comment]
> @liangxianlong I guess you meant `nofw` and `vmtemplating` ? afaik for `vmtemplating` you need qemu > 4.0 but these versions don't include support for `nofw`

does vm cache also has the requirement for qemu version? @devimc

**Comment by devimc** [comment]
@nixun yes, the current version of kata needs qemu 4.1 for `vmtemplating` , if you want to use nofw + vmtemplating you will need an old version of kata, 1.6 or 1.5 I think

**Comment by nixun** [comment]
> @nixun yes, the current version of kata needs qemu 4.1 for `vmtemplating` , if you want to use nofw + vmtemplating you will need an old version of kata, 1.6 or 1.5 I think
Thanks for your reply, but i still have a question, what's the difference between vmtemplating and vmcache in qemu? does vmcache still need new qemu?

**Comment by devimc** [comment]
@nixun 
> what's the difference between vmtemplating and vmcache in qemu?

https://github.com/kata-containers/documentation/blob/master/how-to/what-is-vm-cache-and-how-do-I-use-it.md 
https://github.com/kata-containers/documentation/blob/master/how-to/what-is-vm-templating-and-how-do-I-use-it.md

> does vmcache still need new qemu?

 I haven't tried with an old version, maybe @lifupan or @bergwolf can help you here
