### ISSUE TITLE
Add an force kill and cleanup mechinisam for Kata 

### ISSUE THREAD

**Issue by zhiminghufighting** [kata-containers/runtime#2152]
**Is your feature request related to a problem? Please describe.**
Sometimes there is a possibility of failing to kill kata container when issue a stop cmd especially lots of kata containers are being launched on debugging purpose. Under that condition, kata container may fail to exit and cleanup host left files.
So is there possible to add a configuration option in configuration.toml such as:
//When "force_kill_kata" is "yes", kata runtime will force to kill kata VM&container when user to
//issue a stop or kill container command whatever the cmd is executed successfully or not.
//This config is a protection cautions for user to auto release kata containers once stop/kill
//container cmd failed.
//default setting is no;
force_kill_kata=yes

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?Yes

**Comment by zhiminghufighting** [comment]
@egernst , could you please give comments about this requirement? This request is raised by PRC customers who plan to launching lots of Kata container and find some kata container can't be stopped randomly in low rate.

**Comment by egernst** [comment]
@bergwolf @lifupan wdyt?
