### ISSUE TITLE
How to limit disk size of vms?

### ISSUE THREAD

**Issue by shinebayar-g** [kata-containers/runtime#2168]
How to limit disk size of vms? Currently it looks like using all of the available disk space.

```
$ df -hT
Filesystem     Type   Size  Used Avail Use% Mounted on
kataShared     9p      58G  2.3G   56G   4% /
tmpfs          tmpfs   64M     0   64M   0% /dev
tmpfs          tmpfs  999M     0  999M   0% /sys/fs/cgroup
shm            tmpfs   64M     0   64M   0% /dev/shm
tmpfs          tmpfs  999M     0  999M   0% /proc/acpi
tmpfs          tmpfs  999M     0  999M   0% /sys/firmware
```

My apologies if this is not correct place to ask this question. Slack invite is not working.

**Comment by devimc** [comment]
This is not an issue in kata, you can set the limit size in the container engine, for example in [docker](https://docs.docker.com/engine/reference/commandline/dockerd/) you can set the limit using `--storage-opt overlay2.size=XXG` for overlay2 or `--storage-opt  dm.basesize=20G` for devicemapper

**Comment by shinebayar-g** [comment]
I see, so that was it. Thank you.
