### ISSUE TITLE
qemu-system-x86_64 not in 1.9.1+ release binaries

### ISSUE THREAD

**Issue by jcrowthe** [kata-containers/runtime#2175]
# Description of problem

`/opt/kata/bin/qemu-system-x86_64` is referenced in `/opt/kata/share/defaults/kata-containers/configuration-qemu.toml`. While this binary was included in the release up until 1.9.0, release 1.9.1 and the current 1.10.0-alpha0 do not contain this binary. As such, deployments fail.

# Expected result

`qemu-system-x86_64` should be included in the release binary.

# Actual result

`qemu-system-x86_64` is missing.

**Comment by egernst** [comment]
The GH release page version didn't match what was in katadocker/kata-deploy.  Our release process is migrating to leverage GH Actions, and it looks like container image is in good shape, while the static tarball has an issue.

As a first step, I modied GH page tarball to match what is tested and in container image.

This is pretty bad -- sorry you had to discover this.

**Comment by jcrowthe** [comment]
Thanks!
