### ISSUE TITLE
cpuset.mems: numerical result out of range

### ISSUE THREAD

**Issue by lauatic** [kata-containers/runtime#2176]
# Description of problem
My environment configured containerd with kata-runtime.  I followed the setup instructions on https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md#configuration and packaging/kata-deploy/scripts/kata-deploy.sh

When I create a kata container in this environment, I got this error message.  Anyone know how I can resolve this?

rpc error: code = Unknown desc = failed to create containerd task: Could not run process: container_linux.go:346: starting container process caused "process_linux.go:297: applying cgroup configuration for process caused \"failed to write 0,1 to cpuset.mems: write /sys/fs/cgroup/cpuset/k8s.io/f1fdd8d5be9030388e4e04dd7d42df9e77a3d46ecb4922ecb2936bf92f74595d/cpuset.mems: numerical result out of range\"": unknown 

kata-runtime  : 1.8.2
   commit   : cdc30296c370414d8ef445abd06378199775d076
   OCI specs: 1.0.1-dev

containerd github.com/containerd/containerd 1.2.4 e6b3f5632f50dbc4e9cb6288d911bf4f5e95b18e

$ cat /etc/containerd/config.toml. . .        [plugins.cri.containerd.runtimes.kata]
          runtime_type = "io.containerd.kata.v2"
          [plugins.cri.containerd.runtimes.kata.options]
            ConfigPath = "/etc/kata-containers/configuration.toml"
      [plugins.cri.cni]
        bin_dir = "/opt/cni/bin"
        conf_dir = "/etc/cni/net.d"
        conf_template = ""

(replace this text with the list of steps you followed)

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

**Comment by egernst** [comment]
I have seen this as well. The guest doesn't have a notion of topology at this point, and it doesn't make sense to set cpuset.mems. We should, however, set it on host side.

I'll resolve this failure first, then look at adding cpuset.mems support to the overall pod (we do this for cpuset.cpus on latest today).
