### ISSUE TITLE
unify command line API, configuration and annotations

### ISSUE THREAD

**Issue by laijs** [kata-containers/runtime#22]
Command line APIs, configuration file and annotations are parts of the cli API, they need to be unified. This unification is important for future fusing runv/cc into a single kata-runtime.

## command line API

Both command lines of runv/cc are compatible with runc. But there are some differences respectively which should be also compatible with each other.

## configuration file

cc has a global configuration file while runv doesn't. runv cli should use a configuration file(/usr/share/defaults/kata-containers/configuration.toml) like cc. But the details of the configuration file should be discussed more. 

## annotations

runv uses crio annotations, but it doesn't have its own annotations. However, cc has its own annotations with good definitions. To make runv/cc unified on annotations, it is better to rename the annotations of cc/virtcontainers to kata-containers' and make runv use these annotations.

**Comment by WeiZhang555** [comment]
A big :+1: 

Especially the configuration file, it's very useful and flexible.

**Comment by laijs** [comment]
> it is better to rename the annotations of cc/virtcontainers to kata-containers'

@sameo Would cc-team mind to do so?

**Comment by sameo** [comment]
@laijs Thanks a lot for opening this issue, those are 3 good points. My comments:

* CLI: When comparing both runtimes CLIs, the disjoint command sets are:
  * `runv` specific commands: `spec`, `manage`, `proxy`, `shim`, `network-nslisten`, `watcher`
  * `cc-runtime` specific commands: `cc-check`, `cc-env`

I can only talk about the cc-runtime commands here: Both `cc-check` and `cc-env` are debug/report tools that are quite useful. Especially `cc-env`: Issue reporters can dump its output and we know pretty much all their host setup. `cc-check` verifies that a given host can actually run hardware virtualized containers, which is also helpful when getting `Clear Containers do not work on my machine` type of issues. I think both could be ported to Kata, they're not CC specific and add some real value imho.
It would be interesting to get a description of the `runv` specific commands and understand which ones would be valuable to Kata as well.

* Configuration file
This is going to change a bit on our side, as we're probably going to remove some sections to make them as subsections. For the rest, we'd really like to hear what you guys would like to see added/removed/modified from the current config file structure.

* Annotations
Are you suggesting to move https://github.com/containers/virtcontainers/tree/master/pkg/annotations to a Kata Containers repo, or simply rename https://github.com/containers/virtcontainers/blob/master/pkg/annotations/annotations.go#L20 to e.g. `io.katacontainers." ?

**Comment by laijs** [comment]
- Command line APIs
 This problem might not be critical since both command lines of runv/cc are compatible with runc.
 And the additional subcommands would not become a big problem. Especially `proxy`, `shim`, `network-nslisten`, and `watcher` are hidden subcommands.  But runv has its own global flags and some unhandled global/subcommand flags compared with runv. These will be a problem of compatibility. Does cc have this issue?

- Could you please create a PR to add the configuration-file related code to kata-containers/runtimes/pkg/configuration and let us review the detail? (I just picked the random package path and random name, feel free to change it).

- Annotations
>  Are you suggesting to move https://github.com/containers/virtcontainers/tree/master/pkg/annotations to a Kata Containers repo, or simply rename https://github.com/containers/virtcontainers/blob/master/pkg/annotations/annotations.go#L20 to e.g. io.katacontainers. ?

Both, please. And move them to kata-containers/runtimes/pkg/annotations.

Is configuration-file for runtime global configuration and annotations for the individual container? I'm not sure about them.

**Comment by jodh-intel** [comment]
> But runv has its own global flags and some unhandled global/subcommand flags compared with runv. These will be a problem of compatibility. Does cc have this issue?

The commands we don't implement are listed in:

- https://github.com/clearcontainers/runtime/blob/master/docs/limitations.md#runtime-commands

There is also this limitation that isn't in the doc yet:

- https://github.com/clearcontainers/runtime/issues/565

Also, in addition to the CC-specific commands that @sameo has mentioned, we also have a few CC-specific options (`--cc-config=` and `--cc-show-default-config-paths`). Like the commands, we've "namespaced" these by prefixing with `--cc-*` as shown in `cc-runtime --help`.

**Comment by egernst** [comment]
Since we now have kata-runtime, and no cc-runtime/runv, let's call it unified.
