### ISSUE TITLE
Utilize map for newMounts to speed up replaceOCIMountSource

### ISSUE THREAD

**Issue by tedyu** [kata-containers/runtime#2212]
**Which feature do you think can be improved?**

Currently replaceOCIMountSource uses nested loop to match destinations of newMounts and ociMounts.

**How can it be improved?**

mountSharedDirMounts can return map for new mounts keyed by destination.
This way the inner loop of replaceOCIMountSource can become (one single) map lookup.

**Additional Information**

**Comment by tedyu** [comment]
@jodh-intel 
What do you think of this proposal ?

**Comment by jodh-intel** [comment]
@tedyu - sounds reasonable to me.

You might also want to enable runtime tracing in `configuration.toml` to see where the current code hotspots are as that sort of technique may help in other areas.

**Comment by tedyu** [comment]
@jodh-intel 
I am working on the PR.
Can you drop the needs-review label ?

Thanks

**Comment by jodh-intel** [comment]
Done.
