### ISSUE TITLE
Delete as many containers as possible

### ISSUE THREAD

**Issue by tedyu** [kata-containers/runtime#2236]
# Description of problem

In Sandbox#Delete,
```
	for _, c := range s.containers {
		if err := c.delete(); err != nil {
			return err
```
If single container deletion has error, we return.

# Expected result

I think we should delete as many containers as possible.

# Actual result

**Comment by grahamwhaley** [comment]
Maybe. In which case, make sure we still report the error for the one(s) that failed.

**Comment by tedyu** [comment]
@grahamwhaley 
There is some error aggregation code from kubernetes.

Is it Okay if I borrow that for error reporting ?

**Comment by grahamwhaley** [comment]
if the code is under a suitable license (ideally also Apache2), and the way it collects/returns errors fits in with the kata logger structure, probably fine. Do you have a link for @jodh-intel et. al. to check @tedyu ?

**Comment by tedyu** [comment]
Here is the code:

https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/apimachinery/pkg/util/errors/errors.go

**Comment by jodh-intel** [comment]
I don't see the value in importing this code - we want to return the errors for all failures to allow the caller to log that and handle the failure scenario. Hence can't you just concatenate the error messages in some simple way (`errors.Wrapf()` or `fmt.Errorf("%v", err)` or similar)?
