### ISSUE TITLE
race when devices hostplug

### ISSUE THREAD

**Issue by Kvasscn** [kata-containers/runtime#2269]
Refrence to the link https://github.com/kata-containers/documentation/blob/master/design/architecture.md#hot-plug-devices,
at the container start progress,  devices are hotplugged to the VM, and i'am not sure whether there is a race condition at this progress.
For example, try to load vfio device driver but the device is not ready (kata already support  loading kernel modules at the latest version).
Or something like this: docker run --runtime=kata-runtime  --device /dev/vfio/0  tensorflow:latest-gpu   python  gpu_example.py,
after the container startup, then immediately run the gpu test program，maybe the gpu is not ready.

**Comment by Kvasscn** [comment]
I meet this problem when testing with nvidia gpu device.  Unlike intel gpu drivers compiled to kernel,  i need to add nvidia vgpu driver to the kata  rootfs image, and load the driver modules in systemd scripts when kata vm starting. The issue is  vgpu device not ready when loading the drivers, and i have to do a short delay in the systemd scripts. Is it possible that loading vfio device together with kata qemu daemon, such as virtio devices ?

**Comment by grahamwhaley** [comment]
@Kvasscn - thanks for the report/query. There is another Issue/thread related to nvidia GPU support over at https://github.com/kata-containers/documentation/issues/517 that is probably worth reading - it would be great if we could re-awaken the nvidia engineers to help here. @egernst - I don't suppose you have had an interaction with them recently have you?
