### ISSUE TITLE
Cloud Hypervisor: kill virtiofsd not working properly

### ISSUE THREAD

**Issue by ericooper** [kata-containers/runtime#2270]
# Description of problem

A typo (minus sign in front of the pid) has been introduced in the line responsible for killing the virtionfsd when the hypervisor fails to start hence leaving processes running unnecessary.

syscall.Kill(-clh.state.VirtiofsdPID, syscall.SIGKILL)

# Expected result

virtiofsd should be killed properly

# Actual result

it doesn't get killed due to the typo in the source code

I'll fix this in the next upcoming PR for clh hence this one can be assigned to me.

**Comment by jodh-intel** [comment]
Interesting as that *looks* like valid code (which is trying to kill all processes in the process group whose ID is the value of `clh.state.VirtiofsdPID`).
