### ISSUE TITLE
Consider 5.4.x kernel (new LTS)

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#2349]
**Which feature do you think can be improved?**

For ARM, we carry some cumbersome patches on top of 4.19.  Most of this has landed upstream, and would be available in 5.4.

It likely makes sense to upgrade to this kernel, and we need help with a quick review on performance / footprint with this kernel. This should be straight forward using the [existing metrics tests](https://github.com/kata-containers/tests/tree/master/metrics)

If it all checks out, we should adopt newer LTS.

**Comment by Pennyzct** [comment]
Hi @egernst thanks!!!!!
I've raised a PR to enable new LTS 5.4.3 on AArch64. plz, take a review~~
