### ISSUE TITLE
Implement support for QEMU's microvm machine type

### ISSUE THREAD

**Issue by slp** [kata-containers/runtime#2360]
Add support for using the microvm machine type, recently added to QEMU:

 - https://github.com/qemu/qemu/blob/master/docs/microvm.rst

This machine type uses the MMIO transport for virtio devices, so we need to ensure all added devices are using this transport. Most changes are actually needed in govmm, and there's already a PR for that there:

 - https://github.com/intel/govmm/pull/111

These are the task needed to be done here:

- [ ] Once the govmm's PR is merged, update the vendorized version.
- [ ] Add explicit support for the microvm machine type
- [ ] Honour `block_device_driver` when using a disk image as rootfs
- [ ] Add an example `configuration.toml` file with the optimal configuration.

**Comment by slp** [comment]
@devimc Hi Julio. I think you told me someone was already working on this. Could you please confirm me that's still the case?

**Comment by devimc** [comment]
Hi Sergio, we assigned this to @cmaf . She is still learning Go and this issue may require more time. @cmaf is it ok if this issue comes back to @slp? 

@slp apologies for the inconvenience caused

**Comment by cmaf** [comment]
@devimc @slp sure, no problem

**Comment by merwick** [comment]
I submitted a PR, #intel/govmm121 with some followup govmm changes to use microvm.

With these changes, plus some minor kata-runtime changes, I can specify 'machine_type = "microvm"' in /etc/kata-containers/configuration.toml and see a 170ms (13%) improvement in startup time compared with 'machine_type = "pc"'.  Running kata metrics I see a 106ms (8%) improvement in startup time and a 6% reduction in memory footprint.

**Comment by merwick** [comment]
I can pick this task up (but don't have permissions to assign it to myself)

Below is the commit I'd send a PR for (but it won't build until govmm is revendored to pick up  intel/govmm#121 - right now I have the govmm changes as a separate commit in my repo)
https://github.com/merwick/runtime/commit/fdfccc3bf1b2c4b16facbbc5580facb079d54228

**Comment by devimc** [comment]
merged intel/govmm#121 and assigned this to you, thanks @merwick
