### ISSUE TITLE
user namespace with kata-container

### ISSUE THREAD

**Issue by remyd1** [kata-containers/runtime#2364]
# Description of problem

I followed the instructions to install kata-container on [Ubuntu](https://github.com/kata-containers/documentation/blob/master/install/ubuntu-installation-guide.md) with [docker](https://github.com/kata-containers/documentation/blob/master/install/docker/ubuntu-docker-install.md). I chose the systemd modification.

Eveything worked as expected. However, with security in mind, I tried to setup the docker namespace with the docker instructions : https://docs.docker.com/engine/security/userns-remap/

This does not work.

The runtime is kata-container; maybe this behaviour is normal... ?

# Expected result

Being able to launch containers with kata-runtime while launching and running it in a specific user namespace.

# Actual result

Not working:

```
docker: Error response from daemon: OCI runtime create failed: rpc error: code = Unknown desc = User namespaces enabled, but no user mapping found.: unknown.
ERRO[0001] error waiting for container: context canceled
```

**Comment by grahamwhaley** [comment]
Thanks for the question/report @remyd1 . I don't see it listed as a kata limitation over at https://github.com/kata-containers/documentation/blob/master/Limitations.md - so, I'll pull in some others - and hopefully we can clarify, and update that Limitations document if need be.
