### ISSUE TITLE
ut failure with non-root

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#2370]
# Description of problem

I see many ut failures like below when running ut locally without root privilege.

```
--- FAIL: TestAcrnCreateSandbox (0.00s)
        Error Trace:    acrn_test.go:222
        Error:          Received unexpected error:
                        mkdir /var/lib/vc/uuid: permission denied
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x917f3f]
```

**Comment by bergwolf** [comment]
@jcvenegas @grahamwhaley are we catching non-root UT in CI?

**Comment by grahamwhaley** [comment]
afaik we run the test suites as both root and non-root in the CI
/cc @chavafg @jodh-intel for confirmation.

**Comment by jodh-intel** [comment]
Yes we do. If a test shouldn't be run as `root` or non-`root`, you need to use the appropriate helper function. See:

- https://github.com/kata-containers/runtime/tree/master/pkg/katatestutils#skip-tests-based-on-user

**Comment by jcvenegas** [comment]
@bergwolf  as aditional comment (not sure if docuemented somewhere)  I do `export CI=true` to get a successful run of the current uni test

**Comment by grahamwhaley** [comment]
@jcvenegas - you might be better off (less destructive iirc) with [KATA_DEV_MODE=true](https://github.com/kata-containers/tests#run-the-tests) - @jodh-intel @chavafg ?

**Comment by bergwolf** [comment]
It seems that we simply mask the problem with `KATA_DEV_MODE=tree` and `CI=true`? UTs are not really run with both root and non-root for `virtcontainers`.

```
182         echo "INFO: Currently running as user '$(id -un)'"
183         for pkg in $test_packages; do
184                 for user in $users; do
185                         # Run virtcontainers tests only if user is root.
186                         if [[ "$user" != "root" ]] && [[ "$pkg" = *"virtcontainers"* ]]; then
187                                 echo "Skip testing $pkg with user $user"
188                                 continue
189                         fi
190
191                         test_go_package "$pkg" "$user"
192                 done
193         done
```

**Comment by bergwolf** [comment]
@jodh-intel @grahamwhaley @jcvenegas Can we drop the above CI hack and treat `virtcontainers` UTs the same as others? I don't think we should just let it skip under the radar.
