### ISSUE TITLE
kata-runtime kata-check failed

### ISSUE THREAD

**Issue by Fvoiretryzig** [kata-containers/runtime#2374]
# Description of problem

I followed the instructions to install kata runtime.
`
$ go get -d -u github.com/kata-containers/runtime`
`$ cd $GOPATH/src/github.com/kata-containers/runtime  `
`$ make && sudo -E PATH=$PATH make install  
`
I did these successfully. I found /usr/local/bin/kata-runtime and /usr/share/defaults/kata-containers/configuration.toml existed. Then I checked  the kata-runtime version. It showed,
`
kata-runtime  : 1.10.0-rc0`
   `commit   : 1296f6f1ad95cd7288f5e78e7c7dc39abe2d786a`
   `OCI specs: 1.0.1-dev
`
However when I enter instruction `sudo kata-runtime kata-check`, it output as follows,
`
ERRO[0000] /usr/share/defaults/kata-containers/configuration-qemu.toml: file /usr/share/kata-containers/vmlinuz.container does not exist  arch=amd64 name=kata-runtime pid=17608 source=runtime`
`/usr/share/defaults/kata-containers/configuration-qemu.toml: file /usr/share/kata-containers/vmlinuz.container does not exist
`
I found  /usr/share/kata-containers didn't exist.
# Expected result

Maybe some information about device.

# Actual result

`
ERRO[0000] /usr/share/defaults/kata-containers/configuration-qemu.toml: file /usr/share/kata-containers/vmlinuz.container does not exist  arch=amd64 name=kata-runtime pid=17608 source=runtime`
`/usr/share/defaults/kata-containers/configuration-qemu.toml: file /usr/share/kata-containers/vmlinuz.container does not exist
`

**Comment by grahamwhaley** [comment]
Hi @Fvoiretryzig . Thanks for the report.

First, you get that error as you have not built and installed all the components of 'kata containers'. The `runtime` is just one of the necessary components. If you are installing from source, and have not already, take a look at the [developers guide](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#initial-setup). There you find the instructions to build and install the other components as well such as the agent/filesystem and kernel images that are required.

Secondly, is that the only error line that was printed out? If so, I think that could be improved - the kata `runtime` is complaining that it cannot find one of its vital components, but I think it could/should also list all the information it can find (such as its own build/version information). Please let us know if that was the complete output?

thanks.

**Comment by Fvoiretryzig** [comment]
> Hi @Fvoiretryzig . Thanks for the report.
> 
> First, you get that error as you have not built and installed all the components of 'kata containers'. The `runtime` is just one of the necessary components. If you are installing from source, and have not already, take a look at the [developers guide](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#initial-setup). There you find the instructions to build and install the other components as well such as the agent/filesystem and kernel images that are required.
> 
> Secondly, is that the only error line that was printed out? If so, I think that could be improved - the kata `runtime` is complaining that it cannot find one of its vital components, but I think it could/should also list all the information it can find (such as its own build/version information). Please let us know if that was the complete output?
> 
> thanks.

Thanks for your help. The error messages  were complete output. 
Because in the developers guide the command `kata-runtime kata-check` is just after the runtime installation, I thought I needed to check this before doing following things.
