### ISSUE TITLE
Issue with Kata container reported metrics through cadvisor  

### ISSUE THREAD

**Issue by Galansary** [kata-containers/runtime#2377]
# Description of problem
Using a docker-compose file containing cadvisor, Influxdb, Graphana, to collect metrics of 2 similar containers one with docker default **runc** and the second using **Kata-runtime**.

Example of the docker-compose used:

'version: '2.3'
services:
 busybox:
    image: busybox:latest
    restart: always
    container_name: busybox
    command: tail -F anything
    volumes:
    - ./data/influxdb:/data
 busybox-default:
    image: busybox:latest
    restart: always
    runtime: runc
    container_name: busybox-default
    command: tail -F anything
    volumes:
    - ./data/influxdb:/data
 influxdb:
  image: tutum/influxdb:0.9
  restart: always
  runtime: runc
  environment:
   - PRE_CREATE_DB=cadvisor
  ports:
   - "8083:8083"
   - "8086:8086"
  expose:
   - "8090"
   - "8099"
  volumes_from:
   - "busybox"
   - "busybox-default"
 cadvisor:
  image: google/cadvisor:v0.29.0
  runtime: runc
  links:
    - influxdb:influxsrv
  command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=influxsrv:8086
  restart: always
  ports:
   - "8091:8080"
  volumes:
   - /:/rootfs:ro
   - /var/run:/var/run:rw
   - /sys:/sys:ro
   - /var/lib/docker/:/var/lib/docker:ro
  depends_on:
    - busybox
    - busybox-default
 grafana:
   image: grafana/grafana:2.6.0
   runtime: runc
   restart: always
   links:
    - influxdb:influxsrv
   ports:
    - "3000:3000"
   environment:
    - HTTP_USER=admin
    - HTTP_PASS=admin
    - INFLUXDB_HOST=influxsrv
    - INFLUXDB_PORT=8086
    - INFLUXDB_NAME=cadvisor
    - INFLUXDB_USER=root
    - INFLUXDB_PASS=root'

# Expected result

Given the identical containers running in the same exact environment, the resulted metrics and resource usage should make sense and should be at least close enough to each other. 

# Actual result
Certain issue and observation were recorded with the metrics when this setup was in use; these issues and observations were mainly around the metrics collected form both containers, kata container always showed far lower memory and in some cases CPU usage than runc container, the bigger the container size, the biggest the observed difference between the metrics coming out of the container.
This low resource usage in Kata raised some concerns around the way the metrics are exposed and collected from within that kata container. In the beginning, we suspected that the issue is to do with the **docker-compose network**, so we ran some tests with docker commands only without using docker-compose file and only using cadvisor confirm the suspicion,  the result was not very different, to some extent the result was the same.
 In an attempt to investigate why the Kata metrics are far below runc was to make sure that kata exposes metrics in docker the same way other containers do. To do that, we tried to locate the directories under which kata metrics are exposed in docker.
Docker documentation states that; container relies on the control groups (Cgroups) to track groups of process and to exposes the metrics of memory, CPU, and block I/O usage for that group of process. These control groups are found under /sys/fs/Cgroup. Under this directory, a group of subdirectories called devices, freezer, blkio, etc can be found; each subdirectory represents a different cgroup hierarchy.
To locate a specific container cgroup for a docker container using cgroups, you will need the container name, in this case, the long container ID that can be found when we run the docker inspect command, adding this to the following hierarchy for memory stats for example: /sys/fs/cgroup/memory/docker/<longid>/  will give us the location of the directory under which the container memory metrics can be found, in Kata case a prefix Kata_ is attached to the long ID to distinguish Kata containers, the location for kata containers will be: /sys/fs/cgroup/memory/docker/kata_<longid>/.
By investigation these subdirectories in our case, we can see that metrics are being thrown out to those files, but we can still see that the consumption is far lower than the on for runc containers. 
In the second step in the investigation, we zoomed in a little bit, by reducing the window we are tracking in the Graphana dashboard to 5 minutes and reducing the reported metrics to be grouped each second we could clearly see that kata container report memory metrics less frequently than runc as in the below figures :
![image](https://user-images.githubusercontent.com/36736397/71450338-32234900-2758-11ea-9759-935d0605f7b2.png)
 
By taking a closer look, it looked like when taking the sum of the memory used for each container by changing the aggregation to sum as opposed to mean or average and group the reading by 15minutes to avoid the discrepancy of the metrics reporting frequency. At this point, we can see that the two containers have a little bit of similarity in terms of memory usage between them, but following the same approach with different container type and size (gitlab) did not lead to the same conclusion.
 The below two snapshots represents the two containers sizes, in the case of the small size containers (busybox) the memory_usage for both containers is close to each other with slight edge usage on the runc side, while in the case of big size container (Gitlab) containers the difference is very vast: 
![image](https://user-images.githubusercontent.com/36736397/71450352-49623680-2758-11ea-9c1f-c087a82ca024.png)

 
![image](https://user-images.githubusercontent.com/36736397/71450353-4f581780-2758-11ea-938f-a93c6623b7e5.png)

 
The same approach above was not correct when we tried to use with cpu_usage reporting,  indicating an issue with the way Kata metrics are collected from kata containers or the way kata runtime present those metrics, below figure shows the resulted graph after using the same approach used for memory metrics, we had to put them in logarithmic scale to show them together:
![image](https://user-images.githubusercontent.com/36736397/71450356-5bdc7000-2758-11ea-95a5-4fda84c5ee32.png)

**Comment by devimc** [comment]
@Galansary thanks for raising this, two things: 
* in **expected result** section you mention that *the resulted metrics and resource usage should be at least close enough to each other.* afaik this is not possible since  there is an overhead that we have to pay (qemu, kata-proxy, kata-shim).
* did you enable [`sandbox_cgroup_only`](https://github.com/kata-containers/runtime/blob/3ea3d3201b3a0b6fc35dea48192e73a021b4734b/cli/config/configuration-qemu.toml.in#L423-L429) ?

**Comment by Galansary** [comment]
@devimc sorry for the delayed reply.

- for point 1, my expectation is to get at least a kind of similar graphs, if you checked my results above, we had to put the results in a logarithmic scale to be able to show it in the same graph

- No,  I didn't enable `sandbox_cgroup_only`, do I need to do?

**Comment by devimc** [comment]
@Galansary 

> No, I didn't enable sandbox_cgroup_only, do I need to do?

Yes, all components (qemu, proxy and shim) will be placed in the same cgroup

**Comment by egernst** [comment]
For accurate constraining and measuring, you'll definitely want to set "sandbox_cgroup_only."  Eventually this will be the default for Kata Containers, but this is a difficult transition, as it will lead to failures in K8S if kubelet doesn't size the pod cgroup to take into overheads of running a Pod.  See [1].

[1] - https://kubernetes.io/docs/concepts/configuration/pod-overhead/
