### ISSUE TITLE
Dump stacks when received SIGUSR1 in Agent/Runtime/Shim/Proxy?

### ISSUE THREAD

**Issue by jingxiaolu** [kata-containers/runtime#241]
When we debugging some kind of deadlock or so issues in Docker/Containerd, sending SIGUSR1 to dockerd or containerd, and collect their goroutine stacks for further analysis are very helpful.

Should we implement the similar feature also in Agent/Runtime/Shim/Proxy in kata? 

Thanks guys :-)

**Comment by jodh-intel** [comment]
Hi @jingxiaolu - thanks for raising. We actually already have this facility, although not for `SIGUSR1`.

For example, if you `sudo kill -SEGV $shim_pid`, it will write a full stacktrace and full goroutine details to the system journal:

- https://github.com/kata-containers/agent/pull/161
- https://github.com/kata-containers/proxy/pull/61
- https://github.com/clearcontainers/runtime/pull/1054
  (Added before the Clear Containers runtime was added to https://github.com/kata-containers/runtime).
- https://github.com/kata-containers/shim/pull/59

Further, if debug is enabled, you'll get a coredump for most components (although not the agent).

In fact, our PR CI checks for this to see if any component died unexpectedly. If it did, we fail the CI run:

- https://github.com/kata-containers/tests/blob/master/.ci/run.sh#L35..L50

I guess we could extend the feature by adding `SIGUSR1` to the `sigFatal` map for most of the above? wdyt @sboeuf, @amshinde?

**Comment by jingxiaolu** [comment]
Hi @jodh-intel , thanks for your reply. 

Yes, sending `SIGSEGV` to kata-shim can produce dump stacks to system journal and kata-shim will be killed too :-)

However, handling `SIGUSR1` in docker/containerd only outputs dump stacks, process is still running.

Yes, I'm finding a way to trigger shim/agent/proxy/runtime to output full stacktrace only, but leave it running~

Correct me if I am wrong

**Comment by jodh-intel** [comment]
I'll take a look at implementing this...

**Comment by sboeuf** [comment]
I would allow this behavior only if the component (agent/shim/proxy/runtime) has been started in `debug` mode.

**Comment by bergwolf** [comment]
What if the container app requires `SIGUSR1` handler of its own? I know some daemons use custom signal handlers to trigger config file reload.

**Comment by jodh-intel** [comment]
Yeah, that's going to potentially be an issue for the shim. However, we could just have the shim catch `SIGUSR1`, dump the stack and then forward it on to the container as usual.

/cc @amshinde.

**Comment by bergwolf** [comment]
@jodh-intel ok, so the agent should do the same I assume, -- dump the stack and then forward the signal to the process. Sounds good to me!

**Comment by jingxiaolu** [comment]
@jodh-intel thanks for your quick response~
