### ISSUE TITLE
Reimplement rootless

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#2412]
# Description of problem

Current rootless implementation is a mess and it's causing me headaches:

* Why on earth are we maintaining a rootless API when `libcontainer`  already has one? [1][2]
* Currently `--rootless` flag is not implemented and it's really hard to implement when `rootless.IsRootless` is hardcoded everywhere

Issues to fix:

- [x] https://github.com/kata-containers/runtime/issues/2415
- [x] https://github.com/kata-containers/runtime/issues/2416
- [x] https://github.com/kata-containers/runtime/issues/2417 

[1] - https://github.com/opencontainers/runc/blob/master/libcontainer/system/linux.go#L103-L123
[2] - https://github.com/opencontainers/runc/tree/master/libcontainer/user

**Comment by devimc** [comment]
btw I need this for rootless cgroups

**Comment by amshinde** [comment]
@devimc I think the api was added to runtime while testing with podman when rootless support for docker was not around. So you are planning to use the libcontainer functions instead getting rid of our api? that sounds ok to me as long as we continue to work with podman.

**Comment by devimc** [comment]
@amshinde 

> So you are planning to use the libcontainer functions instead getting rid of our api? 

no, I plan to use libcontainer and get rid of our API

> that sounds ok to me as long as we continue to work with podman.

latest runc + podman + rootless work for me

```
$ sleep 2; podman run --runtime=runc --rm -ti debian bash
root@f70fac6e70c5:/#
```

**Comment by devimc** [comment]
all sub-issues have been fixed
