### ISSUE TITLE
conmon version out of date

### ISSUE THREAD

**Issue by haircommander** [kata-containers/runtime#2427]
CRI-O tests are running with a conmon a couple of sub-minor versions behind. This is because the latest version breaks kata for some reason

This is a follow up of https://github.com/kata-containers/runtime/pull/2425#issuecomment-580343831

Making an issue to track it for myself

**Comment by amshinde** [comment]
@haircommander Some additional info about the tests. We are actually running the tests from the crio repo The failure occurs at this point:
https://github.com/cri-o/cri-o/blob/master/test/ctr.bats#L825

As per that, the expected output should contain "command timed out", which is no longer happening with the latest conmon. 
Is this bug not affecting runc? The last I checked (a month back) I saw a similar failure with runc as well.

**Comment by ariel-adam** [comment]
@haircommander is this still an issue or can we close it?

**Comment by haircommander** [comment]
I believe we are still pinning the old conmon

**Comment by jodh-intel** [comment]
Hi @haircommander - would you like to tal at fixing this (by updating https://github.com/kata-containers/runtime/blob/master/versions.yaml)?
