### ISSUE TITLE
Add support for hotplug PCIe device in q35

### ISSUE THREAD

**Issue by Jimmy-Xu** [kata-containers/runtime#2432]
# Use Case
I'm trying to passthrough Nvidia GPU(Tesla P100) to a kata container.

I referenced the following docs:
- https://github.com/kata-containers/documentation/blob/master/use-cases/GPU-passthrough-and-Kata.md
- https://github.com/kata-containers/documentation/issues/517

I have the following VFIO devices(Nvidia) in my hosts
```
$ ll /dev/vfio
total 0
crw------- 1 root root 248,   0 Jan 22 23:11 45
crw------- 1 root root 248,   1 Jan 22 23:11 54
crw-rw-rw- 1 root root  10, 196 Jan 22 23:11 vfio
```

I can passthrough the Nvidia device to the kata container by adding `--device=/dev/vfio/45`, but I cannot load the nvidia driver in the kata container.

I tried the following 4 tests:

### config
modify configuration.toml
```
machine_type = "pc"
hotplug_vfio_on_root_bus = false
```
### result
run a kata container and run the following commands:
```
#lspci -t -vv -nn | grep -i nvidia
           +-02.0-[01]----01.0  NVIDIA Corporation Device [10de:15f8]

#lspci -s 01:01.0 -vv | grep -i Region
lspci: Unable to load libkmod resources: error -12
  Region 1: Memory at <unassigned> (64-bit, prefetchable) [disabled]
  Region 3: Memory at <unassigned> (64-bit, prefetchable) [disabled]
```

### config
```
machine_type = "pc"
hotplug_vfio_on_root_bus = true
```
### result
```

#lspci -t -nn -vv | grep -i nvidia
           \-07.0  NVIDIA Corporation Device [10de:15f8]

#lspci -s 00:07.0 -vv | grep Region
lspci: Unable to load libkmod resources: error -12
  Region 0: Memory at 80000000 (32-bit, non-prefetchable) [disabled] [size=16M]
  Region 1: Memory at <unassigned> (64-bit, prefetchable) [disabled]
  Region 3: Memory at 4240000000 (64-bit, prefetchable) [disabled] [size=32M]
```
> The Nvidia Tesla P100 is a large BAR space(MMIO >4GB) PCIe device.

### config
```
machine_type = "q35"
hotplug_vfio_on_root_bus = false
```
### result
```
#lspci -t -nn -vv | grep -i nvidia
           +-02.0-[01]----01.0  NVIDIA Corporation Device [10de:15f8]

#lspci -s 01:01.0 -vv | grep Region
lspci: Unable to load libkmod resources: error -12
	Region 1: Memory at <unassigned> (64-bit, prefetchable) [disabled]
	Region 3: Memory at <unassigned> (64-bit, prefetchable) [disabled]
```

### config 
```
machine_type = "q35"
hotplug_vfio_on_root_bus = true
```
### result
Creating kata container fails with the following error:
`QMP command failed: Bus 'pcie.0' does not support hotplugging: unknown`

## summary
- the parameter `hotplug_vfio_on_root_bus` should be `true`
- when the machine_type is `pc`, the root bus is `pci.0`, and the MMIO space cannot exceed 4GB. 
  Plugging a PCI Express device into a PCI slot will hide the Extended
Configuration Space thus is also not recommended.
   So if we want to use a large BAR space PCIe device, the machine_type should be `q35`
- when the machine_type is `q35`, the root bus is `pcie.0`. The PCIe device can not be hot-plugged into `pcie.0`.  We can solve it by add  the `pcie-root-port` device.

<img width="878" alt="image" src="https://user-images.githubusercontent.com/5432547/73842955-973e8400-4858-11ea-90e9-da043abf4929.png">

REF: https://github.com/qemu/qemu/blob/master/docs/pcie.txt

# Feature Request
- add `pcie-root-port` device in qemu command line
- modify hotplug VFIO device: hot-plug/hot-unplug PCIe device to `pcie-root-port`

Related PR: https://github.com/intel/govmm/pull/116

**Comment by Kvasscn** [comment]
sorry to  comment on the closed isse, :) 
I had a similar problem when using nvidia  V100 PCIe 16GB, the difference was I used vgpu  mode (not 
  passthrough )potplug to kata container.  When  the vgpu framebuffer size < 4G， the vgpu device can be initialized in the kata container， but  failed to initialize when the vgpu framebuffer >= 4G.
Refer to the link  https://github.com/kata-containers/documentation/blob/master/use-cases/GPU-passthrough-and-Kata.md#host-kernel-requirements, i added "intel_iommu=on" to the host system's grub config.
Though  i set  machine_type = "q35"   and  hotplug_vfio_on_root_bus = true  in the kata config,
the vgpu still failed   initialized if  vgpu  frame memory greater than 4G。
Could you give me some helpful information？thanks.

**Comment by devimc** [comment]
@Kvasscn try with `hotplug_vfio_on_root_bus = true` and/or this patch https://github.com/kata-containers/runtime/pull/2461

**Comment by Jimmy-Xu** [comment]
@Kvasscn 
The guest kernel should enable VFIO and load module also, FIY https://github.com/kata-containers/packaging/pull/938

**Comment by Kvasscn** [comment]
Thanks for all,  i will  try it later.  :)
