### ISSUE TITLE
Simplify struct VhostUserDeviceAttrs

### ISSUE THREAD

**Issue by dong-liuliu** [kata-containers/runtime#2433]
If vhost-user-blk device are supported in Kata, then in struct VhostUserDeviceAttrs ( in virtcontainers/device/config/config.go and virtcontainers/persist/api/device/go),
```
// VhostUserDeviceAttrs represents data shared by most vhost-user devices
type VhostUserDeviceAttrs struct {
	DevID      string
	SocketPath string
	Type       DeviceType

	// MacAddress is only meaningful for vhost user net device
	MacAddress string

        ........

	// PCIAddr is the PCI address used to identify the slot at which the drive is attached.
	// It is only meaningful for vhost user block devices
	PCIAddr string
}
```
Element MacAddress is only meaningful for vhost-user-net device.
Probably a new element named PCIAddr might be only meaningful for vhost-user-blk device.
And if vhost-user-scsi device is supported, then some exclusive element might be added.
So elements in this struct can be simplified, especially for MacAddress and PCIAddr.

It can be improved by renaming the existing MacAddress string to Addr, and use that to store the PCIAddr in case of vhost-usr-block, mac address in case of vhost-user-net and in case of (still to be handled )vhost-user-scsi devices maybe use that to store SCSI address if required.

_Originally posted by @amshinde in https://github.com/kata-containers/runtime/pull/2390#discussion_r369285816

**Comment by dgibson** [comment]
IMO, best left to Kata 2.

**Comment by jodh-intel** [comment]
@dgibson - would you like to look at this with @c3d?
