### ISSUE TITLE
clh: Set serial to "null"

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#2437]
If we want to avoid any potential weird behavior regarding the boot of the guest kernel, it's better to provide an emulated serial port. Because we don't care about getting the logs from this port, we simply need to set it to "null" so that these logs get discarded.

**Comment by grahamwhaley** [comment]
@sboeuf - I presume there is some way to debug kernel boot fails - to get the bootlog (other than `dmesg` from userland once it has booted) ?
Just for that time when we cannot boot a kernel and want to figure out why...

**Comment by sboeuf** [comment]
@grahamwhaley problem is, it might not prevent the kernel from booting, but just causing the kernel to boot slow. The kernel might be trying to read from the serial (because the I/O port `0x3f8` returns `0` when it should really return `0x60` to say the serial is __idle__) when there's nothing to read, but it would boot eventually.

**Comment by grahamwhaley** [comment]
@sboeuf - sure. I meant more, is there some method to get the kernel boot messages - the boot log - out of clh, if we need to debug a bust boot? So, not 100% related to this Issue, but close :-).
I don't mind if it is something you have to enable in a config or command line somewhere, but ideally we'd not have to re-build the hypervisor iyswim.

**Comment by sboeuf** [comment]
@grahamwhaley oh yes the best way to get the kernel logs from CH is to run it with `--serial tty` and make sure you have `console=ttyS0` as part of your kernel command line.
