### ISSUE TITLE
clh: keep the stdout/stderr open for CLH until its process exits

### ISSUE THREAD

**Issue by likebreath** [kata-containers/runtime#2439]
**Which feature do you think can be improved?**

The `kata-runtime` now captures `cloud-hypervisor` (CLH) output (stdout/stderr) to a local buffer `cloudHypervisor::cmdOutput` when launching CLH. The `kata-runtime` will exit when CLH launched successfully, and will leave CLH's output closed (not redirected) afterwards.

This issue can cause unexpected behaviors from CLH, e.g. causing CLH (child thread) panic while CLH tries to log warnings (to stderr) and stderr is not open (https://github.com/cloud-hypervisor/cloud-hypervisor/pull/703).

**How can it be improved?**

One potential solution is, instead of redirecting to a local buffer that lives with `kata-runtime`, CLH's output can be redirected to a file, e.g. `/dev/null` for production, or a log file for debugging.

**Additional Information**

Please share your thoughts and advises.

**Comment by grahamwhaley** [comment]
I'm prone to say you might want to capture the output, even in a production deployment. The end users might want to import those into their logging stack for post-analysis etc.
I don't know the wrinkles of how/where is going to be best to re-direct/capture/push that data in the kata runtime stack - but, I reckon @jodh-intel will have an idea (basically, whatever route we do today for qemu etc.).

**Comment by amshinde** [comment]
Based on the debug settings for the hypervisor in our config.toml we can either have this redirected to a log file or /dev/null when debug is not enabled.
