### ISSUE TITLE
Can't run kata-static distribution from custom directory.

### ISSUE THREAD

**Issue by szimonek** [kata-containers/runtime#2459]
# Description of problem

I'm trying to use kata-static-1.10.0-x86_64.tar.xz deployed in custom directory of /u01/bin/kata/
So I have: /u01/bin/kata/opt/kata/bin /u01/bin/kata/opt/kata/libexec /u01/bin/kata/opt/kata/share and so on.

I've written custom config file and changed paths in it (path, kernel, images ) to point to my directory structure. Such configuration is added as runtime to containerd.

Then I'm starting new container with:
crictl run -r kata container-config.yaml podsandbox-config.yaml

# Expected result

Started and accessible container.

# Actual result

I encoutered such errors:
FATA[0000] Running container failed: run pod sandbox failed: rpc error: code = Unknown desc = failed to create containerd task: failed to launch qemu: exit status 1, error messages from qemu log: qemu: could not load PC BIOS 'bios-256k.bin'

FATA[0020] Running container failed: run pod sandbox failed: rpc error: code = Unknown desc = failed to create containerd task: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing: unknown

# Additional info

First error (BIOS not found) can be solved with symbolic link:
ln -s /u01/bin/kata/opt/kata/share/kata-qemu/qemu /u01/bin/kata/opt/kata/bin/qemu

For second I have no other solution, than placing kata-static in /opt
ln -s /u01/bin/kata/opt/kata /opt/kata

How can I diagnose what else in kata-static-1.10.0-x86_64.tar.xz package is statically referencing to /opt/kata? Is that even possible to run this package from custom directory?

**Comment by grahamwhaley** [comment]
Hi @szimonek - thanks for the report.
For a start, can you try to run `kata-runtime kata-env`, and post the output here (after checking it looks sane ;-) ). That should tell you the paths of the components kata thinks it is configured for. Let's see if that has any clues.

Beyond that, you could try [enabling all the debug](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug) and checking what is reported in the system journal.

/cc @devimc @egernst for other thoughts.

**Comment by szimonek** [comment]
Hi @grahamwhaley 

Sorry for the weekend delay. I've just executed `/u01/bin/kata-v1.10.0/opt/kata/bin/kata-runtime --kata-config /u01/app/kata-v1.10.0/configuration.toml kata-env`. All shown paths look are correct:

[Meta]
  Version = "1.0.23"

[Runtime]
  Debug = false
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  SandboxCgroupOnly = false
  Path = "/u01/bin/kata-v1.10.0/opt/kata/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.10.0"
    Commit = "ebe9677f23b574c5defacf57456d221d8ce901f2"
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/u01/app/kata-v1.10.0/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 4.1.0 (kata-static)\nCopyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers"
  Path = "/u01/bin/kata-v1.10.0/opt/kata/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = false
  UseVSock = false
  SharedFS = "virtio-9p"

[Image]
  Path = "/u01/bin/kata-v1.10.0/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.10.0_agent_a8007c2969.img"

[Kernel]
  Path = "/u01/bin/kata-v1.10.0/opt/kata/share/kata-containers/vmlinuz-4.19.86-60"
  Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.10.0-bbc3f73a3b003f57c20f4dad4bffb22580864926"
  Path = "/u01/bin/kata-v1.10.0/opt/kata/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.10.0-6db555216f68a14b68ce64713083c5f5b4684aea"
  Path = "/u01/bin/kata-v1.10.0/opt/kata/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"
  Debug = false
  Trace = false
  TraceMode = ""
  TraceType = ""

[Host]
  Kernel = "3.10.0-1062.9.1.el7.x86_64"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "CentOS Linux"
    Version = "7"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) CPU E5-2667 0 @ 2.90GHz"

[Netmon]
  Version = "kata-netmon version 1.10.0"
  Path = "/u01/bin/kata/opt/kata/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false


The `/u01/bin/kata` is a symbolic link to `/u01/bin/kata-v1.10.0` so it is basically the same.

I'm using such configuration in containerd:

`
        [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata]
          runtime_type = "io.containerd.kata.v2"
          [plugins."io.containerd.grpc.v1.cri".containerd.runtimes.kata.options]
            ConfigPath = "/u01/app/kata/configuration.toml"
`

With that I've such problems as described in first post. Something not mentioned in configuration file is still reffering to static path /opt/kata and I have no idea what it is.

**Comment by grahamwhaley** [comment]
@szimonek - simple question - I presume this did all work when the kata binaries lived in `/opt/kata`, before you moved them? Just want to check that the `grpc` error you see is not something else (possibly unrelated to the kata path) iyswim?

**Comment by szimonek** [comment]
Yes, you are right. When kata binaries is located in /opt/kata or even has symbolic link there, everything is working fine. Below the exact steps (relevant to kata) I take. I'm starting with kata static unarchived in /u01/bin/kata-v1.10.0 and empty /opt :

`# ls /u01/bin/kata-v1.10.0/opt/kata/`
`bin  libexec  share`
`# ls /opt/`
`# crictl run -r kata container-config.yaml podsandbox-config.yaml`
`FATA[0000] Running container failed: run pod sandbox failed: rpc error: code = Unknown desc = failed to create containerd task: failed to launch qemu: exit status 1, error messages from qemu log: qemu: could not load PC BIOS 'bios-256k.bin'`
`: unknown`
`#`

To fix "missing bios" error, I point to it firmware parameter in my configuration file:
`# grep "firmware =" /u01/app/kata-v1.10.0/configuration.toml`
`#firmware = ""`
`firmware = "/u01/bin/kata-v1.10.0/opt/kata/share/kata-qemu/qemu/bios-256k.bin"`

`# crictl run -r kata container-config.yaml podsandbox-config.yaml`
`FATA[0020] Running container failed: run pod sandbox failed: rpc error: code = Unknown desc = failed to create containerd task: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing: unknown`

To fix "grpc error" I need to have binaries accessible in /opt/kata

`# ln -s /u01/bin/kata-v1.10.0/opt/kata /opt/kata`
`# ls -l /opt/kata`
`lrwxrwxrwx 1 root root 30 Feb 17 13:40 /opt/kata -> /u01/bin/kata-v1.10.0/opt/kata`
`#`
`# crictl run -r kata container-config.yaml podsandbox-config.yaml`
`651179d6399526d2e5877150881994c7a240d4e4b2c2c4bcacc1420c910d9ab2`
`# crictl pods`
`POD ID              CREATED             STATE               NAME                NAMESPACE           ATTEMPT`
`62361be3e4735       20 seconds ago      Ready               alpine              default             1`
`# crictl rmp -f 62361be3e4735`
`Stopped sandbox 62361be3e4735`
`Removed sandbox 62361be3e4735`
`#`

I try to invoke "grpc error" with debug on.

**Comment by devimc** [comment]
I'd like to see kata's logs, otherwise I'm blind, https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug

**Comment by szimonek** [comment]
Sorry for no answer. When I figured out that I can workaround that problem with simple link:
"ln -s /my/kata/package/location /opt/kata" I focused on other problems. I will try to collect and provide that debug logs, but when I was debugging I didn't saw any problems in them.

**Comment by egernst** [comment]
Hey @szimonek -- some of the static binaries (QEMU) require a known path at build time, in particular for finding the firmware, etc, IIRC.  If you want to store these at a different location you'd have to at least rebuild QEMU for your new path, just use a symlink, or rebuild the whole "tarball"

Closing as this is a bit stale, and apologize for the late reply!
