### ISSUE TITLE
Add special branch for virtio-mem in Linux and qemu

### ISSUE THREAD

**Issue by teawater** [kata-containers/runtime#2485]
kata-containers runtime supports virtio-mem. 
This feature in Linux kernel and qemu is still not merged.
To use virtio-mem need Linux kernel in https://github.com/davidhildenbrand/linux/tree/virtio-mem-rfc-v4, kernel config in https://gist.github.com/teawater/016194ee84748c768745a163d08b0fb9 and qemu in https://github.com/teawater/qemu/tree/kata-virtio-mem.

And the next plan of virtio-mem is in https://github.com/kata-containers/documentation/pull/592#discussion_r378184070
```
I'm planning to post v1 (as follow up to RFC v4) of the Linux guest driver side soon. Depending on the review feedback (and the missing ACK for a mm patch), I guess this could get merged fairly soon.

I'm currently working on the QEMU side, which is an early RFC. A very basic version could be posted/upstream soon, however, I am looking into implementing some reasonable improvements (e.g., resizeable memory regions) before sending out a v1. My goal is to send a v1 within the next months.

As always with upstream work, it's hard to make estimates :)
```

**Comment by ariel-adam** [comment]
We switched to the upstream kernel and we don't have a QEMU repo thus we are closing this issue.

**Comment by c3d** [comment]
virtio-mem is in the upstream kernel, see https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=b3562c6087b585abba53d906f127d6fd5a92829c and in the upstream qemu, see https://github.com/qemu/qemu/commit/c22aba196341995f2e45c37eed36cc7be09e4bc3.
