### ISSUE TITLE
cri-o: keep track of the new cri-o release

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/runtime#2486]
# Description of problem
Lately, in PR https://github.com/kata-containers/runtime/pull/2458, we temporarily updated `cri-o` version to  commit ID of the fix.
All following significant fixes are not included in the latest stable tag version `v1.17.0`.

- PR cri-o/cri-o#3239 is critical for running cri-o v1.17.x on `AArch64`, and specific reason is elaborated here cri-o/cri-o#3233.

- PR https://github.com/kata-containers/tests/pull/2305 needs to include commit https://github.com/cri-o/cri-o/pull/3203 in cri-o `v1.17.x`.

Let's keep track of the new stable cri-o release . ;)

**Comment by Pennyzct** [comment]
Hi guys

cri-o has new stable release v1.17.2, and it include the changes in cri-o/cri-o#3239. 

But for another change https://github.com/cri-o/cri-o/pull/3203 we wanted to include, I just found that, it will not be included in any v1.17.x release, it has been merged into master and may plan to include it in the future v1.18.x.
I could use a temporary workaround to fix it until the new v1.18.x age is coming.
but Wdyt, @devimc @amshinde @chavafg , we keep waiting or upgrade it to v1.17.2?

**Comment by fidencio** [comment]
v1.17.3 is out already. And it does include some fixes needed when using shimv2, such as: https://github.com/cri-o/cri-o/pull/3530

If bumping, may be worth to bump to v1.17.3

**Comment by devimc** [comment]
@Pennyzct @fidencio  what about the 1.18 release candidate? may worth to try it out and be ready for the stable release?

 https://github.com/cri-o/cri-o/releases/tag/v1.18.0-rc1

**Comment by fidencio** [comment]
@devimc, I do think so.
@haircommander, I'd guess you're totally in favour on getting the tests in the latest cri-o, even if that means a release candidate, right? :-)

**Comment by haircommander** [comment]
definitely in favor!

**Comment by amshinde** [comment]
I am fine with moving to 1.18.0-rc1.
@chavafg We should move to testing with kubernetes 1.18 as well in our CI.

**Comment by chavafg** [comment]
Yeah, we should move the k8s version at the same time. And also the `Sonobuoy` version to [0.18](https://github.com/vmware-tanzu/sonobuoy/releases/tag/v0.18.0)

**Comment by amshinde** [comment]
@chavafg cri-o 1.18 has landed. We should move to this version:
https://cri-o.github.io/cri-o/v1.18.0

cc @jodh-intel Copying you in for reference to the release notes from cri-o. I think the split of the commits in the release notes into bugs, features and documentation is pretty neat.

**Comment by jodh-intel** [comment]
Thanks @amshinde - that triggered me to remember to raise an issue on "conventional commits": https://github.com/kata-containers/kata-containers/issues/195.
