### ISSUE TITLE
qemu-vanilla version not match

### ISSUE THREAD

**Issue by packyzbq** [kata-containers/runtime#2497]
# Description of problem
I'm using this script to install kata containers
```bash
source /etc/os-release
sudo yum -y install yum-utils
ARCH=$(arch)
BRANCH="${BRANCH:-master}"
sudo -E yum-config-manager --add-repo "http://download.opensuse.org/repositories/home:/katacontainers:/releases:/${ARCH}:/${BRANCH}/CentOS_${VERSION_ID}/home:katacontainers:releases:${ARCH}:${BRANCH}.repo"
sudo -E yum -y install kata-runtime kata-proxy kata-shim
```

There's an error, `kata-runtime-1.11.0~alpha0-65.1.x86_64` needs `qemu-vanilla = 4.1.1+git.99c5874a9b`, there is only `qemu-vanilla-4.1.0+git.9e06029aea-46.1.x86_64 (home_katacontainers_releases_x86_64_master)`

Do you need to update the new version qemu-vanilla in the repo ?

# Expected result

Install Kata container successfully

**Comment by ariel-adam** [comment]
Since we have not seen this issue laterly we will not fix and close.
