### ISSUE TITLE
Is there Manual for docker running with kata-clh ? Something goes wrong when I do

### ISSUE THREAD

**Issue by Apokleos** [kata-containers/runtime#2498]
# Description of problem
When I  ```docker run -it --runtime=kata-clh ubuntu:18.04 /bin/bash``` . The result is as below:
# Expected result
docker with kata-clh runtime created and run successfully!
# Actual result
```
docker: Error response from daemon: OCI runtime create failed: error: 500  reason: VmBoot(VmBoot(DeviceManager(CreateVirtioFs(VhostUserGetFeatures(VhostUserProtocol(SocketBroken(Os { code: 104, kind: ConnectionReset, message: "Connection reset by peer" }))))))): unknown.
ERRO[0000] error waiting for container: context canceled
```

# My pre operation as below:
(1) download the kata static tarball and untar into /op/
```
# wget https://github.com/kata-containers/runtime/releases/download/1.10.1/kata-static-1.10.1-x86_64.tar.xz
# tar -xvf kata-static-1.10.1-x86_64.tar.xz -C /
```
(2) Docker have been installed, and daemon.json
```
{
  "runtimes": {
    "kata-qemu": {
      "path": "/opt/kata/bin/kata-runtime",
      "runtimeArgs": [ "--kata-config", "/opt/kata/share/defaults/kata-containers/configuration-qemu.toml" ]
    },
    "kata-qemu-virtiofs": {
      "path": "/opt/kata/bin/kata-runtime",
      "runtimeArgs": [ "--kata-config", "/opt/kata/share/defaults/kata-containers/configuration-qemu-virtiofs.toml" ]
    },
     "kata-fc": {
      "path": "/opt/kata/bin/kata-runtime",
      "runtimeArgs": [ "--kata-config", "/opt/kata/share/defaults/kata-containers/configuration-fc.toml" ]
    },
     "kata-clh": {
      "path": "/opt/kata/bin/kata-runtime",
      "runtimeArgs": [ "--kata-config", "/opt/kata/share/defaults/kata-containers/configuration-clh.toml" ]
    }
  },
  "storage-driver": "devicemapper"
}
```
then, systemctl daemon-reload and systemctl restart docker
(3) docker run a container
```
docker run -ti --runtime=kata-clh ubuntu:18.04 /bin/bash
```
Something goes wrong as descripted as `Description of problem`

# OS
```
OS: CentOS 7
Kernel： Linux 3.10.0-957.el7.x86_64 x86_64
```
# Docker
```
Client:
 Debug Mode: false

Server:
 Containers: 4
  Running: 0
  Paused: 0
  Stopped: 4
 Images: 2
 Server Version: 19.03.6
 Storage Driver: devicemapper
  Pool Name: docker-253:3-8419597-pool
  Pool Blocksize: 65.54kB
  Base Device Size: 10.74GB
  Backing Filesystem: xfs
  Udev Sync Supported: true
  Data file: /dev/loop0
  Metadata file: /dev/loop1
  Data loop file: /var/lib/docker/devicemapper/devicemapper/data
  Metadata loop file: /var/lib/docker/devicemapper/devicemapper/metadata
  Data Space Used: 121.8MB
  Data Space Total: 107.4GB
  Data Space Available: 3.223GB
  Metadata Space Used: 17.62MB
  Metadata Space Total: 2.147GB
  Metadata Space Available: 2.13GB
  Thin Pool Minimum Free Space: 10.74GB
  Deferred Removal Enabled: true
  Deferred Deletion Enabled: true
  Deferred Deleted Device Count: 0
  Library Version: 1.02.158-RHEL7 (2019-05-13)
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: kata-qemu-virtiofs runc kata-clh kata-fc kata-qemu
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: b34a5c8af56e510852c35414db4c1f4fa6172339
 runc version: 3e425f80a8c931f88e6d94a8c831b9d5aa481657
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 24
 Total Memory: 62.65GiB
 ID: JQ32:YN6T:6BGP:WV55:33N7:BD6G:M73H:CLUG:IVZM:XA7E:GRDD:ADES
 Docker Root Dir: /var/lib/docker
 Debug Mode: false

 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false

WARNING: the devicemapper storage-driver is deprecated, and will be removed in a future release.
WARNING: devicemapper: usage of loopback devices is strongly discouraged for production use.
         Use `--storage-opt dm.thinpooldev` to specify a custom block storage device.
```

and I have verified the cloud-hypervisor alone with cloud-hypervisor's manual, It works fine:
```
/opt/kata/bin/cloud-hypervisor --kernel ./hypervisor-fw --disk path=clear-29160-kvm.img --cpus boot=4 --memory size=1024M --net "tap=,mac=,ip=,mask=" --rng
```

**Comment by amshinde** [comment]
@jcvenegas Can you take a look?

**Comment by jcvenegas** [comment]
Hey I will take a look later today

**Comment by jcvenegas** [comment]
@amshinde  I dont see any clh binary added to the tarballs I tried to use. We need to fix that
@Apokleos  I imagine that you installed clh manually? meanwhile the tarball is fixed could you checkout to the version/tag that clh requires for example for 1.10.1  could you checkout to https://github.com/kata-containers/runtime/blob/stable-1.10/versions.yaml#L78

**Comment by jcvenegas** [comment]
https://github.com/kata-containers/kata-containers/pull/158 adding logs to get more information what was missing in last release

**Comment by amshinde** [comment]
@jcvenegas I do see `/opt/kata/bin/cloud-hypervisor` binary inside the tarball.

**Comment by jcvenegas** [comment]
@amshinde thanks, my bad. Seems that my system is having another issue.

@Apokleos going back to bug

could you provide what is the output runtime version:
```
 /opt/kata/bin/kata-runtime --version
```
Same for cloud-hypervisor just to verify that the binaries match.
```
/opt/kata/bin/cloud-hypervisor --version
```

For installation I recommend you do via kata-deploy
https://github.com/kata-containers/packaging/tree/master/kata-deploy#install-kata-and-configure-docker
```
docker run -v /opt/kata:/opt/kata -v /var/run/dbus:/var/run/dbus -v /run/systemd:/run/systemd -v /etc/docker:/etc/docker -it katadocker/kata-deploy kata-deploy-docker install
```
Note: I install it and it is installing an not updated version but still should work.

**Comment by Apokleos** [comment]
> @amshinde thanks, my bad. Seems that my system is having another issue.
> 
> @Apokleos going back to bug
> 
> could you provide what is the output runtime version:
> 
> ```
>  /opt/kata/bin/kata-runtime --version
> ```
> 
> Same for cloud-hypervisor just to verify that the binaries match.
> 
> ```
> /opt/kata/bin/cloud-hypervisor --version
> ```
> 
> For installation I recommend you do via kata-deploy
> https://github.com/kata-containers/packaging/tree/master/kata-deploy#install-kata-and-configure-docker
> 
> ```
> docker run -v /opt/kata:/opt/kata -v /var/run/dbus:/var/run/dbus -v /run/systemd:/run/systemd -v /etc/docker:/etc/docker -it katadocker/kata-deploy kata-deploy-docker install
> ```
> 
> Note: I install it and it is installing an not updated version but still should work.

Thanks very much @jcvenegas @amshinde 

```
[root@xxx kata]# /opt/kata/bin/cloud-hypervisor --version
cloud-hypervisor 0.4.0
[root@xxx kata]# /opt/kata/bin/kata-runtime --version
kata-runtime  : 1.10.1
   commit   : 2007b96cd84dbe6a16b0bfe32cd6ab01adfaddce
   OCI specs: 1.0.1-dev
```

**Comment by jcvenegas** [comment]
I will close this issue, feel free to open it again  if there any other gap for now kata-deploy will be the only method to use for now as installation, dont see packages will include cloud-hypervisor in a near time.
