### ISSUE TITLE
Does Kata limit the CPU, Mem through cgroup? 

### ISSUE THREAD

**Issue by YongHaoWu** [kata-containers/runtime#2500]
**Which feature do you think can be improved?**

Homemake container manager read the container infos through cgroup files, like `/sys/fs/cgroup/cpuacct/docker`.
Seems Kata is just use VM to limit the memory instead of cgroup.

**How can it be improved?**

Can also write the limit to cgroup also?

**Additional Information**

` docker run --rm -it --memory 4g --cpus 3  ubuntu `  only works inside the container, not cgroup.
```
root@localhost:~# cat /sys/fs/cgroup/memory/docker/kata_860d4bc08c796bab3806b7382fe7ebad6e706288c6d44022971e6c4ac21c1e3d/memory.soft_limit_in_bytes
9223372036854771712
root@localhost:~# cat /sys/fs/cgroup/memory/docker/kata_860d4bc08c796bab3806b7382fe7ebad6e706288c6d44022971e6c4ac21c1e3d/memory.kmem.limit_in_bytes
9223372036854771712
```

**Before raising this feature request**

Yes.

**Comment by YongHaoWu** [comment]
@grahamwhaley @devimc  As you had create the host's cgroup file, I think u can also set the value to it.  

![image](https://user-images.githubusercontent.com/7270555/75438427-e0cf4a00-5992-11ea-91ec-4e473ebb79dc.png)

`6dad6d50be20` is my container created by `docker run --rm -it --memory 2g --cpus 3  ubuntu`.

Seems `docker stats` on host is not correct? e.g., MEM, CPU

**Comment by devimc** [comment]
@YongHaoWu did you enable `sandbox_cgroup_only`? 

https://github.com/kata-containers/documentation/blob/master/design/host-cgroups.md

**Comment by egernst** [comment]
In the context of Kubernetes, the pod cgroup is created by Kubelet, which will also restrict them the containers (in kata case, the vmm, vcpu threads, io threads). We then create further cgroups within the VM to manage each container.

**Comment by egernst** [comment]
And, is your own goal docker CLI or something like Kubernetes?

**Comment by YongHaoWu** [comment]
@egernst  Hi, the docker CLI is only original docker CLI.

@devimc Hi, I didn't enable `sandbox_cgroup_only`. 

When I just use `docker runc` before, my program can  get the container cpu usage, mem usage through `cgroup` system.

You can check the code here: https://github.com/projecteru2/agent/blob/master/engine/stat.go#L57


Thanks!

**Comment by devimc** [comment]
@YongHaoWu please enable `sandbox_cgroup_only` and try again

**Comment by YongHaoWu** [comment]
@devimc  Hi, I had enable `sandbox_cgroup_only ` and tried, still the same:

![image](https://user-images.githubusercontent.com/7270555/75953504-75cec780-5eec-11ea-85e7-8e120a96a6b9.png)


config is :
```

root@localhost:~# kata-runtime kata-env
[Meta]
  Version = "1.0.23"

[Runtime]
  Debug = false
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  SandboxCgroupOnly = true
  Path = "/usr/bin/kata-runtime"
  [Runtime.Version]
    Semver = "1.10.0-alpha1"
    Commit = ""
    OCI = "1.0.1-dev"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 4.1.0\nCopyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-vanilla-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  Msize9p = 8192
  MemorySlots = 10
  Debug = false
  UseVSock = false
  SharedFS = "virtio-9p"

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.10.0-alpha1_agent_c87f497312.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-4.19.75.55-44.container"
  Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.10.0-alpha1-3b405f7"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.10.0-alpha1-54f93db"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"
  Debug = false
  Trace = false
  TraceMode = ""
  TraceType = ""

[Host]
  Kernel = "4.15.0-42-shopee-generic"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) Silver 4116 CPU @ 2.10GHz"

[Netmon]
  Version = "kata-netmon version 1.10.0-alpha1"
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
```

**Comment by devimc** [comment]
I see the same behaviour with runC

```
$ docker run -dti -m 1G --rm --runtime=runc centos bash
79ae73d2ef64ddc24902f67aef6280c8d40fe3bb454f8ade5933ce3b7954802c
$ cat /sys/fs/cgroup/memory/docker/79ae73d2ef64ddc24902f67aef6280c8d40fe3bb454f8ade5933ce3b7954802c/memory.soft_limit_in_bytes 
9223372036854771712
$ cat /sys/fs/cgroup/memory/docker/79ae73d2ef64ddc24902f67aef6280c8d40fe3bb454f8ade5933ce3b7954802c/memory.limit_in_bytes 
1073741824
```

maybe you confused `soft_limit_in_bytes` with `limit_in_bytes` .. ?

**Comment by YongHaoWu** [comment]
Hi, @devimc . It is not the same with runC. 

```
root@localhost:~# docker run   --rm -it --memory 1g --cpus 3  ubuntu
WARNING: Your kernel does not support swap limit capabilities or the cgroup is not mounted. Memory limited without swap.
root@c941d40dc058:/#
```


```
root@localhost:~# cat /sys/fs/cgroup/memory/docker/kata_c941d40dc0584d514ff34843c10273cc89a1be5d2403bfac87f842c944bb927a/memory.soft_limit_in_bytes
9223372036854771712
root@localhost:~# cat /sys/fs/cgroup/memory/docker/kata_c941d40dc0584d514ff34843c10273cc89a1be5d2403bfac87f842c944bb927a/memory.limit_in_bytes
9223372036854771712
```


Note that this is set to `sandbox_cgroup_only=true`.

**Comment by devimc** [comment]
alright, I see what's the issue, you're using `1.10.0-alpha1` and the fix for this is in `1.11.0-alpha0`

**Comment by YongHaoWu** [comment]
@devimc Great, everything works find on `1.11.0-alpha0` at my first glance.
Could u plz show me the PR of this change? I would love to study kata's code.

**Comment by devimc** [comment]
@YongHaoWu https://github.com/kata-containers/runtime/pull/2441

please close this issue when you think it's no longer needed

**Comment by YongHaoWu** [comment]
@devimc Sure, thanks.
