### ISSUE TITLE
I would like to contribute SELinux support to kata-runtime.

### ISSUE THREAD

**Issue by rhatdan** [kata-containers/runtime#2501]
Basically I want to launch the KVM launcher tool (qemu?) with an SELinux label, similar to what we do with libvirt.
Currently when I use kata with podman, it complains if we specify a label that kata does not support SELinux labels.  What I would like to do is have kata just use this label to apply to the KVM launcher.  Then I will work to generate a new policy type (container_kvm_t) that will allow the KVM Launcher tool to do its thing, but prevent breakout.

The problem I have is I don't know where to put the SELinux code changes into the kata source code.  The SELinux code has to be executed as close to the execution of the KVM Launcher as possible.  I could spend a lot of time trying to figure out the kata code, but I would prefer a quick pointer to where this should be added.

**Comment by devimc** [comment]
@rhatdan I think you are looking for this function:

https://github.com/kata-containers/runtime/blob/6bed2a724d3944f2226c9abd03c0b8718dab4be1/virtcontainers/sandbox.go#L993
