### ISSUE TITLE
standard_init_linux.go:211: exec user process caused "exec format error"

### ISSUE THREAD

**Issue by jeremiah** [kata-containers/runtime#2502]
# Description of problem
Run a ARM64 container on AMD64 with the kata-runtime
`$ docker run -v /usr/bin/qemu-arm-static:/usr/bin/qemu-arm-static --rm -ti arm64v8/debian:buster-slim uname -a`

# Expected result
uname -a output for container

# Actual result
standard_init_linux.go:211: exec user process caused "exec format error"
ERRO[0000] init failed                                   error="standard_init_linux.go:211: exec user process caused \"exec format error\"" name=kata-agent pid=1 source=agent
panic: --this line should have never been executed, congratulations--

goroutine 1 [running, locked to thread]:
main.init.0()
	/tmp/build-image-tmp.URDzNipYqO/go/src/github.com/kata-containers/agent/agent.go:1446 +0x10f

**Comment by grahamwhaley** [comment]
Hi @jeremiah - are you hoping to be able to run an ARM image on a X86 host (that is, a different architecture)? Kata does not do that I'm afraid. It's not supported functionality - it is not implemented.
Sure, in theory, as containers run in VMs, and the VMs could emulate the other architecture, technically it might be feasible with some work - but - it's not be done for Kata, as you would have to fully emulate the non-native processor architecture, and that would have a serious performance impact.
The topic has come up a couple of times before, but never with enough frequency or 'weight' for anybody to try and implement it.

**Comment by jeremiah** [comment]
Okay, thanks @grahamwhaley. I couldn't find any documentation saying that it wasn't possible so I just went ahead and tried it. :-) Thanks for letting me know it's out of scope for Kata! I'll still use it on Intel because of it's isolation and speed, but will look for other technologies to use with emulation.
