### ISSUE TITLE
persist: refactor the HypervisorState struct for better readability

### ISSUE THREAD

**Issue by likebreath** [kata-containers/runtime#2508]
The `HypervisorState` struct from `virtcontainers/persist/api/hypervisor.go` can be improved in a few ways for better readability:
* Adjust comments to reflect support of cloud-hypervisor
* Re-arrange the struct members to reflect dependency on different types of hypervisor.
   * We may need to discuss whether we can and should split hypervisor-specific members into different structs.

**Comment by jcvenegas** [comment]
I feel that  struct members  or different  stores per hypervisor type would be the cleanest way implement.

**Comment by amshinde** [comment]
cc @WeiZhang555

**Comment by jodh-intel** [comment]
Any update on this @likebreath?

**Comment by likebreath** [comment]
Closing the issue now given not many discussions/inputs are collected for the potential refactoring.
