### ISSUE TITLE
RFC: logging: shimv2 logging control is rather 'coarse', and does not match 'classic' kata.

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#2513]
**Which feature do you think can be improved?**

## Problem description

Looking into integration of kata shimv2 logs into a stack such as ELK, a few things occur to me:

1) Log en/disable granularity control for both kata runtime shimv2 and 'classic' is quite coarse
2) The default log levels of runtime shimv2 and 'classic' are different.

#### shimv2

Today, afaict, our shimv2 log level [defaults to `WarnLevel`](https://github.com/kata-containers/runtime/blob/master/containerd-shim-v2/service.go#L69-L71), unless `containerd` has had `debug` enabled in its config, in which case we go to `DebugLevel`.

```go
	if !opts.Debug {
		logrus.SetLevel(logrus.WarnLevel)
	}
```

Presently this gives us a pretty coarse choice of log output - either:

- Warnings, Errors etc., which is good (that is possibly all you want to know and monitor - did something go fairly wrong)
- Debug - which is pretty verbose, and in most cases, unless you are debugging something, is probably not what you want.

What this currently effectively ignores is that we also have an `InfoLevel` set of log messages spread through the code. A rough peek at the code in the runtime for instance looks like:

```bash
kata-containers/runtime $ git grep 'Info(' | fgrep -v vendor | fgrep -i log | wc
    119     579   10452
kata-containers/runtime $ git grep 'Debug(' | fgrep -v vendor | fgrep -i log | wc
     76     421    6932
```

#### classic

In Kata 'classic', the log level is controlled by the `enable_debug` boolean settings in the config file. The default log level in 'classic' is 'Info', so we can only move from 'Info' up to 'Debug'. afaict, there is no way to set the log level to 'Warn' for instance.

### Default log level

As hinted at above, In Kata runtime 'original', afaict, we default to 'InfoLevel' (the `logrus` default), but in runtime shimv2 we default to 'WarnLevel'. This is a disparity - we should at least discuss, and document, this.

## Proposals

1) We discuss if we should expand our kata config file `enable_debug` entries from being just a boolean true/false, to also having the ability to set levels, such as `enable_debug = info`. This will allow more flexibility in end user choice of what warning levels to get. We could also leave the option of 'true' as valid (so as not to break existing config files), and make that align with the current 'Debug' level.
2) TBH, I'm not sure we need to log 'Info' messages by default, unless somebody deliberately wants to see them. I suggest we turn the default 'classic' Kata runtime log level **down** to `WarnLevel` from `InfoLevel`.
  This will then match the shimv2 runtime, reduce our default log verboseness, but still generate logs for Warnings and Errors.

**Comment by grahamwhaley** [comment]
/cc @amshinde @jodh-intel @lifupan 
Related to https://github.com/kata-containers/documentation/pull/597

**Comment by lifupan** [comment]
Hi @grahamwhaley 

Yes, the logger is much more confused and it needs much more setting to enable logs for containerd + shimv2. 
The current logic is as below:

If containerd didn't enable debug option, than shimv2 will not forward any  kata runtimes log to containerd's log pipe, which was added by this PR https://github.com/kata-containers/runtime/pull/2208/files . The author wanted to respect the containerd's debug setting and didn;t want to see much more kata's log if containerd didn't enable debug. 
IMO, this logic is unsophisticated.  

In order to keep align with containerd and make the setting as simple as possible, I think 
We can do as below:
1) make kata's default debug level as "Warning" which can produce  few log which would's annoy user who didn't want to much more logs. 
2) if containerd didn't enable "debug", then shimv2 also forward the kata's runtime log to containerd's log pipe, but set runtime's log level as default "Warning" level.  This can also make the containerd see kata's error log instead of  see nothing as we did now. 
3) if containerd enabled "debug" option, then forward the kata's log to containerd's log pipe and 
set the kata's runtime log level as "debug" which would produce much more info.

**Comment by grahamwhaley** [comment]
Hi @lifupan - thanks for the info...

> If containerd didn't enable debug option, than shimv2 will not forward any kata runtimes log to containerd's log pipe, which was added by this PR https://github.com/kata-containers/runtime/pull/2208/files . The author wanted to respect the containerd's debug setting and didn;t want to see much more kata's log if containerd didn't enable debug.

I think this is not quite right. As noted in that commit and in the code fragment above, if debug is not set, then shimv2 defaults the log level to `WarnLevel`. So, we do still get Error and Warn messages from shimv2 in the containerd logs (this confused me last week). To try and prove this (to myself), I started some kata pods, and then killed one of the `qemu`s on the node. I get this in the containerd log:

```bash
$ journalctl -f -t containerd
...
Mar 06 11:18:29 minikube containerd[12128]: time="2020-03-06T11:18:29.313977757Z"
 level=error msg="Fail to execute qmp QUIT"
 ID=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8
 error="exitting QMP loop, command cancelled" source=virtcontainers subsystem=qemu
```

So, we do see shimv2 messages - but only if there are fairly fatal problems. I think this is actually probably a good default.

And, thanks to I think it was @devimc who clarified to me, the shimv2 does still log its own log directly into the system journal on the node, but under the type `kata`, so on a node I can do:

```bash
$ journalctl -t kata
...
Mar 06 11:18:28 minikube kata[13485]: time="2020-03-06T11:18:28.536438108Z" level=error msg="Wait for process failed" container=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 error="rpc error: code = Unavailable desc = transport is closing" pid=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8
Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.265903265Z" level=error msg="Wait for process failed" container=01c82e34bf84a3a7deddcfee372513f141ba6624235acf58053906928da98fa9 error="rpc error: code = Canceled desc = grpc: the client connection is closing" pid=01c82e34bf84a3a7deddcfee372513f141ba6624235acf58053906928da98fa9
Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.313663546Z" level=warning msg="Agent did not stop sandbox" ID=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 error="Dead agent" sandbox=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 sandboxid=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 source=virtcontainers subsystem=sandbox
Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.313977757Z" level=error msg="Fail to execute qmp QUIT" ID=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 error="exitting QMP loop, command cancelled" source=virtcontainers subsystem=qemu
Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.320860348Z" level=warning msg="sandox cgroups path is empty" ID=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 sandbox=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 source=virtcontainers subsystem=sandbox
Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.323160033Z" level=warning msg="stop container failed" container=01c82e34bf84a3a7deddcfee372513f141ba6624235acf58053906928da98fa9 error="Could not find the container \"01c82e34bf84a3a7deddcfee372513f141ba6624235acf58053906928da98fa9\" from the sandbox \"4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8\" containers list: Container does not exist"
```

That is different functionality from 'classic' kata, where it logs under different units and names I think (as [we document currently](https://github.com/kata-containers/runtime#logging)) - so, we should improve our documentation to cover that as well...

>     1. make kata's default debug level as "Warning" which can produce  few log which would's
>     annoy user who didn't want to much more logs.

@lifupan - do you mean for shimv2, or 'classic' Kata? For shimv2, this is already the default for what goes into the containerd logs I believe. For 'classic' Kata, yes, I'd like to make that change to "Warning". The default in 'classic' Kata today is "Info" I believe, which is too noisy imo.

> 
>     2. if containerd didn't enable "debug", then shimv2 also forward the kata's runtime log to 
>     containerd's log pipe, but set runtime's log level as default "Warning" level. 
>     This can also make the containerd see kata's error log instead of  see nothing as we did now.

I believe this is how it is today already.

>     3. if containerd enabled "debug" option, then forward the kata's log to containerd's log pipe and
>      set the kata's runtime log level as "debug" which would produce much more info.

I think this is also the default today - if containerd has set `debug`, then shimv2 skips the code to set the level to "Warning", and uses the default inherited from the containerd code, which is "Debug".

**Comment by lifupan** [comment]
> Hi @lifupan - thanks for the info...
> 
> > If containerd didn't enable debug option, than shimv2 will not forward any kata runtimes log to containerd's log pipe, which was added by this PR https://github.com/kata-containers/runtime/pull/2208/files . The author wanted to respect the containerd's debug setting and didn;t want to see much more kata's log if containerd didn't enable debug.
> 
> I think this is not quite right. As noted in that commit and in the code fragment above, if debug

Yes, you are right. I always thought containerd only do the log forward when debug enabled.


> And, thanks to I think it was @devimc who clarified to me, the shimv2 does still log its own log directly into the system journal on the node, but under the type `kata`, so on a node I can do:
> 

> ```shell
> $ journalctl -t kata
> ...
> Mar 06 11:18:28 minikube kata[13485]: time="2020-03-06T11:18:28.536438108Z" level=error msg="Wait for process failed" container=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 error="rpc error: code = Unavailable desc = transport is closing" pid=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8
> Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.265903265Z" level=error msg="Wait for process failed" container=01c82e34bf84a3a7deddcfee372513f141ba6624235acf58053906928da98fa9 error="rpc error: code = Canceled desc = grpc: the client connection is closing" pid=01c82e34bf84a3a7deddcfee372513f141ba6624235acf58053906928da98fa9
> Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.313663546Z" level=warning msg="Agent did not stop sandbox" ID=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 error="Dead agent" sandbox=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 sandboxid=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 source=virtcontainers subsystem=sandbox
> Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.313977757Z" level=error msg="Fail to execute qmp QUIT" ID=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 error="exitting QMP loop, command cancelled" source=virtcontainers subsystem=qemu
> Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.320860348Z" level=warning msg="sandox cgroups path is empty" ID=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 sandbox=4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8 source=virtcontainers subsystem=sandbox
> Mar 06 11:18:29 minikube kata[13485]: time="2020-03-06T11:18:29.323160033Z" level=warning msg="stop container failed" container=01c82e34bf84a3a7deddcfee372513f141ba6624235acf58053906928da98fa9 error="Could not find the container \"01c82e34bf84a3a7deddcfee372513f141ba6624235acf58053906928da98fa9\" from the sandbox \"4744436518c2cae76dcd22ad6b2481007f9b4d83decb3a6b81cc76a6f196baf8\" containers list: Container does not exist"
> ```
> 
> That is different functionality from 'classic' kata, where it logs under different units and names I think (as [we document currently](https://github.com/kata-containers/runtime#logging)) - so, we should improve our documentation to cover that as well...
> 

Yes, I do see it. but I think both of the shimv2 and 'classic' kata share the same codes of syslog , 
why are they under different names
BTW, since the shimv2 had forwarded the log to containerd, is it necessary to log it into syslog another copy?  Can we disable it for shimv2? 

> > ```
> > 1. make kata's default debug level as "Warning" which can produce  few log which would's
> > annoy user who didn't want to much more logs.
> > ```
> 
> @lifupan - do you mean for shimv2, or 'classic' Kata? For shimv2, this is already the default for what goes into the containerd logs I believe. For 'classic' Kata, yes, I'd like to make that change to "Warning". The default in 'classic' Kata today is "Info" I believe, which is too noisy imo.
> 

Yes, I do mean for the common kata, including shimv2 and 'classic' kata.

**Comment by grahamwhaley** [comment]
> > That is different functionality from 'classic' kata, where it logs under different units and names I think (as [we document currently](https://github.com/kata-containers/runtime#logging)) - so, we should improve our documentation to cover that as well...
> 
> Yes, I do see it. but I think both of the shimv2 and 'classic' kata share the same codes of syslog ,
> why are they under different names

I don't know - I tried to have a look at the code earlier to work out where/how, but failed to find it. I think it is to do with the `name` variable in the from the [katautils](https://github.com/kata-containers/runtime/blob/master/pkg/katautils/config-settings.go#L63), which can then be over-ridden from [this code](https://github.com/kata-containers/runtime/blob/master/pkg/katautils/config.go#L1370-L1383)... maybe we don't call that piece of code for shimv2. @jodh-intel - I think you were the main author of the kata logging and journal code, any idea here?

> BTW, since the shimv2 had forwarded the log to containerd, is it necessary to log it into syslog another copy? Can we disable it for shimv2?
Indeed. I'm not convinced that we should *always* output to the system journal as well as stdout - it feels like duplication, and we do generate a *lot* of information into the system journal. Again, @jodh-intel , any thoughts on that?

> Yes, I do mean for the common kata, including shimv2 and 'classic' kata.
OK, I think that is a **+2** then for reducing the standard classic kata log level(s) down to 'Warn' from 'Info'.... I'll let folks mull over and respond, and if nothing happens, will start to send RFC PRs next week ;-)

**Comment by jodh-intel** [comment]
Responding to the original proposals

# 1) Expand the scope of `enable_debug`

I'd personally consider leaving the `enable_debug` boolean as -- it theory -- that could do multiple things. Yes, by increasing the range of permitted values we get what we want, but I think setting something like `enable_debug = info` is just not clear enough.

So, to avoid any confusion, I think we should add a `log-level={debug,info,warn,error}` option for the components (probably both in `configuration.toml` and as CLI options. That can have a default value (see below), but **iff** `enable_debug=true`, the log level will always be set to `debug`, regardless of the value of `--log-level` (for backwards compatibility).

# 2) Switch the default log level

I think switching the default logging level for all components from "info" to "warn" is worth considering (ftr, I vote "yes"). Sounds like a good discussion topic for the Arch Committee meeting to me... :)

**Comment by jodh-intel** [comment]
Closing. Feel free to re-open if required. We are adding tracing to shimv2, which has the ability to log key/value pairs like the logging. This may be a better approach going forward.
