### ISSUE TITLE
Add Selinux support for containers running within guest

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#2514]
PR https://github.com/kata-containers/runtime/pull/2503 adds selinux support for confining the VM. 
The next step would be to confine the containers within the guest itself. There is quite a bit of work involved here. 
We would need to add selinux support to the guest kernel.
Using SELinux inside of the VM would require the VM to load SELinux policy. We need to figure out how the SELinux policy will be provided, either use a policy from the host and pass that to the VM or create a policy within the guest.(Would this mean changes to the Kata VM root filesystem?)

We also need to figure out how to pass 2 selinux labels to Kata for the VM confinement and other for the container itself. (Could be Kata config.toml or longterm adding this change in the OCI spec itself)

**Comment by amshinde** [comment]
cc @rhatdan

**Comment by jodh-intel** [comment]
@fidencio - could you comment on whether this is currently possible?

**Comment by fidencio** [comment]
This is yet not possible. I don't think we'll implement this in the short-term period. Next week (when I come back from staycation) I can check our documents, make this limitation explicit and move this one to the backlog.

@amshinde. would that work for you?

@jodh-intel, does the suggestion make sense?
