### ISSUE TITLE
clh: Enable Memory hotplug

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#2526]
**Which feature do you think can be improved?**

Allow to update memory to be increased with cloud-hypervisor

**How can it be improved?**

Update clh driver to do proper calls for memory hotplug

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by sboeuf** [comment]
Since Kata always uses virtio-fs with Cloud-Hypervisor, there's a hard dependency on first solving the issue https://github.com/cloud-hypervisor/cloud-hypervisor/issues/941 before we can expect memory hotplug to work for Kata + CH.
