### ISSUE TITLE
Update container status properly in case of kata_builtin_shim

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#253]
When we enable kata_builtin_shim, there is no shim process and thus the shim pid is not available for representing the container liveness.

**Comment by tedyu** [comment]
Is the above PR ready to go ?

**Comment by grahamwhaley** [comment]
@tedyu - you mean did anybody actually submit a PR to remove the shim pid.... /cc @bergwolf @egernst - any idea?
