### ISSUE TITLE
clh: Usage of REST APIs in Kata

### ISSUE THREAD

**Issue by likebreath** [kata-containers/runtime#2541]
This issue tracks how the [REST APIs](https://github.com/cloud-hypervisor/cloud-hypervisor/blob/master/docs/api.md#rest-api) provided by cloud-hypervisor is being used in Kata. We plan to integrate all REST APIs from CLH in Kata unless we don't find a valid use-case in the container land.

## REST APIs being used

Action                             | Endpoint                                                                                                               
-----------------------------------|----------------                                                                                                        
Check for the REST API availability| `/vmm.ping`                                                                                                            
Shut the VMM down                  | `/vmm.shutdown`                                                                                                        
Create the VM                      | `/vm.create`                                                                                                           
Boot the VM                        | `/vm.boot`                                                                                                             
Dump the VM information            | `/vm.info`                                                                                                             
Add/remove CPUs to/from the VM     | `/vm.resize` 
Add VFIO PCI device to the VM      | `/vm.add-device`    
Add/remove memory from the VM      | `/vm.resize`                                                                    

## REST APIs NOT being used
Action                             | Endpoint            | Note                                                                                             
-----------------------------------|---------------------|-----------------                                                                                 
Delete the VM                      | `/vm.delete`        | Probably would be nice to use as cleanup in driver
Shut the VM down                   | `/vm.shutdown`      | Want it for force stop?                                                                                    
Reboot the VM                      | `/vm.reboot`        | No use-case                                                                                      
Pause the VM                       | `/vm.pause`         | Needed for VM templating #2557                                                                        
Resume the VM                      | `/vm.resume`        | Needed from VM templating #2557                                                                        
Remove VFIO PCI device from the VM | `/vm.remove-device` | #2569
Add disk device to the VM | `/vm.add-disk` | Work-in-progress #2570
Add fs device to the VM | `/vm.add-fs` | All shared directories are mounted under the same path so only one fs dir is used in katal, not needed at the moment.
Add pmem device to the VM | `/vm.add-pmem` | Work-in-progress #2575
Add network device to the VM | `/vm.add-net` | May be needed for advanced CNI pluggins but not tests today to confirm, need to add test first and enable if needed.
Add vsock device to the VM | `/vm.add-vsock` | Kata works with vsock as could plug device, and we need this ready to allow the agent can connect so not a priority in kata.

**Comment by likebreath** [comment]
Please share if you have comments/advises/questions, epscially about REST APIs that are not being used.
/cc @jcvenegas @amshinde @sameo @sboeuf

**Comment by sboeuf** [comment]
@likebreath if there's no use case for some of the APIs, that's totally fine. Cloud-Hypervisor has a broader scope than just Kata, and Kata only uses the API that can fit in the container ecosystem.
Maybe `pause`/`resume` could have a use case, but I know that the container is already paused in the VM when that's needed.

**Comment by jcvenegas** [comment]
@likebreath @sboeuf probably we will want to use pause/resume for VM  factory, this  a use case were missing but not sure if is part of clh next items to add

**Comment by sboeuf** [comment]
@jcvenegas 
>but not sure if is part of clh next items to add

What do you mean? In terms of priority?
I'd say it's definitely not high priority (even from Kata's perspective), but it's ready from a CH perspective, so if this does not take too much effort to enable it for Kata, go for it :)

**Comment by amshinde** [comment]
@likebreath I think we do call the Remove method on vfio devices, so should make use of `/vm.remove-device` to implement that.

**Comment by likebreath** [comment]
@sboeuf @jcvenegas In the status update tomorrow, we can talk about whether the VM factory is something we want to include in the near future.
@amshinde Thanks for the comments on `/vm.remove-device`. I have put its status as `To be added`.

**Comment by likebreath** [comment]
Two more new APIs being added from CLH for the past month: `/vm.add-fs` and `/vm.add-vsock`.

As noted [here](https://github.com/kata-containers/documentation/blob/master/design/virtualization.md#hotplug-devices), Kata prefers to start with minimum configurations and hot-plug devices on-the-fly as needed, Do we see potential benefits of hot-plugging `vosck` and/or  `virtio-fs` devices? 

/cc @jcvenegas
