### ISSUE TITLE
clh: Complete the 'hypervisor' interface functions in the clh driver code

### ISSUE THREAD

**Issue by likebreath** [kata-containers/runtime#2544]
This issue tracks the status of all [`hypervisor` interface functions](https://github.com/kata-containers/runtime/blob/master/virtcontainers/hypervisor.go#L763-L793) being supported in [`clh` driver code](https://github.com/kata-containers/runtime/blob/master/virtcontainers/clh.go). We take the [`qemu` driver code](https://github.com/kata-containers/runtime/blob/master/virtcontainers/qemu.go) as a reference. We aim to provide  support for all interface functions comparable to `qemu`, unless we identify necessary adjustments required by `clh`.

## List of APIs being fully supported 
With all the APIs listed below, we are covering all core functionalities of using CLH as a new hypervisor in kata.

Interface function | Note | 
------------------- | ----- |
createSandbox() | Done |
startSandbox()  | Done |
stopSandbox()  | Done |
resizeVCPUs() | Done | 
capabilities() | Done | 
hypervisorConfig() |  Done | 
check() | Done  | 
save() | Done |
load() | Done | 
generateSocket() | Done | 
resizeMemory() |  #2526 only hotplug implemented, not virtio-mem #2406 , no probe based support | 
addDevice() |  Partially legacy, as CLH provides cleaner APIs that offloads this API quite a bit| 
getSandboxConsole() | This should be solved with the new debug console support (https://github.com/kata-containers/documentation/pull/704)

## List of APIs to-be-supported
Those APIs are work-in-progress. At the time of writing, all three APIs here are for improvements and hence are all in `Medium` priority.

Interface function | Priority | Note 
------------------- | ----- | ----
hotplugAddDevice()  | Medium| Support blk/vfio hotplug. To-be-added: pmem(#2575) /netDev(https://github.com/kata-containers/kata-containers/pull/454) /vhostuserDev hotplug
hotplugRemoveDevice() | Medium|  Support blk unplug. To-be-added: the blk unplug can be extended to general device unplug in clh (#2569)
getThreadIDs() | Medium  | Needed enable legacy sandbox constrains model #2572
getPids() | Medium  | Need to provide virtiofsd pid as qemu does #2573

## List of APIs not supported
This is a list of 'hypervisor' APIs that we are planning not to support for now. They are either legacy interface APIs that won't be needed for CLH, or only required if we want to support VM factory/templating in Kata with CLH (which is to be determined).

Interface function | Label| Note 
------------------- | ----- | ---- 
disconnect() | Legacy | May not be needed for `clh`.  Used to stop qmp client in qemu, probably could be used to drop clh client connection, but not as critical as qmp that only supports one client.
cleanup() | Legacy | Nothing relevant to cleanup, not extra fds like qemu or jailer like fc
pauseSandbox() | TBD | Needed for VM templating
saveSandbox() | TBD | Needed for VM templating
resumeSandbox() | TBD | Needed for VM templating (and shimv2?)
fromGrpc()  | TBD | Needed to enable VM templating 
toGrpc() | TBD | Needed to enable VM templating

**Comment by jcvenegas** [comment]
@likebreath  updated list, a there still some functions to fix that would improve the integration in general, there are some of them that are related with VM templating a feature we have not enabled yet.

**Comment by ariel-adam** [comment]
@likebreath is this still relevant?
