### ISSUE TITLE
clh: Enable vmfactory

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#2557]
Today clh support some functions that could enable VM factory, this issue is a record to decide if want to enable as next integration step.

**Comment by jodh-intel** [comment]
@likebreath - can you comment on this?

**Comment by ariel-adam** [comment]
We decided we want to keep this open as part of the backlog

**Comment by likebreath** [comment]
@jodh-intel @ariel-adam Thanks for reviewing the issue. Yes, I agree we should keep this issue open. This is a feature we may want to enable w/ kata+clh (yet with a lower priority).
