### ISSUE TITLE
add forcibly_disable_pmu option

### ISSUE THREAD

**Issue by hejianet** [kata-containers/runtime#2558]
**Which feature do you think can be improved?**

Allow the guest to disable pmu
**How can it be improved?**

The user sometimes doesn't care about pmu usage(e.g. perf tool profiling).
But pmu will cost significant overhead on boot time and virtualization
context switch. E.g. on arm64, if guest pmu is enabled, kvm should save
and restore all PMU registers when guest/host switching.

**Additional Information**

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)? Yes

**Comment by justin-he** [comment]
new issue was opened to track the followup https://github.com/kata-containers/runtime/issues/2576

**Comment by ariel-adam** [comment]
@hejianet is this still relevant? do we know what the actual performance impact is?

**Comment by jodh-intel** [comment]
I'm going to close this since, as shown on the commits referenced by #2576, we removed the hard-coded `pmu=off`. You can now specify `pmu` options in the `configuration.toml` config file in the `cpu_features=` option (the comments even show a pmu example).
