### ISSUE TITLE
clh: Enable virtio-mem

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#2568]
**Which feature do you think can be improved?**

Cloud hypervisor recently added support for virtio-mem this required kernel patches that are not part of mainline kernel but could be added to experimental kernel. Depending how difficult to maintain new kernel patches would be a good option for early adoption. 

**How can it be improved?**

Enable virtio-mem

**Comment by egernst** [comment]
@jcvenegas @likebreath -- any updates on this one?  AFAIU virtio-mem will help us with  https://github.com/kata-containers/runtime/issues/1244#issuecomment-647576087.
