### ISSUE TITLE
--root= does nothing

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#257]
From @jodh-intel:
_The runtime supports the --root= global option but, although it is mentioned in a few strings, this option does nothing._

_Further, the build is setting the value of defaultRootDirectory to $(PKGRUNDIR) which is also incorrect given that container data is stored by virtcontainers, not the runtime._

**Comment by sboeuf** [comment]
Related to #22

**Comment by jodh-intel** [comment]
If we want this option to be truly honoured, we'll clearly need to add a new virtcontainers API to set it's `configStoragePath` / `runStoragePath` (`fileystem.go`).
