### ISSUE TITLE
clh: Enable persistent memory hotplug support

### ISSUE THREAD

**Issue by likebreath** [kata-containers/runtime#2575]
Cloud-hypervisor recently provides support to hotplug persistent memory with its REST API `/vm.add-pmem`.

**Comment by pohly** [comment]
Does this issue also include PMEM volume passthrough (https://github.com/kata-containers/runtime/issues/2262)?

**Comment by jcvenegas** [comment]
Actually this fits good with that issue.

@likebreath I have created an extra issue https://github.com/kata-containers/runtime/issues/2589 for boot. `vm.add-pmem` fits with #2262 as that is a happen after the VM boots and then seems that is hot-plugged.  This also in a way related with your current work with https://github.com/kata-containers/runtime/issues/2570
