### ISSUE TITLE
virtiofs to NFS volume shows strange "access denied" errors

### ISSUE THREAD

**Issue by c3d** [kata-containers/runtime#2598]
# Description of problem

This was first seen running Jenkins with NFS volumes, see https://github.com/kata-containers/runtime/issues/2597#issuecomment-611089093.

Running a container with an NFS volume gives partial write access to the volume, but semi-random `access denied` errors. This was tested using kubernetes, not tested with `podman` yet.

# Expected result

All write operations on the volume should succeed equally well.

# Actual result

Some operations work, others don't. Here is a sequence of operations illustrating this behaviour:

```
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ touch toto
  touch: setting times of 'toto': Permission denied
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ rm toto
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ echo Hello > toto
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ pwd
  /var/jenkins_home
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ cat toto
  Hello
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ echo Tada > toto
  bash: toto: Permission denied
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ echo Tada > toto
  bash: toto: Permission denied
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ echo Tada >> toto
  bash: toto: Permission denied
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ rm toto
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ echo Tada >> toto
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ echo Tada >> toto
  bash: toto: Permission denied
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ rm toto
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ touch toto
  touch: setting times of 'toto': Permission denied
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ touch toto
  touch: cannot touch 'toto': Permission denied
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ echo toto > toto
  bash: toto: Permission denied
  jenkins@jenkins-kata-7c755495c-dvvhb:~$ touch toto
  touch: cannot touch 'toto': Permission denied
```

**Comment by c3d** [comment]
@dagrh Would you like to take a look on this one? I will try to reproduce with podman.

**Comment by dagrh** [comment]
Have you tried reproducing with just a qemu+virtiofsd onto your NFS mount?
If you ls -l a newly created file what do you get:
  * Inside the container
  * On the host looking at the NFS mount

Dave

**Comment by c3d** [comment]
Exactly the same thing with podman. Also, @rhatdan, I tried with `--security-opt label=disable`, same. Anything else I should try?

**Comment by c3d** [comment]
@dagrh 

Inside the conatiner:

```
jenkins@82008007b9d7:~$ ls -lZ toto
-rw-r--r-- 1 jenkins jenkins ? 18 Apr  8 17:53 toto
```

On the NFS server:

```
ls -lZ toto                            /data/k8s@turbo.dinechin.lan
-rw-r--r--. 1 1000 1000 system_u:object_r:unlabeled_t:s0 18 Apr  8 19:53 toto
```

**Comment by rhatdan** [comment]
NFS enforces on the server side.  So any privileged process by root are going to be blocked.  For example Root inside of a container will be prevented from chown command.
NFS does not know about Capabilities.
Those would be a coule of ideas.

**Comment by rhatdan** [comment]
Could you give a simple reproducer of what is being blocked?

**Comment by rhatdan** [comment]
Oops you did include messages.

Does `setenforce 0`
allow the access?

**Comment by stefanha** [comment]
virtiofsd changes uid for file creation but not opening files, I/O, etc.  This would explain why an NFS server that refuses root would be unhappy with its client.

**Comment by stefanha** [comment]
Please post the /etc/exports file from the NFS server so it's clear how this NFS export is configured.  root_squash would be an interesting setting for example.

**Comment by ariel-adam** [comment]
@c3d can you provide @stefanha with the files?
