### ISSUE TITLE
kata container doesn't work with k8s local volume

### ISSUE THREAD

**Issue by coderplay** [kata-containers/runtime#2607]
# Description of problem
I am evaluating various local storage solutions listed below with kata runtime on kubernetes.  
1.  Maps a block device to kata guest VMs 
2. Leverages SPDK to create user space volumes and maps them to kata guest VMs.

I just tried the option 1,  looks like kata container doesn't work with k8s local volume.  Here is my setup 

* Cluster
```bash
$ kubectl get nodes
NAME              STATUS   ROLES    AGE   VERSION
ip-172-31-0-245   Ready    <none>   20h   v1.18.1
ip-172-31-71-2    Ready    master   25h   v1.18.1
```
ip-172-31-0-245 is a bare metal machine. 

* Storage 

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: local-pv
spec:
  capacity:
    storage: 1024Gi
  volumeMode: Filesystem
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  storageClassName: local-storage
  local:
    path: /dev/nvme0n1
    fsType: ext4
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: instance-type
          operator: In
          values:
          - i3.metal

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-claim
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1024Gi
  storageClassName: local-storage
```

* Pod

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: nginx-untrusted-pv
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  containers:
    - name: nginx
      image: nginx
      volumeMounts:
      - mountPath: "/var/www/html"
        name: nginx-vol
  volumes:
    - name: nginx-vol
      persistentVolumeClaim:
        claimName: nginx-claim
```

# Expected result

Here is an example output from a pod created by `runc`

```bash
$ kubectl exec -it nginx-untrusted-pv -- /bin/bash
root@nginx-untrusted-pv:/# df -h | grep www
/dev/nvme0n1    1.7T   77M  1.7T   1% /var/www/html
```
As you can see, nvme0n1 from host is mounted to guest.   When I tried the same thing with kata runtime,  the device didn't show up.

# Actual result
Below is the result when I tried with kata runtime
```
$ kubectl exec -it nginx-untrusted-pv -- /bin/bash
root@nginx-untrusted-pv:/# df -h | grep www
```

I noticed that somehow the device is mounted to host local 

```
$ mount | grep nvme0n1
/dev/nvme0n1 on /var/lib/kubelet/plugins/kubernetes.io/local-volume/mounts/local-pv type ext4 (rw,relatime,data=ordered)
/dev/nvme0n1 on /var/lib/kubelet/pods/ddd5a5aa-51f5-4f2c-85fa-0a6077a516d7/volumes/kubernetes.io~local-volume/local-pv type ext4 (rw,relatime,data=ordered)
/dev/nvme0n1 on /run/kata-containers/shared/sandboxes/c22fcbe328e26fc4f79a503ae5a0bbf2f35ecf85f42d5b0528b3bb78aa0d4118/04470b210b555f4c80a64146607a56cdce3862435c7d24397ca5e3ff4005b8aa-68aba3185a5b8e9f-html type ext4 (rw,relatime,data=ordered)
```

Did I miss anything?

**Comment by coderplay** [comment]
Any updates on this one?

**Comment by devimc** [comment]
I'm not an expert on this, but kata 1.11-rc0 supports SPDK, I don't know if this is what you need for the second case.

https://github.com/kata-containers/documentation/blob/master/use-cases/using-SPDK-vhostuser-and-kata.md

**Comment by coderplay** [comment]
Synced up with @dong-liuliu earlier,  kata SPDK currently only work with docker, it doesn't work with k8s.

**Comment by dong-liuliu** [comment]
hi, @coderplay 
Your are right, currently, vhost-user-blk device can't directly working inside K8S for local storage or snapshotter yet.

The enablement work on Kata containers is a starting point for the whole container ecosystem.
What I expect is same with you: for K8S local volume, and even for images/bundles. This requires extra plugins work in containerd and K8S.

Please wait for some weeks. I'm now working on that, and will add the extra the information into Kata documentation and containerd.

**Comment by dong-liuliu** [comment]
It is not a bug or issue in Kata. It just requries follow-up work in Containerd and K8S.
So I recommend to **remove the lable of `bug`**, @coderplay . And replace it with another proper lable name.

**Comment by dong-liuliu** [comment]
@coderplay @devimc 
sorry, I didn't noticed the issue until your `@`.
You may directly `@`me next time, if there is issue on related topics. :)

**Comment by coderplay** [comment]
@dong-liuliu thanks for the efforts on SPDK supporting.  And I do agree that was not a bug, more like a feature miss of k8s local PV (likely all PV types) support. 

However, I don't think the problem is originally related to SPDK. The support of k8s PV and SPDK are different features, although they might likely sharing some same code paths. 

I spent a few hours to dive deeper on the implementation of k8s PV yesterday.  Basically under the hod PVC(persisent volume claim) in k8s can be broken down to 3 stages:  provision, attach and mount.  At least, Normal container PVC and kata container PVC should diverge on the last stage: mount,  where for normal container the steps are: 
1. format the device (ext4 for example)
2. mount the formatted filesystem onto a host global path for the pod
3. mapping the mounted volume to container 

I don't think the way kata mapping a volume to guest is exactly the same way as it's for normal container.  It should through 9p virtio , see the [kvm introduction](http://www.linux-kvm.org/page/9p_virtio). For supporting such a diverge,  it's better create a out-of-tree CSI for kata instead of adding it to kata runtime.  Runtime is more towards to be a CRI.  I am willing to contribute one if you guys think it's the right way to go. 

@dong-liuliu Would you please give me more color on how you will implement the support of k8s SPDK for kata?    From my understanding, it's also better do it through a CSI where the provisioner in it would be able to create SPDK bdevs as well as  unix domain sockets & vhost-user-blk  devices on the host.

**Comment by coderplay** [comment]
I couldn't relabel this issue, could you guys please help?

**Comment by amshinde** [comment]
@coderplay I had tested Kata with local volumes based on block devices a while back. Here is a gist for reference:https://gist.github.com/amshinde/2ab9b5a2f2e91694a7421b1e2b787b58
Will have to see what needs to be done for Filesystem based local volumes.

**Comment by coderplay** [comment]
@amshinde  Thanks for sharing the gist, trying.

**Comment by coderplay** [comment]
@amshinde looks like there are some manual work.  The gist you shared was for mapping raw blocks from host to guest.   In order to work with `volumeMode: Filesystem` , you manually created a filesystem from host. The filesystem turned to a formatted device in the guest,  you manually remount it in the guest.  

> Will have to see what needs to be done for Filesystem based local volumes.
In order to make things transparent,  I think kata should handle above two manual works for users.
