### ISSUE TITLE
Merge build produced config-settings files

### ISSUE THREAD

**Issue by fidencio** [kata-containers/runtime#2622]
We currently have a config-settings generated during build time used by the `runtime` binary and a different one used by the `shimv2` binary.

Would be really good to have both merged into a single one, as both `shimv2` and `runtime` import the config-settings file in the pkg package.

This one has been opened based on the @lifupan's comment during the review of #2617: https://github.com/kata-containers/runtime/pull/2617#issuecomment-614357916

**Comment by jodh-intel** [comment]
Hi @fidencio - This isn't a complete solution but we do now [generate a single file and symlink it](https://github.com/kata-containers/runtime/commit/ad78c6fabe20cfcfe0d9f749f4b40c285e330b3f). If that's sufficient, can we close this?
