### ISSUE TITLE
versions.yml: Need spelling fix and capitalize descriptions.

### ISSUE THREAD

**Issue by wainersm** [kata-containers/runtime#2630]
In `versions.yml` most of the description fields have capitalized text. Let's keep all them capitalized for the sake of consistency.

Also need to fixed spelling of 'requried'.

**Comment by wainersm** [comment]
Fixed by #2629

**Comment by grahamwhaley** [comment]
;-) - when you add the 'Fixes #nnn' to one of your commits and re-force-push to your PR, then I believe github will make that reference for you automatically ;-)
