### ISSUE TITLE
Remove golangci-lint from versions.yaml

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#2636]
The runtime versions database contains an entry for `golangci-lint`:

- https://github.com/kata-containers/runtime/blob/master/versions.yaml#L227..L230

However, we have an entry for the same tool in the tests repo:

- https://github.com/kata-containers/tests/blob/master/versions.yaml#L56..L59

It looks like the tests version is the one being used:

- https://github.com/kata-containers/tests/blob/master/.ci/static-checks.sh#L291..L299

... so I think we can delete the entry from the runtime's `versions.yaml`.

@GabyCT, @chavafg - could you confirm this is safe to do?

**Comment by chavafg** [comment]
yeah, we can remove `golangci-lint` from the `versions.yaml` in this repo

**Comment by jodh-intel** [comment]
Thanks @chavafg.
