### ISSUE TITLE
How to get inside the virtual machine

### ISSUE THREAD

**Issue by free2k** [kata-containers/runtime#2637]
**Which feature do you think can be improved?**

You can enter the container through the crictl exec command. What command should I use if I want to enter the virtual machine?
**How can it be improved?**

Can enter the virtual machine

**Additional Information**

Anything else to add?

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by devimc** [comment]
https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#set-up-a-debug-console

initrd images already have a shell, you only need to add `agent.debug_console` in the kernel cmdline and run `socat` in the host.

**Comment by grahamwhaley** [comment]
(beat me to it....) Also note @free2k - generally not being able to get into the VM is a security feature, so is not normally enabled by default.

**Comment by free2k** [comment]
@devimc @grahamwhaley Thank you for your answers. I'm just curious and want to take a look at the virtual machine ~
