### ISSUE TITLE
Some doubts about limiting memory

### ISSUE THREAD

**Issue by free2k** [kata-containers/runtime#2639]
**Is your feature request related to a problem? Please describe.**
I want to create a container with 4G memory. After creating it, free will see 2G larger than the actual
**Describe the solution you'd like**
Can create 4G memory containers

https://github.com/kata-containers/runtime/issues/400#issuecomment-397469834

I have read this issue and there is one thing I cannot understand. If the memory is adjusted by hot-plug, is the adjustment based on actual needs, rather than adding 2G of memory to the actual needs

**Describe alternatives you've considered**

If you apply for 4g of memory, you want to see 4G memory in the free command in the container.
**Additional context**

**Before raising this feature request**

**Comment by free2k** [comment]
![image](https://user-images.githubusercontent.com/14852402/80174069-2ec79d80-8624-11ea-9899-1966f9812f64.png)
![image](https://user-images.githubusercontent.com/14852402/80174087-3b4bf600-8624-11ea-9a37-f1fc04c33e39.png)

**Comment by caoruidong** [comment]
Since we are running a VM, we need extra memory to run VM. See https://github.com/kata-containers/documentation/wiki/UserGuide#memory-allocation

**Comment by free2k** [comment]
> Since we are running a VM, we need extra memory. See https://github.com/kata-containers/documentation/wiki/UserGuide#memory-allocation

Because I need extra memory to run virtual machines, I can understand this. But why I see 2G more than the allocated memory in the container, that is, I allocate 8G memory, but the actual free command looks at 10G memory. So can I use 10G memory inside the container or only 8G memory?

**Comment by grahamwhaley** [comment]
iirc, `free` does not take into account the cgroups - so, although you can see 10G of memory in the VM, your container workload lives inside a cgroup that should have restricted actual memory access to 8G. I don't know how to check that though ... presumably one can go and look at the cgroup setup .... anybody?

**Comment by free2k** [comment]
> iirc, `free` does not take into account the cgroups - so, although you can see 10G of memory in the VM, your container workload lives inside a cgroup that should have restricted actual memory access to 8G. I don't know how to check that though ... presumably one can go and look at the cgroup setup .... anybody?

![image](https://user-images.githubusercontent.com/14852402/80197749-a95ae200-8651-11ea-929e-e7a8c82442d8.png)
Just wrote a program to test it, if the application memory exceeds 8G, it will be killed directly. So 8G is in effect, and cgroup viewing can prove this.

**Comment by free2k** [comment]
This problem can be closed, the free information in the container is / proc / meminfo of the virtual machine

**Comment by yadzhang** [comment]
I also have one question for limiting memory.  If a pod  has no limit for memory and the vm default memory size is 2G,  would that means the pod can only use 2G memory at most? 
But I think the pod can use all memory on the use without limit.
