### ISSUE TITLE
Hooks are invoked with incomplete state JSON

### ISSUE THREAD

**Issue by stefanha** [kata-containers/runtime#264]
# Description of problem

According to the OCI specification the state JSON passed to hooks must contain certain required fields:
https://github.com/opencontainers/runtime-spec/blob/master/runtime.md#state

virtcontainers/hook.go:buildHookState() only fills in the "pid" field.  Other required fields are empty strings, which does not conform to the specification (they need meaningful values).

One OCI hook that fails is oci-systemd-hook.  It cannot open the bundle config.json due to the missing state JSON "bundle" field:
https://github.com/projectatomic/oci-systemd-hook/blob/master/src/systemdhook.c#L884

Other hooks are likely to fail too.

# Expected result

OCI-compliant state JSON:
{
    "ociVersion": "0.2.0",
    "id": "oci-container1",
    "status": "running",
    "pid": 4422,
    "bundle": "/containers/redis"
}

# Actual result

{
    "ociVersion": "",
    "id": "",
    "status": "",
    "pid": 4422,
    "bundle": ""
}

**Comment by stefanha** [comment]
+caoruidong Hard to know until this bug is fixed.

**Comment by caoruidong** [comment]
https://github.com/intel/cc-oci-runtime/issues/270 shows that CC is unhappy with oci-systemd-hook. IMO, so is kata

**Comment by stefanha** [comment]
@caoruidong Did you see the oci-systemd-hook fix referenced from the issue you linked?  It seems like it might work now: https://github.com/projectatomic/oci-systemd-hook/issues/27

Anyway, this issue is not about oci-systemd-hook, it's about Kata not complying with the OCI hook specification.  Another hook installed on my system, oci-umount, also failed due to the invalid state JSON produced by Kata.

**Comment by stefanha** [comment]
@amshinde Sounds promising, I will try it on Wednesday and let you know the result!

**Comment by stefanha** [comment]
@amshinde Your commit a301a9e641 fixed the oci-systemd-hook issue, thanks!

I suggest leaving this issue open because Kata still does not conform to the OCI hooks specification for other state JSON fields.  Other OCI hooks may not work until the spec is met.

**Comment by amshinde** [comment]
@stefanha Glad it fixed the oci-systemd-hook issue. 
Agree, this issue should be left open until we support all the state fields.
