### ISSUE TITLE
Question: Firecracker slower than Qemu?

### ISSUE THREAD

**Issue by geverartsdev** [kata-containers/runtime#2642]
# Description of problem

I am currently comparing different containerisation solutions and I of course had to check how well could `kata-container`'s runtime perform compare to the classical `runc` one.  In the test I show here, I compare those three things: `runc`, `kata-container`with `qemu` as hypervisor, `kata-container` with `firecracker` as hypervisor.  I am using Docker as container manager for all of them, and *devicemapper* as storage driver (as it is the only one available yet for firecracker with docker+kata, and I want the comparison to be fair with the others).
Here are my results:
![Benchmark - Test - Hello World](https://user-images.githubusercontent.com/26028129/80212910-a9021d00-8638-11ea-8945-007083b65b01.png)
The three measurements create, start and exec correspond to the execution time of those commands:
 - `docker create --rm -ti --runtime whateverruntime alpine:latest sh`
 - `docker start whatevercontainerwascreated`
 - `docker exec whatevercontainerwascreated echo Hello World`

# Expected result

I was expecting Firecracker to be faster than Qemu.

# Actual result

Qemu is faster than Firecracker.  Any idea why?  From what I understood, those two hypervisors could coexist in an application, whith Firecracker being used for quick instantiation and Qemu for part of the application that would required a more complete VM experience (with devices interactions and things like that).
The only way I could get Firecracker to beat Qemu is for big file writing (doing a lot of inserts in a sqlite database)
![IO Tests - Test - Write execution](https://user-images.githubusercontent.com/26028129/80217685-65abac80-8640-11ea-9376-c138396fe263.png)

# Some more informations
I am running my tests on a bare-metal nuc, with 4 cores and 16GB or RAM, images and containers are stored on SSDs.  Each scenario is repeated 10 times, after a warm up phase where a simple `docker run --rm --runtime whateverruntime alpine:latest echo Hello World` is executed multiple times.

**Comment by devimc** [comment]
@geverartsdev you see these results because of qemu supports nvdimm and firecracker not, maybe you want to take a look to [cloud-hypervisor](https://github.com/cloud-hypervisor/cloud-hypervisor) as an alternative to firecracker. 

tip: you can improve a little bit more the boot time by changing the init process. Add `init=/usr/bin/kata-agent` to the kernel command line 

https://github.com/kata-containers/runtime/blob/d65dcdf2437fccbcdfe5a0ac1affd1d484116901/cli/config/configuration-fc.toml.in#L35

**Comment by grahamwhaley** [comment]
And just for reference @geverartsdev , I'll point you at some metrics tools that live in the kata repos:
https://github.com/kata-containers/tests/tree/master/metrics
There is a launch time test that tries to gather data on what phase of the process takes how long - it is not perfect, but could be fun to look at:
https://github.com/kata-containers/tests/blob/master/metrics/time/launch_times.sh
And then there is an Rmarkdown based report generator that does the analysis/graphing:
https://github.com/kata-containers/tests/tree/master/metrics/report

You might find that it needs some 'hand holding' to run the tests with anything other than Kata-qemu as the runtime. I have done in the past (with both `runc` and `fc`), but, not tried it for a while - things may have rotted a little.

**Comment by geverartsdev** [comment]
@devimc, thanks for you reply, indeed changing the init process improved a bit the booting time, still not enough to beat qemu though.
![Benchmark - Test - Hello World](https://user-images.githubusercontent.com/26028129/80234086-d5796180-8657-11ea-993c-92eeb0cfdc42.png)
What is it about nvdimm support that makes a difference?  I don't really get it.  All I think I know about this is that nvdimm memory will keep data even when not powered, but here I am running all my tests on a powered on machine, from the beginning to the end...  What did I miss?
The Cloud Hypervisor project seems indeed interesting, but is still a little bit to much in its early days for me to really consider it.  I will definitely keep a eye on it though.

@grahamwhaley thank you for pointing out those.  They might be useful to me if I decide to isolate execution phases even more in my comparison.

**Comment by jodh-intel** [comment]
@geverartsdev - have you seen https://github.com/kata-containers/documentation/blob/master/design/architecture.md which covers NVDIMM?

**Comment by devimc** [comment]
@geverartsdev we use nvdimm to provide the rootfs for the VM, so the same read-only rootfs is shared across different VMs. You can compare `qemu + image` (comment initrd) vs `qemu + initrd` (comment image) and you will see a considerable difference.

https://github.com/kata-containers/runtime/blob/d65dcdf2437fccbcdfe5a0ac1affd1d484116901/cli/config/configuration-qemu.toml.in#L16-L17

**Comment by geverartsdev** [comment]
@jodh-intel I never went that far in that document before indeed, I did now, thank you.

@devimc Here are the new tests, unfortunetly I don't see the considerable difference I was expecting.  What is it about `qemu + image`and `qemu + initrd` that should change so much?  From the [architecture](https://github.com/kata-containers/documentation/blob/master/design/architecture.md) I see that initrd actually compress the rootfs that will be used for the container.  Could this counter-intuitive results be caused by the really small image size (5.61 MB) I am using (and the cost of the compression being then higher than the benefit it brings)?
![Benchmark - Test - Hello World](https://user-images.githubusercontent.com/26028129/80241872-acab9900-8664-11ea-9ace-05377c47ab01.png)


One more question, what did it mean to set `init=/usr/bin/kata-agent` ? Did it replace systemd as init process in the guest? Instead of being called by it?

> Small side note, during the execution of my tests, I once had that error, don't realy know what to do with it:
> ```
> Error response from daemon: OCI runtime create failed: rpc error: code = Internal desc = Could not resolve symlink for source /dev/sda: unknown
> Error: failed to start containers: c6e58489afae75bda5d22493ff31d32966a8aa19ae170cee83a0fd4fdba05fd4
> ```

**Comment by devimc** [comment]
@geverartsdev 
 
> What is it about qemu + imageand qemu + initrd that should change so much?

ouch! I got confused (need more coffee), the difference is considerable in memory consumption

> what did it mean to set init=/usr/bin/kata-agent ? Did it replace systemd as init process in the guest? Instead of being called by it?

yes, kata-agent replaces systemd

I think you can improve a little bit more qemu's boot time, you need to enable `CONFIG_PVH=y` in the guest kernel and QEMU >= 4.0, I haven't played with this recently.
more details here https://stefano-garzarella.github.io/posts/2019-08-23-qemu-linux-kernel-pvh/

**Comment by geverartsdev** [comment]
@devimc 
> the difference is considerable in memory consumption  

Okay it makes more sense to me then

> I think you can improve a little bit more qemu's boot time  

Actually it wasn't my original goal, I was more hoping to see Firecracker as a (out of the box) faster solution than Qemu.  This is apparently not the case (for creation and starting time at least) and Qemu even propose more features if I'am not mistaking (I saw that [here](https://aws.amazon.com/fr/blogs/opensource/kata-containers-1-5-firecracker-support/)).  Why (when) should I use Firecracker instead of Qemu then?  I originally though that boot time was the reason, but it seems it can't be.

**Comment by devimc** [comment]
@geverartsdev

> Why (when) should I use Firecracker instead of Qemu then?  I originally though that boot time was the reason, but it seems it can't be.

to be honest I prefer to use QEMU, but if you compare attack surfaces and not sure if memory footprints, Firecracker can be a little bit better than QEMU

**Comment by geverartsdev** [comment]
@devimc Thank you for taking time to respond to my questions.  Indeed this [article](https://lwn.net/Articles/775736/) gave the same advantages to Firecracker (memory and attack surface), but promising a better booting time too, which I am still disappointed not to see.
I am closing the issue as I don't have anymore question, but if anyone has anything to add to the debate, please do and reopen the issue!

**Comment by geverartsdev** [comment]
Hi @devimc, after some more thinking about all this I got a few more questions, I hope you can answer to them.
> First just to check that I did understand everything correctly, here is a small summary of the conversation:
> 
> - *When used with Kata-container* (I didn't compare them in a standalone way), Qemu offers better creation and starting time than Firecracker.
> - The reason seems to be that Qemu supports vNVDIMM and that this feature is used to load the image of the guest VM in memory, with read-only access, so that multiple VMs can access it.

My questions are then:

1. How is the image of the guest VMs passed in the case of Firecracker? And are they still read-only and shared across multiple VMs?
1. When using Qemu, when is the image loaded in memory?  (And when is it removed from it)  Is it for each new VM created, unless another one is not already running (the image would then already be in memory)?  Is there an easy way for me to check that?
 1. On another subject, you showed we the trick of changing the init process to improve a little bit the starting time.  Why isn't kata-agent the default one? And what did I give up by switching to it, that I might be missing later?

**Comment by devimc** [comment]
Hi @geverartsdev 

> How is the image of the guest VMs passed in the case of Firecracker? And are they still read-only and shared across multiple VMs?

(firecracker internals) I'm not the right person to answer these two, might be Firecracker folks can help us here 

cc @dianpopa @andreeaflorescu @dhrgit @acatangiu @alexandruag

> When using Qemu, when is the image loaded in memory? (And when is it removed from it) Is it for each new VM created, unless another one is not already running (the image would then already be in memory)? Is there an easy way for me to check that?

(qemu internals) afaik qemu uses mmap https://github.com/qemu/qemu/blob/master/docs/nvdimm.txt ,  I don't know if there is an easy way to check that

cc @dagrh @stefanha

> On another subject, you showed we the trick of changing the init process to improve a little bit the starting time. Why isn't kata-agent the default one? 

I still have the same question, the reason was https://github.com/kata-containers/runtime/pull/768#issuecomment-443768359 

> And what did I give up by switching to it, that I might be missing later?

nothing, it's the init process in the initrd images, kata agent supports:
* debug console
* cgroups v1 and v2
* kernel modules

**Comment by acatangiu** [comment]
Hi @geverartsdev, @devimc,

> How is the image of the guest VMs passed in the case of Firecracker? And are they still read-only and shared across multiple VMs?

I'm not 100% sure what you mean by the _image of the guest VMs_, but the `kernel_image` file, the possible `initrd` file and all `disk` files are `read()` by Firecracker and not `mmap()`ed.

Firecracker can share these in read-only mode. Whether they are read-only and shared across multiple VMs is a question I'll defer to the Kata maintainers.

**Comment by devimc** [comment]
@acatangiu thanks for replying 

> Firecracker can share these in read-only mode. 

mmap()'ed? 

> Whether they are read-only and shared across multiple VMs is a question I'll defer to the Kata maintainers.

yes, the rootfs is read-only, but I don't see the option to enable read-only in the `kernel_image`, is this a new feature?

**Comment by acatangiu** [comment]
> yes, the rootfs is read-only, but I don't see the option to enable read-only in the kernel_image, is this a new feature?

`kernel_image` and `initrd` files are only ever read using standard file IO reading - it's not configurable so no options necessary.

Disks are read and written using standard file IO (no `mmap`). RW permission specified for disk in Firecracker API will be reflected in the permissions used by Firecracker to open the file, as well as the advertised permissions to the guest for that block device.

**Comment by devimc** [comment]
@acatangiu thanks for clarifying  :+1:

**Comment by geverartsdev** [comment]
Thank you for the additional explainations!
