### ISSUE TITLE
Fix structured logging in config package

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#2643]
`virtcontainers/device/config/pmem.go` creates a "stand-alone logrus logger", `pmemLog`. That breaks the CI which runs the [log-parser](https://github.com/kata-containers/tests/tree/master/cmd/log-parser#logfile-requirements).

`pmem.go` (or the `config` package) needs to expose a `SetLogger(logger *logrus.Entry)` API which should be called from `SetLogger()` in `virtcontainers/api.go` to resolve this issue.

For a similar example of the problem and the fix see:

- https://github.com/kata-containers/runtime/issues/2305
- https://github.com/kata-containers/runtime/pull/2306

**Comment by jodh-intel** [comment]
@devimc - do you wanna tal at this? ;)

**Comment by devimc** [comment]
@jodh-intel sure
