### ISSUE TITLE
virtcontainers: Append max ports to virtio-serial device

### ISSUE THREAD

**Issue by hejianet** [kata-containers/runtime#2676]
**Which feature do you think can be improved?**

virtcontainers: Append max ports to virtio-serial device 

**How can it be improved?**
Govmm has provided a "max_ports" parameter to allow API consumers to change the maximum number of ports in the virtio-serial devices, setting a lower number of ports can improve the
boot time and reduce the attack surface.

**Additional Information**

No

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?
Yes

**Comment by c3d** [comment]
Open PR https://github.com/kata-containers/runtime/pull/2677 not correctly linked here.

**Comment by c3d** [comment]
Linking to https://github.com/kata-containers/kata-containers/issues/249 (2.0 placeholder, apparently)
