### ISSUE TITLE
clh: creating VM fails due to use of deprecated memory.file parameter

### ISSUE THREAD

**Issue by gkunz** [kata-containers/runtime#2693]
# Description of problem

When attempting to create a sandbox VM using Kata 1.11 and CLH 0.7, creation of the VM fails due to usage of the memory.file parameter which has been deprecated in the 0.7 release of CLH:

Log file of CLH instance:
`
cloud-hypervisor: 11.797974ms: ERROR:vmm/src/config.rs:1268 -- Use of backing file ('--memory file=') is deprecated. Use the 'shared' and 'hugepages' controls.
`

Debug output of parameters passed to CLH. See memory.file parameter:

> May 18 23:12:07 pod2-blade08 containerd[9647]: time="2020-05-18T23:12:07.218883526+02:00" level=debug msg="VM config" ID=e483f86a4fd237bf56f227a59c694e006c4318cd51539839cee650fcf7c076da body="{\"cpus\":{\"boot_vcpus\":1,\"max_vcpus\":48},\"memory\":{\"size\":2147483648,\"hotplug_size\":135137894400,**\"file\":\"/dev/shm\"**,\"shared\":true},\"kernel\":{\"path\":\"/opt/kata/share/kata-containers/vmlinux-virtio-fs-dev-73-virtiofs\"},\"cmdline\":{\"args\":\"root=/dev/0p1 panic=1 no_timer_check noreplace-smp agent.log_vport=1025 rootflags=data=ordered,errors=remount-ro ro rootfstype=ext4 console=ttyS0,115200n8 systemd.log_level=debug systemd.log_target=console initcall_debug=1 systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none\"},\"net\":[{\"tap\":\"tap0_kata\",\"mac\":\"c6:9c:cf:c2:20:11\"}],\"rng\":{\"src\":\"/dev/urandom\"},\"fs\":[{\"tag\":\"kataShared\",\"sock\":\"/run/vc/vm/e483f86a4fd237bf56f227a59c694e006c4318cd51539839cee650fcf7c076da/virtiofsd.sock\",\"cache_size\":1073741824}],\"pmem\":[{\"file\":\"/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.11.0_agent_80de213dde.img\",\"discard_writes\":true}],\"serial\":{\"file\":\"/run/vc/vm/e483f86a4fd237bf56f227a59c694e006c4318cd51539839cee650fcf7c076da/serial-tty.log\",\"mode\":\"File\"},\"console\":{\"mode\":\"Off\"},\"vsock\":{\"cid\":3,\"sock\":\"/run/vc/vm/e483f86a4fd237bf56f227a59c694e006c4318cd51539839cee650fcf7c076da/clh.sock\"}}" source=virtcontainers subsystem=cloudHypervisor
`

Check of memory.file parameter in CLH 0.7:
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/v0.7.0/vmm/src/config.rs#L1268

# Expected result

Sandbox VM gets created created by CLH.

# Actual result

Sandbox VM creation fails. In fact, new instances of CLH get spawned in quick succession.

# Potential fix
Do not set memory.file parameter in CLH driver:
https://github.com/kata-containers/runtime/blob/master/virtcontainers/clh.go#L222

The file parameter still exists in the REST API of CLH and should actually be removed there as well.
https://github.com/cloud-hypervisor/cloud-hypervisor/blob/v0.7.0/vmm/src/api/openapi/cloud-hypervisor.yaml

**Comment by gkunz** [comment]
Closing since my problem was actually related to virtiofsd and seccomp.

**Comment by grahamwhaley** [comment]
Thanks @gkunz . If you happen to have any details or the workaround/fix and fancy dropping those here, it might help others look for an answer in the future (or even make it into the kata documentation).
