### ISSUE TITLE
/usr/bin/containerd-shim-kata-v2 processes persist and consume heavy CPU after corresponding containers exit

### ISSUE THREAD

**Issue by RobertKrawitz** [kata-containers/runtime#2719]
# Description of problem

Ran a test that created 40 CPU soaker containers on a 32/64 thread system w/192 GB RAM.

Using the `clusterbuster` tool from https://github.com/RobertKrawitz/OpenShift4-tools

```clusterbuster -b 5 -p 5 -P soaker -T pod -Y -e --container-resource-request=cpu=10m -v -N 1 -d 40 -r 1 -t 30 --report --cleanup -Q --kata```

which I ran a number of times, I observed that the node in question retained hundreds of containerd-shim-kata-v2 processes that were consuming a large amount of CPU.  Accompanying this were wide variations in the CPU utilization reported by the containers, wide variation in the work (simple loop iterations) accomplished by the containers, and amount of time required for containers to start from first to last.

Without use of Kata, it took about 1.1 seconds between the first and last container to start, achieved 3986% CPU utilization (within .5% of max), and achieved about 613M loop iterations/sec.  With Kata, the first run was very close to that (3.9 seconds for the containers to start, 3984% CPU utilization, and 603M loop iterations/second.  Running this in a loop 5 times, all of these numbers got worse.  By the final iteration, I observed 506% CPU utilization, 45 seconds between first and last pod (in some cases I saw much more), and about 69M loop iterations/second.

# Expected result

Performance to remain consistent with multiple runs, no accumulation of processes.

# Actual result
See attached: 
[kata-log.txt](https://github.com/kata-containers/runtime/files/4713127/kata-log.txt)

**Comment by RobertKrawitz** [comment]
@fidencio @haircommander

**Comment by fidencio** [comment]
Thanks, I could noticed that when a pod using shimv2 is stopped, it does take several seconds for the shimv2 process to disappear.

I'll take a look at this one in the next few days.

**Comment by RobertKrawitz** [comment]
After a while, the load drops, but the processes do not go away.

**Comment by RobertKrawitz** [comment]
This is many minutes.

**Comment by RobertKrawitz** [comment]
The containerd-shim processes only start consuming a lot of CPU when the underlying containers exit (with this test, all of the containers exit more or less simultaneously).

**Comment by RobertKrawitz** [comment]
Running `strace` on one of them shows this:

```[pid 834077] socket(AF_VSOCK, SOCK_STREAM, 0) = 9
[pid 834077] connect(9, {sa_family=AF_VSOCK, sa_data="\0\0\0\4\0\0c0\20\252\0\0\0\0"}, 16) = -1 ENODEV (No such device)
[pid 834077] close(9)                   = 0
[pid 834077] socket(AF_VSOCK, SOCK_STREAM, 0) = 9
[pid 834077] connect(9, {sa_family=AF_VSOCK, sa_data="\0\0\0\4\0\0c0\20\252\0\0\0\0"}, 16) = -1 ENODEV (No such device)
[pid 834077] close(9)                   = 0
```

continuously.

**Comment by fidencio** [comment]
Turns out this seems to be an issue on CRI-O. I'm sending them a PR and I'd appreciate if you could give it a try to ensure it does solve your issue.

**Comment by fidencio** [comment]
I'm closing this one as all the patches ended up being merged on CRI-O.

**Comment by haircommander** [comment]
https://github.com/fidencio/cri-o/commit/345c016eda17fb56d0193e02a8d436ae1bae996e is leading to problems where we remove the container on a successful container exit, and the kubelet tries to remove the container (but it doesn't exist in the ctrs map)

**Comment by evanfoster** [comment]
Do we know why the shim uses so much CPU when the containers die? I wonder if it's busy-looping.
