### ISSUE TITLE
[NEED HELP] firecracker sometimes get stuck.

### ISSUE THREAD

**Issue by zhuangh7** [kata-containers/runtime#2733]
# Description of problem

Hi there, I try to find a good firecracker manager to help me start, running, and remove firecracker instances. And I found kata-container in a recent paper. Then I find a nice wiki in kata-container' wiki 
as below:
https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support

I follow the wiki step by step, and install the kata version 1.5 in my host pc and successfully start up a firecracker microVM by add '--runtime kata-fc' to the docker run command.

But the firecracker doesn't seem to be working properly. When I use
```bash
scp host@xxx,xxx,xxx,xxx:~/test/exec .
```
And try to copy an executable binary compiled in an other docker container with the same contianer image to my newly microVM. Sometimes, **scp** ccommand just never return and the whole VM seems stuck. I can execute **docker exec -it myvm bash**, but the new window still can't work like the VM itself is block.
Sometimes, Im luck enough to execute the scp command and get the file from my host. After that, I use 
```bash
dmesg
```
and see some strange output there.
```bash
[   46.399634] EXT4-fs warning (device vdb): ext4_dirent_csum_verify:353: inode #531335: comm ssh: No space for directory leaf checksum. Please run e2fsck -D.
[   46.399639] EXT4-fs error (device vdb): ext4_find_entry:1447: inode #531335: comm ssh: checksumming directory block 0
[   47.748667] EXT4-fs error (device vdb): ext4_validate_inode_bitmap:101: comm scp: Corrupt inode bitmap - block_group = 64, inode_bitmap = 2097168
```
Then I run **df -h** and get the response as:
```bash
bash-5.0# df -h
Filesystem                Size      Used Available Use% Mounted on
/dev/vdb                  9.8G    448.1M      8.8G   5% /
tmpfs                    64.0M         0     64.0M   0% /dev
tmpfs                    54.1M         0     54.1M   0% /sys/fs/cgroup
shm                      64.0M         0     64.0M   0% /dev/shm
tmpfs                    54.1M    904.0K     53.2M   2% /etc/resolv.conf
tmpfs                    54.1M    904.0K     53.2M   2% /etc/hostname
tmpfs                    54.1M    904.0K     53.2M   2% /etc/hosts
tmpfs                    64.0M         0     64.0M   0% /proc/keys
tmpfs                    64.0M         0     64.0M   0% /proc/timer_list
tmpfs                    64.0M         0     64.0M   0% /proc/sched_debug
tmpfs                    54.1M         0     54.1M   0% /proc/scsi
tmpfs                    54.1M         0     54.1M   0% /sys/firmware
```
The disk looks like not full.
And sometimes I can use **scp** to download files without these errors in dmesg.

--------

I do some test and try to find more information about why the VM will stuck.
I try to move the file I downloaded bofore to change its name:
```bash
bash-5.0# mv exec exec2
Killed
bash-5.0# ls
-----> never response
```
I find the VM will frequently no response when I use command like **apk add ..**, **scp**,**ping**
And I get more information from dmesg output which may be helpful as :

```bash
[    0.614093] EXT4-fs (vdb): mounted filesystem with ordered data mode. Opts: (null)
[   45.925035] NOHZ: local_softirq_pending 202
[   58.846567] BUG: unable to handle kernel NULL pointer dereference at 0000000000000008
[   58.846638] IP: jbd2_journal_add_journal_head+0xb6/0xf0
[   58.846646] PGD 0 P4D 0
[   58.846657] Oops: 0002 [#1] SMP NOPTI
[   58.846663] Modules linked in:
[   58.846674] CPU: 0 PID: 146 Comm: bash Not tainted 4.14.67 #1
[   58.846681] task: ffff8800063a4040 task.stack: ffffc9000031c000
[   58.846691] RIP: 0010:jbd2_journal_add_journal_head+0xb6/0xf0
[   58.846698] RSP: 0018:ffffc9000031fb90 EFLAGS: 00010206
[   58.846705] RAX: 0000000000000000 RBX: ffff880006e983a8 RCX: 0000000000000000
[   58.846713] RDX: ffff880006e983ab RSI: ffff880006e983a8 RDI: ffff880006e983a8
[   58.846720] RBP: ffffffff81c1f880 R08: ffff880006e983a8 R09: ffff880006ebed80
[   58.846727] R10: 0000000000000040 R11: ffffc9000031fab0 R12: 0000000000001645
[   58.846734] R13: ffffc9000031fcd8 R14: 0000000000000000 R15: 0000000000001000
[   58.846743] FS:  00007f2cfee56d48(0000) GS:ffff880007c00000(0000) knlGS:0000000000000000
[   58.846751] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[   58.846758] CR2: 0000000000000008 CR3: 0000000003848001 CR4: 00000000003606b0
[   58.846772] DR0: 0000000000000000 DR1: 0000000000000000 DR2: 0000000000000000
[   58.846779] DR3: 0000000000000000 DR6: 00000000fffe0ff0 DR7: 0000000000000400
[   58.846785] Call Trace:
[   58.846800]  jbd2_journal_get_write_access+0x33/0x60
[   58.846828]  __ext4_journal_get_write_access+0x27/0x60
[   58.846839]  ext4_reserve_inode_write+0x91/0xc0
[   58.846848]  ext4_mark_inode_dirty+0x29/0x110
[   58.846857]  ext4_dirty_inode+0x41/0x60
[   58.846892]  __mark_inode_dirty+0x2d/0x220
[   58.846907]  generic_update_time+0x71/0xc0
[   58.846918]  touch_atime+0x9e/0xc0
[   58.846937]  generic_file_buffered_read+0x4e2/0x6c0
[   58.846949]  __vfs_read+0xfb/0x140
[   58.846959]  vfs_read+0x85/0x130
[   58.846968]  kernel_read+0x27/0x40
[   58.846977]  prepare_binprm+0x145/0x170
[   58.846985]  do_execveat_common+0x3c6/0x640
[   58.846994]  SyS_execve+0x23/0x30
[   58.847028]  do_syscall_64+0xa1/0x2bf
[   58.847054]  ? do_page_fault+0x3b/0x76
[   58.847094]  entry_SYSCALL_64_after_hwframe+0x3d/0xa2
[   58.847104] RIP: 0033:0x7f2cfee001eb
[   58.847110] RSP: 002b:00007ffe2299b090 EFLAGS: 00000246 ORIG_RAX: 000000000000003b
[   58.847119] RAX: ffffffffffffffda RBX: 0000000000000000 RCX: 00007f2cfee001eb
[   58.847126] RDX: 000055a9c4a7a340 RSI: 000055a9c4aafc20 RDI: 000055a9c4aafbe0
[   58.847133] RBP: 000055a9c4aafbe0 R08: 0000000000000041 R09: 0000000000000000
[   58.847140] R10: 0000000000000008 R11: 0000000000000246 R12: 0000000000000001
[   58.847147] R13: 000055a9c4aaffc0 R14: 000055a9c4aafc20 R15: 000055a9c4aafc80
[   58.847154] Code: f7 c2 00 00 00 01 75 f3 e9 6e ff ff ff 48 8b 53 10 48 85 d2 74 0b 48 83 7a 08 00 0f 85 77 ff ff ff 0f 0b 48 8b 4b 40 48 8d 53 03 <83> 41 08 01 3e 80 22 fe 48 85 c0 74 0f 48 8b 3d b6 16 2f 01
48
[   58.847238] RIP: jbd2_journal_add_journal_head+0xb6/0xf0 RSP: ffffc9000031fb90
[   58.847244] CR2: 0000000000000008
[   58.847251] ---[ end trace 1781578666bad6b8 ]---

a moment later
---> no response
```

## Host Environment
```bash
cat /proc/version                                                   
Linux version 4.15.0-91-generic (buildd@lgw01-amd64-013) (gcc version 7.4.0 (Ubuntu 7.4.0-1ubuntu1~18.04.1)) #92-Ubuntu SMP Fri Feb 28 11:09:48 UTC 2020

lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 18.04.4 LTS
Release:        18.04
Codename:       bionic

docker version
Client:
 Version:           19.03.6
 API version:       1.40
 Go version:        go1.12.17
 Git commit:        369ce74a3c
 Built:             Fri Feb 28 23:45:43 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          19.03.6
  API version:      1.40 (minimum version 1.12)
  Go version:       go1.12.17
  Git commit:       369ce74a3c
  Built:            Wed Feb 19 01:06:16 2020
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.3.3-0ubuntu1~18.04.1
  GitCommit:        
 runc:
  Version:          spec: 1.0.1-dev
  GitCommit:        
 docker-init:
  Version:          0.18.0
  GitCommit:        

```
kata-container is installed entirely follow the wiki page at 

https://github.com/kata-containers/documentation/wiki/Initial-release-of-Kata-Containers-with-Firecracker-support

# Expected result

The firecracker MVs should not stuck at any time when I just use some simple command.

# Actual result

**sry IDK where the file 'kata-collect-data.sh' is.**
(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by devimc** [comment]
> I follow the wiki step by step, and install the kata version 1.5 

wow! 1.5 is too old, would you mind updating to 1.11?

**Comment by zhuangh7** [comment]
> > I follow the wiki step by step, and install the kata version 1.5
> 
> wow! 1.5 is too old, would you mind updating to 1.11?

THX for your quick reply!!!
After upgrade, the VM has become much more stable!
By the way, could you plz give some advice about where to find documents about kata-fc, like build from src, change its kernel or rootfs ? I had a glance at the document rep but it rarely mention about firecracker, and I only find the path to build kata-runtime from src, I guess this is the default runtime like kata-fc but based on QEMU right?

Thanks for you quick reply again, this issue can be close right now.

**Comment by devimc** [comment]
there are no specific documentation for firecracker, but maybe next documents can help you

https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md
https://github.com/kata-containers/documentation/wiki/Kata-images
https://github.com/kata-containers/packaging/blob/master/kernel/README.md

**Comment by zhuangh7** [comment]
> there are no specific documentation for firecracker, but maybe next documents can help you
> 
> https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md
> https://github.com/kata-containers/documentation/wiki/Kata-images
> https://github.com/kata-containers/packaging/blob/master/kernel/README.md

Thank you !
