### ISSUE TITLE
guest OCI hooks are not working with Kata

### ISSUE THREAD

**Issue by bpradipt** [kata-containers/runtime#2763]
# Description of problem
OCI hooks are not working with Kata. Created a rootfs with hook scripts and enabled `guest_hook_path = "/usr/share/oci/hooks"` in the configuration.toml. 
Running the container results in the following error:
```
Error response from daemon: OCI runtime create failed: rpc error: code = Unknown desc = open /run/kata-containers/shared/containers/7217217f69ef8af65581790aa06fe3b54499dd3b8f1a79e6116
94ec670a6182a/config.json: read-only file system: unknown.
time="2020-06-10T11:49:58Z" level=error msg="error waiting for container: context canceled"
```

The problem got introduced since the following commit https://github.com/kata-containers/runtime/commit/a3dec262c5d750c3b7201e19bb504b1ca22c30a9

# Expected result

Container should start and hooks should run

# Actual result

Container fails to start.

**Comment by bpradipt** [comment]
The following call is failing - https://github.com/kata-containers/agent/blob/master/grpc.go#L679
since the root path is read-only and it's trying to write the config.json in that path
Relevant code - https://github.com/kata-containers/agent/blob/master/oci.go#L29-L39

One option is to write the config.json to a rw path - eg `/run/`. However I'm not sure what's the other side-effect of the same.

**Comment by dgibson** [comment]
To clarify, AFAICT this is specifically about hooks set with the `guest_hook_path` configuration option.  Hooks set in the OCI config.json appear to work ok, and are executed on the host, rather than the sandbox VM.

**Comment by jodh-intel** [comment]
Updated title to make that point clearer.

**Comment by amshinde** [comment]
I think the fix has been merged.
@bpradipt Please feel free open if work still needs to be done in this area.
