### ISSUE TITLE
Less pods can be launched with virtio-fs as sharedfs

### ISSUE THREAD

**Issue by arronwy** [kata-containers/runtime#2766]
# Description of problem

I have a NUC with 8G memory, follow this guide https://github.com/kata-containers/documentation/blob/master/how-to/containerd-kata.md to use kata and containerd and launch pods with CRI interface. The kata version is latest 1.11.0 with qemu 4.1.1. We use the default configuration of configuration-qemu.toml and configuration-qemu-virtiofs.toml. The default configuration is 1vcpu, 2G default memory.

For Qemu with virtio-9p as the sharedfs, we can launch about 74 secure container and consume most of the host memory:

```
[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 4.1.1 (kata-static)\nCopyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers"
  Path = "/opt/kata/bin/qemu-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  SharedFS = "virtio-9p"
  VirtioFSDaemon = "/opt/kata/bin/virtiofsd"
  Msize9p = 8192
  MemorySlots = 10
  PCIeRootPort = 0
  HotplugVFIOOnRootBus = false
  Debug = false
  UseVSock = false
```

For Qemu with virtio-fs as the sharedfs, we can only launch about 35 secure container and still have many host memory when failed to launch new VM:

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:           7840        1800        1594        3871        4445        1970
Swap:          4095          21        4074

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 4.1.0 (kata-static)\nCopyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers"
  Path = "/opt/kata/bin/qemu-virtiofs-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  SharedFS = "virtio-fs"
  VirtioFSDaemon = "/opt/kata/bin/virtiofsd"
  Msize9p = 8192
  MemorySlots = 10
  PCIeRootPort = 0
  HotplugVFIOOnRootBus = false
  Debug = false
  UseVSock = false
```

Even we disable fs cache for virtio-fs, we still have similar issue which can only launch about half of the pods compared with virtio-9p
```
virtio_fs_cache_size = 0
virtio_fs_cache = "none"

 /opt/kata/bin/virtiofsd --fd=3 -o source=/run/kata-containers/shared/sandboxes/058529d8fcf077bd2cf614f99f003afaada39cf6281af8e467832e89a17e763b/shared -o cache=none --syslog -o no_posix_lock -f
```
# Expected result

virtio-9p and virtio-fs should can launch nearly the same number of pod with the same hardware configuration

# Actual result

virtio-fs as shared fs can only launch half of the pods compared with virtio-9p.

**Comment by egernst** [comment]
@arronwy  thanks for opening this issue. Are there any messages in journal or dmesg which help indicate the failure point when this occurs?

 I'm wondering if this is a pid or fd limit that we're hitting -- I noticed virtio-fsd creates a lot of threads.  Heads up @jcvenegas.

**Comment by arronwy** [comment]
> @arronwy thanks for opening this issue. Are there any messages in journal or dmesg which help indicate the failure point when this occurs?
> 
> I'm wondering if this is a pid or fd limit that we're hitting -- I noticed virtio-fsd creates a lot of threads.
> When it fails, can you share `ps -eLf | wc` ?
> Heads up @jcvenegas.

Thanks for your suggestions, I finally found the root cause maybe due to the default config size of /dev/shm:
```
# free -m
              total        used        free      shared  buff/cache   available
Mem:           7840         367        4657           1        2815        7189
Swap:          4095           0        4095

# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            3.8G     0  3.8G   0% /dev
tmpfs           785M  1.3M  783M   1% /run
/dev/sda2       234G   29G  193G  14% /
tmpfs           3.9G     0  3.9G   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           3.9G     0  3.9G   0% /sys/fs/cgroup
/dev/loop1       10M   10M     0 100% /snap/helm/241
/dev/loop3       92M   92M     0 100% /snap/go/5759
/dev/loop4       94M   94M     0 100% /snap/core/9066
/dev/loop2       81M   81M     0 100% /snap/kata-containers/629
/dev/loop0       92M   92M     0 100% /snap/go/5830
/dev/loop6       14M   14M     0 100% /snap/prometheus/18
/dev/loop5       55M   55M     0 100% /snap/core18/1754
/dev/loop7       98M   98M     0 100% /snap/core/9289
/dev/loop8       10M   10M     0 100% /snap/helm/244
/dev/loop9       81M   81M     0 100% /snap/kata-containers/655
/dev/sda1       511M  6.1M  505M   2% /boot/efi
tmpfs           785M     0  785M   0% /run/user/1000
```
The default maximum size of the /dev/shm filesystem is half of the total system memory, and virtio-fs mainly use /dev/shm to host shared filesystem, after we resize /dev/shm to the whole of the system memory, Qemu with virtio-fs as sharedfs backend can launch nearly the same pods as virtio-9p.
After we launch one pod:
```
# mount |grep shm
tmpfs on /dev/shm type tmpfs (rw,nosuid,nodev)
shm on /run/containerd/io.containerd.grpc.v1.cri/sandboxes/dd6f84775e5d5cd555a7e998345b770721ba2677233529d2dbdb915d26ff6dda/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=65536k)
# df -h /dev/shm/
Filesystem      Size  Used Avail Use% Mounted on
tmpfs           3.9G  111M  3.8G   3% /dev/shm
```
and we can use this command to resize the /dev/shm
```
# mount -o remount,size=8G /dev/shm
```

**Comment by amshinde** [comment]
@arronwy Thanks for debugging this. We should update our docs including configuration.toml to mention this.

**Comment by amshinde** [comment]
cc @ganeshmaharaj This may be of interest to you, since cloud hypervisor uses virtiofs, you may encounter the same limit due to default `/dev/shm` size.

**Comment by arronwy** [comment]
I think we can close this issue since virtio-fs docs already updated.
