### ISSUE TITLE
runtime `make check` fails in golangci

### ISSUE THREAD

**Issue by c3d** [kata-containers/runtime#2768]
# Description of problem

Running `make check` from 1.x branches fails on `golint`

# Expected result

`make check` used to work. Seen my multiple people in my team "at the same time" (i.e. seems to be recent).

# Actual result

```
INFO: Using github.com/golangci/golangci-lint version v1.18.0
warning: refname 'v1.18.0' is ambiguous.
fatal: A branch named 'v1.18.0' already exists.
make: *** [Makefile:676: check-go-static] Error 128
```

Trying to remove the `golangci` directory and retry results in

```
INFO: Building github.com/golangci/golangci-lint
make[1]: Entering directory '/home/ddd/go/src/github.com/golangci/golangci-lint'
GO111MODULE=on go mod verify
go: github.com/golangci/tools@v0.0.0-20190910062050-3540c026601b: invalid version: unknown revision 3540c026601b
make[1]: *** [Makefile:107: go.mod] Error 1
make[1]: Leaving directory '/home/ddd/go/src/github.com/golangci/golangci-lint'
make: *** [Makefile:676: check-go-static] Error 2
```

**Comment by dgibson** [comment]
I'm hitting this too, which is basically blocking me from doing anything much.  I'm utterly baffled as to why it is failing on my (and your) machines, but not in travis.

**Comment by dgibson** [comment]
Actually, on second thoughts I have one theory: could the 3540c026601b commit have been (stupidly) removed from the github.com/golangci/tools repository by a rebase or something, but travis is using a cached mirror which still has the commit?

**Comment by dgibson** [comment]
Note, incidentally that there is an github issue against golangci-lint for this precise problem.  It's been fixed there - but not in the specific 1.18.0 version we check out for Kata.

**Comment by dgibson** [comment]
Urgh, no.  Some experimentation with dev environments in containers shows that the problem occurs with the Fedora 32 packaged golang, but *not* with the upstream golang from google of the same version (1.14.3).

How the packaged version manages to have a bug of that subtlety, I have no freaking idea, but I guess it's a Fedora bug.

**Comment by dgibson** [comment]
This turns out to be a problem in the Fedora golang package, which I eventually figured out late yesterday with help from Pradipta and others.  The golangci-build only works if we have a GOPROXY set, which upstream golang does (pointing to google's proxy), but Fedora's does not.  A Fedora bug has been filed (https://bugzilla.redhat.com/show_bug.cgi?id=1847717)

**Comment by c3d** [comment]
Per @dgibson's investigation, closing as it seems to be  Fedora bug.

**Comment by amshinde** [comment]
@dgibson @c3d Glad this is solved. You mentioned in the AC call, that you were seeing several other issues, are those still valid?

**Comment by c3d** [comment]
@amshinde The other issues that come up are being tracked separately.

**Comment by wainersm** [comment]
I'm hitting this issue too (Fedora 32). In case you read until here and don't want to drill down in the bugzillas mentioned, just do:

```
export GOPROXY="https://proxy.golang.org,direct"
```
