### ISSUE TITLE
Health check never pass with kata + shimv2

### ISSUE THREAD

**Issue by snir911** [kata-containers/runtime#2769]
# Description of problem

1. Create a pod with some [health check / readinessProbe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-readiness-probes) (for [example](https://raw.githubusercontent.com/openshift-evangelists/kbe/master/specs/healthz/ready.yaml))
2. make sure it becomes "ready" when you run it.
3. create similar pod with and use kata runtime (`runtimeClassName: kata`)

# Expected result

Pod becomes "ready" (health check passed).

# Actual result

Pod never becomes "ready".

This happens only when shimv2 is used, not with shimv1, describe on the failing pod doesn't present any complains.

**Comment by RobertKrawitz** [comment]
Is this specific to exec-based probes or do http probes also fail?  `oc rsh` into a Kata pod fails too (which is likely why this fails).

**Comment by snir911** [comment]
Fix was merged in upstream crio.
I was not able reproduce the oc rsh issue, if it still exist it probably wroth another issue.
