### ISSUE TITLE
With virtio-fs and cache enabled, deleting a mapped file from host doesn't allow it to be recreated in the container to be saved back to host again which could result in data loss.

### ISSUE THREAD

**Issue by eadamsintel** [kata-containers/runtime#2770]
# Description of problem

I am using  Kubernetes 1.7.4 + Containerd 1.3.4 + Kata 1.11.1  using `kata-deploy` to install Kata 1.11.1 using the `kata-qemu-virtiofs` runtime.  If I use the default settings in the `configuration-qemu-virtiofs.toml` file where `virtio_fs_cache_size=1024` and `virtio_fs_cache=always` and mount in a folder and then delete the file from the host then I can't recreate that file inside the container.  It appears to be stuck in the cache. There does not appear to be any way to add that same file name back from inside the container where it will show up back on the host.  If I do a `ls` on the directory then I can't see the file I deleted and recreated, but if I `cat test.txt` where `test.txt` is the file I deleted on the host but then recreated in the container then it is there but only in the containers virtio-fs cache. It does not get written to the host.  If you then delete the pod that file is lost forever. 

If I set `virtio_fs_cache_size=0` or set `virtio_fs_cache=none` then this issue does not occur. 

# Expected result

I should be able to recreate the file inside the container and run a `ls` and be able to see it.

# Actual result

Below is a flow showing the bug. I create a `test.txt` inside the container, delete it on the host, and then try to recreate `test.txt` inside the container again. The file does not show up in a `ls` command in either the container or on the host, but if you `cat` the file by name the contents are there even though you can't see it in the container or on the host. If you stop the container then the file is permanently gone.  This could lead to situations where data is lost.

In the example below I am using `hostPath` to map `/home/eadams/temp` to the `/localssd` folder in the container.

```bash
eadams@otc-tme-tp-01b~/temp $ kubectl get pods
NAME                                 READY   STATUS    RESTARTS   AGE
fiotest-ramdisk-kata-qemu-virtiofs   1/1     Running   0          18s
eadams@otc-tme-tp-01b~/temp $
eadams@otc-tme-tp-01b~/temp $ ls -la
total 8
drwxr-xr-x  2 eadams eadams 4096 Jun 11 16:34 .
drwxr-x--- 22 eadams eadams 4096 Jun 11 15:27 ..
eadams@otc-tme-tp-01b~/temp $
eadams@otc-tme-tp-01b~/temp $ kubectl exec -it fiotest-ramdisk-kata-qemu-virtiofs bash
root@fiotest-ramdisk-kata-qemu-virtiofs:/#
root@fiotest-ramdisk-kata-qemu-virtiofs:/# cd localssd/
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd#
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# ls -la
total 8
drwxr-xr-x 2 1000 1000 4096 Jun 11 23:34 .
drwxr-xr-x 1 root root 4096 Jun 11 23:45 ..
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# echo "test" > test.txt
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd#
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# ls -la
total 12
drwxr-xr-x 2 1000 1000 4096 Jun 11 23:46 .
drwxr-xr-x 1 root root 4096 Jun 11 23:45 ..
-rw-r--r-- 1 root root    5 Jun 11 23:46 test.txt
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# exit
exit
eadams@otc-tme-tp-01b~/temp $ ls -la
total 12
drwxr-xr-x  2 eadams eadams 4096 Jun 11 16:46 .
drwxr-x--- 22 eadams eadams 4096 Jun 11 15:27 ..
-rw-r--r--  1 root   root      5 Jun 11 16:46 test.txt
eadams@otc-tme-tp-01b~/temp $
```
Lets remove the `test.txt` file from the host
```bash
eadams@otc-tme-tp-01b~/temp $ rm test.txt
rm: remove write-protected regular file 'test.txt'? y
eadams@otc-tme-tp-01b~/temp $
eadams@otc-tme-tp-01b~/temp $ kubectl exec -it fiotest-ramdisk-kata-qemu-virtiofs bash
root@fiotest-ramdisk-kata-qemu-virtiofs:/#
root@fiotest-ramdisk-kata-qemu-virtiofs:/# cd localssd/
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd#
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# ls -la
total 8
drwxr-xr-x 2 1000 1000 4096 Jun 11 23:46 .
drwxr-xr-x 1 root root 4096 Jun 11 23:45 ..
```
Now lets try to recreate the same file inside the container after deleting it.  You will see that `test.txt` is no longer visible by `ls`
```bash
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# echo "test 2" > test.txt
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd#
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# ls -la
total 8
drwxr-xr-x 2 1000 1000 4096 Jun 11 23:46 .
drwxr-xr-x 1 root root 4096 Jun 11 23:45 ..
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# echo "test new" > testnew.txt
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd#
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# ls -la
total 12
drwxr-xr-x 2 1000 1000 4096 Jun 11 23:47 .
drwxr-xr-x 1 root root 4096 Jun 11 23:45 ..
-rw-r--r-- 1 root root    9 Jun 11 23:47 testnew.txt
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# exit
exit
```
You can see that the `test.txt` file is not on the host anymore nor does it show up with `ls` in the container even though I recreated it right above. You can see that `testnew.txt` is there so new files with a different filename can be created and can be seen. 
```bash
eadams@otc-tme-tp-01b~/temp $ ls -la
total 12
drwxr-xr-x  2 eadams eadams 4096 Jun 11 16:47 .
drwxr-x--- 22 eadams eadams 4096 Jun 11 15:27 ..
-rw-r--r--  1 root   root      9 Jun 11 16:47 testnew.txt
eadams@otc-tme-tp-01b~/temp $ kubectl exec -it fiotest-ramdisk-kata-qemu-virtiofs bash
root@fiotest-ramdisk-kata-qemu-virtiofs:/#
root@fiotest-ramdisk-kata-qemu-virtiofs:/# cd localssd/
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd#
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# ls -la
total 12
drwxr-xr-x 2 1000 1000 4096 Jun 11 23:47 .
drwxr-xr-x 1 root root 4096 Jun 11 23:45 ..
-rw-r--r-- 1 root root    9 Jun 11 23:47 testnew.txt
```
Even though `test.txt` is invisible to `ls` in the container and on the host the file is there if you `cat` it. 
```bash
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# cat test.txt
test 2
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# cat testnew.txt
test new
root@fiotest-ramdisk-kata-qemu-virtiofs:/localssd# exit
exit
eadams@otc-tme-tp-01b~/temp $ ls -la
total 12
drwxr-xr-x  2 eadams eadams 4096 Jun 11 16:47 .
drwxr-x--- 22 eadams eadams 4096 Jun 11 15:27 ..
-rw-r--r--  1 root   root      9 Jun 11 16:47 testnew.txt
eadams@otc-tme-tp-01b~/temp $ cat test.txt
cat: test.txt: No such file or directory
eadams@otc-tme-tp-01b~/temp $ cat testnew.txt
test new
```

Here is the yaml I used for convenience.
``` yaml
kind: Pod
apiVersion: v1
metadata:
  name: fiotest-ramdisk-kata-qemu-virtiofs
spec:
  runtimeClassName: kata-qemu-virtiofs
  containers:
    - name: fio
      image: rohanmehto2/fio-test
      command: [ "sleep", "100000" ]
      volumeMounts:
      - mountPath: "/contents"
        name: contents
      - mountPath: "/localssd"
        name: localssd
  volumes:
  - name: contents
    emptyDir:
      medium: Memory
      sizeLimit: 1Gi
  - name: localssd
    hostPath:
      path: /home/eadams/temp
      type: Directory
```

**Comment by amshinde** [comment]
cc @jcvenegas 
@stefanha @rhvgoyal Looks like like a legit bug to me. Any input on this?

**Comment by rhvgoyal** [comment]
In general, I don't think we right now allow modifications on host while virtiofs is mounted.

**Comment by rhvgoyal** [comment]
If cache=none fixes it, we should clsoe this issue. cache=always will not work because host and guest metadata will get out of sync and we don't have any notification mechanism yet to notify guest.

**Comment by eadamsintel** [comment]
@rhvgoyal 

Is this documented somewhere that cache should be set to none? Perhaps just referring to that makes sense.

**Comment by jcvenegas** [comment]
We now use cache=auto, this should be fixed now - @eadamsintel  please confirm .

**Comment by rhvgoyal** [comment]
I would say use cache=auto. This expires cached dentries and inode attrs after a second. I am not sure what configuration you are running. I tried it and I can't see the problem.

- I ran virtiofsd with cache=auto.
- Mounted virtiofs with dax enabled.

After I remove file on host, I see it disappeared inside guest. And when I tried to recreate file, I could do that.

**Comment by rhvgoyal** [comment]
I am using latest fuse code from Miklos kernel repository.

https://git.kernel.org/pub/scm/linux/kernel/git/mszeredi/fuse.git/log/?h=for-next

**Comment by rhvgoyal** [comment]
This works even without dax enabled. I think dax is irrelevant here. Its all about using right caching mode. cache=always means that guest cached data is always valid and never expires. While cache=auto means guest's cached data expires after 1 second. So if host changed something, that change is noticed in guest after 1 second.

**Comment by eadamsintel** [comment]
I did a quick check and with `virtio_fs_cache=auto` and the issue didn't happen anymore. If that is the new default setting, then I think this issue can be closed.

**Comment by fidencio** [comment]
That's the new defalt, Eric.
Thanks for re-checking this, I'm closing the issue per your comment.
