### ISSUE TITLE
remove "default hypervisor" message from build

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#2785]
AFAIU, there really isn't a notion of "default" VMM for Kata. Let's update the build summary to remove this:

```
• hypervisors:
	Default: qemu
	Known: acrn cloud-hypervisor firecracker qemu qemu-virtiofs
	Available for this architecture: acrn cloud-hypervisor firecracker qemu qemu-virtiofs
```

We should be able to remove the `Default` line, and keep the remaining.

**Comment by bporter816** [comment]
Hi! @tommyrousey, @maomarcus, and @yasv123 and I are students at UT Austin, and we're looking to make some open source contributions over the course of the rest of the year as a part of our virtualization class. Could we be assigned to this issue?

**Comment by bporter816** [comment]
@egernst  
@jodh-intel @ariel-adam @fidencio We will be completing this issue soon and were wondering if there are any functional changes that need to happen outside of removing references to DEFAULT_HYPERVISOR from the Makefile.

**Comment by egernst** [comment]
Hey there @bporter816! I don't think there are any functional changes required; just cleanup/removal for this one.

**Comment by egernst** [comment]
And, sorry for not responding in September! Thanks for the help!

**Comment by egernst** [comment]
If you're interested, we can see if there are more interesting issues within the code base for you :)

**Comment by bporter816** [comment]
@egernst Yes, that would be great! We would love to pick up another issue. Please let us know if you're aware a good one we could scope out that would take about a week to complete.

**Comment by egernst** [comment]
> @egernst Yes, that would be great! We would love to pick up another issue. Please let us know if you're aware a good one we could scope out that would take about a week to complete.

Yes - will do! TAL @ https://github.com/kata-containers/runtime/issues/3093

**Comment by liubin** [comment]
@bporter816 Thanks, you can also filter issues by label `good-first-issue`.
