### ISSUE TITLE
[question] does kata support shareProcessNamespace?

### ISSUE THREAD

**Issue by LinShuicheng** [kata-containers/runtime#2788]
# Description of problem
In k8s, there is "shareProcessNamespace: true" to Share Process Namespace between Containers in a Pod.
Does kata support it or not?
It seems kata doesn't support it per below open issues:
https://github.com/kata-containers/runtime/issues/493
and
https://github.com/kata-containers/runtime/issues/2633
But there is one closed issue seems kata support it:
https://github.com/kata-containers/tests/issues/336

Could you share me whether kata support it or not?
Thanks.
In my test, after switch to kata as runtime, shareProcessNamespace doesn't work, so it seems kata doesn't support it.
If this feature is not supported, could you help add it to the limitations documentation explicitly? Thanks.
https://github.com/kata-containers/documentation/blob/master/Limitations.md#architectural-limitations

# Expected result
n/a

# Actual result
n/a

**Comment by amshinde** [comment]
@LinShuicheng This feature is supported with Kata. We have an integration test that verifies this as seen here:
https://github.com/kata-containers/tests/blob/745a730fdcb59d96cceb116e2dbc26bdec2cfc82/integration/kubernetes/k8s-pid-ns.bats

**Comment by LinShuicheng** [comment]
@amshinde  It seems the test compare pause process id only, which seems doesn't exist in my test.
Here is my test step, could you help check is there any problem?
My pod yaml file:
controller-0:~$ cat pod.yaml
apiVersion: v1
kind: Pod
metadata:
  name: busybox
  annotations:
    io.kubernetes.cri.untrusted-workload: "true"
spec:
  shareProcessNamespace: true
  containers:
  - name: first-test-container
    image: registry.dcp-dev.intel.com/busybox
    command:
        - sleep
        - "1000"
  - name: second-test-container
    image: registry.dcp-dev.intel.com/busybox
    command:
        - sleep
        - "10000"
    stdin: true
    tty: true

I run it first with "untrusted-workload" commented, which means it run with runc as runtime.
Here is the result:
controller-0:~$ kubectl exec -it busybox -c first-test-container sh
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
    6 root      0:00 sleep 1000
   11 root      0:00 sleep 10000
   16 root      0:00 sh
   22 root      0:00 ps
/ # exit
controller-0:~$ kubectl exec -it busybox -c second-test-container sh
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
    6 root      0:00 sleep 1000
   11 root      0:00 sleep 10000
   23 root      0:00 sh
   28 root      0:00 ps

We could find both containers share process with each other, it is what shareProcessNamespace expected. Right?

Then I enable "untrusted-workload", and run again. Here is the result:
controller-0:~$ kubectl exec -it busybox -c first-test-container sh
/ # uname -a
Linux busybox 5.4.32-3.1.container #1 SMP Thu Jan 1 00:00:00 UTC 1970 x86_64 GNU/Linux
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 1000
    6 root      0:00 sh
   12 root      0:00 ps
/ # exit
controller-0:~$ kubectl exec -it busybox -c second-test-container sh
/ # uname -a
Linux busybox 5.4.32-3.1.container #1 SMP Thu Jan 1 00:00:00 UTC 1970 x86_64 GNU/Linux
/ # ps -a
PID   USER     TIME  COMMAND
    1 root      0:00 sleep 10000
    6 root      0:00 sh
   13 root      0:00 ps -a
/ # exit

Each container could see its process only. Process is not shared. So the feature is not working. Is it right?
Thanks.

**Comment by amshinde** [comment]
@LinShuicheng Yes, I was able to see this bug with shimv2. 
shareProcessNamespace works with the cli runtime, but not with the shimv2 interface. Will take a look at this.

**Comment by amshinde** [comment]
@LinShuicheng PR https://github.com/kata-containers/runtime/pull/2794 raised to address this issue. Can you test the patch and confirm on your side?

**Comment by LinShuicheng** [comment]
@amshinde  Thanks. I verified your patch, it works in my environment.
Here is the results:
controller-0:~$ kubectl exec -it busybox sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
Defaulting container name to first-test-container.
Use 'kubectl describe pod/busybox -n default' to see all of the containers in this pod.
/ # uname -a
Linux busybox 5.4.15 #2 SMP Wed Jun 24 14:25:10 CST 2020 x86_64 GNU/Linux
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
    6 root      0:00 sleep 1000
   11 root      0:00 sleep 10000
   16 root      0:00 sh
   22 root      0:00 ps
/ # exit
controller-0:~$ kubectl exec -it busybox -c second-test-container sh
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
/ # uname -a
Linux busybox 5.4.15 #2 SMP Wed Jun 24 14:25:10 CST 2020 x86_64 GNU/Linux
/ # ps
PID   USER     TIME  COMMAND
    1 root      0:00 /pause
    6 root      0:00 sleep 1000
   11 root      0:00 sleep 10000
   23 root      0:00 sh
   29 root      0:00 ps

**Comment by amshinde** [comment]
@GabyCT Looks like the test we have in place for this itself is buggy:
https://github.com/kata-containers/tests/blob/745a730fdcb59d96cceb116e2dbc26bdec2cfc82/integration/kubernetes/k8s-pid-ns.bats#L31
We check for `[ "$first_pid_container" == "$second_pid_container" ]`, but we need to also add a check to verify that `first_pid_container` and `second_pid_container` are not empty.

**Comment by GabyCT** [comment]
@amshinde , let me re-work that test
