### ISSUE TITLE
overconstraining sandbox in case of k8s

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#2792]
# Description of problem

https://github.com/kata-containers/runtime/pull/2409 introduced an undesirable behavior in the scenario where Kata is being integrated with Kubernetes. In this case, kubelet manages the sandbox cgroup, including memory and cpu subsystems. By applying these cgroups, we are over-constraining the sandbox cgroup

# Expected result

CPU and Memory subsystems are left untouched by default.

# Actual result

It looks like the cgroup would be set based on pause container in case of k8s, or at least doesn't appear to take into consideration the sum of container requests.  Further, even if it was considering container summation, it is not able to apply an overhead for running in a sandbox.

I'd recommend reverting 2409 and hiding this behavior change behind a non-default flag.

**Comment by egernst** [comment]
heads up @devimc @jcvenegas

**Comment by jcvenegas** [comment]
Thanks for open the issue, so now given that  `sandbox_cgroup_only=true` additionally an annotation has to be given from the CRI runtime used?

Correct me if I am wrong but this is a consequence of the fragmentation on how Kata is expected to manage resources. PodLavel vs Container Level. Based on our previous checks, trying to do assumptions of how resources should be contain for a Pod makes difficult.  I still missing context, but https://github.com/kata-containers/runtime/issues/2408 documents that sandbox_cgroup_only=true + docker was not applying limits. Something we could do is suggest if folks want docker limited host level keep using `sandbox_cgroup_only=false`.

Anyway, some questions may help us to understand.
1. Does it `CRI runtime` annotation is not passed when running in K8s ? 
2. Do we want a context-dependent configuration? If yes we need some good testing to avoid hide this kind of issue.

**Comment by egernst** [comment]
There is no annotation from CRI to indicate K8S.

K8S is and should be the default configuration for Kata Containers. The prior PR breaks this. I would recommend creating a flag in toml for indicating that the runtime should manage cpu/mem group subsystems on the host. This would be set if folks want to constrain and are using Docker or Podman.

In any case - we should be careful not to break kata+k8s...
