### ISSUE TITLE
metrics ci: blong bench hangs using qemu + virtiofsd

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#2799]
# Description of problem

Trying to enable virtiofs for qemu + virtiofsd  I found that jobs hangs.  

# Expected result

blog bench works

# Actual result

The test hangs until the job is aborted
```
TODO collect kata logs
```

**Comment by amshinde** [comment]
@jcvenegas @GabyCT Can you add logs here ?

**Comment by GabyCT** [comment]
@amshinde the logs of virtiofs are here https://github.com/kata-containers/tests/issues/2717

**Comment by jcvenegas** [comment]
Closing this as duplicated of kata-containers/tests#2717
