### ISSUE TITLE
check sandbox pointers in virtcontainers internal functions

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#280]
From @jodh-intel:
> I'd honestly take the opposite approach and not trust anything! 😄
>
> imho we need to "fail fast" since if we start trusting ourselves, we get into horrible situations where func1 calls func2 calls funcN, and funcN explodes because func1 forgot to check if sandbox == nil. That makes debugging very difficult. This is not theoretical - we've been in that situation before in the very early days of vc which prompted me to raise PRs such as containers/virtcontainers#163.
>
> We also have precedent for checking all parameters, for example:
>
> https://github.com/kata-containers/runtime/blob/master/virtcontainers/container.go#L480..L483

IMHO, to make such a change, we need to clarify a few things:
1. What is the guideline for internal function parameter sanity check? Do we want to check sandbox pointers in every function?
2. What to do about other parameters? Do we want to make sandbox pointers a special case?

@jodh-intel @sboeuf @egernst please comment.

**Comment by sboeuf** [comment]
Thanks for opening this, I have assigned P1 priority as it might be good to address it asap.

**Comment by bergwolf** [comment]
@sboeuf Why is it a P1 issue? AFAICT, it is not a bug and does not block any functionality. I am not even convinced we should do it. A P1 issue means it must be fixed ASAP but I see otherwise on this one.

And please comment on the two things I listed above so that we can get consensus on internal function parameter sanity checking before introducing random checks here and there.

**Comment by grahamwhaley** [comment]
You may not get feedback from @jodh-intel this week. I strongly suspect he'd vote for checking all interface parameters all the time, at all levels... but, let's wait for his input on that.

Personally, I do think that whilst that leads to better/safer software, it is possibly overkill from the performance pov. I'd vote we check all parameters at all boundaries (API and module interfaces etc.) at a minimum (but I think we all agree on that already).

**Comment by bergwolf** [comment]
@egernst I asked about sandbox pointer specifically because I was asked to check it but not other parameters. I think we should not make it a special case but need to confirm with you guys.

I guess we all likely agree on checking all parameters at API and module boundaries. Let's wait @jodh-intel's input when he come back.
