### ISSUE TITLE
allow parallel vm resource hotplug

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#281]
# Description of problem

Currently the container rootfs block device, volume block devices, CPU and memory are all hot plugged sequentially. We should be able to add these resources in parallel, further reducing container spinning up time.

**Comment by WeiZhang555** [comment]
Issue https://github.com/kata-containers/runtime/issues/50 , https://github.com/kata-containers/runtime/issues/113 and PR https://github.com/kata-containers/runtime/pull/214 are parts of this.
