### ISSUE TITLE
Cloud hypervisor + kata does not start when using high CPU & memory config

### ISSUE THREAD

**Issue by ganeshmaharaj** [kata-containers/runtime#2814]
# Description of problem
Creating a kata+clh k8s pod with huge amounts of CPU(>32 cores) and memory (>128GB) will always fail and the container will never start.  @jcvenegas  was able to reproduce this issue with Kata 1.11.1 and CLH 0.7 
https://gist.github.com/jcvenegas/465be230a85b1800e23b4d7dda1d7add#file-guest-logs

# Expected result
Kata + CLH can run VMs with large number of cores and memory

# Actual result

Container will fail to start. @jcvenegas  has confirmed that CLH 0.8 version has a fix for this issue (https://github.com/cloud-hypervisor/cloud-hypervisor/issues/1132) and should fix the problem. Opening this bug to track the issue and close it once 1.11.x stable gets a CLH update (if needed).

**Comment by ganeshmaharaj** [comment]
@jcvenegas @amshinde @likebreath

**Comment by amshinde** [comment]
@chavafg We need to add a test for this. Test both qemu and clh with large CPUs and memory config. I dont think the VMs we get from Azure will be adequate for this.

**Comment by chavafg** [comment]
@amshinde agree, could this run on nightly basis? If so, we could use baremetal from aws.

**Comment by jcvenegas** [comment]
This is fixed in master, was a fix after upgrade to cloud-hypervisor 0.9
