### ISSUE TITLE
How to specify  cold plug  flag for vfio device when kata start

### ISSUE THREAD

**Issue by Kvasscn** [kata-containers/runtime#2821]
I found that in the changlog of kata runtime already  supported  coldplug device， refer to the links below:
https://github.com/kata-containers/runtime/commit/970ef454c2e508912d036bf8bdf8c3359e55e387
But no documentation describe  how to specify the clod pulg flag  in command line when kata starts, anybody know how to do that?

**Comment by devimc** [comment]
VFIO cold plug is only supported when the network endpoint is a physical endpoint (VFIO / SPDK), the rest of VFIO devices are hotplugged, there is no way to change this behaviour, what issue are you facing? why do you want to coldplug VFIO devices ?

**Comment by ariel-adam** [comment]
Closing this issue for now.
Feel free to open if you would like to lead the investigation.
