### ISSUE TITLE
containerd-shim-kata-v2 debug option cannot be opened

### ISSUE THREAD

**Issue by free2k** [kata-containers/runtime#2824]
**Is your feature request related to a problem? Please describe.**

When I use containerd-shim-kata-v2, the debug option cannot be opened

**Describe the solution you'd like**

containerd-shim-kata-v2 can open debug options

**Describe alternatives you've considered**

Modify the default value of debug flag to true
![image](https://user-images.githubusercontent.com/14852402/87242764-3f88f200-c462-11ea-9100-8ef22e0a55b9.png)

**Additional context**
No

**Before raising this feature request**

yes

**Comment by fidencio** [comment]
I don't fully understand the request. If you pass "-debug" to the containder-shim-kata-v2 binary it just works. Mind that configuring it depends on the what's calling the binary and for a better explanation, check: https://github.com/fidencio/kata-documentation/blob/wip/shimv2-and-crio/Developer-Guide.md#debug-logs-and-shimv2

If you're talking about having different log levels traced, other than debug, take a look at: https://github.com/kata-containers/kata-containers/issues/366

Please, let us know if this solve your issue.

**Comment by free2k** [comment]
> I don't fully understand the request. If you pass "-debug" to the containder-shim-kata-v2 binary it just works. Mind that configuring it depends on the what's calling the binary and for a better explanation, check: https://github.com/fidencio/kata-documentation/blob/wip/shimv2-and-crio/Developer-Guide.md#debug-logs-and-shimv2
> 
> If you're talking about having different log levels traced, other than debug, take a look at: [kata-containers/kata-containers#366](https://github.com/kata-containers/kata-containers/issues/366)
> 
> Please, let us know if this solve your issue.

Thanks, your answer solved my problem
