### ISSUE TITLE
Disable some kubectl commands in kata-runtime for security reason. 

### ISSUE THREAD

**Issue by liudalibj** [kata-containers/runtime#2841]
**Is your feature request related to a problem? Please describe.**

After we setup kata with kubernetes, end user can use some kubectl commands to communicate with container.
such as:
kubectl exec 
kubectl cp
kubectl attach

With these commands end user can go into your running container, get application details of your container, or can copy the files from you container out.

From a security perspective, I only want the end user access the container by the Rest API, all other access should be disabled. 

**Describe the solution you'd like**

Add a configuration item in kata, to disable these kubectl commands,
In kataruntime related codes, check the configuration item, when these kubectl commands configed as disable, then return error message to enduser directly, otherwise pass these commands to container.

**Describe alternatives you've considered**

We may add a new annotation, use this annotation to disable these kubectl commands.

**Additional context**

no

**Before raising this feature request**

Have you looked at the [limitations document](https://github.com/kata-containers/documentation/blob/master/Limitations.md)?

**Comment by amshinde** [comment]
@liudalibj This is something that should be handled at the kubernetes level and not by Kata. You can take a look at RBAC roles and policies https://kubernetes.io/docs/reference/access-authn-authz/rbac/

**Comment by liudalibj** [comment]
Thanks your comments @devimc @amshinde I will study the related documents to see if they can meet my requirement.
