### ISSUE TITLE
Do we need a native way to start up a pod by `docker cli`

### ISSUE THREAD

**Issue by jshachm** [kata-containers/runtime#285]
Nowadays, we support to start up a `pod` using `Annotations` -- a `k8s` way
However, we don't have a native way to start up a pod by `docker cli` . Because `annotations` haven't been pass through `docker` to `kata-runtime`.

There are two ways I can find：
- pass `annotations` through `docker`  
[docker annotations pr by laijs](https://github.com/moby/moby/pull/36181)
- maybe use `runv` way like `--net container xxxx`

or any other good thing I want to hear from you guys ~

@sameo @bergwolf @laijs @gnawux @egernst @grahamwhaley @WeiZhang555

**Comment by WeiZhang555** [comment]
+1 on this
