### ISSUE TITLE
QEMU instance does not exit when VM shuts itself down.

### ISSUE THREAD

**Issue by merwick** [kata-containers/runtime#2866]
# Description of problem

Stopping a Kata VM (e.g. using /proc/sysrq-trigger) from within the VM doesn't cause the QEMU process to exit.

# Expected result

echo b >  /proc/sysrq-trigger, Kata VM shuts down and QEMU process exits

# Actual result

QEMU instance keeps running but VM is now unresponsive having shut down.

---

**Comment by merwick** [comment]
The Kata architecture does not support rebooting VMs (the lifecycle being start/exec/kill) and if a VM is killed (e.g. using sysrq-trigger), the VM does not exit fully and other layers do not notice the state change.

The QEMU instance needs to be told to exit and not reboot which can be done by passing the --no-reboot command line option when creating the VM.

I am working on a fix for this, please assign issue to me.

**Comment by merwick** [comment]
@devimc This covers Kata 1.12 but I'm not sure how to deal with Kata 2.0.  I ported the changes to the 2.0-dev branch [1] and they pass Travis CI [2] - does it need a separate PR?
[1] https://github.com/merwick/kata-containers/commit/c15ef219e521a1f23de8bef57b273c9a632c0dab
[2] https://travis-ci.org/github/merwick/kata-containers/builds/713350564

**Comment by devimc** [comment]
@merwick yes please, forwardport this patch, 

NOTE: 2.0-dev uses `go modules` (not `dep`)

**Comment by devimc** [comment]
>  does it need a separate PR?

yes, please

**Comment by merwick** [comment]
In https://github.com/merwick/kata-containers/commit/5010e3a368406f4a650def0cf787d9a6b422c9f1 I made the changes to go.mod, got.sum & vendor/modules.txt  (I'm not sure if I should have deleted the old govmm lines (167-168) in go.sum). I'll submit the PR and people can comment there.
