### ISSUE TITLE
failed to ping agent: Failed to check if grpc server is working

### ISSUE THREAD

**Issue by free2k** [kata-containers/runtime#2879]
# Description of problem
The container automatically restarts after the connection agent fails during the ltp stress test

`Aug 06 13:32:31 myhost1 containerd[255157]: time="2020-08-06T13:32:31.586498504+08:00" level=error msg="Wait for process failed" container=3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d error="Dead agent" pid=bd6da7ff-0c0e-4c6d-9553-71abdd2932d6
Aug 06 13:32:31 myhost1 containerd[255157]: time="2020-08-06T13:32:31.586564715+08:00" level=error msg="Wait for process failed" container=3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d error="Dead agent" pid=27860447-b7d9-412f-9b65-2eb8a0aebac6
Aug 06 13:32:31 myhost1 kata[255645]: time="2020-08-06T13:32:31.586438005+08:00" level=error msg="Wait for process failed" container=d0ef34f8c209717ea8b080fe582b1f3c47dabf9b3c47f379173850663afb9bfc error="rpc error: code = Unavailable desc = transport is closing" pid=d0ef34f8c209717ea8b080fe582b1f3c47dabf9b3c47f379173850663afb9bfc
Aug 06 13:32:31 myhost1 containerd[255157]: time="2020-08-06T13:32:31.586439362+08:00" level=error msg="Wait for process failed" container=3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d error="Dead agent" pid=3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d
Aug 06 13:32:31 myhost1 containerd[255157]: time="2020-08-06T13:32:31.586617832+08:00" level=error msg="collecting metrics for 3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d" error="transport is closing: unavailable"
Aug 06 13:32:31 myhost1 kata[255645]: time="2020-08-06T13:32:31.586498504+08:00" level=error msg="Wait for process failed" container=3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d error="Dead agent" pid=bd6da7ff-0c0e-4c6d-9553-71abdd2932d6
Aug 06 13:32:31 myhost1 kata[255645]: time="2020-08-06T13:32:31.586564715+08:00" level=error msg="Wait for process failed" container=3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d error="Dead agent" pid=27860447-b7d9-412f-9b65-2eb8a0aebac6
Aug 06 13:32:31 myhost1 kata[255645]: time="2020-08-06T13:32:31.586439362+08:00" level=error msg="Wait for process failed" container=3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d error="Dead agent" pid=3fb6bdf1c82c0b81d61fc4442c12246158318c7255f5a5b578c3784bfaabcb0d
Aug 06 13:32:37 myhost1 containerd[255157]: time="2020-08-06T13:32:37.518292182+08:00" level=warning msg="Agent did not stop sandbox" ID=d0ef34f8c209717ea8b080fe582b1f3c47dabf9b3c47f379173850663afb9bfc error="Dead agent" sandbox=d0ef34f8c209717ea8b080fe582b1f3c47dabf9b3c47f379173850663afb9bfc sandboxid=d0ef34f8c209717ea8b080fe582b1f3c47dabf9b3c47f379173850663afb9bfc source=virtcontainers subsystem=sandbox
Aug 06 13:32:37 myhost1 kata[255645]: time="2020-08-06T13:32:37.518292182+08:00" level=warning msg="Agent did not stop sandbox" ID=d0ef34f8c209717ea8b080fe582b1f3c47dabf9b3c47f379173850663afb9bfc error="Dead agent" sandbox=d0ef34f8c209717ea8b080fe582b1f3c47dabf9b3c47f379173850663afb9bfc sandboxid=d0ef34f8c209717ea8b080fe582b1f3c47dabf9b3c47f379173850663afb9bfc source=virtcontainers subsystem=sandbox
Aug 06 13:32:37 myhost1 kata[255645]: time="2020-08-06T13:32:37.562547023+08:00" level=warning msg="sandbox stopped unexpectedly" error="failed to ping agent: Failed to check if grpc server is working: rpc error: code = DeadlineExceeded desc = context deadline exceeded"`
(replace this text with the list of steps you followed)

# Expected result

The container should not be restarted

# Actual result

The container restarts automatically

**Comment by jodh-intel** [comment]
Hi @free2k - please can you provide further information on this. Ideally, please run `sudo kata-collect-data.sh`, review the output to ensure it doesn't contain any private/sensitive information and paste the output here.

If we don't hear back within a week, we'll close this issue (but you can always re-open it).

**Comment by ariel-adam** [comment]
We are closing the issue for now.
Feel free to reopen once the information is provided.

**Comment by RyanAoh** [comment]
Hi @free2k,  have you solved this? 
The same problem encounts to me now.

**Comment by mappjzc** [comment]
> We are closing the issue for now.
> Feel free to reopen once the information is provided.

I have add "return nil" when the failed to ping to agent happened
and into the VM to see the agent.
There is one thread of kata-agent keep 100% cpu cost
And when  I cat /proc/{pid}/task/{tid}/stack 
it print:

[<0>] __x64_sys_sched_yield+0x9/0x10
[<0>] do_syscall_64+0x8b/0x2e0
[<0>] entry_SYSCALL_64_after_hwframe+0x44/0xa9
[<0>] 0xffffffffffffffff

Is there anyone know where agent to call this system call?

**Comment by jodh-intel** [comment]
@mappjzc - please open a fresh issue and provide the details requested rather than commenting on a closed issue.
