### ISSUE TITLE
Is qemu-system-x86_64 or qemu-lite-system-x86_64 in kata-containers configuration.toml 

### ISSUE THREAD

**Issue by gnodli** [kata-containers/runtime#293]
# Description of problem
I follow [Developer-Guide.md](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md)  

conditions:
- initrd image and hyperstart kernel
-default runtime is kata-runtime

when I use below command to start a container, which return an error
`  sudo docker run -ti busybox sh`

# Expected result
start a busybox container

# Actual result
output:
```
docker: Error response from daemon: OCI runtime create failed: /usr/share/defaults/kata-containers/configuration.toml: file /usr/bin/qemu-system-x86_64 does not exist: unknown.
```

---
Finally, I found the QEMU version should be qemu-lite, and the dir of `/usr/bin/` only have qemu-lite-system-x86_64。  Then, I change the qemu-system-x86_64 to qemu-lite-system-x86_64, it works.

**Comment by jodh-intel** [comment]
Thanks for raising this. I'm slightly confused though - the error states that you do not have qemu installed.

The developer guide does state that you need to install `qemu-lite` here:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#assumptions

That said, we do need to update the dev guide now that we also support vanilla qemu (see #119). I've raised https://github.com/kata-containers/documentation/issues/67 to deal with this.

**Comment by gnodli** [comment]
Thank you for your answer. I did not install qemu, just install qemu-lite package according to above guide. That said, qemu-lite can also work , but it has been dropped.

**Comment by jodh-intel** [comment]
Oh sorry, I see what you mean now. I'll try to update the dev guide today to avoid this confusion...

**Comment by jodh-intel** [comment]
Hi @gnodli - are you happy for this issue to be closed when https://github.com/kata-containers/documentation/pull/68 lands?

**Comment by gnodli** [comment]
Now I understand，thank you very much

**Comment by urbandroid** [comment]
Configuration looks for qemu-lite but snap package has qemu bin and bam! you can't change conf file because snaps are read only that's why i love snap, reveals the lazy, pain in the ass software at early stage. Issue is still there but issue is closed what should i do? i know $sudo snap remove kata-containers --never-look-back

**Comment by caoruidong** [comment]
cc @jcvenegas @jodh-intel

**Comment by bergwolf** [comment]
I think we should provide qemu-lite snap package as well cc @devimc .
