### ISSUE TITLE
Memory footprint has been increased

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#2942]
Currently we have a failure that memory footprint has been increased, this is maybe related with this change https://github.com/kata-containers/runtime/commit/e529c010e0708954ce9924d5f10aa4d0c47708f6. Should we increase the limit to fix the CI or what is the best approach?
/cc @amshinde @likebreath @chavafg

**Comment by jodh-intel** [comment]
Related:

- https://github.com/kata-containers/tests/issues/2839
- https://github.com/kata-containers/tests/pull/2840

**Comment by GabyCT** [comment]
To unblock the CI we have https://github.com/kata-containers/tests/pull/2840

**Comment by ariel-adam** [comment]
Closing this since we decided the workaround is good enough.
