### ISSUE TITLE
Can Centos image run on Ubuntu nodes？

### ISSUE THREAD

**Issue by timyinshi** [kata-containers/runtime#2946]
# Description of problem
when i use kata on a ubuntu node,i want to run a container with centos img, can kata support that?

the config:
[hypervisor.qemu]
path = "/usr/bin/qemu-vanilla-system-x86_64"
kernel = "/usr/share/kata-containers/vmlinuz.container"     //this is centos kernel
initrd = "/usr/share/kata-containers/kata-containers-initrd.img"  //this is cenos img
machine_type = "pc"

**Comment by fidencio** [comment]
It should, but it depends on the configuration you're using, which CentOS version you're using, etc.

Please, provide all the configuration and versions of what you want to use.

**Comment by egernst** [comment]
Shouldn’t be anime issue. Give it a try. If you use github/kata-containers/osbuilder, you’ll see that centos is a supported target for the rootfs builder. I’m not sure you’ll have requirements on the kernel, versus rootfs?

**Comment by timyinshi** [comment]
@fidencio @egernst thanks.
