### ISSUE TITLE
how to cross build binary for arm64 on amd64 platform

### ISSUE THREAD

**Issue by lovebaby979** [kata-containers/runtime#2977]
# Description of problem
how to build binary for arm64 on amd64 platform

build binary for arm64 on amd64（ubuntu18.04）
I update variable “golang_version_raw” in golang.mk， replace “amd64” to “arm64”, when make, report the errors:

(cd cli && GOARCH=arm64 go build  -buildmode=pie  -o /usr/local/gopath/src/github.com/kata-containers/runtime/kata-runtime .)
# github.com/kata-containers/runtime/cli
./kata-check_arm64.go:32:44: undefined: kernelModule
./kata-check_arm64.go:53:44: undefined: kvmExtension
./kata-check_arm64.go:67:9: undefined: genericKvmIsUsable
./kata-check_arm64.go:71:18: undefined: genericCheckKVMExtensions
./kata-check_arm64.go:98:39: undefined: vmContainerCapableDetails
./kata-check_arm64.go:100:12: undefined: getCPUInfo
./kata-check_arm64.go:105:16: undefined: checkKernelModules
./kata-check_arm64.go:114:33: undefined: failMessage
./main.go:140:2: undefined: kataCheckCLICommand
./main.go:143:2: undefined: kataOverheadCLICommand
./kata-check_arm64.go:114:33: too many errors
Makefile:566: recipe for target '/usr/local/gopath/src/github.com/kata-containers/runtime/kata-runtime' failed
make: *** [/usr/local/gopath/src/github.com/kata-containers/runtime/kata-runtime] Error 2

**Comment by jodh-intel** [comment]
Maybe @jongwu might have thoughts on how to do a cross-build like this.

**Comment by jongwu** [comment]
Hi @lovebaby979 . Good question. If your target is armv8, you can install cross toolchain(in ubuntu, just install gcc-aarch64-linux-gnu) first and try "export GOARCH=arm64 GOARM=""  CGO_ENABLED=1 CC=aarch64-linux-gnu-gcc && make" under kata-containers/runtime. more info see https://github.com/golang/go/wiki/GoArm. Good luck.

**Comment by lovebaby979** [comment]
Thanks.

**Comment by jodh-intel** [comment]
Hi @lovebaby979 - can we close this issue now?
