### ISSUE TITLE
Logging system for kata-containers

### ISSUE THREAD

**Issue by gnawux** [kata-containers/runtime#3]
Now we have `logrus` and `glog` as candidate, both are widely used in the golang world. We all agree the logrus are more flexible and powerful. However, glog is come from Google, and used by most of the kubernetes family projects.

The question is, could we wrapped the log engine, which allows the users could select log engine if they import kata code as vendor?

**Comment by gnawux** [comment]
As discussed in the meeting, I created the issue, correct me if there is anything wrong.
@laijs @bergwolf @sboeuf @jodh-intel @sameo

**Comment by grahamwhaley** [comment]
A quick github search turned up this:
https://github.com/bookerzzz/glog
Not sure if that will be of use...?

**Comment by grahamwhaley** [comment]
or (/me goes to check)... is that the same glog. hmm...

**Comment by sboeuf** [comment]
@grahamwhaley it creates an implementation of the glog interface it seems.

**Comment by gnawux** [comment]
Since there is no more discussion on this topic, I wrote a log adapter to allow using glog as the output of logrus: https://github.com/gnawux/glog4logrus 

then we could coding with logrus and log to logrus or glog as required. Any comments?

**Comment by sameo** [comment]
@gnawux Thanks a lot.
So would the typical usage for exported Kata Containers component be:

1. Import github.com/gnawux/glog4logrus
2.  When starting the component, call:
```Go
        logrus.SetLevel(glog4logrus.GlogLevel())
	logrus.SetFormatter(&glog4logrus.GlogFormatter{})
	logrus.SetOutput(&glog4logrus.GlogOuptut{})
```

**Comment by WeiZhang555** [comment]
Or should we expose an option to user and let user choose which log system to use?

For example:

```
--log-driver=logrus:json-file
--log-driver=glog:text
```

**Comment by gnawux** [comment]
@sameo @WeiZhang555 The simple answer is No.

I used to think about such ways. However, if you read more `glog` code, you will found --

`glog` has a `init()` method, which will insert some flags to your binary, such as `-v`, `-logtostderr`, etc. I guess you don't want to have these flags if you wan to use native
`logrus`, however, you have to run the `init()` if you import `glog` no matter whether 
you log with it.

Then how to use `glog4logrus`, my assumption is ---

If you have a program use kata as a library, say `hyperd` here (just for illustration), and you
want use `glog`, because k8s use `glog` as well, it is reasonable to have all the binaries 
output logs in the same manner. When the `hyperd` call `kata` as a lib, it could set the logrus
format and output driver with `glog4logrus`.

Let me summary here:

- kata components use logrus, and provide method to setup logrus (this should not be a problem).
- kata components don't import `glog4logrus` 
- If a guest code want to use `glog`, then they must have already imported `glog`, and they could import `glog4logrus` and configure logrus to export to glog.

**Comment by sameo** [comment]
@gnawux I think this is the right approach, thanks for the clarification.

**Comment by WeiZhang555** [comment]
Yeah, sounds quite good :+1:

**Comment by egernst** [comment]
Seems we have agreement based on @gnawux's proposal.  Closing this resolved issue.
