### ISSUE TITLE
clh: Consolidate the code path for device unplug

### ISSUE THREAD

**Issue by likebreath** [kata-containers/runtime#3001]
In cloud-hypervisor, it provides a single unified way of unplugging devices, e.g. the `/vm.RemoveDevice` HTTP API. Taking advantage of this API, we can simplify our implementation of `hotplugRemoveDevice` in `clh.go`, where we can consolidate similar code paths for different device unplug (e.g. no need to implement `hotplugRemoveBlockDevice` and `hotplugRemoveVfioDevice` separately). We will only need to retrieve the right `deviceID` based on the type of devices, and use the single unified HTTP API for device unplug.

**Comment by dgibson** [comment]
Fwiw, I believe we could make the qemu paths for unplugging much more unified too.  It'll probably take me a while before I can look at that, though.
