### ISSUE TITLE
Validate annotations that refer to binaries

### ISSUE THREAD

**Issue by c3d** [kata-containers/runtime#3004]
The description of the problem is in https://bugs.launchpad.net/katacontainers.io/+bug/1878234.

This issue is a placeholder to allow the fixes to be submitted.

It also contains a fix for #2943

**Comment by GabyCT** [comment]
@c3d , I see at the kata-collect the following failures
```

Output of "`/usr/bin/kata-runtime kata-env`":
```toml
Cannot find usable config file (config file "/etc/kata-containers/configuration.toml" unresolvable: file /etc/kata-containers/configuration.toml does not exist, config file "/usr/share/defaults/kata-containers/configuration.toml" unresolvable: file /usr/share/defaults/kata-containers/configuration.toml does not exist)
```
```

**Comment by GabyCT** [comment]
In the CI's that are failing ...I see in the logs
# Runtime config files


## Runtime default config files

```
/etc/kata-containers/configuration.toml
/usr/share/defaults/kata-containers/configuration.toml
```

## Runtime config file contents

Config file `/etc/kata-containers/configuration.toml` not found
Config file `/usr/share/defaults/kata-containers/configuration.toml` not found

---


# KSM throttler


## version

Output of "` --version`":
```
/usr/bin/kata-collect-data.sh: line 178: --version: command not found
```

**Comment by GabyCT** [comment]
is that expected?

**Comment by c3d** [comment]
@GabyCT No, not expected. Looking. I guess I was not looking at the right spot. Which log is this in?
