### ISSUE TITLE
kata-runtime not respecting CPU flags with docker

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#3018]
I am trying to run a container with kata-runtime but I see that is not respecting the CPUs flags.
For example
```
$ docker run -ti --privileged --cpuset-cpus=0-23,48-71 --cpuset-mems=0 --runtime=kata-runtime test bash
root@7547f18f2d50:/test# cat /proc/cpuinfo
processor       : 0
vendor_id       : GenuineIntel
cpu family      : 6
model           : 85
model name      : Intel(R) Xeon(R) Gold 6252 CPU @ 2.10GHz
stepping        : 7
microcode       : 0x1
cpu MHz         : 2095.078
cache size      : 16384 KB
physical id     : 0
siblings        : 1
core id         : 0
cpu cores       : 1
apicid          : 0
initial apicid  : 0
fpu             : yes
fpu_exception   : yes
cpuid level     : 22
wp              : yes
flags           : fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl xtopology cpuid tsc_known_freq pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch cpuid_fault invpcid_single ssbd ibrs ibpb stibp ibrs_enhanced tpr_shadow vnmi flexpriority ept vpid ept_ad fsgsbase tsc_adjust bmi1 avx2 smep bmi2 erms invpcid mpx avx512f avx512dq rdseed adx smap clflushopt clwb avx512cd avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves arat umip pku avx512_vnni md_clear arch_capabilities
bugs            : spectre_v1 spectre_v2 spec_store_bypass swapgs
bogomips        : 4190.15
clflush size    : 64
cache_alignment : 64
address sizes   : 40 bits physical, 48 bits virtual
power management:
```
It is only giving one core id, it seems it is not respecting the cpu flags like RUNC.

Also when I tried to run a container using the following

```
$ docker run -ti --privileged --cpus=96 --runtime=kata-runtime test bash
```
the test will only run in 1 cpu, again kata is not respecting the cpu flag like RUNC.

/cc @amshinde @jcvenegas @likebreath

**Comment by likebreath** [comment]
@GabyCT Would you mind share more about your setup, also the complete `cpuinfo` from  the container?

I tried the current kata-runtime [master](https://github.com/kata-containers/runtime/commit/cb196de50180fdb212551713c600fb1c861be56e) and run the following container (very similar to yours): 

`docker run --rm -ti --privileged --cpus=24 --runtime=kata-runtime ubuntu bash`

Inside the container I ran a workload `stress --cpu 24`, and I see all my 24 (logical) cpus on host are running 100% utilization.

**Comment by egernst** [comment]
What version of Kata? Master? this should work with this PR: https://github.com/kata-containers/runtime/pull/2972

**Comment by egernst** [comment]
I see that cpuset is getting set to 0 in the docker CLI case.

This works okay in the kube / pod scenario, since cpuset is cleared during the 'update' call.  

We should take a look addressing it on the single container / docker cli case.

**Comment by GabyCT** [comment]
The kata version that I am using is 
```
kata-runtime  : 1.12.0-alpha1
commit   : 87d215ee3aa3c108c977f6a578e4b21d57ffab0a
OCI specs: 1.0.1-dev
```
I am using a mysql benchmark. And what I see is that RUNC is running it with a CPU Utilization of > 90%. Here it is a screenshot of `htop` inside the container
![image](https://user-images.githubusercontent.com/20359065/96505354-9baaa180-121b-11eb-9606-c173d66444ee.png)

Running the same benchmark with kata-runtime seems that is not triggering correctly as I only have a CPU Utilization of < 30%. Here it is a screenshot of `htop` inside the container
![image](https://user-images.githubusercontent.com/20359065/96505534-e0ced380-121b-11eb-80bd-ad2cdd395a35.png)

It seems that kata is performing all the utilization while running with --privileged --cpus=

**Comment by egernst** [comment]
Not a real solution, but I'm curious if you can run same benchmark using `ctr`, `crictl` or Kubernetes?

There's an issue with our handling with docker cli for cgroups in the guest.

**Comment by tommyrousey** [comment]
Hey @egernst @GabyCT, my group (@bporter816, @maomarcus, @yasv123 and myself) in my Virtualization class at UT is looking for issues to complete and was wondering what your assessment of the potential difficulty of this issue.  

Thanks a bunch!

**Comment by tommyrousey** [comment]
Hey @egernst @GabyCT @likebreath, in addition for my request for some background, can I be assigned to this issue ?

Thanks!

**Comment by GabyCT** [comment]
@tommyrousey thanks :) about how difficult is, I am not sure but let me see what @likebreath @egernst and @fidencio think

**Comment by likebreath** [comment]
The same issue is https://github.com/kata-containers/kata-containers/issues/1405 (back-porting the fixing PR https://github.com/kata-containers/kata-containers/pull/1406).

**Comment by likebreath** [comment]
The issue has been fixed by https://github.com/kata-containers/runtime/pull/3138.
