### ISSUE TITLE
keep caution to use golang 1.15.x to compile kata

### ISSUE THREAD

**Issue by jongwu** [kata-containers/runtime#3029]
There maybe a bug or incompatible issue in golang 1.15.x.
If you happen to see the error log "Error response from daemon: OCI runtime create failed: fork/exec /usr/libexec/kata-containers/kata-shim: Setctty set but Ctty not valid in child: unknown" when run kata, just update your golang version forward or backward and recompile.

someone complains about it, I'm not sure if it is always happen, so just describe it here to give some hint.

**Comment by mappjzc** [comment]
I have meet the same error when I update the golang version from 1.14.1 to 1.15.3 for fixed a golang lib error.

And I grep the "Setctty set but Ctty not valid in child" In my $GOROOT

It error in this file "/usr/local/go/src/syscall/exec_unix.go"

**Comment by mappjzc** [comment]
> There maybe a bug or incompatible issue in golang 1.15.
> If you happen to see the error log "Error response from daemon: OCI runtime create failed: fork/exec /usr/libexec/kata-containers/kata-shim: Setctty set but Ctty not valid in child: unknown" when run kata, just update your golang version forward or backward and recompile.
> 
> someone complains about it, I'm not sure if it is always happen, so just describe it here to give some hint.

your said "update golang version backward"
Can you tell me which golang version backward 1.15.3 and have fiexd this error?

**Comment by jongwu** [comment]
I'm glad to see this issue can help someone. I downgrade the golang to 1.14 and the error is gone. so you can try it.

**Comment by zer0def** [comment]
Duplicate of #2982, fixed in #3082.

**Comment by jongwu** [comment]
thanks @zer0def, I will close this issue.
