### ISSUE TITLE
How to limit disk quota of sharedFS？

### ISSUE THREAD

**Issue by mikumaycry** [kata-containers/runtime#3049]
When using Kata with Containerd, devmapper can be used to limit the root partition of container.

But once **VOLUME** is declared in image's Dockerfile, the directory will be mount to corresponding path under **/run/vc**.

For exmaple, the **redis:5** image use **/data** to store data. 

```
root@container-23336666:/data# df -hT
Filesystem     Type   Size  Used Avail Use% Mounted on
/dev/sdc       ext4   4.8G  120M  4.5G   3% /
tmpfs          tmpfs   64M     0   64M   0% /dev
tmpfs          tmpfs  1.1G     0  1.1G   0% /sys/fs/cgroup
kataShared     9p     512G   15G  498G   3% /data
shm            tmpfs   64M     0   64M   0% /dev/shm
root@uedn-cntr-23336666:/data#
```

This directory is mounted on host machine. And this container could take up all space if needed.

shared_fs is enabled by default when using qemu as hypervisor, is it possible to disbale shared_fs or limit disk quota of sharedFS?

**Comment by devimc** [comment]
@mikumaycry thanks for raising this, can you limit disk quota with runC? afaik that's not possible

**Comment by mikumaycry** [comment]
> @mikumaycry thanks for raising this, can you limit disk quota with runC? afaik that's not possible

runC is the same as kata, the root parition can be limited with devmapper, but volumes are mounted under 

**/var/lib/containerd/io.containerd.grpc.v1.cri/containers/xxxxxxx/volumes/xxxxxx**

And hosts, resolv.conf, hostname are writable both in kata and runC, writing large content into those files will directly take host's disk space.

**Comment by devimc** [comment]
@mikumaycry if that's the case (same as runC) then I guess there is nothing we can do, have you considered mounting such file/volumes as read-only ?

**Comment by mikumaycry** [comment]
> @mikumaycry if that's the case (same as runC) then I guess there is nothing we can do, have you considered mounting such file/volumes as read-only ?

Yes, I just found a way to limit disk quota of sharedFS

（1）enable **ignore_image_defined_volumes** to ignore all VOLUME paths declared in Dockerfile, those paths will be created in rootfs
（2）Add /etc/hosts, /etc/resolv.conf, /etc/hostname to **ReadonlyPaths** in ContainerConfig.Linux.SecurityContext when creating containers

**Comment by devimc** [comment]
@mikumaycry cool, can we close this?

**Comment by mikumaycry** [comment]
> @mikumaycry cool, can we close this?

Yes
