### ISSUE TITLE
BUG: unhandled scenario: current version: 1.12.0-rc0, latest version: 1.12.0

### ISSUE THREAD

**Issue by didier-durand** [kata-containers/runtime#3069]
Hello,

After installation of kata,  _'kata-runtime kata-check'_ now produces the following:

ERRO[0000] **BUG: unhandled scenario**: current version: 1.12.0-rc0, latest version: 1.12.0  arch=amd64 name=kata-runtime pid=7617 source=runtime
BUG: unhandled scenario: current version: 1.12.0-rc0, latest version: 1.12.0

My install via _'$(curl -fsSL https://raw.githubusercontent.com/kata-containers/tests/master/cmd/kata-manager/kata-manager.sh) install-docker-system"'_  was repeatedly working just fine until the version 1.12 of the project was published 1 hour go.

Is there a workaround until you fix?

Thanks

DIdier

**Comment by didier-durand** [comment]
More information: kata-runtime seems properly installed as per below. Just _'kata-runtime kata-check'_ seems to fail.

_**'kata-runtime kata-env'**_ produces 

[Meta]
  Version = "1.0.24"

[Runtime]
  Debug = false
  Trace = false
  DisableGuestSeccomp = true
  DisableNewNetNs = false
  SandboxCgroupOnly = false
  Path = "/usr/bin/kata-runtime"
  [Runtime.Version]
    OCI = "1.0.1-dev"
    [Runtime.Version.Version]
      Semver = "1.12.0-rc0"
      Major = 1
      Minor = 12
      Patch = 0
      Commit = ""
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 5.0.0\nCopyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-vanilla-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  EntropySource = "/dev/urandom"
  SharedFS = "virtio-9p"
  VirtioFSDaemon = "/usr/bin/virtiofsd"
  Msize9p = 8192
  MemorySlots = 10
  PCIeRootPort = 0
  HotplugVFIOOnRootBus = false
  Debug = false
  UseVSock = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-image_clearlinux_1.12.0-rc0_agent_5cfb8ec960.img"

[Kernel]
  Path = "/usr/share/kata-containers/vmlinuz-5.4.60.89-51.container"
  Parameters = "systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none"

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false
  [Proxy.Version]
    Semver = "1.12.0-rc0-adde733"
    Major = 1
    Minor = 12
    Patch = 0
    Commit = "<<unknown>>"

[Shim]
  Type = "kataShim"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false
  [Shim.Version]
    Semver = "<<unknown>>"
    Major = 0
    Minor = 0
    Patch = 0
    Commit = "<<unknown>>"

[Agent]
  Type = "kata"
  Debug = false
  Trace = false
  TraceMode = ""
  TraceType = ""

[Host]
  Kernel = "5.4.0-1029-gcp"
  Architecture = "amd64"
  VMContainerCapable = true
  SupportVSocks = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "20.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Xeon(R) CPU @ 2.20GHz"

[Netmon]
  Path = "/usr/libexec/kata-containers/kata-netmon"
  Debug = false
  Enable = false
  [Netmon.Version]
    Semver = "1.12.0-rc0"
    Major = 1
    Minor = 12
    Patch = 0
    Commit = "<<unknown>>"

**Comment by jodh-intel** [comment]
Hi @didier-durand - thanks for reporting. Please can you try running the following until we investigate and fix the issue:

```bash
$ kata-runtime kata-check -n
```

**Comment by didier-durand** [comment]
Thanks for this workaround! I get now the final sentence that I need.

Output:

_kata-runtime kata-check -n
WARN[0000] modprobe insert module failed: modprobe: ERROR: could not insert 'vhost_vsock': Operation not permitted  arch=amd64 error="exit status 1" module=vhost_vsock name=kata-runtime pid=11351 source=runtime
ERRO[0000] kernel property not found                     arch=amd64 description="Host Support for Linux VM Sockets" name=vhost_vsock pid=11351 source=runtime type=module
**System is capable of running Kata Containers**_

**Comment by jodh-intel** [comment]
@didier-durand - I'm actually going to fix this in 2.0 first and as soon as that has landed backport the fix to the 1.x releases (here). The 2.0 PR is:

- https://github.com/kata-containers/kata-containers/pull/1105

**Comment by jodh-intel** [comment]
@didier-durand - it's worth pointing out that if you run `sudo kata-runtime kata-check`, it will perform a more comprehensive check (and wouldn't have run the network version check which is the problematic one you can disable using `-n`).

**Comment by didier-durand** [comment]
@jodh-intel : Thanks for this complementary info! 
Can I remove "-n" in my scripts as soon as kata-containers/kata-containers#1105 gets merged?

**Comment by jodh-intel** [comment]
@didier-durand - Well that PR is for [Kata 2.x](https://github.com/kata-containers/kata-containers/tree/2.0-dev/docs/install) (which you may want to switch to anyway? See https://github.com/kata-containers/kata-containers/releases/tag/2.0.0 for some details of 2.x). Once https://github.com/kata-containers/kata-containers/pull/1105 is merged, I will fix the problem in this repository (which is for Kata 1.x only).

By the way, as an alternative to `-n`, you can set `KATA_CHECK_NO_NETWORK=1` instead, which may be less invasive.

**Comment by didier-durand** [comment]
@jodh-intel :
I'd be happy to switch to Kata 2.x as I am doing initial tests: I'd prefer to be on last version

As said above, I currently install Kata via  '$(curl -fsSL https://raw.githubusercontent.com/kata-containers/tests/master/cmd/kata-manager/kata-manager.sh) install-docker-system' as per project documentation 

How do I enforce 2.x in the command line above? Any additional param that I should specify?
Thanks for your help!

BTW, I will publish my repo encompassing a fully automated GitHub workflow driving tests on MicroK8s + GCE as soon as I get it to work. It may help others. I'll let you know by then.

Didier

**Comment by jodh-intel** [comment]
@didier-durand - We are developing Kata 2.0 and onwards in a different repository. As such, to install Kata 2.0 you need to look at https://github.com/kata-containers/kata-containers/tree/2.0-dev/docs/install instead. The recently updated readme in the 2.x repository explains some of the differences between 1.x and 2.x in terms of repositories: https://github.com/kata-containers/kata-containers/blob/2.0-dev/README.md.

**Comment by jodh-intel** [comment]
> BTW, I will publish my repo encompassing a fully automated GitHub workflow driving tests on MicroK8s + GCE as soon as I get it to work. It may help others. I'll let you know by then.

Thanks!

**Comment by jodh-intel** [comment]
1.x PR raised: https://github.com/kata-containers/runtime/pull/3070.

**Comment by didier-durand** [comment]
Thanks for the backport!

I am trying to switch to v2.0 as suggested above.

It installs fine via snap.

But, I used to run 'kata-runtime kata-check' & 'kata-runtime kata-env'.  Now, I get a 'command not found' on kata-runtime. What are he replacing commands? Thanks in advance.
Didier

**Comment by didier-durand** [comment]
Please, forget my question above: I used 'find' to locate kata-runtime in the installed snap
