### ISSUE TITLE
Error during system resource analysis using kata-qemu-virtiofs

### ISSUE THREAD

**Issue by DavideAG** [kata-containers/runtime#3071]
# Description of problem

Good morning everyone, I begin by congratulating all of you for the great work you are doing with kata-containers. I am testing the performance and impact on system resources between various runtimes including `kata-qemu` and `kata-qemu-virtiofs`.
When I try to create 70 containers in a row (using docker as container manager) I have a problem when using the virtiofs version. In particular the following error is reported when the 32st container trying to start up: `docker: Error response from deamon: OCI runtime create failed: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing: unknown.` \
\
I have installed kata using `kata-deploy` in a bare metal ubuntu server 18.04 .
The kata configuration has been not modified.
The CPU used is an `Intel core i5 6600`.
Here a little chart about the memory situation on my system:
![MEM_70_usage](https://user-images.githubusercontent.com/53214522/99151923-ca8f2880-269e-11eb-905c-925a4db985f8.png)

Why does this error happens? \
Thank you for your time! 🤗 

# Expected result

I expect the container to run

# Actual result

`docker: Error response from deamon: OCI runtime create failed: Failed to check if grpc server is working: rpc error: code = Unavailable desc = transport is closing: unknown.`

**Comment by devimc** [comment]
@DavideAG thanks for raising this, Is DAX enabled? (Check in your configuration file)
can you enable debug, restart the kata-qemu-virtiofs test and run `sudo kata-collect-data.sh`? I'd like to see the logs

thanks

**Comment by DavideAG** [comment]
@devimc Thank you for your answer. DAX is enable and `virtio_fs_cache_size = 1024`.\
Launching `sudo kata-collect-data.sh` the result is `sudo: kata-collect-data.sh: command not found`.\
In `/opt/kata/bin` there is a script called `kata-collect-data.sh` but launching it with `sudo ./kata-collect-data.sh` I have the following error `ERROR: kata-collect-data.sh: cannot find runtime 'kata-runtime'`. \
Maybe it is similar to https://github.com/kata-containers/runtime/issues/1720

**Comment by devimc** [comment]
> @devimc Thank you for your answer. DAX is enable and virtio_fs_cache_size = 1024.

please set `virtio_fs_cache = "none"` and `virtio_fs_cache_size = 0` and try again

**Comment by DavideAG** [comment]
@devimc Thank you for your tip. I have changed `virtio_fs_cache = "none"`, `virtio_fs_cache_size = 0` and rebooted the system. Now I have relaunched the test but the error continues to be present. \
\
If it is can be helpful, each single container is launched using
`sudo docker run --runtime=kata-qemu-virtiofs -id alpine`

**Comment by DavideAG** [comment]
I don't know if it is a timeout problem, anyway I'm attaching here a chart about the boot time (usr + kernel) of each container during the experiment. Maybe it can help to understand the problem.\
\
![real_70_docker](https://user-images.githubusercontent.com/53214522/98979938-46149c80-251c-11eb-940b-4404c9f3ed40.png)

**Comment by devimc** [comment]
> In /opt/kata/bin there is a script called kata-collect-data.sh but launching it with sudo ./kata-collect-data.sh I have the following error ERROR: kata-collect-data.sh: cannot find runtime 'kata-runtime'. 

runtime following commands:

```
sudo journalctl -b -t kata-runtime
sudo journalctl -b -t kata-proxy
```

**Comment by DavideAG** [comment]
In this [link](https://drive.google.com/drive/folders/1ClQl5yDw_-rgjLqh1Xu3U9JRiLDfwroW?usp=sharing) you can find the two outputs reported in two different text files.
The two files are also attached to this comment.
[kata-proxy.txt](https://github.com/kata-containers/runtime/files/5533196/kata-proxy.txt)
[kata-runtime.txt](https://github.com/kata-containers/runtime/files/5533197/kata-runtime.txt)

\
I will also paste a snip (it is too long to be pasted in a single hit)

<details><summary>sudo journalctl -b -t kata-runtime</summary>
<p>
-- Logs begin at Sat 2020-11-07 20:36:00 UTC, end at Thu 2020-11-12 20:15:25 UTC. --
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.109923752Z" level=info msg="loaded configuration" arch=amd64 command=create file=/opt/kata/share/defaults/kata-containers/configuration-qemu-virtiofs.toml format=TOML name=kata-runtime pid=4931 source=katautils
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.111126114Z" level=info arch=amd64 arguments="\"create --bundle /run/containerd/io.containerd.runtime.v1.linux/moby/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 --pid-file /run/containerd/io.containerd.runtime.v1.linux/moby/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/init.pid 7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2\"" command=create commit=984ccea48a1badd2863a68f91c8d95e229898095 name=kata-runtime pid=4931 source=runtime version=1.11.1
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.115401526Z" level=info msg="shm-size detected: 67108864" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=oci
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.117664846Z" level=info msg="create netns" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime netns=/var/run/netns/cnitest-e6c7fe0a-0036-d82c-8fdc-32e07846a1e3 pid=4931 source=katautils
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.277894969Z" level=info msg="adding volume" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qemu volume-type=virtio-fs
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.282396583Z" level=info msg="Endpoints found after scan" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 endpoints="[0xc0002c5900]" name=kata-runtime pid=4931 source=virtcontainers subsystem=network
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.283722999Z" level=info msg="Attaching endpoint" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 endpoint-type=virtual hotplug=false name=kata-runtime pid=4931 source=virtcontainers subsystem=network
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.339055357Z" level=info msg="Starting VM" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 sandbox=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 source=virtcontainers subsystem=sandbox
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.344282028Z" level=info msg="Adding extra file [0xc0000b7498 0xc0000b7480]" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qmp
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.344504109Z" level=info msg="launching /opt/kata/bin/qemu-virtiofs-system-x86_64 with: [-name sandbox-7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 -uuid 7403e2ff-0a84-44cc-b8c2-f5bcdd7cd934 -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=8874M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,disable-modern=false,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/opt/kata/share/kata-containers/kata-containers-image_clearlinux_1.11.1_agent_34a000d0cf.img,size=134217728 -device virtio-scsi-pci,id=scsi0,disable-modern=false,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng-pci,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/kata.sock,server,nowait -chardev socket,id=char-ce233ba334bedd36,path=/run/vc/vm/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/vhost-fs.sock -device vhost-user-fs-pci,chardev=char-ce233ba334bedd36,tag=kataShared,romfile= -netdev tap,id=network-0,vhost=on,vhostfds=3,fds=4 -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02,disable-modern=false,mq=on,vectors=4,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -object memory-backend-file,id=dimm1,size=2048M,mem-path=/dev/shm,share=on -numa node,memdev=dimm1 -kernel /opt/kata/share/kata-containers/vmlinuz-virtio-fs-dev-73-virtiofs -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro ro rootfstype=ext4 quiet systemd.show_status=false panic=1 nr_cpus=4 agent.use_vsock=false systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket scsi_mod.scan=none -pidfile /run/vc/vm/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/pid -smp 1,cores=1,threads=1,sockets=4,maxcpus=4]" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qmp
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.565562857Z" level=info msg="{\"QMP\": {\"version\": {\"qemu\": {\"micro\": 0, \"minor\": 1, \"major\": 4}, \"package\": \"kata-static\"}, \"capabilities\": [\"oob\"]}}" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qmp
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.565904027Z" level=info msg="QMP details" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 qmp-capabilities=oob qmp-major-version=4 qmp-micro-version=0 qmp-minor-version=1 source=virtcontainers subsystem=qemu
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.566046418Z" level=info msg="{\"execute\":\"qmp_capabilities\"}" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qmp
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.566708034Z" level=info msg="{\"return\": {}}" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qmp
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.566966655Z" level=info msg="sanner return error: read unix @->/run/vc/vm/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/qmp.sock: use of closed network connection" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qmp
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.567100058Z" level=info msg="VM started" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 sandbox=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 source=virtcontainers subsystem=sandbox
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.579695844Z" level=info msg="proxy started" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 proxy-pid=4999 proxy-url="unix:///run/vc/sbs/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/proxy.sock" sandbox=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 source=virtcontainers subsystem=kata_agent
Nov 12 20:02:42 performance kata-runtime[4931]: time="2020-11-12T20:02:42.579920354Z" level=info msg="New client" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 proxy=4999 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/proxy.sock"
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.510080617Z" level=info msg="New client" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 proxy=4999 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/proxy.sock"
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.522786416Z" level=info msg="New client" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 proxy=4999 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/proxy.sock"
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.527601284Z" level=info msg="New client" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 proxy=4999 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/proxy.sock"
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.548367597Z" level=info msg="Agent started in the sandbox" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 sandbox=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 source=virtcontainers subsystem=sandbox
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.549193971Z" level=info msg="New client" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 proxy=4999 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/proxy.sock"
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.553939512Z" level=info msg="device details" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 device-major=0 device-minor=53 mount-point=/var/lib/docker/overlay2/8e00b413da1de591b1b7cdf941d3dce9917eba8c048348937cb903996e5c11ae/merged name=kata-runtime pid=4931 sandbox=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 source=virtcontainers subsystem=container
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.554177485Z" level=info msg="normal attach devices" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 devices="[]" machine_type=pc name=kata-runtime pid=4931 sandbox=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 source=virtcontainers subsystem=container
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.555707385Z" level=info msg="Using sandbox shm" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 shm-size=67108864 source=virtcontainers subsystem=kata_agent
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.557436834Z" level=info msg="New client" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 proxy=4999 source=virtcontainers subsystem=kata_agent url="unix:///run/vc/sbs/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/proxy.sock"
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.638979472Z" level=info msg="{\"QMP\": {\"version\": {\"qemu\": {\"micro\": 0, \"minor\": 1, \"major\": 4}, \"package\": \"kata-static\"}, \"capabilities\": [\"oob\"]}}" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qmp
Nov 12 20:02:43 performance kata-runtime[4931]: time="2020-11-12T20:02:43.639292566Z" level=info msg="{\"execute\":\"qmp_capabilities\"}" arch=amd64 command=create container=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 name=kata-runtime pid=4931 source=virtcontainers subsystem=qmp
</p>
</details>

<details><summary>sudo journalctl -b -t kata-proxy</summary>
<p>
-- Logs begin at Sat 2020-11-07 20:36:00 UTC, end at Thu 2020-11-12 20:15:46 UTC. --
Nov 12 20:03:22 performance kata-proxy[6816]: time="2020-11-12T20:03:22.826592081Z" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/3f2d42503017811007afffe31301606e367046951a5074309f521bcb78d75fb8/kata.sock: use of closed network connection" name=kata-proxy pid=6816 sandbox=3f2d42503017811007afffe31301606e367046951a5074309f521bcb78d75fb8 source=proxy
Nov 12 20:03:22 performance kata-proxy[13770]: time="2020-11-12T20:03:22.865841106Z" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/5824ac815a3be8825773825d2890c6a2b3908d6a74ccd285d2f7b74b51206ff8/kata.sock: use of closed network connection" name=kata-proxy pid=13770 sandbox=5824ac815a3be8825773825d2890c6a2b3908d6a74ccd285d2f7b74b51206ff8 source=proxy
Nov 12 20:03:23 performance kata-proxy[4999]: time="2020-11-12T20:03:23.027134358Z" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2/kata.sock: use of closed network connection" name=kata-proxy pid=4999 sandbox=7cfc26aa37f64ce6237f166493a8e01db63b82564829890ab227840b77d7e7b2 source=proxy
Nov 12 20:03:23 performance kata-proxy[11181]: time="2020-11-12T20:03:23.182813225Z" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/5f8194db6b90233b2dab8b93d1105accff24c681208c641d9ee5db57927c524f/kata.sock: use of closed network connection" name=kata-proxy pid=11181 sandbox=5f8194db6b90233b2dab8b93d1105accff24c681208c641d9ee5db57927c524f source=proxy
Nov 12 20:03:23 performance kata-proxy[10162]: time="2020-11-12T20:03:23.268476121Z" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/0c1bb348c7c9b901964a63e764285483d30e463774f1d552e0b317daff8ba7dc/kata.sock: use of closed network connection" name=kata-proxy pid=10162 sandbox=0c1bb348c7c9b901964a63e764285483d30e463774f1d552e0b317daff8ba7dc source=proxy
Nov 12 20:03:23 performance kata-proxy[12741]: time="2020-11-12T20:03:23.373725415Z" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/b1c85ab4fef389805cd25668cb86eb9e05fb1d3ad2cc3f04cefb36cade3abb55/kata.sock: use of closed network connection" name=kata-proxy pid=12741 sandbox=b1c85ab4fef389805cd25668cb86eb9e05fb1d3ad2cc3f04cefb36cade3abb55 source=proxy
Nov 12 20:03:23 performance kata-proxy[8609]: time="2020-11-12T20:03:23.382694222Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/02707e4d07a1197e6c8e3f19a297fe71ebf6db338fdd9cbd5b15b540c3e91db3/proxy.sock: use of closed network connection" name=kata-proxy pid=8609 sandbox=02707e4d07a1197e6c8e3f19a297fe71ebf6db338fdd9cbd5b15b540c3e91db3 source=proxy
Nov 12 20:03:23 performance kata-proxy[11699]: time="2020-11-12T20:03:23.45694597Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/127b3d3d26bef2bee0841edfb24c8e0c21727f776cc47abacc6a7b7196abc632/proxy.sock: use of closed network connection" name=kata-proxy pid=11699 sandbox=127b3d3d26bef2bee0841edfb24c8e0c21727f776cc47abacc6a7b7196abc632 source=proxy
Nov 12 20:03:23 performance kata-proxy[13512]: time="2020-11-12T20:03:23.646975554Z" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/a66214cd86f3868a7cc13fc620e58d22088e8fd08bdb4d4c22f9f7503449cf25/kata.sock: use of closed network connection" name=kata-proxy pid=13512 sandbox=a66214cd86f3868a7cc13fc620e58d22088e8fd08bdb4d4c22f9f7503449cf25 source=proxy
Nov 12 20:03:23 performance kata-proxy[12992]: time="2020-11-12T20:03:23.694662443Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/0cd442280959f625425da86743a1de1ce4ccdb9275a818576605e167ec75e04f/proxy.sock: use of closed network connection" name=kata-proxy pid=12992 sandbox=0cd442280959f625425da86743a1de1ce4ccdb9275a818576605e167ec75e04f source=proxy
Nov 12 20:03:23 performance kata-proxy[8361]: time="2020-11-12T20:03:23.77124778Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/3bb5ec398fa51d5321f00a9b44123e7421fd64caa3a9631b8baebe970a607c82/proxy.sock: use of closed network connection" name=kata-proxy pid=8361 sandbox=3bb5ec398fa51d5321f00a9b44123e7421fd64caa3a9631b8baebe970a607c82 source=proxy
Nov 12 20:03:23 performance kata-proxy[5518]: time="2020-11-12T20:03:23.832789155Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/aaf6f092fb13901c42e334b627d5d7c2c059a0fdbf6dbc7a05918c7b8c0f2b56/proxy.sock: use of closed network connection" name=kata-proxy pid=5518 sandbox=aaf6f092fb13901c42e334b627d5d7c2c059a0fdbf6dbc7a05918c7b8c0f2b56 source=proxy
Nov 12 20:03:24 performance kata-proxy[11961]: time="2020-11-12T20:03:24.062290392Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/9e6190ebaec174e6365087d096eb80d619896c2a2e36a19cec31b734884a4ad0/proxy.sock: use of closed network connection" name=kata-proxy pid=11961 sandbox=9e6190ebaec174e6365087d096eb80d619896c2a2e36a19cec31b734884a4ad0 source=proxy
Nov 12 20:03:24 performance kata-proxy[11441]: time="2020-11-12T20:03:24.147660765Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/073cae700fcc456f35718d766545b087e413811dc0f4ef8a9043fb4971b6832a/proxy.sock: use of closed network connection" name=kata-proxy pid=11441 sandbox=073cae700fcc456f35718d766545b087e413811dc0f4ef8a9043fb4971b6832a source=proxy
Nov 12 20:03:24 performance kata-proxy[12218]: time="2020-11-12T20:03:24.148876816Z" level=fatal msg="channel error" error="accept unix /run/vc/sbs/b97d67c95b24a8f04a1b23c98c5abccb216399a1091aabbc1013a6e48470afc0/proxy.sock: use of closed network connection" name=kata-proxy pid=12218 sandbox=b97d67c95b24a8f04a1b23c98c5abccb216399a1091aabbc1013a6e48470afc0 source=proxy
</p>
</details>

 \
Thank you for your patience @devimc !

**Comment by devimc** [comment]
thanks @DavideAG but I don't see any error in the logs :disappointed: 
could you [enable full debug](https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#enable-full-debug) and try again?
Thanks

**Comment by devimc** [comment]
thanks @DavideAG let me look at kata-proxy.txt and kata-runtime.txt

**Comment by devimc** [comment]
Thanks again @DavideAG -  @dagrh @jcvenegas @likebreath  do you know if this is a known (scalability) issue in qemu-virtiofs?

**Comment by dagrh** [comment]
Hmm, not sure; do you know what parameters are being passed to the virtiofsd?  I'd be tempted to try --thread-pool-size=1 to reduce the default number of threads each virtiofsd is taking.

**Comment by DavideAG** [comment]
@dagrh Thank you for your interest. I tried to change the default number of threads of virtiofsd but where no improvements after running again the test. I tried to restart the system too but the result is the same.\
In particular I added: `virtio_fs_extra_args = ["--thread-pool-size=1"]` in the virtiofs configuration file. (in my case is located in `/opt/kata/share/defaults/kata-containers/configuration-qemu-virtiofs.toml`) \
\
Another strange thing is that when I execute the command to create the 32nd container (using the docker `-d` flag), the error is launched but immediately afterwards the id of the container (that is not created) is printed by docker to the stdout.

**Comment by c3d** [comment]
@devimc @dagrh Looking at the initial graph, memory usage with kata-qemu seems to be three times that of kata-qemu-virtiofs. Is that expected? Is 9p that much of a memory hog?

**Comment by DavideAG** [comment]
@c3d thank you for your interest. The memory usage of k9 seems to be twice as much as virtiofs. \
Here another little memory on the same configuration test:

<details><summary>test_mem.sh</summary>
<p>

```
#!/bin/bash

file="$3"
echo -n "" > $file

for i in $(seq "$2")
do
	sudo docker run --runtime=$1 -id alpine
	mem_usage=$(free | awk '/Mem/{printf("%.3f"), $3/$2*100}')
	echo "$i - mem usage = $mem_usage%" >> $file
done

sudo docker stop $(sudo docker ps -aq) > /dev/null
sudo docker rm $(sudo docker ps -aq) > /dev/null
echo "Done."
```

</p>
</details>

Using `sudo ./test_mem.sh kata-qemu 30 kata-qemu.dat`
<details><summary>kata-qemu.dat</summary>
<p>

```
1 - mem usage =  5.397%
2 - mem usage =  7.135%
3 - mem usage =  8.868%
4 - mem usage =  10.596%
5 - mem usage =  12.340%
6 - mem usage =  14.058%
7 - mem usage =  15.796%
8 - mem usage =  17.530%
9 - mem usage =  19.265%
10 - mem usage =  21.000%
11 - mem usage =  22.736%
12 - mem usage =  24.464%
13 - mem usage =  26.200%
14 - mem usage =  27.925%
15 - mem usage =  29.667%
16 - mem usage =  31.402%
17 - mem usage =  33.143%
18 - mem usage =  34.903%
19 - mem usage =  36.638%
20 - mem usage =  38.350%
21 - mem usage =  40.111%
22 - mem usage =  41.858%
23 - mem usage =  43.589%
24 - mem usage =  45.326%
25 - mem usage =  47.047%
26 - mem usage =  48.702%
27 - mem usage =  50.394%
28 - mem usage =  52.048%
29 - mem usage =  53.683%
30 - mem usage =  55.398%
```
</p>
</details>


Using `sudo ./test_mem.sh kata-qemu-virtiofs 30 kata-qemu-virtiofs.dat`
<details><summary>kata-qemu-virtiofs.dat</summary>
<p>

```
1 - mem usage =  4.319
2 - mem usage =  4.928
3 - mem usage =  5.568
4 - mem usage =  6.203
5 - mem usage =  6.825
6 - mem usage =  7.464
7 - mem usage =  8.098
8 - mem usage =  8.735
9 - mem usage =  9.344
10 - mem usage =  9.979
11 - mem usage =  10.616
12 - mem usage =  11.248
13 - mem usage =  11.898
14 - mem usage =  12.530
15 - mem usage =  13.171
16 - mem usage =  13.806
17 - mem usage =  14.444
18 - mem usage =  15.081
19 - mem usage =  15.712
20 - mem usage =  16.353
21 - mem usage =  16.980
22 - mem usage =  17.626
23 - mem usage =  18.260
24 - mem usage =  18.908
25 - mem usage =  19.552
26 - mem usage =  20.182
27 - mem usage =  20.837
28 - mem usage =  21.479
29 - mem usage =  22.125
30 - mem usage =  22.765
```

</p>
</details>

**Comment by DavideAG** [comment]
As reported [here](https://github.com/kata-containers/documentation/blob/master/how-to/how-to-use-virtio-fs-with-kata.md#pre-requisites) it is necessary to change the size of `/dev/shm` on the system. Thanks to all, I'm closing this issue.
