### ISSUE TITLE
`Intel RDT` not supported by `events` cli 

### ISSUE THREAD

**Issue by jshachm** [kata-containers/runtime#309]
#299 Implement the kata-runtime events cli.

However, kata-runtime events cli doesn't fully support `intel RDT` stats by now.
It only supports generic `cgroups stats`.

**Comment by WeiZhang555** [comment]
Intel RDT isn't supported in virtualization environment as I know, so I doubt if we can support it in the kata-container level(inside VM).

**Comment by sboeuf** [comment]
Yeah forget the Intel RDT for now since it cannot be virtualized, hence it cannot be used inside the VM by libcontainer.

**Comment by chavafg** [comment]
should we close this one?
