### ISSUE TITLE
Enabling sangbox_cgroup_only causes the creation of pods with small memory.limits settings to fail

### ISSUE THREAD

**Issue by Bevisy** [kata-containers/runtime#3145]
Enabling sandbox_cgroup_only will add VM processes etc. to the pod's cgroups, when setting Pod a small resource.limits.memory, e.g. 50MiB, will cause the VM to fail to start. 
Or set a larger value, for example 2GiB, the container will be OOM during actual use, even if the container is not used to the limit value.
Should we consider adding vm's quota to cgroupfs?

**Comment by ariel-adam** [comment]
@Bevisy could you please provide the relevant logs so we can see what's going on? 
Running kata-collect-data.sh

**Comment by devimc** [comment]
this is is expected since kata needs more than 50M of ram to run, please consider using Pod Overhead https://kubernetes.io/docs/concepts/scheduling-eviction/pod-overhead/
