### ISSUE TITLE
Manually hot-plugged interfaces don't work

### ISSUE THREAD

**Issue by networkop** [kata-containers/runtime#3164]
I'm trying to test the network interface [hot-plug functionality](https://github.com/kata-containers/documentation/blob/master/design/architecture.md#network-hotplug) with kata and docker.

I create two docker containers with kata-runtime, and interconnect them manually, i.e. by creating a veth link and `ip link set netns` each side to each individual namespace. As the result I do see them with `ip netns exec <name> ip link` command, but they are not plugged into the VM.

I'm not sure if this is supposed to work if kata relies on interfaces being added by CNM/CNI?

**Comment by egernst** [comment]
I think you’ll want to take a look at Kata-netmon. If you add multiple devices at pod creation time, it’ll work fine. For network hotplug, you’ll need a service that is looking for net link events in the netns. I believe that’s what the intention of kata-netmon is. 

I haven’t tested this recently - there may be gaps in 2.0 release in supporting this. It should be working with 1.x branch. https://github.com/kata-containers/kata-containers/issues/1154

**Comment by networkop** [comment]
Awesome :tada:  I just enabled netmon in kata's configuration file and it worked!
Thanks heaps @egernst
