### ISSUE TITLE
qemu seccomp support

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#327]
QEMU enforces a seccomp-bpf syscall blacklist when started with [`-sandbox on` option](https://github.com/qemu/qemu/blob/7a9180b77eca258ab418ec00ab397392e70e55d9/qemu-options.hx#L3819). We may want to enable it to get an extra layer of protection with less attack interfaces. It comes with some performance cost and we can enable `/proc/sys/net/core/bpf_jit_enable` to reduce the impact.

**Comment by WeiZhang555** [comment]
Security is always welcome :smile: 
As I know, the performance cost brought by `seccomp` is often expensive, so a little bit worried about it too.
