### ISSUE TITLE
build: Make generate configuration.toml with both initrd and image path

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#332]
# Description of problem
Make generate configuration.toml with both initrd and image path
When this config is used  is not "ready" to use because the runtime require that only image or initrd is defined. 

Today an extra step is done 

https://github.com/kata-containers/tests/blob/master/.ci/install_runtime.sh#L51 
https://github.com/kata-containers/packaging/blob/master/runtime/kata-runtime.spec-template#L94

# Expected result
 make should generate a configure ready to use 

# Actual result

configuration file has both paths , so it is needed to modify it after generation.

---

We should have makefile variable  DEFAULT_INITRD(?) to configure the runtime to use initrd else an image

**Comment by jcvenegas** [comment]
ping @jodh-intel @bergwolf

**Comment by jodh-intel** [comment]
This issue has been discussed previously: https://github.com/kata-containers/runtime/pull/98#issuecomment-376431565

/cc @grahamwhaley, @egernst, @bergwolf.

**Comment by grahamwhaley** [comment]
Yep, I think everybody agrees it should generate a working 'out of the box' config file - the only decision to make afaik is which image/initrd is the default...
As I think most folks would make their choice based on their previous uses (from CC and runv), then I think the sane way to make a choice is to examine if there are technical merits to each case, and choose based on that.

**Comment by bergwolf** [comment]
How about commenting the initrd option by default? But please keep its actual contents so that user can enable it by just removing the leading `#` instead of having to try to look for the initrd image by hand. And we can add some comment to mention that only one of `initrd` and `image` option can be set.

**Comment by bergwolf** [comment]
@grahamwhaley I believe there is value in both cases. The initrd is small to ship and load, while raw image allows for DAX and do not need to be fully loaded into the guest memory. I guess we need a HOWTO somewhere to guide users to choose each of the config options :-)

**Comment by grahamwhaley** [comment]
I think you won't get any objection from the ex-CC folks on that :-)
@jcvenegas - does osbuilder generate a .img by default - maybe it makes sense to align the config file with the default osbuilder generation, in which case commenting out the initrd would be the right thing to do.
And, yes, +1 for commenting out the line, not deleting it, and also for adding an extra comment noting you can only have one of them enabled at a time (which I believe we now check in the code as well).

**Comment by jodh-intel** [comment]
Defaulting to having `image=` enabled and `initrd=` disabled but present in the config file wfm.

**Comment by jodh-intel** [comment]
osbuilder doesn't "take sides" - if you run `make` it builds both :smile:

Helpfully, I think that once we've made this change we can avoid updating the dev guide due to the current careful wording:

- https://github.com/kata-containers/documentation/blob/master/Developer-Guide.md#configure-to-use-initrd-or-rootfs-image
