### ISSUE TITLE
DESTDIR is ignored

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#337]
# Description of problem

`make install DESTDIR=${foobar}` is supposed to install all artifacts in dest dir ${foobar}.

# Expected result

All artifacts are installed under ${foobar}

# Actual result

Only kata-collect-data.sh is installed at ${foobar}

**Comment by sboeuf** [comment]
I am always in favor of removing things if we don't need them :)

**Comment by WeiZhang555** [comment]
https://github.com/kata-containers/runtime/pull/402 is trying resolve this issue.
