### ISSUE TITLE
Error in the example "Preparing and running a sandbox"

### ISSUE THREAD

**Issue by ZeroMagic** [kata-containers/runtime#339]
# Description of problem

Following the example [https://github.com/kata-containers/runtime/blob/master/virtcontainers/documentation/api/1.0/api.md#examples](https://github.com/kata-containers/runtime/blob/master/virtcontainers/documentation/api/1.0/api.md#examples), 
I use the latest code to run sandbox. 

# Expected result

No error return.

# Actual result

It returns me the error "_unknown field 'VCPUs' in struct literal of type virtcontainers.Resources_". 
Then I find there is really no "VCPUs" in "Resources". Here is the struct.[https://github.com/kata-containers/runtime/blob/master/virtcontainers/sandbox.go#L297](https://github.com/kata-containers/runtime/blob/master/virtcontainers/sandbox.go#L297).

Is the field 'VCPUs' abandoned now ?

**Comment by caoruidong** [comment]
Yes. Please see https://github.com/containers/virtcontainers/commit/c3ad9c2e54b71ebac259125d77011f6d44340b19. Now virtcontainers is a part of kata-containers, welcome to use kata directly.

**Comment by ZeroMagic** [comment]
Thx.
