### ISSUE TITLE
Facing issue while installing katacontainer runtime.

### ISSUE THREAD

**Issue by dungeonmaster18** [kata-containers/runtime#34]
I was trying to install katacontainer runtime and I got this issue
```
./configure: line 4360: syntax error near unexpected token `LIBVIRT,'
./configure: line 4360: `       PKG_CHECK_MODULES(LIBVIRT, libvirt >= $LIBVIRT_REQUIRED, , with_libvirt=no)'
Makefile:53: recipe for target 'build' failed
make: *** [build] Error 2
```
I have no idea how to solve this.

**Platform**
aws ubuntu instance

**KATA_RUNTIME**
runv

**Comment by grahamwhaley** [comment]
Hi @dungeonmaster18 . A few questions and notes:

- Ah, I've just spotted you are talking about `runv` runtime (I was about to ask). I'll /cc @gnawux to get to the right folks.

- Either way, it seems like `libvirt` is not installed on your ubuntu - something along the lines of `apt-get install libvirt` is probably what you need to get it installed

- But, before you take those steps - can I check if your AWS instance supports nested virtualization? I believe most do not?, but some of the higher end instances (like the bare metal ones) do - see https://aws.amazon.com/blogs/aws/new-amazon-ec2-bare-metal-instances-with-direct-access-to-hardware/ for more info in this area. If your instance does not support nested virtualisation, then even if you do manage to build the runtime, you will not be able to execute it.

For reference, we have executed the runtime on both Azure and GCE instances that have supported nested virtualisation.

I hope that helps?

**Comment by dungeonmaster18** [comment]
Libvirt was installed but i my instance doesn't support nested virtualization.

**Comment by dungeonmaster18** [comment]
Hey @grahamwhaley now I have installed katacontainers on local machine evrything went smooth. Bu now when i am trying to run container it gives me this error
```
$ sudo docker run -ti --runtime kata-runtime hello-world
docker: Error response from daemon: OCI runtime create failed: unable to retrieve OCI runtime error (open /run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/b05eb301240dfec82df74f0c732f4b6d90f1b12b437e0ce4a9a539c9384b5c31/log.json: no such file or directory): /usr/local/bin/kata-runtime did not terminate sucessfully: Unsupported driver ""

NAME:
   kata-runtime create - create a container

USAGE:
   kata-runtime create [command options] <container-id>

Where "<container-id>" is your name for the instance of the container that you
are creating. The name you provide for the container instance must be unique on
your host.

DESCRIPTION:
   The create command creates an instance of a container for a bundle. The bundle
is a directory with a specification file named "config.json" and a root
filesystem.

The specification file includes an args parameter. The args parameter is used
to specify command(s) that get run when the container is started. To change the
command(s) that get executed on start, edit the args parameter of the spec. See
"runv spec --help" for more explanation.

OPTIONS:
   --bundle value, -b value  path to the root of the bundle directory, defaults to the current directory (default: "/run/docker/containerd/daemon/io.containerd.runtime.v1.linux/moby/b05eb301240dfec82df74f0c732f4b6d90f1b12b437e0ce4a9a539c9384b5c31")
   --console value           specify the pty slave path for use with the container
   --console-socket value    specify the unix socket for sending the pty master back
   --pid-file value          specify the file to write the process id to
   --no-pivot                [ignore on runv] do not use pivot root to jail process inside rootfs.  This should be used whenever the rootfs is on top of a ramdisk
   
ERROR: logging before flag.Parse: E0216 07:33:58.315401   19805 main.go:158] app.Run(os.Args) failed with err: &errors.errorString{s:"Unsupported driver \"\""}
Unsupported driver ""
: unknown.

```
Here is the output for ```docker info```
```
Containers: 6
 Running: 0
 Paused: 0
 Stopped: 6
Images: 9
Server Version: 18.01.0-ce
Storage Driver: overlay2
 Backing Filesystem: extfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file logentries splunk syslog
Swarm: inactive
Runtimes: kata-runtime runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 89623f28b87a6004d4b785663257362d1658a729
runc version: b2567b37d7b75eb4cf325b77297b140ea686ce8f
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.13.0-32-generic
Operating System: Ubuntu 16.04.3 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.658GiB
Name: containerd
ID: UKZB:UF2I:GSUA:QCJN:KMNR:YCVF:2I4K:KHQR:U3R2:PXNV:HHZP:CEXB
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 20
 Goroutines: 32
 System Time: 2018-02-16T07:34:46.051419215-05:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

WARNING: No swap limit support

```

ABove it clearly shows I have kata-runtime but I am still getting error.

**Comment by grahamwhaley** [comment]
Hi @dungeonmaster18  - some progress :-)
Just to check, I presume you have been following the guide here: https://github.com/kata-containers/documentation/wiki/Developer-Guide ?

@chavafg @sboeuf - does that error look at all familiar? A very brief scan shows docker v18.x - not sure if we've tried that version ?

**Comment by egernst** [comment]
This doesn't look familiar to me, but I haven't been testing on runv yet.  I think most of the relevant engineers are still on CNY.

**Comment by dungeonmaster18** [comment]
Yes @grahamwhaley I am using that guide only.

**Comment by grahamwhaley** [comment]
Ah, good point(s) @egernst 
@dungeonmaster18  - to check, did you use the 'cc' or 'runv' runtime?
If runv, we will need input from others like @gnawux  = who are on ChineseNewYear holidays (CNY ;-))

**Comment by dungeonmaster18** [comment]
Oh okay. @grahamwhaley I am using runv.

**Comment by caoruidong** [comment]
You can use kata without cc and runv now

**Comment by dungeonmaster18** [comment]
Hey thanks. Sure I will give a try.

**Comment by dungeonmaster18** [comment]
@jodh-intel I given the try to new kata-containers. I got the following error. I tried finding the solution but couldn't.
```
docker: Error response from daemon: OCI runtime create failed: qemu-system-x86_64: Property '.nvdimm' not found: unknown.
```

**Comment by egernst** [comment]
@dungeonmaster18 this is because the CI / directions uses a different QEMU version.  Can you verify everything works well if you update /usr/share/defaults/kata-runtime/configuration.toml to point to qemu-lite-* instead of qemu-* ?

**Comment by devimc** [comment]
@dungeonmaster18  `qemu-system-x86_64: Property '.nvdimm' not found: unknown.`, means that you are using an old version of qemu (2.6 might be...), ensure your qemu version is >= 2.7

**Comment by dungeonmaster18** [comment]
Hey Thanks @egernst it solved the problem. Closing the issue
