### ISSUE TITLE
Isolate hypervisor process through namespaces

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#345]
The hypervisor process is responsible of taking care of the VMs, and if a security breach was related to the hypervisor itself, it could give a way for a VM to escape.
In order to increase the security, we should isolate the hypervisor process leveraging namespaces on the host.
For now, it only runs inside the network namespace, but the mount namespace and other namespaces could be relevant.

**Comment by jodh-intel** [comment]
We could also investigate `-runas $user`.

**Comment by sboeuf** [comment]
@jodh-intel yeah we should be able to start Qemu (or the hypervisor I should say) without being root. As long as the user is into the appropriate group and as long as we have enough caps to interact with /dev/kvm, this should be enough.

**Comment by WeiZhang555** [comment]
> yeah we should be able to start Qemu (or the hypervisor I should say) without being root

This sounds like an interesting idea, putting hypervisor into net/mount namespace could be beneficial, but not sure about others(PID/IPC/UTS/USER namespaces)

**Comment by sboeuf** [comment]
@kata-containers/runtime This issue should be looked at in order to increase security around the VM process. Please assign it to yourself if interested in it.

**Comment by chavafg** [comment]
@devimc are you still taking a look into this?

**Comment by devimc** [comment]
@chavafg nop, since it's really difficult to implement because of Go

**Comment by mcastelino** [comment]
@devimc @egernst along the lines of how we added support for jailer in firecracker it may be possible to use `runc` as the jailer for the VMM. The firecracker jailer itself is quite restrictive and may not be a fit for the more generalized use case. I have not spent too much time exploring this though.

In the case of `jailer` we invoke the standalone `jailer` binary to confine the firecracker VMM.
