### ISSUE TITLE
Ubuntu source kata doesn't have config file

### ISSUE THREAD

**Issue by teawater** [kata-containers/runtime#359]
# Description of problem
Install kata according to https://github.com/kata-containers/documentation/blob/master/install/ubuntu-installation-guide.md
Cannot find kata config file.

root@ubuntu:~# which kata-runtime
/usr/bin/kata-runtime
root@ubuntu:~# ls -al /etc/kata*
ls: cannot access '/etc/kata*': No such file or directory
root@ubuntu:~# ls -al /usr/share/kata-containers/
total 562532
drwxr-xr-x   2 root root      4096 Jun  1 00:18 .
drwxr-xr-x 342 root root     12288 Jun  1 00:18 ..
-rwxr-xr-x   1 root root 536870912 May 21 19:25 kata-containers-image_clearlinux_agent_a099747.img
lrwxrwxrwx   1 root root        50 May 21 19:25 kata-containers.img -> kata-containers-image_clearlinux_agent_a099747.img
-rwxr-xr-x   1 root root   8991400 May 21 19:25 kata-containers-initrd_alpine_agent_a099747.initrd
lrwxrwxrwx   1 root root        50 May 21 19:25 kata-containers-initrd.img -> kata-containers-initrd_alpine_agent_a099747.initrd
-rwxr-xr-x   1 root root  25206088 May 29 08:24 vmlinux-4.14.22.1-128.container
lrwxrwxrwx   1 root root        31 May 29 08:24 vmlinux.container -> vmlinux-4.14.22.1-128.container
-rwxr-xr-x   1 root root   4939904 May 29 08:24 vmlinuz-4.14.22.1-128.container
lrwxrwxrwx   1 root root        31 May 29 08:24 vmlinuz.container -> vmlinuz-4.14.22.1-128.container

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by jodh-intel** [comment]
Hi @teawater - is this still a problem or can we close this?

**Comment by teawater** [comment]
Thanks @jodh-intel 
I found it in /usr/share/defaults/kata-containers/configuration.toml
