### ISSUE TITLE
ppc64le: Restrict maxmem to avoid  HTAB allocation failure

### ISSUE THREAD

**Issue by nitkon** [kata-containers/runtime#363]
# Description of problem

PowerPC guests need a data structure called HTAB (hash table) that stores the virtual to physical page mappings for the guest. HTAB for guest is allocated by the host in host contiguous memory area (CMA) which is a limited resource (by default 5% of host RAM is CMA region). All guests running in the host get their HTAB allocated from this CMA region. HTAB size depends on the maxmem size and specifying huge values of maxmem for guest could result in failures like below:

qemu-system-ppc64 … -m 4G,slots=32,maxmem=1T
qemu-system-ppc64: Failed to allocate HTAB of requested size, try with smaller maxmem
Aborted

In such cases lowering the maxmem is recommended.

# Expected result
```
docker run -it --runtime kata-runtime busybox /bin/sh
/ # 
```
# Actual result
```
docker run -it --runtime kata-runtime busybox /bin/sh
docker: Error response from daemon: OCI runtime create failed: Unexpected error in spapr_alloc_htab() at /build/qemu-ozKJoj/qemu-2.5+dfsg/hw/ppc/spapr.c:1030:
qemu-system-ppc64: Failed to allocate HTAB of requested size, try with smaller maxmem: unknown.
```
---

**Comment by mpe** [comment]
This is supposed to have been fixed in upstream kernel/qemu.

The qemu support was merged in qemu 2.10, and the kernel support in 4.11.

Is there some reason that's not working for you?

**Comment by jodh-intel** [comment]
Hi @nitkon - please could you confirm which version of qemu you're using?

You could just paste in the output of `sudo kata-collect-data.sh` (build from the runtime repo from https://github.com/kata-containers/runtime/blob/master/data/kata-collect-data.sh.in) as that will provide all details on qemu.

**Comment by jodh-intel** [comment]
Re-opening until we understand this issue more fully...

**Comment by nitkon** [comment]
@jodh-intel : When I hit this issue, I was using the following version of qemu.
```QEMU emulator version 2.5.0 (Debian 1:2.5+dfsg-5ubuntu10.25), Copyright (c) 2003-2008 Fabrice Bellard```

**Comment by jodh-intel** [comment]
Hi @nitkon - thanks, that aligns with the info provided by @mpe. Out of interest, can you run newer versions of qemu on ppc64el with Kata?

We record the latest versions in the packaging versions database:

- https://github.com/kata-containers/packaging/blob/master/versions.txt#L15..L16

For `qemu-lite`, see:

- https://github.com/kata-containers/qemu/tree/qemu-lite-2.11.0

**Comment by nitkon** [comment]
Hi @jodh-intel : I tried kata with the latest qemu on ppc64le and it works fine without the HTAB patch. 
```
• Summary:

	binary install path (DESTTARGET)      : /usr/local/bin/kata-runtime
	config install path (DESTCONFIG)      : /usr/share/defaults/kata-containers/configuration.toml
	alternate config path (DESTSYSCONFIG) : /etc/kata-containers/configuration.toml
	hypervisor path (QEMUPATH)            : /usr/bin/qemu-system-ppc64le
	assets path (PKGDATADIR)              : /usr/share/kata-containers
	proxy+shim path (PKGLIBEXECDIR)       : /usr/libexec/kata-containers

     INSTALL install-scripts
     INSTALL install
     INSTALL install
# /usr/bin/qemu-system-ppc64le --version
QEMU emulator version 2.12.50 (v2.12.0-1104-g8e36d27-dirty)
Copyright (c) 2003-2017 Fabrice Bellard and the QEMU Project developers
# sudo sed -i 's/^\(image =.*\)/# \1/g' /usr/share/defaults/kata-containers/configuration.toml
# docker run -ti --runtime kata-runtime busybox sh
/ # exit

```

**Comment by nitkon** [comment]
@jodh-intel :  So, are we looking at anything else on this issue?

**Comment by jodh-intel** [comment]
Not from me @nitkon - let's put this one to bed again ... ;)

**Comment by mpe** [comment]
The 32GB limit is still merged though isn't it? Or is it a soft limit or something?

**Comment by bergwolf** [comment]
Yes @mpe!

@nitkon @jodh-intel, I think we should revert #364 then, wdyt?

**Comment by jodh-intel** [comment]
Reverting #364 wft. wdyt @nitkon?

**Comment by nitkon** [comment]
@mpe @jodh-intel : As this works on all qemu versions, I think we should keep it as a short-term solution at least. Going ahead we can have an enhancement patch which offers a configurable option to restrict maxmem for x86 as well as ppc64le.

Removing this restriction will currently break kata on Power. (esp: qemu versions below 2.10 )
Does x86 restrict qemu versions to be used currently?

**Comment by grahamwhaley** [comment]
afaik, the x86 qemu version restrictions are based around when nvdimm was introduced, which iirc (and I might not...) was maybe around the 2.5 version - I think @devimc would know better from a lot of experimentation with qemu versions and distribution qemu versions etc.

I agree, if there are Power QEMU versions commonly out there 'in the wild' at the moment, then you should probably keep the check (or, make it a very obvious failure case if you run into the issue).

**Comment by mpe** [comment]
Do you really support running against arbitrary qemu versions? I assumed you'd be shipping a particular version that's been tested.

**Comment by jodh-intel** [comment]
Hi @mpe - to clarify what @grahamwhaley meant by "qemu restrictions" - there are particular features we require in qemu (such as nvdimm) so the runtime is restricted to using such versions of qemu. However, the runtime itself does not perform any qemu version checks - it assumes the version of qemu configured in the config file is a usable one.

Yes, the packaged version of Kata provides a pre-configured system that uses a version of qemu  (currently [`qemu-lite`](https://github.com/kata-containers/qemu/tree/qemu-lite-2.11.0)) which has been tested and is thus known to work. See more details on qemu versions here: https://github.com/kata-containers/packaging/issues/73#issuecomment-397586987.

**Comment by mpe** [comment]
@jodh-intel OK thanks for the detail. I guess if you have no mechanism for checking the qemu version then doing the 32GB limit is preferable to not being able to start VMs. The 32GB value is totally arbitrary so I worry it is going to trip folks up, but I guess we can wait and see.

**Comment by jodh-intel** [comment]
Hi @mpe - well, to be clear, although we do not currently filter on qemu versions, we could add that trivially:

- https://github.com/kata-containers/runtime/blob/master/virtcontainers/qemu.go#L594

The 2nd value returned by `govmmQemu.QMPStart()` -- which we currently ignore -- is the QMP / Qemu version information.
