### ISSUE TITLE
Refine CPUInfo in Arm64

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/runtime#368]
# Description of problem
Thanks @jodh-intel for fixing arm build😊, and it may need some refinement for CPUInfo. 
Variable vendor and model in struct` CPUInfo` may refer to different meaning in Arm architecture. The CPU Model for Arm should mean the Instruction set, that is the variant number of Arm processor and the CPU Vendor for Arm should be the CPU core IP Implementer.

# Expected result
some example from `kata-runtime kata-env`:

 ```
 [Host.CPU]
    Vendor = "ARM Limited"
    Model = "v8"

```
# Actual result

 ```
 [Host.CPU]
    Vendor = "0x41"
    Model = "0x1"

```

**Comment by Pennyzct** [comment]
@weichen81

**Comment by Weichen81** [comment]
LGTM @Pennyzct  👍
