### ISSUE TITLE
speed up kata container creation

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#382]
# Description of problem

kata containers are created much slower than expected. On my local bare metal machine, 
- docker container is created in **900+ms**.
- [hypercontainer](https://hypercontainer.io/) (using runv) is created in about **300ms** (w/ vm templating) or in **1500ms** (w/o vm templating).
- But kata containers are always created in more than **1600ms** even if vm templating is enabled.

VM templating is supposed to reduce the time for creating a new virtual machine, which is the most time consuming part of a new container creation process. However, even with vm template support, kata container creation is still slow. It indicates that other part of the kata container creation process is using too much time unnecessarily, causing vm creation to be out of the time critical path.

# Expected result

kata containers creation should be much faster (close to hypercontainer) when vm template is supported.

# Actual result
docker container:
```
$time docker run -d busybox top
97561178fe13a1ac48aefca08c19c9363e1a20404d24c1d9a140bbeebce43ae3

real    0m0.969s
user    0m0.032s
sys     0m0.028s
```
kata containers:
```
$time docker run -d --runtime kata busybox top
eceabc0af066f9dc62a662d223d221104775c43b7b589bd65bc62f45940f8a19

real    0m1.679s
user    0m0.048s
sys     0m0.020s
```
hypercontainer w/ vm template:
```
$sudo hyperctl run -d busybox top
POD id is busybox-1163118027
Time to run a POD is 306 ms
```
hypercontainer w/o vm template:
```
$sudo hyperctl run -d busybox top
POD id is busybox-8229737402
Time to run a POD is 1533 ms
```
# Analysis
For starters, we need to look more closely at kata containers creation process and try to parallel more things:
- [ ] 1. network preparation and hotplug
- [ ] 2. storage preparation and hotplug
- [ ] 3. cpu/memory hotplug
- [ ] 4. shim/proxy creation

Other things to optimize imo include:
- [ ] 5. keep agent connection when possible. Right now each agent grpc call requires a new connection to be established and disconnected, which means unnecessary handshakes.
- [x] 6. keep qmp connections when possible. Right now most QMP commands require a new QMP connection, which also means unnecessary handshakes.
- [ ] 7. keep sandbox and container structure in memory when possible, so that we don't have to read disk to reconstruct them every time.
- [ ] 8. use a database rather than plain on disk json files to store metadata, which would allow less open/read/write/close cycles.

**Comment by jodh-intel** [comment]
Out of interest, have you tried running the log-parser on the debug-enabled logs to see which time delta is shows is the biggest?

- https://github.com/kata-containers/tests/tree/master/cmd/log-parser

No guarantee this will work as it is only showing the delta between log calls, but might point to something interesting?

**Comment by bergwolf** [comment]
@jodh-intel Thanks for the hint. I'll give it a try.

**Comment by grahamwhaley** [comment]
We have a simple test over in the metrics: https://github.com/kata-containers/tests/blob/master/metrics/time/launch_times.sh that uses `date` to gather some host/container metrics - it's a bit coarse and presumes `date` inside the container is in sync with that on the host.
Beyond that, I'm presuming you have done a bunch of this type of analysis on `runv` in the past - so let's share tooling :-)  We have previously used both systemd and the kernel bootchart tools to look into timings and parallelism of the boots - I don't have any scripts to hand or in the repos though.

**Comment by markdryan** [comment]
This is more or less how QMPStart is intended to be used ( and is used in other projects ).  You call QMPStart to connect to the instance, and keep the connection open, using the *QMP handle to send commands when necessary.  The advantage of doing this is that not only do you avoid having to open/close a socket and do the QMP setup on each command, but you also get notified when the instance dies and closes the socket.

**Comment by bergwolf** [comment]
From log-parser, the most time consuming ones are:

> Record 15: {Count:15 TimeDelta:63214111 Filename:/home/bergwolf/log Line:15 Time:2018-06-11 18:34:53.396205547 +0800 CST Pid:2591 Level:info Msg:{"QMP": {"version": {"qemu": {"micro": 1, "minor": 11, "major": 2}, "package": " (v2.11.0-rc0-360-g6517c9b-dirty)"}, "capabilities": []}} Source:virtcontainers Name:kata-runtime Data:map[Jun: 11: 18:34:53: vmfarm: kata-runtime[2591]:: arch:amd64 subsystem:qmp]}
Record 21: {Count:21 TimeDelta:1010662307 Filename:/home/bergwolf/log Line:21 Time:2018-06-11 18:34:54.408498249 +0800 CST Pid:2591 Level:info Msg:device details Source:virtcontainers Name:kata-runtime Data:map[subsystem:container Jun: vmfarm: kata-runtime[2591]:: arch:amd64 container-id:1d8d1d4df52b8b1ce67b18c5dc6b3bb43bf94fa9e1b3b8932192081d5b3198ac device-major:0 sandbox-id:1d8d1d4df52b8b1ce67b18c5dc6b3bb43bf94fa9e1b3b8932192081d5b3198ac 11: 18:34:54: device-minor:49 mount-point:/var/lib/docker/overlay2/a014030909c4faea5a5b42e51c498d6916aa9bdfc98046004c526804f0283159/merged]}
Record 22: {Count:22 TimeDelta:3085086 Filename:/home/bergwolf/log Line:22 Time:2018-06-11 18:34:54.411583335 +0800 CST Pid:2591 Level:debug Msg:Replacing OCI mount (/etc/resolv.conf) source /var/lib/docker/containers/1d8d1d4df52b8b1ce67b18c5dc6b3bb43bf94fa9e1b3b8932192081d5b3198ac/resolv.conf with /run/kata-containers/shared/containers/1d8d1d4df52b8b1ce67b18c5dc6b3bb43bf94fa9e1b3b8932192081d5b3198ac-ab6c3c9b83342083-resolv.conf Source:virtcontainers Name:kata-runtime Data:map[vmfarm: kata-runtime[2591]:: arch:amd64 subsystem:kata_agent Jun: 11: 18:34:54:]}
Record 25: {Count:25 TimeDelta:45371588 Filename:/home/bergwolf/log Line:25 Time:2018-06-11 18:34:54.457142894 +0800 CST Pid:2591 Level:info Msg:path mounted Source:runtime Name:kata-runtime Data:map[path:/sys/fs/cgroup/memory type:cgroup Jun: 11: 18:34:54: vmfarm: kata-runtime[2591]:: command:create]}
Record 29: {Count:29 TimeDelta:11846339 Filename:/home/bergwolf/log Line:29 Time:2018-06-11 18:34:54.469137359 +0800 CST Pid:2689 Level:info Msg:loaded configuration Source:runtime Name:kata-runtime Data:map[command:state file:/etc/kata-containers/configuration.toml format:TOML Jun: 11: 18:34:54: vmfarm: kata-runtime[2689]::]}
Record 31: {Count:31 TimeDelta:1289354 Filename:/home/bergwolf/log Line:31 Time:2018-06-11 18:34:54.470670889 +0800 CST Pid:2689 Level:debug Msg:Disable nesting environment checks Source:virtcontainers Name:kata-runtime Data:map[18:34:54: vmfarm: kata-runtime[2689]:: arch:amd64 inside-vm:false subsystem:qemu Jun: 11:]}
Record 33: {Count:33 TimeDelta:5836403 Filename:/home/bergwolf/log Line:33 Time:2018-06-11 18:34:54.477114423 +0800 CST Pid:2702 Level:info Msg:loaded configuration Source:runtime Name:kata-runtime Data:map[Jun: 11: 18:34:54: vmfarm: kata-runtime[2702]:: command:start file:/etc/kata-containers/configuration.toml format:TOML]}
Record 37: {Count:37 TimeDelta:3343788 Filename:/home/bergwolf/log Line:37 Time:2018-06-11 18:34:54.481992036 +0800 CST Pid:2702 Level:info Msg:Sandbox is started Source:virtcontainers Name:kata-runtime Data:map[arch:amd64 sandbox-id:1d8d1d4df52b8b1ce67b18c5dc6b3bb43bf94fa9e1b3b8932192081d5b3198ac subsystem:sandbox Jun: 11: 18:34:54: vmfarm: kata-runtime[2702]::]}
Record 38: {Count:38 TimeDelta:5095817 Filename:/home/bergwolf/log Line:38 Time:2018-06-11 18:34:54.487087853 +0800 CST Pid:2712 Level:info Msg:loaded configuration Source:runtime Name:kata-runtime Data:map[command:state file:/etc/kata-containers/configuration.toml format:TOML Jun: 11: 18:34:54: vmfarm: kata-runtime[2712]::]}
Record 40: {Count:40 TimeDelta:900269 Filename:/home/bergwolf/log Line:40 Time:2018-06-11 18:34:54.488162638 +0800 CST Pid:2712 Level:debug Msg:Disable nesting environment checks Source:virtcontainers Name:kata-runtime Data:map[vmfarm: kata-runtime[2712]:: arch:amd64 inside-vm:false subsystem:qemu Jun: 11: 18:34:54:]}

**Comment by jshachm** [comment]
I did a little more test on this.
And here is my input for this issue:

I try to start a native `kata-container` without any optimization, 
```
time docker run -tid --runtime kata-runtime --net=none busybox
500f07025f563c4d11fd7ed5fea5663c57e00906e36a07318a6f4ef929754f18
real    0m1.681s
```
in `runtime.log`,

these lines took my eyes:
```
time="2018-06-13T14:05:23.957639926+08:00" level=info msg="proxy started" arch=amd64 name=kata-runtime pid=54529 proxy-pid=54568
time="2018-06-13T14:05:24.964129393+08:00" level=info msg="device details" arch=amd64 container-id=5fba4fe6f597102fd39bdb599a4c1b
time="2018-06-13T14:05:24.964824386+08:00" level=info msg="Block device detected" 
```

from `proxy start` to `hotplugdrive`, it took more than 1 sec.

Will add more logs to find out where indeed the time costs.

**Comment by jshachm** [comment]
a little more input:
try to add more log to find out where the time gone, finally fount it took about 1 sec in `createSandbox`  grpc request.

and in `agent`,  there is 1 sec later than we send req to server.Maybe it's about the `init` boot and connection establish time.

Still try to find the details about it. More inputs later.

cc\ @WeiZhang555  @bergwolf

**Comment by sboeuf** [comment]
@kata-containers/runtime please assign this issue to yourself if interested in working on this.

**Comment by jodh-intel** [comment]
Related: https://github.com/kata-containers/kata-containers/issues/27.
