### ISSUE TITLE
Add support for vsocks

### ISSUE THREAD

**Issue by devimc** [kata-containers/runtime#383]
If the host supports vsocks use them to comunicate shim/runtime directly with the agent

To create a vsock a context ID must be specified, the context ID must be `> 3` and unique. Since other  processes or kata-containers can be using context IDs, we have to
- [ ] track the context IDs we are using in Kata Containers

Since we don't know the context IDs that are being used by other processes, we have to 
- [ ] check if the context ID we are about to use is free (`ioctl VHOST_VSOCK_SET_GUEST_CID`) see [VSOCK.go][1] 

even implementing above points, we might face race conditions with other processes, because of `ioctl VHOST_VSOCK_SET_GUEST_CID` doesn't lock the context ID and other process can use it before we launch the QEMU process, to avoid this issue
- [ ] `vsocks` must be hot plugged

[1]: https://github.com/devimc/kata-runtime/blob/topic/vsocks/VSOCK.go

**Comment by sboeuf** [comment]
Ah nice, that's something I was about to open because we've been advertising vsock support but never took the time to implement it and test it.

@devimc could you describe the way you're gonna implement this before your actually start the development. This is a task involving several repos, and it would be good to clarify here what needs to happen to fully support it.

**Comment by gnawux** [comment]
@jcvenegas @sboeuf following the discussion in the meeting this week, I discussed with @bergwolf. if there was nothing done in this issue, @lifupan and @bergwolf could help to add the vsock support.

**Comment by sboeuf** [comment]
It's up to @jcvenegas on this one since he started to work on it. @jcvenegas let @bergwolf and @lifupan know if you need help!

**Comment by jcvenegas** [comment]
@sboeuf @gnawux I'll be working on this,  @gnawux  @bergwolf  @lifupan I am happy to talk about any implementation idea you have.
