### ISSUE TITLE
Logo contribution

### ISSUE THREAD

**Issue by reallinfo** [kata-containers/runtime#387]
Hello!

I designed a logo for runtime. Please tell me what you think. I waiting feedback.

![runtime](https://user-images.githubusercontent.com/36298335/41293349-b182ca46-6e5d-11e8-8509-913d1cbfe263.jpg)

**Comment by bergwolf** [comment]
Maybe a naive question (sry I am not familiar with marketing), but I would wonder why we are not using the kata containers logo here. It's a bit confusing to have different logos for the same project.

**Comment by reallinfo** [comment]
Thanks community!

I designed a logo to better reflect the property of this repository. A single logo is a good idea. 

In that case,
If you need a logo for other projects,feel free to say me.

Best regards.

**Comment by annabellebertooch** [comment]
Thanks for the creative contribution, @reallinfo, but I agree with the others above--we'll stick with the one Kata logo. If you're interested in working on the marketing side of Kata, join the Working Committee meetings to get involved! Otherwise we can close this issue out.

**Comment by devimc** [comment]
Thanks @reallinfo and @annabellebertooch
