### ISSUE TITLE
Lower privileges for Kata components

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#389]
I think it would be a good exercise to go through each component and assess which one actually needs to run as root. The `kata-runtime` is run as `root`, and because it starts all the components (VM, shim, proxy), everything actually runs as root. As part of being more secure, not running the Kata components as root could be a nice thing to implement.

As a first step, there is no reason for both proxy and shim to run as root, and I think we could drop the privs before to start those binaries.

As a second step, the VM process, in this case the Qemu process, we need to access `/dev/kvm`, which we could avoid to access as a root user if we were creating a `kata-containers` user being part of the kvm group. Of course, we would need some specific capabilities for this to be able to run, but root is not strictly needed. The remaining problem is about the rootfs on the host that is shared with the VM because it does not know about the `kata-containers` user inside the VM. That's something to investigate as part of lowering the VM process privs.

**Comment by sboeuf** [comment]
_Some notes from my past experiments:_
I have been able to run Kata as __non-root__ user, and particularly the Qemu process with the shim and the proxy. I have managed to get the all of those running with a specific `kata-user` that was not __root__, but was part of the __kvm__ group to access `/dev/kvm`. Also, using `virtfs-proxy-helper` binary as a separate process running as __root__, allowed me to still modify the exported `9p` path the same way this is done right now.

We also had some feedback from the libvirt maintainers that libvirt-go should support all the use cases that Kata expects. This needs more investigations and assessment but it should not be too complicated to get this supported if we wanted to. The idea is to get a lot of support for the non root case directly supported by libvirt. But we have to make sure this would not bring a higher memory consumption. We could ask Hyper folks to look into this since they had a partial `libvirt` support for `runv`.

_Summary:_
- Increase security/Non-root experiments:
  - Access to both `/dev/kvm` and `/dev/vhost` devices can be easily solved by changing the ownership of those to a specific group. And as long as we create a specific `kata-containers` user part of this group, it could access those devices.
  - `9pfs` filesystem can be accessed by QEMU even if it's running as non-root, but it does require a process running as root to access the filesystem (`virtfs-proxy-helper`). The proxy, on behalf of QEMU, will be able to access and modify files as it is root.
  - Block devices, the same way we did with `/dev/kvm` and `/dev/vhost`, should have their ownership modified before we can access them. But the problem is that we need to keep in memory the value of previous ownership, which adds to the burden of maintaining those info.

- Thinking about supporting `libvirt`/ What could change our mind:
  -Libvirt has a go binding/package that might be very handy for Kata
  - This Go binding is complete, that is contains all the features from QEMU that Kata requires
  - Libvirt already handles the way to run QEMU as non-root (taking care of the various use cases enumerated), and would avoid to be re-implemented in Kata.

**Comment by jodh-intel** [comment]
Note that if you set `use_vsock = true` in `configuration.toml`, to run as non-`root` you also need to change perms / group of `/dev/vsock` and `/dev/vhost-vsock` on the host.

**Comment by sboeuf** [comment]
@jodh-intel yes good point!

**Comment by zeigerpuppy** [comment]
Until running as non-root is working, perhaps it may be useful to set up an AppArmour profile.  I'll look into building a profile, but if anyone else already has a starting point, that'd be much appreciated!

**Comment by jodh-intel** [comment]
Thanks @zeigerpuppy! I'm not aware of an existing apparmor profile but @devimc may have some info on this.

Ideally, we'd have profiles for both apparmor and SELinux so if there are any SELinux gurus out there...? :smile:

For SELinux, we have got the following which might be useful as a starting point:

- https://github.com/clearcontainers/proxy/tree/master/selinux
- https://github.com/clearcontainers/packaging/blob/master/clear-containers-selinux/clear-containers-selinux.spec

**Comment by grahamwhaley** [comment]
Yay - and, good luck!
afaik, we've never had an AppArmor profile for Kata. I think the links @jodh-intel provided are the best reference for any SELinux profile work done previously.
I am wondering if any of the distro folks have made profiles we can utilise? @marcov @dagrh ?
/cc @egernst @mcastelino who may also have data/input/views/interest.
