### ISSUE TITLE
Fix Jenkins build status URL 

### ISSUE THREAD

**Issue by chavafg** [kata-containers/runtime#391]
now we should point to:
http://199.204.45.34/job/kata-containers-runtime-ubuntu-16-04-master/badge/icon

**Comment by sboeuf** [comment]
@chavafg this makes sense but I think we need to understand the mid/long term plans before we change everything.

**Comment by WeiZhang555** [comment]
All PRs are blocked by the failing CI, should we merge it first to make the CI happy?
