### ISSUE TITLE
Import virtcontainers into Kata Containers runtime

### ISSUE THREAD

**Issue by sameo** [kata-containers/runtime#40]
As agreed by the community through issue #33, we have to import virtcontainers into the runtime repo.

Currently the virtcontainers code lives under https://github.com/containers/virtcontainers, and the plan is to move it from there to https://github.com/kata-containers/runtime/virtcontainers/. This will happen gradually:

1. Import the latest virtcontainers release into kata-containers/runtime
2. Set the kata-containers/runtime CI to test any kata-containers/runtime/virtcontainers/ change against github.com/clearcontainers/runtime: We can only move virtcontainers upstream if we can guarantee that it does not break Clear Containers.
3. Make the Clear Containers runtime switch to github.com/kata-containers/runtime/virtcontainers
4. Stop accepting issues and PRs on https://github.com/containers/virtcontainers
5. Import all existing virtcontainers issues and PRs into kata-containers/runtime/virtcontainers
6. Redirect https://github.com/containers/virtcontainers to https://github.com/kata-containers/runtime/

**Comment by gnawux** [comment]
I think we should decide some interfaces before we import virtcontainers as discussed before

- the hypervisor drivers interface, as we want to move runV drivers here
- keep the runV runtime APIs for smoothly migrating the workload from runV to kata

**Comment by sameo** [comment]
@gnawux You are right, those 2 points still need to be discussed. But I also believe that having a code base to build actual PRs on top of would be much more helpful than just discussions.
This is exactly what happened with the agent gRPC discussions: We started from the hyperstart gRPC definitions that you prepared, and made it evolve to fit everyone needs. We could have talked and discussed about it but that would have been much less efficient.

**Comment by gnawux** [comment]
my consideration is, once we merge some code, it is hard to make changes on top of it. It is better to have agreement on what we want before we merge it.

**Comment by sameo** [comment]
@gnawux The idea is to use the PR as a base for the hypervisor driver and runtime API discussions.

**Comment by gnawux** [comment]
> This is exactly what happened with the agent gRPC discussions: We started from the hyperstart gRPC definitions that you prepared, and made it evolve to fit everyone needs. We could have talked and discussed about it but that would have been much less efficient.

The way in `agent` is: we have interface first, then put implementation here. Now the #41 will do inversely -- put the code firstly, then discuss interface, I don't think it is easy to do.

**Comment by sameo** [comment]
@gnawux All the virtcontainers API and interfaces are part of the PR, and can be discussed there.
Yes, there is an implementation linked to them and that can also change with the discussions.

I even believe that merging the virtcontainers code as it is today would be the best way for everyone to actually send modifications to interfaces *together* with the corresponding implementation. API changes are always stronger when accompanied with implementation.

We also have to keep in mind that whatever we'd push today (runtime API, gRPC, etc...) is not even an alpha. So we're free to break it in any way we want before we tag 1.0.

**Comment by WeiZhang555** [comment]
> I even believe that merging the virtcontainers code as it is today would be the best way for everyone to actually send modifications to interfaces together with the corresponding implementation. API changes are always stronger when accompanied with implementation.

I agree with @sameo , a PR based on existing virtcontainers codes can be better place for discussion than an issue, an example implementation can make the discussion more clear. And we can break any interface when necessary before stable release, importing `virtcontainers` doesn't mean its interface is final

**Comment by bergwolf** [comment]
I agree with @gnawux. It is what we have done with the agent grpc definition as well. The initial set of API gets agreed upon before actual implementation. This way, we adapt implementation to fit API instead of the other way around.

**Comment by sboeuf** [comment]
@gnawux I think it's way easier to properly review some API changes when they come from a PR, but I also understand that you want to reach an agreement before we merge officially into Kata. If we cannot agree on the way to proceed here, I think a tradeoff would be to submit PRs about API changes to the [virtcontainers](https://github.com/containers/virtcontainers) repository directly before we try to merge into Kata.
