### ISSUE TITLE
test: supplement test cases for kata-check and kata-env in Arm64

### ISSUE THREAD

**Issue by Pennyzct** [kata-containers/runtime#403]
# Description of problem
There were missing test cases in Arm64 for platform-dependent kata-check and kata-env, leading to 'make test' failure under kata-containers/runtime. there are some issues to declare:

- func `getCPUDetails()` is platform-dependent, maybe we should relocate it in relevant `kata-check_arch_test.go`.

- The way to extract `vendor and model` info is sort of different in Arm64, generic set-up for test data weren't suitable for us.

relevant pull requests will be online asap.

Furthermore, although all test suites under `cli` have been passed, there were errors like this:
```
=== RUN   TestVersion
--- PASS: TestVersion (0.00s)
PASS
testing: can't write /tmp/go-build729728001/b001/testlog.txt: close /tmp/go-build729728001/b001/testlog.txt: file already closed
FAIL	github.com/kata-containers/runtime/cli	2.885s
Makefile:386: recipe for target 'go-test' failed
make: *** [go-test] Error 1
```
It occurred both in x86_64 and arm64, is something we need to neglect😥?

@jodh-intel @bergwolf @weichen81

**Comment by jodh-intel** [comment]
Hi @Pennyzct - I'm not totally sure I understand what you are saying. `getCPUDetails()` is indeed platform-dependent and we have one implementation per architecture. Are you saying we need to create some tests for that function? If so, I totally agree :smile:

I've never seen that `can't write` error I'm afraid and the tests are all passing on `x86_64` afaik (for example http://jenkins.katacontainers.io/job/kata-containers-runtime-ubuntu-16-04-master/lastBuild/consoleFull).

If you could raise PRs that would be great :smile:

**Comment by Pennyzct** [comment]
Sorry for the ambiguous, I was saying I will create arm64-specific test case for it.😜
I was doing the command `make test` under kata-containers/runtime dir in local machine, not in jenkins CI.

**Comment by grahamwhaley** [comment]
Heh, just a note - I happen to be seeing the:
```
testlog.txt: file already closed
```

error when running `make test` locally.
I suspect maybe some odd defer rm race or something, but it is odd that it appears to be the go test logfile that is faulting?
I'll see if I can figure it out - as it is bugging me, and will confuse others (at it makes it look like the tests have failed...)

**Comment by Pennyzct** [comment]
Hi~ @grahamwhaley same err still occurred in arm64, and it seems that only unit tests under `cli` have executed.
