### ISSUE TITLE
OCI runtime create failed: flag provided but not defined: -no-pivot: unknown.

### ISSUE THREAD

**Issue by wwq19920405** [kata-containers/runtime#409]
# Description of problem

1. set the env variable 'DOCKER_RAMDISK=true' before launching dockerd. (In my environment, docker need to disable ‘pivot_root’)
2. docker run --runtime kata-runtime --rm  busybox echo 'hello'

# Expected result

hello

# Actual result

docker: Error response from daemon: OCI runtime create failed: flag provided but not defined: -no-pivot: unknown.

# P.S.

Can kata-runtime add this flag to made it is compatible with this special environment, so i can choose the runtime by `docker run --runtime xx`.  (kata-runtime can throw a warning, and ignore the flag)

**Comment by WeiZhang555** [comment]
This is a good issue, thanks @wwq19920405! Would you like to file a PR for this?

**Comment by jshachm** [comment]
It can be related to #134. And it's a limitation by now. Glad if you want to raise a PR to solve this @wwq19920405
