### ISSUE TITLE
netns not get cleaned after docker run failed with a not found command

### ISSUE THREAD

**Issue by ghost** [kata-containers/runtime#413]
Hi, all.
I meet an issue on bare metal with Ubuntu 16.04, with docker 18.03.1-ce.
When use docker run with a not exist command, like "sudo docker run -ti busybox bash", containers will be destroyed, but with netns left behind.

**Comment by egernst** [comment]
Where are you seeing the netns?

**Comment by sboeuf** [comment]
Hi @lizk1989 , this should be covered by this commit https://github.com/kata-containers/runtime/pull/351/commits/e1b3ac2d3cf6bbce5e8e393aa75a06c23849c271
That'd be great if you could give this a try !
