### ISSUE TITLE
update supported docker version

### ISSUE THREAD

**Issue by chavafg** [kata-containers/runtime#418]
18.03 is the one being installed in the CI VMs and it seems that we have problems with hotplug CPU using v17.12

**Comment by WeiZhang555** [comment]
Sorry, I didn't get that why docker v17.12 can't work with kata containers?

**Comment by jodh-intel** [comment]
It sounds like v17.12 is buggy wrt cpu hotplug as the same Kata code running with docker v18.03 allows successful hotplug.

Is that right @chavafg, @devimc?
