### ISSUE TITLE
Docs: document how to PR the runtime, with the golang VC build issue

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#430]
# Description of problem
Due to some golang path deps inside virtcontainers, you cannot (trivially) build the runtime in your own fork of the repo.
This makes the build/test/PR workflow for the runtime different from the other repos. We should document that in the Runtime developer docs - a BKM for build/test/PR workflow.

I believe the best way is to work in a clone of the main repo, and then push your working branch to your **user fork** of the main repo (by adding your repo as a remote to your clone of the main branch).

Input on BKM's welcome here @jodh-intel @sboeuf 

This was related in the past, for ref: https://github.com/containers/virtcontainers/issues/655

**Comment by jodh-intel** [comment]
Talking to @grahamwhaley, it seems the problem is building in:

```
$GOPATH/src/github.com/$github_user/$repo
```

Whereas if you build in the following location, there are no problems afaik:

```
$GOPATH/src/github.com/kata-containers/$repo
```

**Comment by grahamwhaley** [comment]
Exactly. It is a golang thing - but, all the other repos (proxy, shim etc.) will build in the `$github_user` path. I think making a note somewhere in the dev docs that this is a golang project and has to build in its 'native' path might help non-golang users when they try their first PR and build.
I think there are some golang links out there, possibly only community links, that talk about this. We'll see if we can find some to place in the docs.

**Comment by gabibeyer** [comment]
@grahamwhaley @jodh-intel could we move this to the documentation repository (I don't think I have permission to do so). I wasn't able to find the documentation surrounding this, so it should probably stay open.

**Comment by grahamwhaley** [comment]
We can probably close it - it is just that the runtime repo does not fit nicely into my normal github/golang workflow, but that seems to be just me ;-)
