### ISSUE TITLE
logs: log line count differs per container

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#450]
# Description of problem

Running and deleting a number of containers, and then examining what is generated in the runtime/proxy/shim logs, shows that we quite a different 'number of log entries' for each container, which was unexpected to me (as nominally all the containers are identical).

# Expected result

I expected all the containers to have the same number of entries, and most likely fairly identical entries (apart from the obvious timestamp/pid/cid etc.), and in the same order.
(all except the one 'dead' container I'm actually trying to debug that is).

# Actual result

Running this script:
```
#!/bin/bash

set -e

NUMBER=${NUMBER:-110}
ITERATIONS=${ITERATIONS:-100}

run() {
        for n in $(seq 1 ${NUMBER}); do
                echo "Run number $n"
                docker run -tid --runtime=kata-runtime nginx
        done

        echo "We have now:"
        docker ps

        echo "And kill them all off"
        docker rm -f $(docker ps -qa)

        echo "And now have:"
        docker ps
        docker ps -qa
}

grab_logs() {
        RUNTIME_LOGFILE=runtime.log
        PROXY_LOGFILE=proxy.log
        SHIM_LOGFILE=shim.log

        echo "Remove any old log backup"
        rm -f ${RUNTIME_LOGFILE}.bup || true
        rm -f ${PROXY_LOGFILE}.bup || true
        rm -f ${SHIM_LOGFILE}.bup || true

        echo "Backup iany old logs"
        mv ${RUNTIME_LOGFILE} ${RUNTIME_LOGFILE}.bup || true
        mv ${PROXY_LOGFILE} ${PROXY_LOGFILE}.bup || true
        mv ${SHIM_LOGFILE} ${SHIM_LOGFILE}.bup || true

        echo "And grab the logs"
        sudo journalctl -q -o cat -a -t kata-runtime --since "${STARTTIME}" --reverse > ${RUNTIME_LOGFILE}
        sudo journalctl -q -o cat -a -t kata-proxy --since "${STARTTIME}" --reverse > ${PROXY_LOGFILE}
        sudo journalctl -q -o cat -a -t kata-shim --since "${STARTTIME}" --reverse > ${SHIM_LOGFILE}
}

death() {
        echo "Died!!! - grab the logs"
        grab_logs
}

main() {
        trap death EXIT QUIT KILL
        for i in $(seq 1 ${ITERATIONS}); do
                echo "Iteration $i"
                STARTTIME=$(date +"%Y-%m-%d %H:%M:%S")
                run
                grab_logs
        done
}


echo "Starting"
main
echo "And finished successfully"
```

and then using this to do the count:
```
#!/bin/bash

containers="91d5709b8654be649337b4ddc2891020d9bf44964909f4dcde5f9441985291e3 \
        4043834e10ef31df878b91cbd8c85d53065a6a387b2bd10887578a1350af69ba \
        a1b5cf0a27b483f22c9a42443c815b006271c45889c48647292627a1a25e678d \
        abd386bb2ba587fdf39efc69d07c9cfb733e19f93743b588c536acc2981bbc6b \
        69a9a70217ddbd4a13ebad2efe382321c0b76916e56ad0c9dc33453ec3749749 \
...
        615d13d56abce91af937028dc0d909a245c73c02920620181ecc4c0d5eb41829 \
        eea1d7311afda83551f4bcd36b3f9c33a427df2647de4921160149642ca50833"

echo "What Runtime Proxy Shim"
for c in $containers; do
        rn=$(grep -i $c runtime.log | wc -l)
        pn=$(grep -i $c proxy.log | wc -l)
        sn=$(grep -i $c shim.log | wc -l)
        echo "Container $c : $rn $pn $sn"
done
```

I get output like:
```
What Runtime Proxy Shim
Container 91d5709b8654be649337b4ddc2891020d9bf44964909f4dcde5f9441985291e3 : 23 2 3
Container 4043834e10ef31df878b91cbd8c85d53065a6a387b2bd10887578a1350af69ba : 23 2 3
Container a1b5cf0a27b483f22c9a42443c815b006271c45889c48647292627a1a25e678d : 18 2 2
Container abd386bb2ba587fdf39efc69d07c9cfb733e19f93743b588c536acc2981bbc6b : 13 2 2
Container 69a9a70217ddbd4a13ebad2efe382321c0b76916e56ad0c9dc33453ec3749749 : 13 2 2
Container 14890f5288977c9900df9e6da2cdc38cb5e6d8ab71f82bef2478634152b42739 : 14 2 2
Container aae8fa1ba41196c564c2d71877ab4717ded64a8a634e9be30ba8153ad7327cb3 : 13 2 2
Container 117e182096a9bd5dcb203f96f759a031c2c1f4aff37c9080905643474e367904 : 13 2 2
Container fabea68acc5a3665e68dfdf2a8cb6aaf6b6b7da97d95cf076f296160dac41f03 : 13 2 2
Container 4c96c1b2dc6ee032ae08d98f55ee40e8178213ae257bb1b410365c0e2d491f45 : 13 2 2
Container 5226e72e82149a2ea86f267d3f0c5d26743f99778157fc7110676cc816c5e962 : 14 2 2
Container 930102d2129c5253a7e6611d6b3157ed0f619b6a22d710a1b2aa66d0f7ea23ae : 13 2 2
Container 94826f102c04afd1c4669f9f86a379170e0784de37efc4dce08c8369137d5ed1 : 13 2 2
Container 0b27aacc34dd27440ef0b9a400075f2ba8381abc80af5c3d16c5f78e280d4b24 : 7 0 0
Container 06e5543d484e916fe75463cb814d8ff6bbcac428f5276a6947170cafba176b7a : 13 2 2
Container d929e9a9582d9687c4817b3c1f397c6a8c876e95c6d1ed9b6bd1a719f964041d : 13 2 2
Container 5d4c67515b689db7358de6a5b9bde055130aa0b39b97125657b1f3f7f760992e : 13 2 2
Container 249b103545b5cfebdaa51cc6ac03093ef1db72f202d4e085d0dea6ef620a9edf : 12 1 1
Container c47de480760a70de1bbc95bdb55f6c6c46437b53f1bb5e8c4b407da2fe5334c9 : 12 1 1
Container 52e4bed8bcab6a5f69a4ce5c95aca58994dc1759a053874655f30c5fc2f2e6fb : 12 1 1
Container 10ba979686a7fb958f3e898c2fac204e847dfa35af37ae3ffb6953cfb2927209 : 12 1 1
Container acb0959e537b24197f6d96a2433be18796dd036a703a25891a96b96a9007a3ed : 21 1 2
Container bfe11201a0add17bd28caef4eaf2df6c5c9118b473d5ac395b26138fc97c2683 : 20 1 2
Container 9a625e24e996e1a8cac64a9cc810de8cd70f5d88b36db7da31ed749bc8c9a04f : 15 1 1
Container 27700cd890b5190c2fd4b290c811a4c4fd255bb3faa247c9b11451f2b0ac8c59 : 11 1 1
Container 29af4983f4e12b9769f188815e6dd2b0f538df68a5328e0e652058231b512d70 : 10 1 1
Container 121595b441b991e77f153b51aea7fcffc39018b1e0699517ba1d8d4ffa00fd9d : 9 1 1
Container 4fb1c770d0b4461875f352c4b1fb58c100d4a88009faed6d4779a88a2afbfee1 : 7 1 1
Container 3ab5676f7ebab294739daca43a2472f15fa68359e8c98c72264d6dd7a5756ee0 : 7 1 1
...
```
Note, that 0b27aacc container is the one I'm trying to debug - it got 'stuck'. I don't think this disparity of log entries is due to that stuck container (but, we should not completely rule that out).

---
I'll just drop the kata-env here for the minute - we can grab a full debug output later if we need. My runtime has a single modification to time out on the stuck grpc call after 120s, which is when the test script then notices the fail and grabs the logs.
```
[Meta]
  Version = "1.0.12"

[Runtime]
  Debug = false
  [Runtime.Version]
    Semver = "1.0.0"
    Commit = "6f409b9528b66c46814eacf72083e2a54645ee89-dirty"
    OCI = "1.0.1"
  [Runtime.Config]
    Path = "/usr/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.7.0, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-lite-system-x86_64"
  BlockDeviceDriver = "virtio-scsi"
  Msize9p = 8192
  Debug = false

[Image]
  Path = "/usr/share/kata-containers/kata-containers-2018-06-13-10:50:04.393273528+0100-3375e73"

[Kernel]
  Path = "/usr/share/kata-containers/kata-vmlinuz-4.14.22.container"
  Parameters = ""

[Initrd]
  Path = ""

[Proxy]
  Type = "kataProxy"
  Version = "kata-proxy version 1.0.0-a69326b63802952b14203ea9c1533d4edb8c1d64"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = true

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 1.0.0-087a5371680f069d45baed8544a09b4e6353c06e"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = true

[Agent]
  Type = "kata"

[Host]
  Kernel = "4.4.0-104-generic"
  Architecture = "amd64"
  VMContainerCapable = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz"
```

**Comment by grahamwhaley** [comment]
We'll start simple. Looking at my shim logs, I believe it is the 'version' Info() I only got for 2 out of 10 containers. From this line: https://github.com/kata-containers/shim/blob/master/main.go#L67
Maybe this is related to the pending https://github.com/kata-containers/shim/pull/95

**Comment by grahamwhaley** [comment]
For the proxy log, in a run of 10 containers, I got 8 of these:
```
time="2018-06-27T14:35:56.693935519+01:00" level=fatal msg="accept unix /run/vc/sbs/a1f66753615378a34200775dcfb3792a945410b60fdb5d72ec6ecca136e1fe39/proxy.sock: use of closed network connection" name=kata-proxy pid=11899 source=proxy
```

and 2 of these:
```
time="2018-06-27T14:35:56.712073777+01:00" level=debug msg="shutting down" name=kata-proxy pid=12242 source=proxy
```

**Comment by grahamwhaley** [comment]
OK, I applied https://github.com/kata-containers/shim/pull/95 to the shim, and ran the test again.
That looks to have improved things (I seem to get more log entries for all of runtime/shim/proxy), but I still see inconsistencies across all three in their linecounts-per-container. I'll do a re-eval of them now.

**Comment by grahamwhaley** [comment]
Note, I ran into the log disparity whilst trying to debug #406 , which utilises the soak test over at https://github.com/kata-containers/tests/pull/414 to show the issue. You *do not have to use those* to show the log issue though - using the script at the top of this Issue is good enough (and is less likely to hang up the runtime, which might perturb or mix two issues together).

**Comment by grahamwhaley** [comment]
@jodh-intel asked if I can upload some log examples.
In the attached, I used the script at the top of this Issue with NUMBER=10 and ITERATIONS=1. I captured the output in a file called `crud`, and used a noddy script to get some log stats:
```
#!/bin/bash

containers="$(grep nginx crud | awk '{print $1}')"

echo "What Runtime Proxy Shim"
for c in $containers; do
        rn=$(grep -i $c runtime.log | wc -l)
        pn=$(grep -i $c proxy.log | wc -l)
        sn=$(grep -i $c shim.log | wc -l)
        echo "Container $c : $rn $pn $sn"
done
```

Here are my notes, including the output of that script:
```
Log disparity - with patch shim#95 in place - which looks to make things better, but there are still disparities:

What Runtime Proxy Shim
Container 3fcfac9a9f5f : 18 2 3
Container 3bf59640bbeb : 14 2 2
Container 79aa7c11f888 : 13 2 2
Container 64632e2b2653 : 13 2 2
Container bc43a5ec2a4c : 13 2 2
Container bdcea7fe8917 : 14 2 2
Container 55559b43c334 : 14 2 2
Container 756d427bca67 : 14 2 2
Container 84e83b06b6a3 : 18 2 2
Container bbc4c414dc53 : 23 1 3

(note, logs are in reverse...)

Shim
----
3fcfac:
  exitcode=137
  rpc error: Unknown read /dev/ptmx
  version

3bf596:
  exitcode=137
  rpc error code /dev/ptmx

Still missing 'version'


Proxy
-----
3fcfac:
  use of closed network connection
  discarding a signal as container stopped

bbc4c4
  discarding a signal as container stopped
```
> had to rename crud->crud.txt to upload.

This was with shim#95 applied, which improved things.
I've been staring at they 'why do we get a ptmx grpc error on some not others', which @devimc suspects is a race, and I suspect he is right. I'll contemplate that some more tomorrow. Races might explain a lot of the log disparity, but I'm not sure all of it (such as why do we get the 'version' log line missing in some of the shims?)

[proxy.log](https://github.com/kata-containers/runtime/files/2142167/proxy.log)
[readme.txt](https://github.com/kata-containers/runtime/files/2142168/readme.txt)
[runtime.log](https://github.com/kata-containers/runtime/files/2142169/runtime.log)
[shim.log](https://github.com/kata-containers/runtime/files/2142170/shim.log)
[crud.txt](https://github.com/kata-containers/runtime/files/2142171/crud.txt)

**Comment by grahamwhaley** [comment]
Small update @jodh-intel. Adding some sleeps into the test run vastly improves things (but I've not proven things are 'wholly fixed' yet). The key might have been a sleep between the last `docker run` and the `docker rm -f`. I suspect as the test is using `-tid` on the run command, we are launching many VMs in parallel, and not all of them have finished before we issue the `kill`.
So, adding the delay gets us log-counts per container that look closer, but still not that close. I do suspect adding the sleep is only masking or avoiding some issues, and is almost definitely not a fix or workaround. I'll keep digging.

**Comment by grahamwhaley** [comment]
See https://github.com/kata-containers/documentation/issues/181 - turns out, on my system (which I believe is using the general journald defaults, so probably on many systems), we get rate limited by `journald`.
There are workarounds, and I'll write that up in our developer documents and do a PR.

**Comment by sboeuf** [comment]
ohhhhhh really, that's interesting. Because I had the same thing when I was debugging with too many logs enabled, sometimes I had the logs and sometimes I simply didn't get them (when everything was working perfectly). I am eager to hear how we can tune the journal :)

**Comment by grahamwhaley** [comment]
The quick fix is to globally disable rate limiting - which is maybe a little 'dangerous', which is whey I'll see if we can do this on a per-unit basis. Details here how to edit `/etc/systemd/journald.conf`:
https://www.rootusers.com/how-to-change-log-rate-limiting-in-linux/

**Comment by jodh-intel** [comment]
Nice find @grahamwhaley! We don't need to modify per unit, but possibly per identifier would be useful if that is supported?

Presumably, since we enable full debug on all our CI (and metrics?) systems, we'll need to encode disabling rate limiting in the setup scripts/configs to make problem determination possible?

/cc @chavafg, @cboylan, @nitkon, @Pennyzct.

**Comment by grahamwhaley** [comment]
I think... we can probably close this one now can't we - with the rate limiting find and the logging improvements we did?

**Comment by jodh-intel** [comment]
wfm - wdyt @chavafg?

**Comment by chavafg** [comment]
Agree, closing it.
