### ISSUE TITLE
CI: checks: go-no-os-exit may not be functioning

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#477]
# Description of problem

Hand running 'make check V=1' locally in the runtime repo hangs up. Adding some debug to the Makefile, it looks like the issue is in:
https://github.com/kata-containers/runtime/blob/master/.ci/go-no-os-exit.sh

```
bash -x .ci/go-no-os-exit.sh
+ go_packages=.
++ go list -f '{{.Dir}}/*.go' .
can't load package: package github.com/kata-containers/runtime: no Go files in /home/gwhaley/gopath/src/github.com/kata-containers/runtime
+ candidates=
+ egrep -n '\<os\.Exit\>'
```

The problem being the `go list` finds no dirs to process, and then the egrep ends up looking at stdin, forever.
I have a feeling we don't see this in the CIs maybe as they don't have a tty associated with them, so maybe they silently fail.

# Expected result

I expect it to run the check on all the .go files, or fail gracefully at least - both on the CI and if run by hand.

# Action
Probably:
1) Add an echo so we know that test is being run
1) Add a check for 'no files to process', echo that status out, and fail gracefully
1) Decide/check that finding 'no go files' in the runtime is the right action - as it is quite possibly not - it should probably be checking all files in `virtcontainers` and the `cli` dirs.

**Comment by grahamwhaley** [comment]
@chavafg @sboeuf - this check was inherited from the CC runtime from way back. It may have been bust for some time and we never noticed. Do we think we want it to check all the go files (well, apart from vendor of course) - in which case I suspect we'll need a bit of modification around the `go list` part.
Input welcome. I'll pre-PR the echos and graceful fail bit probably anyway.

**Comment by sboeuf** [comment]
I do think we still want this check as it gates PR based on the content, which I think is important. But obviously, if it's broken as you described it, we need to fix it first !
