### ISSUE TITLE
Docs: Add possibility to register kata runtime via daemon.json

### ISSUE THREAD

**Issue by morph027** [kata-containers/runtime#484]
Instead of a systemd dropin, one could also use Dockers `/etc/docker/daemon.json` which might better suite some orchestration tools or just use cause you do not have to reload systemd.

**Comment by devimc** [comment]
thanks @morph027 for raising this issue, the documentation has been updated now it includes that information.

see https://github.com/kata-containers/documentation/tree/master/install/docker
