### ISSUE TITLE
Implement containerd shim v2 API for Kata Containers

### ISSUE THREAD

**Issue by gnawux** [kata-containers/runtime#485]
In the arch committee meeting last week, Michael Crosby introduced the containerd shim API v2. After the meeting, read related documents, patches, and discussed with @bergwolf @lifupan and related folks. And I think we could begin to implement the kata shim for containerd v2 API now.

## Current kata & containerd working pattern

Right now, containerd and runtime work in the following pattern:

![containerd-kata-shimv1](https://user-images.githubusercontent.com/54124/42746640-62634562-890b-11e8-9a20-c648400b029d.png)

Whenever containerd tries to create a container, 

- It creates a containerd-shim
- The containerd-shim call runtime cli -- the cli is specified by the `runtime=kata` flag, and the cli should be compatible with runc
- The containerd-shim served at the address specified by containerd, and feedback events to containerd’s listening address

Though the containerd-shim designed to be an replaceable component

- There still has to be one containerd shim per container (or process?)

## Benefits from shim v2 API

With the proposed shim v2 API, the most significant change is

- The shim will write the serving address back to containerd through stdout, instead of specified by containerd

As a result

- We may replace the containerd-shim with a customized shim, and don’t need to implement a runc compatible CLI for containerd-shim.
- We may use a single shim for a couple of containers, such as one shim per pod

Then the architecture may change to the follows:

![containerd-shimv2-per-pod](https://user-images.githubusercontent.com/54124/42746721-d280b23a-890b-11e8-902e-df0d0eb61fd3.png)

- One shim for containerd per pod
- No proxies and kata-shim processes any more

And in v2 API, stats function is moved to shim, which makes the shim more self-contained.

## Where we start

- This routing pattern (built-in proxy + built-in shim) has already been implemented in hyperhq/hyperd#727 
- The OCI Spec processing part exists in kata runtime
- And the other stuff could reference the current kata-shim and v2 shim PR (containerd/containerd#2434).

**Comment by WeiZhang555** [comment]
This is a good proposal, and simplifies the architecture a lot!

One question: I think we need to keep the compatibility with older containerd-shim, we can't only support containerd-shim V2 because it's so new.

**Comment by bergwolf** [comment]
@WeiZhang555 I agree we should keep the runc compatible cli as long as possible. For this new shim, IMO it should have its own repo so that in future we can push it to containerd to be a first class citizen there.

**Comment by sboeuf** [comment]
As said during the Arch committee meeting, I would like to see the Kata implementation of the containerd-shim v2 as a separate directory (different repo might come further down the road, but right now, let's keep this simple). The same way we have the `cli` directory for our OCI implementation (matching runc as much as possible), we would have a new `containerd-shim-v2` directory providing the Kata implementation of this shim v2. Most of the implementation will follow what frakti is actually leveraging (stateless Kata API), to be more efficient.
@gnawux let us know who will work on that, and how we can help with this (if there are some areas where the work can be split).

**Comment by crosbymichael** [comment]
Looks good!

**Comment by WeiZhang555** [comment]
And as @crosbymichael described in the Arch Committee meeting, containerd-shim-v2 isn't aware of POD concept, so the containerd-shim should be one per container, so I think the final arch should be:

![image](https://user-images.githubusercontent.com/1203611/42856382-9e5287b4-8a77-11e8-910f-222ba0f3dc0b.png)

Is this right? @gnawux

**Comment by gnawux** [comment]
@WeiZhang555 we investigated the APIs and code in the PR and has the following conclusion -- though containerd will request for shim service for every container, it does not expect there is a new shim socket or process for the container. As a result, we think it could be implemented as one shim per pod. Let's just try to prove it with a prototype.

**Comment by bergwolf** [comment]
@WeiZhang555 Per discussions in containerd/containerd/issues/2426, `containerd-shim-v2 start` can return the unix socket address of a previously started shim. That's how one shim per pod is supposed to be implemented.

**Comment by WeiZhang555** [comment]
Oh, cool, this sounds a little hacky but workable.

**Comment by crosbymichael** [comment]
I pushed an README this morning for shim authoring.  Please take a look and provide any feedback if you have questions or if something does not make sense.

https://github.com/containerd/containerd/pull/2434/files#diff-9bb937a499e2e6fdc4536481d6315c50

**Comment by gnawux** [comment]
thank you @crosbymichael. One more question -- is it essential for a v2shim commandline to implement the "no action" behavior

```go
	default:
		client := NewShimClient(ctx, service, signals)
		return client.Serve()
```

or it's ok to support `start` and `delete` only?

**Comment by crosbymichael** [comment]
If you want to split it into multiple binaries then that is fine, all we care about is that `start` returns a socket to the API and `delete` lets us call for a cleanup if a shim dies and we can no longer communicate to it.

**Comment by resouer** [comment]
[Update] A temporary branch has been created in [develop repo here](https://github.com/hyperhq/kata-runtime/pulls?q=is%3Apr+is%3Aclosed).

Will send out PRs to upstream when core apis are ready so you can set up basic tests.

**Comment by grahamwhaley** [comment]
Nice @resouer . Just for ref, link to branch itself is [here](https://github.com/hyperhq/kata-runtime/tree/shimv2) I think? (link above goes to closed PRs in that repo afaict).

**Comment by resouer** [comment]
@grahamwhaley Oh, yes. The link I posted seems to be the merged PRs to that branch :/

**Comment by Ace-Tang** [comment]
Looking forward to the implement !
