### ISSUE TITLE
virtcontainers: define and implement pod based external API

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#49]
The existing 1.0 API is designed for an OCI runtime binary's needs.   A pod/sandbox is always restored from storage between runtime calls.   A CRI serve, however, can keep sandbox pointers in memory
Current API examples:
```go
func StartPod(podID string) (VCPod, error) {}

func StartContainer(podID, containerID string) (VCContainer, error) {}
```
These calls would be extended to, respectively:
```go
func (p VCPod) StartPod() (error) {}

func (p VCPod) StartContainer(ctr VCContainer) (error) {}
```

Let's use this issue to define the extended API with respect to pod lifecycle.  This should be closed once we have the API documented and implementation merged.

Sub-issues:
 - fetch/release sandbox: #217

**Comment by egernst** [comment]
cc/ @gnawux @bergwolf @laijs @sboeuf

**Comment by bergwolf** [comment]
ref: https://github.com/kata-containers/documentation/pull/27 on section [Sandbox Based API](https://github.com/kata-containers/documentation/pull/27/files#diff-727ad799425e468e7ffa14abf330457cR8)

**Comment by egernst** [comment]
@bergwolf Are you driving implementation of these API extensions?

**Comment by caoruidong** [comment]
Will we base on https://github.com/kata-containers/runtime/pull/32 or re-implement one?

**Comment by egernst** [comment]
@caoruidong - No, it should be based on what was agreed to and documented @ https://github.com/kata-containers/documentation/blob/master/design/kata-api-design.md#sandbox-based-api

**Comment by bergwolf** [comment]
With relevant PRs (#259, #252, #218, #173) merged, we can close this one now.
