### ISSUE TITLE
vm factory UX enhancements

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#491]
As #303 only targets to get the core part of vm factory landed, there are a few UX-related enhancements that I've been pushing back, and it would be great to look at them after #303 is merged. This issue is to collect and track these enhancements.

- [x] 1. `kata-runtime factory status` checks and prints the vm factory status - by @grahamwhaley 
- [x] 2. `enable_debug` for vm factory config section - by @jodh-intel 
- [ ] 3.  document security implications of vm templating (possibly we can combine this with documentation/issues/167) - by @amshinde
- [x] 4. `kata-runtime create` automatically creates vm factory if it does not exists yet - by @WeiZhang555 

Please feel free to comment on the details or if you have more in mind. Thanks!

**Comment by bergwolf** [comment]
@jodh-intel oops, I just had it done this afternoon... posting PR soon. We don't need a new option, but a new API to let vm factory use the same logger.

**Comment by bergwolf** [comment]
@jodh-intel see #521. I was working on something else today and found out that vm factory logger is not working so I fixed it. I haven't started the rest two. If you want to help with that, please feel free to do so and I won't step on your toes again. sry...

**Comment by jodh-intel** [comment]
No problem - I love it when work disappears like that! :smile:

**Comment by bergwolf** [comment]
ref #545 for item `1`.
