### ISSUE TITLE
virtcontainers: Implement Storage hotplug API

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#50]
To help optimize the container boot process, virtcontainers needs to support hotplugging of storage and network devices.  We need to define and implement an API for attaching NICs and storage endpoints to a Pod/Sandbox, such as:
```go
func AddStorage(podID string) error {
        ...
}


AND/OR

func (p VCPod) AddStorage() error {
        ...
}
```

let's use this issue to define the API for storage  hotplug.  This should be closed once we have the design documented and implementation merged.

**Comment by sboeuf** [comment]
Might worth splitting into 2 different issues once we settled on the design.

**Comment by bergwolf** [comment]
ref: https://github.com/kata-containers/documentation/pull/27 on section [Sandbox Hotpulg API](https://github.com/kata-containers/documentation/pull/27/files#diff-727ad799425e468e7ffa14abf330457cR61)

**Comment by egernst** [comment]
Storage hotplug is being handled in #113.  Updating title of this issue to be specific only to storage support.

**Comment by egernst** [comment]
Design described at https://github.com/kata-containers/documentation/blob/master/design/kata-api-design.md#sandbox-based-api

@bergwolf @laijs - are either of you working on adding this support?

**Comment by egernst** [comment]
Signing up Wei for this feature.  Thanks @WeiZhang555 !

**Comment by sboeuf** [comment]
@egernst this issue might be worthing some rephrasing/refactoring since both storage and network hotplug are mixed together.

**Comment by egernst** [comment]
yes, def. agreed.

**Comment by WeiZhang555** [comment]
I will take some time on this, and try my best not to block anyone :)

**Comment by egernst** [comment]
This got closed with the refactoring work; should still be open AFAIU!

**Comment by WeiZhang555** [comment]
Yes, this should be kept open. I reused this issue number as it's part of the works. Thanks!

**Comment by WeiZhang555** [comment]
The PR is merged, but reverted due to some problem, see error log:

http://jenkins.katacontainers.io/job/kata-containers-agent-ubuntu-16-04-PR/101/console

I'll do more investigation and fix it
