### ISSUE TITLE
virtcontainers: add support for VM templating/caching

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#52]
need to add support for VM caching/cloning

Let's use this issue to discuss the design of this feature.  This issue can be closed once a design document is complete and the feature is merged.

**Comment by bergwolf** [comment]
Related: https://github.com/kata-containers/documentation/pull/27 on section [VM Factory plugin](https://github.com/kata-containers/documentation/pull/27/files#diff-727ad799425e468e7ffa14abf330457cR99).

The VM templating support can be achieved by implementing VM Factory which controls how a new VM is created. Then we add different plugins to support different VM creation methods.

**Comment by devimc** [comment]
@bergwolf  can we close this issue ?

**Comment by bergwolf** [comment]
Yes

**Comment by teawater** [comment]
Reopen it for vm cache
