### ISSUE TITLE
Remove initcall_debug from kernel boot params

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#526]
*A long time ago in a galaxy far, far away*...

Wait a sec, that's no right... cough...

A long time ago, we added the [`initcall_debug`](https://github.com/torvalds/linux/blob/master/Documentation/admin-guide/kernel-parameters.txt#L1592) to the guest kernel boot command-line. This is no longer used nor needed and might in fact be hurting performance due to the number of related kernel messages that get pumped out at boot time.

**Comment by sboeuf** [comment]
Agreed, but we still want to be able to enable it easily for debug purpose.
