### ISSUE TITLE
Add support for process-less shim/proxy functionality

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#53]
Requirement:
Run sandbox without standalone shim/proxy process, nor any IPC that just exists just for message relay/translation.

To support real process-less shim/proxy functionality, we need to:
1. add configuration options to allow to disable shim/proxy process spawning
2. support shim functionality related sandbox APIs
3. support kata agent connection with custom yamux based grpc dialer

Ref: https://github.com/kata-containers/documentation/pull/27 on section [Sandbox Relay API](https://github.com/kata-containers/documentation/pull/27/files#diff-727ad799425e468e7ffa14abf330457cR70) and [Built-in Shim and Proxy Types and Capabilities](https://github.com/kata-containers/documentation/pull/27/files#diff-727ad799425e468e7ffa14abf330457cR121).

**Comment by egernst** [comment]
I think this is already handled in the v2-shim implementation.  @bergwolf please feel free to reopen if you disagree.
