### ISSUE TITLE
vsock support planning

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#532]
As discussed with @sboeuf, we should add vsock support [in several steps](https://github.com/kata-containers/agent/pull/299#issuecomment-407462580):

1.  @devimc should finish his work on coldplugging the vsock (from the runtime) since this is the easiest thing to do. This means the agent would simply have to check for serial of vsock. I think this is an important first step to validate that vsock works properly as expected with the whole chain/stack.
2. As a second step, we make both serial and vsock sockets hotpluggable from the runtime codebase. This will need a corresponding PR on the agent side to detect if serial or vsock get hotplugged (could be based on uevent or simply checking some known paths).
In the meantime, we can add the new gRPC function (something like changeCommChannel()), with the appropriate agent implementation which will take care of stopping the gRPC server, close the current connection and connect to the new socket/port in order to re-spin a new gRPC server. The agent should have a timeout to check for this new socket/port for a certain amount of time since the hotplug might take some time.
3. As a third step, we would use leverage the changeCommChannel() from the runtime in case of VM templating.

And #497 (#383) serves as the implementation for the 1st step above.

**Comment by devimc** [comment]
see https://github.com/intel/govmm/pull/23

**Comment by devimc** [comment]
communication channel won't be hot-added, I think we can close this
