### ISSUE TITLE
Consider update qemu to a newer version

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#556]
# Description of problem

Qemu will release soon to version 3.0.0  see https://github.com/qemu/qemu/releases/tag/v3.0.0-rc4

We should start to use a newer version today we tests 2.11 and 2.12 is the latest release.

**Comment by gabibeyer** [comment]
Will be fixed with PR #1744

**Comment by devimc** [comment]
closing, already updated qemu to 4.0.0
