### ISSUE TITLE
Add initial opentracing support

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#557]
Add the basic framework to enable opentracing support using [jaeger](https://godoc.org/github.com/uber/jaeger-client-go).

Related: https://github.com/kata-containers/kata-containers/issues/27.

**Comment by jamesodhunt** [comment]
Hi - this issue is labelled `release-gating` but doesn't have an associated PR.

Please can you comment on the status of this item so we know if it could be
included in the [upcoming 2.0 release](https://github.com/kata-containers/kata-containers/wiki/Kata-Containers-2.0-Roadmap)?
