### ISSUE TITLE
Allow static runtime build

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#560]
Today kata-runtime is build and is dynamically linked by default.

For solutions like kata-delploy we want to use static binaries.

Lets add a build option to build an static runtime.

\cc @egernst

**Comment by devimc** [comment]
duplicated https://github.com/kata-containers/runtime/issues/342 ?

**Comment by jcvenegas** [comment]
Yes! I did not see it when I created it. Closing here
