### ISSUE TITLE
cli: Make message of using initrd OR rootfs clearer

### ISSUE THREAD

**Issue by nitkon** [kata-containers/runtime#563]
# Description of problem

When starting a kata container, if initrd and rootfs both are provided in the configuration.toml then the error message presented is "cannot specify an image and an initrd in configuration file" which might be a bit confusing.

# Expected result

A suggestion is to have a clearer message like: "specify an image or an initrd in the configuration file, not both"

**Comment by jodh-intel** [comment]
Hi @nitkon - again, please put details in the issue and remove the (untouched) template text :)

**Comment by nitkon** [comment]
Hi @jodh-intel , done!

**Comment by jodh-intel** [comment]
Thanks!
