### ISSUE TITLE
Remove all CNI code

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#567]
We dont really call CNI from Kata  runtime. Remove all of this code as it is not really called. It is also leads to confusion whether CNI is being called by the kata-runitme.

**Comment by sboeuf** [comment]
This makes me think, we should open an issue to track if there's any other code part like this one. Things that we actually don't use at all ?

**Comment by amshinde** [comment]
@sboeuf Sure, please open one. Are you aware of any other unused code at the moment?

**Comment by sboeuf** [comment]
@amshinde nothing comes to mind, but I just want to make sure we reduce the codebase if possible.
