### ISSUE TITLE
Remove any unneeded code

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#569]
This is a generic issue that should not be closed.
The idea is that if you identify some code part for which there is no use case, please feel free to raise a new issue referencing this global one, and raise a PR removing the code that we don't need.

**Comment by jodh-intel** [comment]
We could get brutal and say that valid use cases require full unit-test code. So if code doesn't have unit test coverage, we zap it! :smile:

**Comment by devimc** [comment]
duplicated, we are commenting here https://github.com/kata-containers/runtime/issues/1113
