### ISSUE TITLE
Bump go version to at least 1.9 for Travis CI testing 

### ISSUE THREAD

**Issue by lifupan** [kata-containers/runtime#575]
# Description of problem

Kata containerd shim v2 will import some containerd modules, which needs at least
go version 1.9 to build successfully.  Thus we'd better to bump CI's go version  to 1.9 or
1.10 to build shim v2 successfully.

For more info about containerd's requirement for go version, please see:
https://github.com/containerd/containerd/issues/1632

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by jodh-intel** [comment]
Hi @lifupan - we're already using golang 1.10 for the CI. See:

- https://github.com/kata-containers/tests/blob/master/.ci/install_go.sh#L76
- https://github.com/kata-containers/runtime/blob/master/versions.yaml#L188

**Comment by bergwolf** [comment]
@jodh-intel travis-ci is still using go 1.8.  See
https://github.com/kata-containers/runtime/blob/master/.travis.yml#L18

**Comment by jodh-intel** [comment]
@bergwolf - aha! Good point. I've updated the title of this issue to clarity which CI we're talking about ;)
