### ISSUE TITLE
vsock support check requires manual kernel module loading

### ISSUE THREAD

**Issue by maximilianriemensberger** [kata-containers/runtime#581]
# Description of problem

I configured kata-runtime to use vsocks on ubuntu 18.04 with kata-runtime 1.2.  But the detection of vsock support failed.  It seems that the code explicitly looks for /dev/vsock and /dev/vhost-vsock. Those are only present after loading the vsock and vhost_vsock modules.

```
Aug 14 07:33:39 hix kata-runtime[29715]: time="2018-08-14T07:33:39.953266567+02:00" level=warning msg="No vsock support, falling back to legacy serial port" arch=amd64 command=create name=kata-runtime pid=29715 source=runtime
```
After loading the module:

```
Aug 14 07:48:03 hix kata-runtime[30209]: time="2018-08-14T07:48:03.900473483+02:00" level=info msg="vsock supported" arch=amd64 command=create name=kata-runtime pid=30209 source=runtime
Aug 14 07:48:03 hix kata-runtime[30209]: time="2018-08-14T07:48:03.90062639+02:00" level=info msg="VSOCK supported, configure to not use proxy" arch=amd64 command=create name=kata-runtime pid=30209 source=runtime
```

kata-runtime  : 1.2.0
   commit   : 0bcb32f
   OCI specs: 1.0.1

# Expected result

kata runtime detects vsock support even if the kernel modules are not loaded.
The modules are autoloaded when used, probably by calling socket(AF_VSOCK, ...).

# Actual result

Vsock support was detected only after manually loading all relevant kernel modules, i.e., modprobe vhost_vsock.

**Comment by jodh-intel** [comment]
Thanks for reporting @maximilianriemensberger.

/cc @devimc.

**Comment by maximilianriemensberger** [comment]
I played around with `AF_VSOCK` sockets.  The straightforward call to `socket(AF_VSOCK, SOCK_STREAM, 0)` autoloads the vsock module but not the vhost_vsock module. Instead it various loads vmw_vmci modules (vmw_vsock_vmci_transport, vmw_vmci). I don't know but autoloading vhost_vsock might not be as easy as I thought.

**Comment by devimc** [comment]
@maximilianriemensberger any update on this? I'll close this, please feel free to reopen it if you wish to add something
