### ISSUE TITLE
Add configuration support for hotplugging VFIO devices on root bus

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#594]
There is a limitation in sea-bios firmware that prevents PCI devices with large PCI BARS from being configured correctly when hotplugged on a bridge.
This issue has been seen with Intel graphics cards which require a larger PCI configuration space.
Till this issue gets resolved in the firmware, we need to add support in the runtime to pass in a configuration for hotplugging VFIO devices on the root bus instead.

**Comment by jamesodhunt** [comment]
Hi - this issue is labelled `release-gating` but doesn't have an associated PR.

Please can you comment on the status of this item so we know if it could be
included in the [upcoming 2.0 release](https://github.com/kata-containers/kata-containers/wiki/Kata-Containers-2.0-Roadmap)?
