### ISSUE TITLE
Running a privileged container with devicemapper fails

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#606]
This is because the rootfs device node is passed twice and a change in qemu 2.10 prevents this.
With qemu 2.10, a write lock was added for qcow images that prevents the same image to be passed more than once.
This can be over-ridden using the --share-rw option which is desired for raw images.

**Comment by WeiZhang555** [comment]
I observed same failure when I was trying to pass a block device twice to container with
```
$ docker run -ti -v /dev/loop7:/loop7 -v /dev/loop7:/loop71 busybox sh
```

**Comment by bergwolf** [comment]
@amshinde Could you share more details on this? Why is the rootfs dm device passed to the guest twice? I get it that CLI converts the container rootfs mountpoint back to a block device and passes it to the guest. What is the other code path that is passing the rootfs device directly?

**Comment by WeiZhang555** [comment]
@bergwolf if  `--privileged` is specified in docker use case, docker will pass ALL devices including device mapper blocks to container, that's the second path in my understanding.

I observed that `docker run -v /dev/loop7:/loop7 -v /dev/loop7:/loop72 busybox sh` reported same error, but can't reproduce it on master branch any more, that's weird.

**Comment by WeiZhang555** [comment]
> It's because in master with your volume hotplug PR, the volume source devices are now reference counted and not hotpluged to the guest multiple times.

@bergwolf I'm sorry to say that it's not true. The volume with same src will still be hot plugged twice, the reference counter isn't finished and I am trying to add it soon.

**Comment by amshinde** [comment]
@bergwolf @WeiZhang555 Yes, I agree that the right way to handle this is to pass the rootfs just once with the use of reference counting.
However with qemu 2.10, a lock was introduced to ensure that qcow images are not corrupted with share-rw=on. Since we pass raw images, I dont think we need the locking from qemu. 
This PR addresses that : https://github.com/kata-containers/runtime/pull/607
What do you think?

**Comment by WeiZhang555** [comment]
@amshinde That sounds good to me!

**Comment by bergwolf** [comment]
@amshinde Not just qcow images, most storage devices in qemu are now protected by exclusive locking, usb, scsi, ide etc, so that they are not accessed by multiple writers which might cause data corruption.

**Comment by WeiZhang555** [comment]
Found a QMP error when doing `--privileged`, after applying PR #635 

```
Aug 24 10:30:38 zhangwei-pc kata-runtime[32299]: time="2018-08-24T10:30:38.655572376+08:00" level=info msg="Attaching block device" arch=amd64 command=create container=5e992a0d09106819b54a2872d4269b4293721aee1e29ea26777edb3586476f34 device=/dev/sr0 name=kata-runtime pid=32299 source=virtcontainers subsystem=device
Aug 24 10:30:38 zhangwei-pc kata-runtime[32299]: time="2018-08-24T10:30:38.655606572+08:00" level=info msg="{\"arguments\":{\"driver\":\"raw\",\"file\":{\"driver\":\"file\",\"filename\":\"/dev/sr0\"},\"node-name\":\"drive-fb95b38cb11f620c\"},\"execute\":\"blockdev-add\"}" arch=amd64 command=create container=5e992a0d09106819b54a2872d4269b4293721aee1e29ea26777edb3586476f34 name=kata-runtime pid=32299 source=virtcontainers subsystem=qmp
Aug 24 10:30:38 zhangwei-pc kata-runtime[32299]: time="2018-08-24T10:30:38.709354657+08:00" level=info msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"Could not open '/dev/sr0': No medium found\"}}" arch=amd64 command=create container=5e992a0d09106819b54a2872d4269b4293721aee1e29ea26777edb3586476f34 name=kata-runtime pid=32299 source=virtcontainers subsystem=qmp
```

It seems not related to this PR, I can see the share-rw is on as desiged:

```
Aug 24 10:30:38 zhangwei-pc kata-runtime[32299]: time="2018-08-24T10:30:38.64904634+08:00" level=info msg="Attaching block device" arch=amd64 command=create container=5e992a0d09106819b54a2872d4269b4293721aee1e29ea26777edb3586476f34 device=/dev/sda3 name=kata-runtime pid=32299 source=virtcontainers subsystem=device
Aug 24 10:30:38 zhangwei-pc kata-runtime[32299]: time="2018-08-24T10:30:38.649086658+08:00" level=info msg="{\"arguments\":{\"driver\":\"raw\",\"file\":{\"driver\":\"file\",\"filename\":\"/dev/sda3\"},\"node-name\":\"drive-b490070847605ff7\"},\"execute\":\"blockdev-add\"}" arch=amd64 command=create container=5e992a0d09106819b54a2872d4269b4293721aee1e29ea26777edb3586476f34 name=kata-runtime pid=32299 source=virtcontainers subsystem=qmp
Aug 24 10:30:38 zhangwei-pc kata-runtime[32299]: time="2018-08-24T10:30:38.650801287+08:00" level=info msg="{\"return\": {}}" arch=amd64 command=create container=5e992a0d09106819b54a2872d4269b4293721aee1e29ea26777edb3586476f34 name=kata-runtime pid=32299 source=virtcontainers subsystem=qmp
Aug 24 10:30:38 zhangwei-pc kata-runtime[32299]: time="2018-08-24T10:30:38.650875563+08:00" level=info msg="{\"arguments\":{\"bus\":\"scsi0.0\",\"drive\":\"drive-b490070847605ff7\",\"driver\":\"scsi-hd\",\"id\":\"virtio-drive-b490070847605ff7\",\"lun\":12,\"scsi-id\":0,\"share-rw\":\"on\"},\"execute\":\"device_add\"}" arch=amd64 command=create container=5e992a0d09106819b54a2872d4269b4293721aee1e29ea26777edb3586476f34 name=kata-runtime pid=32299 source=virtcontainers subsystem=qmp
Aug 24 10:30:38 zhangwei-pc kata-runtime[32299]: time="2018-08-24T10:30:38.652144094+08:00" level=info msg="{\"return\": {}}" arch=amd64 command=create container=5e992a0d09106819b54a2872d4269b4293721aee1e29ea26777edb3586476f34 name=kata-runtime pid=32299 source=virtcontainers subsystem=qmp
```

And

```
$ ls -l /dev/sr0
brw-rw---- 1 root cdrom 11, 0 Jun 21 09:54 /dev/sr0
```


PR #635 works properly, so this is another issue for supporting `--privileged`
