### ISSUE TITLE
Physical interface hasn't been recovered back to original state

### ISSUE THREAD

**Issue by linxiulei** [kata-containers/runtime#608]
# Description of problem

As far as I know, kata tries to pass through physical interface into vm for better performance by using vfio, in that case when the container teardown kata would bind the physical interface to previous driver except for the network configuration (route, ipaddr, namespace and so on).

In some cases, the network framework (cni/cnm) would tear down the interface no matter what condition they are under, however, for better compatibility with runc, I think it would be better if we recover the physical interface totally to original state.

This issue wouldn't be just physical interface related as well.

# Expected result

# Actual result

---

kata-runtime  : 1.1.0
   commit   : 5aed178ee99298df9e3f17eeaa31a405a1da38d7-dirty
   OCI specs: 1.0.1

**Comment by devimc** [comment]
cc @amshinde  @egernst  @mcastelino @bergwolf @sboeuf

**Comment by mcastelino** [comment]
@devimc in the case of virtual interfaces they are normally deleted. In the case of the physical interfaces you do have a point. We have cases here. 

1. If the physical device was not reprogrammed, but just moved into the namespace. So its network configuration is inherited from the host.
2. If the physical device network configuration was generated by the IPAM and is namespace specific.

As the network interfaces are moved back into the hostname space on teardown, the recovery of the original information is required only in the first case. However we have not seen such a plugin yet.

**Comment by linxiulei** [comment]
@mcastelino thanks for replying. I didn't catch why recovery isn't required in the second case, which is exactly the situation our plugin has trouble with (We rely on detecting interfaces within network namespace). However, it sure can be worked around, I don't think it's a bad idea if we make kata more runc-compatible.

**Comment by mcastelino** [comment]
@linxiulei The recovery is needed to bind it back to the host. It is the network parameter recovery I was talking about.  So https://github.com/kata-containers/runtime/issues/612 is a bug in our implementation and we should fix it. We just assumed all devices that fit the second case are PCI devices which is not true.

**Comment by linxiulei** [comment]
@mcastelino I was talking  about network parameters too (namespace, ip addr, routes and so on). As I mentioned, physical interfaces were bind back to host namespace and the previous driver without any network configuration. What the recovery I want is also set those interfaces into the container network namespace
