### ISSUE TITLE
Virtio network interfaces failed to be bound back to the driver

### ISSUE THREAD

**Issue by linxiulei** [kata-containers/runtime#612]
# Description of problem

In case of physical network interface, the driver would be virtio_net if using a vm as the host (nested virtualized). After the teardown of container, kata tried to bind interfaces back to virtio_net, but there was no path of /sys/bus/pci/drivers/virtio_net/ (actually it should be /sys/bus/virtio/drivers/virtio_net/). There are two ways fixing that:

1. Whenever using a virtio_ driver, we try to use  /sys/bus/pci/drivers/virtio-pci/{bind, unbind} to manipulate interfaces and drivers
2. Whenever using a virtio_ driver, we try to replace bus type from pci to virtio, that is, /sys/bus/virtio/drivers/virtio_net/{bind, unbind}

**Comment by devimc** [comment]
cc @sboeuf @amshinde  @mcastelino @egernst

**Comment by amshinde** [comment]
@linxiulei Yes, our assumption here was the device was a PCI device here. I can take a look at this. Is there a plugin I can use to test this end to end?

**Comment by linxiulei** [comment]
@amshinde  any progress? thanks

**Comment by amshinde** [comment]
@linxiulei This fell off my radar, sorry for the delay. I think have a fix that should solve your issue : https://github.com/kata-containers/runtime/pull/851

I did test out binding and unbinding a virtio-net device in a VM with the above patch.
In case of virtio-net devices, turns out the device driver should be virtio-pci and not virtio-net.
Can you build using the above fix and let me know if it works out for you.

**Comment by linxiulei** [comment]
@amshinde it worked, cheers

**Comment by amshinde** [comment]
@linxiulei Great, glad that worked. We had mainly tested with PCI devices in the past, so I am curious about your use-case for using virtio devices with vfio. Do you mind sharing some details about your usage?

**Comment by linxiulei** [comment]
@amshinde Sure, my use-case is pretty simple, in which I used Alibaba Cloud ECS virtual machine and setup k8s/kata-runtime within, therefore a cni plugin working with Alibaba Cloud ECS virtual network interface was deployed. As a result, a virtual network interface was set into network namespace when a pod was created and kata-runtime would consider it as a passthrough-able interface, unfortunnately I ran into this bug.

**Comment by amshinde** [comment]
thanks @linxiulei 
cc @mcastelino @egernst
