### ISSUE TITLE
virtcontainers: network: Add VFIO network hotplug

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#619]
In order to support fully hotplugged networks, we also need to implement the VFIO net hotplug.

**Comment by dgibson** [comment]
@sboeuf are you talking about VFIO network devices that are used within the container *as* VFIO devices (e.g. by DPDK), or network devices that you want to be bound to kernel network drivers within the Kata guest?

**Comment by sboeuf** [comment]
@dgibson I wrote this a long time ago :) but I think I was talking about network devices that are passed through the VM and bound to the kernel drivers in the guest. It can't be DPDK since I would have mentioned `vhost-user-net` instead of `VFIO`.

**Comment by dgibson** [comment]
Uh, DPDK can use vfio devices as well as vhost-user.

**Comment by sboeuf** [comment]
>DPDK can use vfio devices as well as vhost-user.

DPDK can rely on VFIO devices as their backend but the frontend exposed to the VMM is always a vhost-user socket. Therefore from a Kata perspective, if we're dealing with DPDK, we're effectively interacting with a vhost-user device.

**Comment by dgibson** [comment]
> > DPDK can use vfio devices as well as vhost-user.
> 
> DPDK can rely on VFIO devices as their backend but the frontend exposed to the VMM is always a vhost-user socket. Therefore from a Kata perspective, if we're dealing with DPDK, we're effectively interacting with a vhost-user device.

Hrm... sorry, I'm clear on what you mean by "frontend".  The situation I'm working with is a DPDK based network function running in a VM (created by Kata or otherwise).  That can function perfectly happily with VFIO interfaces with qemu neither knowing nor caring that the PCI devices it passed through happen to be NICs.  I'm guessing you have some different case?

**Comment by sboeuf** [comment]
Yes I was thinking about DPDK from a host perspective.
