### ISSUE TITLE
qemu: can't run kata-containers with qemu 2.8

### ISSUE THREAD

**Issue by woshijpf** [kata-containers/runtime#637]
I used to run kata-container with qemu stable-2.7, which is compiled from kata-container/qemu repo with the configuration by https://github.com/kata-containers/qemu/pull/1.

And now, I want to try more higher qemu version such as qemu 2.8, so I compile qemu stable-2.8 with the same configuration as we used to compile qemu stable-2.7.After compilation, I get a new `qemu-system-x86_64` executable binary file.Next, I configure the qemu binary path in the _/usr/share/defaults/kata-containers/configuration.toml_ file, then run kata-container with following command: 
```
docker run -itd --runtime kata-runtime ubuntu bash
```
However, I get the following error:
```
docker: Error response from daemon: oci runtime error: QMP command failed.
```
I lookup the kata-runtime log, and find the error info is:
```
 level=info msg="{\"arguments\":{\"options\":{\"driver\":\"raw\",\"file\":{\"driver\":\"file\",\"filename\":\"/dev/mapper/docker-8:1-5374032-047376e01b51785eaafb16e94f1e17fe1a144e1f752140486e1edd688c49b87a\"},\"id\":\"drive-bc6a82eff1f6242f0e396867b\"}},\"execute\":\"blockdev-add\"}" arch=amd64 command=create container=bc6a82eff1f6242f0e396867ba1958742175847706325452a5d458a5148d700a name=kata-runtime pid=153841 source=virtcontainers subsystem=qmp
level=info msg="{\"error\": {\"class\": \"GenericError\", \"desc\": \"Parameter 'driver' is missing\"}}" arch=amd64 command=create container=bc6a82eff1f6242f0e396867ba1958742175847706325452a5d458a5148d700a name=kata-runtime pid=153841 source=virtcontainers subsystem=qmp
```

**Comment by woshijpf** [comment]
After analyzing, I figure out the problem is caused by the  `blockdev-add` qmp command interface has changed since the qemu 2.7. And I'm working to solve this issues.

**Comment by jodh-intel** [comment]
That sounds a little odd as it looks like govmm already supports 2.8 (and 2.9), and the runtime is using a version of govmm that supports those versions:

- https://github.com/intel/govmm/blob/master/qemu/qmp.go#L655

/cc @markdryan, @rbradford, @devimc.

**Comment by woshijpf** [comment]
Yes, govmm has encapsulate  qmp command very well, but there exists a little bug.
I find `blockdev-add` and `blockdev-del` qmp command's usages have some difference between qemu 2.7 and qemu 2.8. The document about these two qmp command usage is compiled from qemu source code, if you compile qemu with `--enable-docs`, it will produce the docs file `qmp-commands.txt` about qmp command usage introduction. 

### blockdev-add change

qemu 2.7 `blockdev-add` qmp-command usage
```
blockdev-add
------------

Add a block device.

This command is still a work in progress.  It doesn't support all
block drivers among other things.  Stay away from it unless you want
to help with its development.

Arguments:

- "options": block driver options

Example (1):

-> { "execute": "blockdev-add",
    "arguments": { "options" : { "driver": "qcow2",
                                 "file": { "driver": "file",
                                           "filename": "test.qcow2" } } } }
<- { "return": {} }
```

qemu 2.8 `blockdev-add` qmp-command usage
```
blockdev-add
------------

Add a block device.

This command is still a work in progress.  It doesn't support all
block drivers among other things.  Stay away from it unless you want
to help with its development.

For the arguments, see the QAPI schema documentation of BlockdevOptions.

Example (1):

-> { "execute": "blockdev-add",
    "arguments": { "driver": "qcow2",
                   "file": { "driver": "file",
                             "filename": "test.qcow2" } } }
<- { "return": {} }
```

**From above usages, we can find the biggest difference is that qemu 2.7 `blockdev-add` command argument has `options` field, however  qemu 2.8 `blockdev-add`  does not have.**

But I find the  `ExecuteBlockdevAdd()` function still use `options` in qemu 2.8 which is wrong. (see the code change)

### x-blockdev-del change

qemu 2.7 `x-blockdev-del` qmp-command usage
```
x-blockdev-del
------------
Since 2.5

Deletes a block device thas has been added using blockdev-add.
The selected device can be either a block backend or a graph node.

In the former case the backend will be destroyed, along with its
inserted medium if there's any. The command will fail if the backend
or its medium are in use.

In the latter case the node will be destroyed. The command will fail
if the node is attached to a block backend or is otherwise being
used.

One of "id" or "node-name" must be specified, but not both.

This command is still a work in progress and is considered
experimental. Stay away from it unless you want to help with its
development.

Arguments:

- "id": Name of the block backend device to delete (json-string, optional)
- "node-name": Name of the graph node to delete (json-string, optional)

-> { "execute": "x-blockdev-del",
     "arguments": { "id": "drive0" }
   }
<- { "return": {} }
```

qemu 2.8 `x-blockdev-del` qmp-command usage
```
x-blockdev-del
------------
Since 2.5

Deletes a block device that has been added using blockdev-add.
The command will fail if the node is attached to a device or is
otherwise being used.

This command is still a work in progress and is considered
experimental. Stay away from it unless you want to help with its
development.

Arguments:

- "node-name": Name of the graph node to delete (json-string)

-> { "execute": "x-blockdev-del",
     "arguments": { "node-name": "node0" }
   }
<- { "return": {} }
```

From above `x-blockdev-del` usage, we know the difference between qemu 2.7 and qemu 2.8 is that qemu 2.7 uses `id` to identify blockdevice and qemu 2.8 uses `node-name` to identify blockdevice.

so we need to make some changes in `ExecuteBlockdevDel()` function.(see the code change)

**Comment by woshijpf** [comment]
#644

**Comment by devimc** [comment]
@woshijpf  good find!
