### ISSUE TITLE
Test Kata on various cloud providers

### ISSUE THREAD

**Issue by ydjainopensource** [kata-containers/runtime#658]
Test kata-runtime on a baremetal instances, documenting any issues observed.
Some of the providers we should test on include :
 
- [x] AWS : See #45  
- [x] Vexxhost : x86 CI is deployed on Vexxhost
- [x] Packet.net : CI runs on it so no need to test again
- [ ] Azure 
- [ ] IBM Cloud 
- [ ] Linux One Cloud (provides Linux on Z nodes)
- [ ] Google Cloud  

feel free to add names of other providers here on this.

**Comment by grahamwhaley** [comment]
Just to note - do these have to be bare metal - I believe we can run on any instance that supports nested virtualisation. OK, so I also think maybe not all architectures currently support nested virtualisation (older ARM does not I think, but x86 does for instance).
Should we have some [google cloud](https://cloud.google.com/) item here as well? - we have a [GCE install](https://github.com/kata-containers/documentation/blob/master/install/gce-installation-guide.md) doc already for instance.

**Comment by chavafg** [comment]
Actually our current x86 CI VMs are deployed on vexxhost and not Azure.
