### ISSUE TITLE
virtcontainers: Split virtcontainers into subpackages

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#66]
This issue follows the discussion started [here](https://github.com/containers/virtcontainers/issues/631).
There might be some reasons we want to move to split virtcontainers into smaller packages but I strongly believe that we'll end up modifying everything, which is gonna be very painful, for no effective gain IMO.

Ok, if you think about the way virtcontainers is designed, every interface that does not need to be public is not exported, which is the way it should be. Now if we want smaller packages, let's take an example with `Pod` and `agent`. The implementation of `pod.go` defines the Pod structure, which allows it to access the private fields of the structure `Pod`, and at the same time, some pod functions needs to interact with the agent by doing `agent.createPod(pod)` for instance. So, if you want to separate the agent from the pod, you will end up making your agent a public interface (I don't think that's a good idea because there is no reason to expose this to the public, but let's say we do it), now `pod.go` will have to import the agent as a package. Unfortunately, you will end up with the agent also needing to import virtcontainers (or more specifically what is described in `pod.go`) because it will need to know about the Pod structure definition. This is a cyclic dependency.
One way to workaround this would be to also move the `Pod` definition to a separate package, and you would have a `pod.go`importing both those `pod` and `agent` packages. It works yay ! But is it worth it ??
The entire code will end up being exported (in this case, all fields from `Pod` will be exported).

I think we need some very good reasons if we want to move this way and which benefits we could get from this. Because this is going to take time and effort.

@sameo @markdryan I might have missed a way to achieve this in a simpler way, please let me know if you think that's the case.

**Comment by sboeuf** [comment]
cc @egernst @bergwolf @laijs

**Comment by egernst** [comment]
cc/ @mcastelino
