### ISSUE TITLE
The multi-queue size for network devices should be the same as the number of CPUs.

### ISSUE THREAD

**Issue by amshinde** [kata-containers/runtime#680]
Today we assign a default number of 8 queues since the network code does not have access to the hypervisor configuration. This should be configure to be the same as the number of CPUs passed to qemu for optimal performance.

**Comment by grahamwhaley** [comment]
Hi @amshinde We seem to be moving more and more towards hotplugging CPUs on demand. How will that fit with this? Can we dynamically size the multi-queue for hotplug events for instance?
Just thinking, and was hoping we don't just end up sticking the queue size to 1 for all instances ;-)

**Comment by amshinde** [comment]
Yes, if the cpus are updated while the container is running with something like `docker update`, I dont think we can update the queue size then.
But we should be getting the total number of CPUs that need to be assigned to the Pod/container I think. cc @devimc

**Comment by devimc** [comment]
@amshinde 

> I dont think we can update the queue size then.

in the case of a reduction (ie from 8 to 2 vcpus), do you know if is possible to change the number of queues by using the kernelfs (/proc or /sys) ?

 > But we should be getting the total number of CPUs that need to be assigned to the Pod/container I think.

Yes, that's right
