### ISSUE TITLE
start proxy in vm factory

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#683]
Right now proxy is always started **after** we assign the guest vm to a sandbox. But then we will have to wait again for the proxy to start up. We can move the creation of proxy to vm factory so that new vms are created with configured proxy type, and then wait for both proxy and vm/agent in parallel. This will save about 300ms startup time for vm factory.

**Comment by jodh-intel** [comment]
And that would presumably be a NOP if vsock was enabled?

**Comment by bergwolf** [comment]
@jodh-intel Yes. It does not matter what proxy type is configured. I just called proxy.start() there.
