### ISSUE TITLE
storage: fio test seems to get 'stuck'

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#69]
Running:
```bash
$(pwd)/storage/fio_job.sh -b 16k -o randread -t "storage IO random read bs 16k"
```

inspired from https://github.com/clearcontainers/tests/blob/master/.ci/run_metrics_ci.sh#L134
seems to hang up, and never return (nor generates significant output).
For reference, the test works with `runc` and `cc-runtime`, and takes something like 3m30s to complete (on my local test machine).

Here is the output from my `kata-env`. These were components installed from HEAD on 2018-03-16 (Friday), including a HEAD agent installed in the image:
```
[Meta]
  Version = "1.0.9"

[Runtime]
  Debug = false
  [Runtime.Version]
    Semver = "0.1.0"
    Commit = "de8506d8e5cbcd87b1c40d9121dc24b056d2a26e-dirty"
    OCI = "1.0.1"
  [Runtime.Config]
    Path = "/usr/local/share/defaults/kata-containers/configuration.toml"

[Hypervisor]
  MachineType = "pc"
  Version = "QEMU emulator version 2.7.0, Copyright (c) 2003-2016 Fabrice Bellard and the QEMU Project developers"
  Path = "/usr/bin/qemu-lite-system-x86_64"
  Debug = false
  BlockDeviceDriver = "virtio-scsi"

[Image]
  Path = "/usr/share/kata-containers/kata-containers-2018-03-16-11:36:56.885986052+0000-6899dec"

[Kernel]
  Path = "/usr/share/clear-containers/vmlinuz-4.14.22-86.container"
  Parameters = ""

[Proxy]
  Type = "kataProxy"
  Version = "<<unknown>>"
  Path = "/usr/libexec/kata-containers/kata-proxy"
  Debug = false

[Shim]
  Type = "kataShim"
  Version = "kata-shim version 0.0.1-9745a6a666daaed8d2d0950c52b76ec2799fbcff"
  Path = "/usr/libexec/kata-containers/kata-shim"
  Debug = false

[Agent]
  Type = "kata"
  Version = "<<unknown>>"

[Host]
  Kernel = "4.4.0-104-generic"
  Architecture = "amd64"
  VMContainerCapable = true
  [Host.Distro]
    Name = "Ubuntu"
    Version = "16.04"
  [Host.CPU]
    Vendor = "GenuineIntel"
    Model = "Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz"
```

**Comment by grahamwhaley** [comment]
A little more info.
Killing off the stuck `fio` test seems to then leave parts of the runtime running (possibly all parts - qemu, runtime, proxy, shim etc.), and leaves the vc pod down in `/var/lib/virtcontainers/pods`.
Killing off the runtime parts still leaves the subdir in the pods dir, and having those orphaned pods seems to slow subsequent container launches down.
This may be a vc issue - I have seen a similar thing happen when killing off a cc-runtime `fio` test - but note, the cc-runtime fio tests do complete, so the dangling orphaned pods may not be anything to do with the fio hangup.

**Comment by gabibeyer** [comment]
@grahamwhaley curious if this is a stale issue, or if you continue to see this with fio and vc?

**Comment by grahamwhaley** [comment]
I think we can call this stale @gabibeyer - it's a long time since I tried/saw this, and soooo much has changed in our code since then...
Sure, might be interesting if somebody wanted to try it (like, on virtio-fs backed storage for instance). But, I'll close for now.
