### ISSUE TITLE
Drop cc related code

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#694]
As @jodh-intel mentioned in [his comments](https://github.com/kata-containers/runtime/pull/684/files#r214339043), we might consider dropping all cc related code. This issue is to track the discussion/AI.

**Comment by WeiZhang555** [comment]
This looks good, but needs more opinions from Intel side, see if there're still some customer needs a cc proxy/agent.

**Comment by bergwolf** [comment]
@WeiZhang555 Yes indeed. I create the issue merely to track @jodh-intel's suggestion. I have no objection to keeping cc code as is.

**Comment by sboeuf** [comment]
I have no objection dropping the CC related code from this repo since all the CC code is living on its own repo (github.com/clearcontainers/runtime).
We need @egernst's approval though!

**Comment by caoruidong** [comment]
I have a try. But find it is hard to remove all the CC related code, especially in test files.
