### ISSUE TITLE
kata hotplugs more vCPU than actually needed

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#695]
```
[macbeth@runtime]$docker run --rm -it --runtime kata --cpu-period "1000" --cpu-quota "1000" busybox
/ # nproc
2
```

**Comment by jodh-intel** [comment]
Seeing your hostname reminds me...

- https://en.wikipedia.org/wiki/Shakespeare_Programming_Language :smile:

**Comment by bergwolf** [comment]
After discussing with @devimc, we decided to add a new cli config option to control the behavior.

**Comment by bergwolf** [comment]
@jodh-intel ha, nice link, thanks!

**Comment by gnawux** [comment]
see the full discussion in #696
