### ISSUE TITLE
Add support for 'coldplugging' PCI devices

### ISSUE THREAD

**Issue by eguzman3** [kata-containers/runtime#704]
Some PCI devices (eg. graphics cards) require being passed to the VM at boot time rather than being hotplugged.

**Comment by sboeuf** [comment]
@eguzman3 what's the specific reason why graphics card cannot be hotplugged through qemu ? It's basically some PCI hotplug and I'm curious what's the blocker here.
Also, in order to give you more background, we moved recently away from coldplug, and that's why we need a good reason before to take any decision of moving back to some coldplug codepath.

**Comment by devimc** [comment]
@eguzman3 have you tried with `hotplug_vfio_on_root_bus = true`?
https://github.com/kata-containers/runtime/blob/master/cli/config/configuration.toml.in#L148

**Comment by WeiZhang555** [comment]
Yes, as @sboeuf mentioned, can you give us more details about what kind of device can't be hot plugged?

**Comment by eguzman3** [comment]
Using `hotplug_vfio_on_root_bus = true` seems to work for my specific use case. However, I am a bit confused as to how this configuration option works since the qemu documentation states `The PCI Express root buses (pcie.0 and the buses exposed by pxb-pcie devices)
do not support hot-plug, so any devices plugged into Root Complexes
cannot be hot-plugged/hot-unplugged`.

**Comment by eguzman3** [comment]
It wasn't working before but I have found the issue to be related to device IDs: https://github.com/kata-containers/runtime/issues/708

**Comment by sboeuf** [comment]
@eguzman3 
>wouldn't hotplugging still be an issue with a large number of devices

If you plan to hotplug more than 32 devices, you won't be able to do so. But @amshinde, is it related to hotplug (the fact that we have to plug the PCI devices to the root bus), or is it also valid for cold plug?

>or with devices that have very large PCI BARs because it requires bus padding?

How would it be different than coldplug? I think (need to check Qemu for that) the PCI host bridge reserves a fixed amount of memory for its PCI32 and PCI64 holes.
