### ISSUE TITLE
Add standard signal handling to netmon

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#718]
Once #534 lands, it needs to have the standard signal handling code added so it dumps a backtrace on `SIGUSR1`, etc.

See:

- https://github.com/kata-containers/runtime/pull/534#discussion_r215640451
- #244

**Comment by jodh-intel** [comment]
Ping @sboeuf - would be good to make the netmon a first class citizen wrt signals :)

**Comment by sboeuf** [comment]
@jodh-intel done ;)
