### ISSUE TITLE
kata-env shows incorrect debug values for runtime+hypervisor

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#724]
The output of `kata-env` incorrectly always shows `Debug = false` for both the runtime and the hypervisor.

The other elements all show correct debug values and although the runtime+hypervisor debug value is incorrect, all the debug options in `configuration.toml` are honoured.

**Comment by jodh-intel** [comment]
@sboeuf, @egernst - I think this should go into stable so label added.

**Comment by sboeuf** [comment]
@jodh-intel makes sense!
