### ISSUE TITLE
Think about better ways to replace sleeps in vm template

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#728]
Currently as of #684, there are two arbitrary sleeps when we create the template vm to make sure that:
1. the agent cleans up the current grpc server and ready to accept new connections
2. `vm.Save()` (which is an asynchronous qmp call) completes

It's better (code) if we can think of better ways to replace these arbitrary sleeps. Not an urgent issue though, since it is not on the regular vm creation code path and only happens once.

/cc @sboeuf

**Comment by bergwolf** [comment]
@sboeuf Thanks for the suggestions. TBH, I don't think it justifies the costs (from security and complexity point of view) to have another serial port connection (which also means another grpc service) just for this. Besides it only solves the first part of the sleep.

**Comment by bergwolf** [comment]
@laijs just mentioned to me that we can use qmp `query-migrate` do check the migration status. I'll post a PR to add it. That will allow us to get rid of the second sleep in the code.

**Comment by sboeuf** [comment]
Sounds good :)
