### ISSUE TITLE
StartContainer issue with devicemapper storage-driver

### ISSUE THREAD

**Issue by chenxumsft** [kata-containers/runtime#74]
This issue is unique with devicemapper storage-driver (overlay works fine). I have a crio daemon with /usr/bin/cc-runtime as its runtime. My code is driving the crio via grpc to operate on VM/containers. Now assuming a VM is running a fedora container and nginx container, I used the command “crictl stop” to stop the fedora container. Below is the steps my code would do after detecting the fedora is gone:
 1. Tried to restart the same container id: failed, which is expected.
`StartContainer gRPC error: 2: failed to start container 4a30e457dc825531644d201206750c19fecbe079b88cf6ba91a08915366a0a7a: '/usr/bin/cc-runtime start 4a30e457dc825531644d201206750c19fecbe079b88cf6ba91a08915366a0a7a' failed: exit status 1`
 
2. Tried to remove the container: failed but we ignore the failure.
`gRPC error: 2: failed to delete container 4a30e457dc825531644d201206750c19fecbe079b88cf6ba91a08915366a0a7a: '/usr/bin/cc-runtime delete --force 4a30e457dc825531644d201206750c19fecbe079b88cf6ba91a08915366a0a7a' failed: Container not ready or stopped, impossible to delete (exit status 1)`
 
3. After 10 seconds, tried to create a new container: CreateContainer succeeded. 
 
4. Tried to start the new container: **StartContainer failed, which is unexpected**.
`failed to start container 36f685921bded0484871b1a6051554e837fd306b43e1e9d25cc85b94acdd9b20: '/usr/bin/cc-runtime start 36f685921bded0484871b1a6051554e837fd306b43e1e9d25cc85b94acdd9b20' failed: exit status 1`

The syslog has this error during that period: 
`cc-runtime[28819]: time="2018-03-19T15:22:37.854147224-07:00" level=error msg="Failed to start container" arch=amd64 container-id=36f685921bded0484871b1a6051554e837fd306b43e1e9d25cc85b94acdd9b20 error="ERROR received from VM agent, control msg received : Timed out waiting for device vde" pod-id=14347b0d546b45543597c26ff456e5b35f5adca166e2541befcab1cb05fed025 source=virtcontainers subsystem=container`

**Comment by amshinde** [comment]
@chenxumsft What version of cc-runtime are you running? You can find that out with `cc-runtime --version`

I would like to see if you face the same issue with the `scsi` support we have added recently.
Can you try this with the latest packages published on OBS, and switch to virtio-scsi driver to see if you face the same issue. Your /usr/share/defaults/configuration.toml file should contain the following for the `block_device_driver` configuration
```
block_device_driver = "virtio-scsi"
```

**Comment by chenxumsft** [comment]
The version I was using is 3.0.19. 
cc-runtime  : 3.0.19
   commit   : 0bada71fce8816a882f3dc848b07fb05d1512d6b
   OCI specs: 1.0.1
After upgrading (to 3.0.22), it worked! Thanks.
