### ISSUE TITLE
When can support macvlan?

### ISSUE THREAD

**Issue by coos** [kata-containers/runtime#754]
When can support macvlan?

**Comment by sboeuf** [comment]
@coos here is the PR that is work in progress regarding MACVLAN: https://github.com/kata-containers/runtime/pull/506
@amshinde is working on it!

**Comment by coos** [comment]
Thank you, I have been waiting for a long time.

**Comment by caoruidong** [comment]
#506 is merged. Close this.

**Comment by coos** [comment]
very good，thanks
