### ISSUE TITLE
network: AddInterface only supports VirtualEndpoints

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#758]
If we look at the way `AddInterface()` has been implemented, it will always create a `virtualEndpoint`, no matter the type of device backing the interface that we're trying to add. Unfortunately, this means neither `vhost-user` nor `vfio` can be leveraged in this case.

This needs to be fixed either by adding a new field `devType` to the `grpc.Interface` structure passed as an argument of `AddInterface()`, or by adding a new argument `devType` directly to the function itself.

@bergwolf @caoruidong @WeiZhang555 @amshinde WDYT?

**Comment by WeiZhang555** [comment]
This is a necessary enhancement, +1 to this.

Maybe it's better to modify parameter from `grpc.Interface` to some wrapper structure, because `grpc.Interface` is structure between runtime and agent, I think it's not very good to expose directly to client users

**Comment by bergwolf** [comment]
+1 for this feature. We defly need it.

OTOH, the grpc interface is for communication between runtime and agent, in which case no matter what kind of interface is added, they would appear the same just as a local network card to a guest. So I'd prefer to add it outside of `grpc.Interface`.

And I agree with @WeiZhang555 that it's better not to expose internal data structures (between runtime and agent) to kata API consumers.

**Comment by sboeuf** [comment]
Well the thing about this structure is that it should be defined outside of the agent so that it can be imported from the agent and from the runtime. This way, it's not only an internal structure shared between runtime and agent only.
But I don't know which package/repo would be the most appropriate for that. Maybe `kata-containers/runtime/pkg/types`

**Comment by caoruidong** [comment]
Yes. Sorry this is actually a defect in my implementation. Code originally comes from https://github.com/kata-containers/runtime/blob/611158ac54812ace1c20f5266626d47462fc870d/virtcontainers/network.go#L1334-L1357. Should we follow these old code or the way @sboeuf said?

**Comment by bergwolf** [comment]
@sboeuf Oh, please do not split it from agent. We already suffer a lot by having to maintain govmm in a separate repo and every time we need something from qemu we have to do it in two PRs :( I would appreciate it if we keep protocol definition inside the agent repo where the grpc server is implemented.

Besides, the grpc types between runtime and agent should be kept minimal -- we only add fields we need there. So I tend to agree with @WeiZhang555 that we do not export the grpc types in runtime API, and let runtime do its conversion when necessary. So yes, we can have a `runtime/virtcontainers/pkg/types` package and let kata APIs use it. But virtcontainers needs to internally convert the new types to grpc types when talking to the agent. This would allow us to add more fields in the runtime API that are not needed between runtime and agent.

**Comment by sboeuf** [comment]
>Oh, please do not split it from agent. We already suffer a lot by having to maintain govmm in a separate repo and every time we need something from qemu we have to do it in two PRs :( I would appreciate it if we keep protocol definition inside the agent repo where the grpc server is implemented.

I understand but what about the case where we want to import those structure definitions without pulling the entire grpc with it. I'm mentioning this as I had the bad experience with `kata-netmon`, and I had to duplicate the structure definition because I didn't want the size of the binary to bump from 4Mib to 11Mib....
Can you think of any way of solving this without extracting those (Interface and Route) structure definition out of the agent grpc?

**Comment by WeiZhang555** [comment]
@sboeuf If the components want to talk to kata-agent, they will always need to import grpc structure in my understanding, I can't think of a way to bypass this.

But take `netmon` as an example, if it uses `kata-runtime cli` or `virtcontainers/` API, I think we can always choose a wrapper structure in `virtcontainers/pkg/types` and let virtcontainers do the translation to `grpc.Interface`

**Comment by WeiZhang555** [comment]
In other words, https://github.com/kata-containers/runtime/blob/master/netmon/netmon.go#L27-L60 This piece of code in netmon can be put in `virtcontainers/pkg/type` and can be shared between netmon and kata-runtime cli and virtcontainers API

**Comment by WeiZhang555** [comment]
> We already suffer a lot by having to maintain govmm in a separate repo and every time we need something from qemu we have to do it in two PRs :( 

And I have to agree with @bergwolf on this, this is often painful and it happens a lot. Just want to complain a bit :-(
If Intel can move it into `virtcontainers/` directly I will be so happy, but this is not a strong request because it's Intel's project and your choice :-)   @sboeuf

**Comment by bergwolf** [comment]
@sboeuf I think @WeiZhang555 has made good enough points and I don't have any more to add :)
