### ISSUE TITLE
How to deal with the Default Setting variables for cli configure

### ISSUE THREAD

**Issue by lifupan** [kata-containers/runtime#787]
# Description of problem

When I try to refactor the cli codes, especially the codes for the "config", and I want to
put those codes into a separated package such as "clilib", but I found those defaults variables
are dynamically produced by Makefile, my questions is how to deal with those defaults variables,
still make them dynamically produced by Makefile or just defined them in a separated file in the package? 
 
If we still want to make them dynamically produced into the "clilib" package, then this package cannot
not be vendored into other projects; In addition, for those dynamically produced variables, some will be referenced by "clilib" and some will be referenced by cli, thus we should produce two files, one is located in "clilib", and the other one is located in cli, thus would it be too complex? 

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by jodh-intel** [comment]
I guess we could hard-code `systemdUnitName`, but the following I don't think we can:

- `defaultRuntimeConfiguration`: uses `PREFIX` which needs to be set for building packages:
  - https://github.com/kata-containers/packaging/blob/master/obs-packaging/runtime/debian.rules-template#L36..L40
  - https://github.com/kata-containers/packaging/blob/master/obs-packaging/runtime/kata-runtime.spec-template#L90..L95

  Admittedly, we set it to `/usr`, but... ;)

- `defaultSysConfRuntimeConfiguration`: hard-coded in the `Makefile` to use a `/etc` prefix, but can be overridden at build time (we don't do this, but it could still be useful for others).
- `defaultRootDirectory`: hard-coded in the `Makefile` to use a `/var` prefix, but can be overridden at build time (we don't do this, but it could still be useful for others).

Random thought: we *could* provide a `config-settings.go` [*] which contains all these variables in their hard-coded form along with a build rule that will only recreate that file *iff* the build is run with something like:

```
# recreate "config-settings.go"
$ make FORCE_CUSTOM_CONFIG=1 PREFIX=/weird ...
```

@jcvenegas will probably have more insight here.

/cc @chavafg, @egernst.

---
[*] - `config-settings.go` would be the same as `config-generated.go` but with a better name given that for most users, they won't need to touch it and it will already exist :)

**Comment by lifupan** [comment]
Hi @jodh-intel, based on your input, I agree to keep defaultSysConfRuntimeConfiguration and defaultRootDirectory in Makefile, since defaultSysConfRuntimeConfiguration will be used by configure file parsing codes, which I'd like to put into a separated package, thus I think we can extract the configure file path finding codes from config.go and put it into main package, and make the file path
as an input to configure parsing function, thus we could separate all of those dynamically created variables from the library package.

**Comment by jodh-intel** [comment]
wdyt @bergwolf, @sboeuf, @grahamwhaley?
