### ISSUE TITLE
Use memory ballooning when memory is reduced

### ISSUE THREAD

**Issue by jcvenegas** [kata-containers/runtime#790]
# Description of problem

When the memory is updated to be reduced today update a memory cgroup inside of the VM this
will prevent the process keep using more memory but if the VM already took the memory before reduce it we never take back memory to the host. 

# Expected result

Ask the VM to return  reduced memory from the VM.

To do this we should start the VM with balloon enabled.
When the memory is updated (via memory update or delete container) request via QMP.

# Actual result

The memory keeps as part of the Guest. 
---
\cc @clarecch  @linzichang @bergwolf

**Comment by sboeuf** [comment]
@jcvenegas is the `virtio-balloon` capable of keeping a specific size? I'm asking because the risk I see using ballooning here is that we will rely on the host to make choices about the size of the balloon for our several VM(aka containers).
And if we think about the case where all guests need the full amount of memory from their own VM, the host will adjust the balloon for some VMs, meaning some other will run out of memory.
I'm worried that ballooning will generate some bad QoS in such cases.

**Comment by jcvenegas** [comment]
@sboeuf  the idea is to send a qmp command  to reduce guest memory here
`qemu.hotplugMemory(remove, memory_bytes)`
https://github.com/kata-containers/runtime/blob/master/virtcontainers/qemu.go#L1057

**Comment by sboeuf** [comment]
@jcvenegas yes as I discussed online, this makes sense ;)

**Comment by clarecch** [comment]
@jcvenegas What's the difference between return memory and hot remove memory?

**Comment by grahamwhaley** [comment]
@clarecch I my understanding:
- hot remove memory removes the memory (DIMM/slot) from the guest memory map. When you do a `free` in the guest you will see the 'total' go down. You are effectively 'physically unplugging' memory in the guest machine. Once the memory is removed, all the physical host side memory backing up that DIMM/slot should be handed back to the host as 'free'.
- return memory (ballooning) finds the empty/un-used memory in the guest (memory that no process is using), and unmaps the physical memory on the host side that is 'backing' that memory.  When you do 'free' in the Guest, you will see no difference - but, the memory listed in the 'free' column may now not have any physical host memory backing it. The benefit here is that memory that VMs are not actually using can be passed back to the host, and used by other VMs. Running 'free' on the Host, you hould see the 'free' column number increase.

Both of these are tricky for different reasons :-)

**Comment by clarecch** [comment]
Thanks for your explanation@grahamwhaley , very fascinating.

**Comment by grahamwhaley** [comment]
:-) I should also add (as it popped into my head)...
for hotunplug, the granularity is a whole 'slot', which tends to be relatively large. To unplug it, all use of the physical space in the guest needs to be undone (so, process pages in the guest moved/migrated out of the slot), which is hard, costly, and sometimes maybe not possible (if something is pinned there for insance - hopefully that never happens...).
For ballooning, iirc the granularity is on a page size - that is, the smallest item you can 'hand back' to the host is a single page. Generally you try not to hand back single pages, as each hand-back is a VM exit call, and costs - so ideally you collect up which pages are free and hand them back as a batch and as ranges of linear free pages.

**Comment by jcvenegas** [comment]
@clarecch @grahamwhaley just as correction when you decrase the memory with the ballon and do `free ` the memory information is updated. So you can not use more than the restricted memory:

```bash
docker run -ti --name kata-1 -m 2G --rm --runtime kata-runtime ubuntu bash
root@6997525a84e9:/# free -h
              total        used        free      shared  buff/cache   available
Mem:           1.9G         21M        1.9G        8.2M         18M        1.9G
Swap:            0B          0B          0B
#do qmp call to reduce memory to 1G in the host.
root@6997525a84e9:/# free -h
              total        used        free      shared  buff/cache   available
Mem:           971M         21M        931M        8.2M         18M        919M
Swap:            0B          0B          0B
```
