### ISSUE TITLE
Network hotplug of v1.3.0 can not be used

### ISSUE THREAD

**Issue by miaoyq** [kata-containers/runtime#800]
# Description of problem

I download the [kata-static-1.3.0](https://github.com/kata-containers/runtime/releases/download/1.3.0/kata-static-1.3.0-x86_64.tar.xz), and test the network hotplug with docker. but I did not see the `kata-netmon` process after creating a container, and with following error:
```
Sep 29 08:00:07 paas-controller-22-0-2-10 kata-runtime[677]: time="2018-09-29T08:00:07.9915428+08:00" level=error msg="Container ID (ab6420fa5e40e24e27e21bc9f6d3fd6ccd9feb7fbd82545470e47ea9b18e9e30) does not exist" arch=amd64 command=kata-network name=kata-runtime pid=677 source=runtime
Sep 29 08:00:07 paas-controller-22-0-2-10 kata-netmon[48974]: time="2018-09-29T08:00:07.993110399+08:00" level=fatal msg="handleEvents()" error="exit status 1" name=kata-netmon pid=48974 sandbox=ab6420fa5e40e24e27e21bc9f6d3fd6ccd9feb7fbd82545470e47ea9b18e9e30 source=netmon
```
(`kata-netmon` is compiled from source code, because there are no `kata-netmon` in static packages )

I have enabled the netmon, the config:
```
[netmon]
# If enabled, the network monitoring process gets started when the
# sandbox is created. This allows for the detection of some additional
# network being added to the existing network namespace, after the
# sandbox has been created.
# (default: disabled)
enable_netmon = true

# Specify the path to the netmon binary.
path = "/opt/kata/libexec/kata-containers/kata-netmon"

# If enabled, netmon messages will be sent to the system log
# (default: disabled)
enable_debug = true

[runtime]
# If enabled, the runtime will log additional debug messages to the
# system log
# (default: disabled)
enable_debug = true
#
```

Is there anything wrong with my configuration? 
@sboeuf @caoruidong @bergwolf 

---

Full logs:  [kata.log](https://github.com/kata-containers/runtime/files/2430062/kata.log)

**Comment by caoruidong** [comment]
Looks like before container fully starts, netmon receives an event and do "update-route". 
```
Sep 29 21:55:24 localhost.localdomain kata-netmon[31069]: time="2018-09-29T09:55:24.325633877-04:00" level=debug msg="handleRouteEvent: netlink event received" name=kata-netmon pid=31069 sandbox=01ddfa442db99b3c143c2fce90d72e3a7969495bf0ad8b2bbdab7ad01e894c7c source=netmon
Sep 29 21:55:24 localhost.localdomain kata-netmon[31069]: time="2018-09-29T09:55:24.325724511-04:00" level=debug msg=RTM_NEWROUTE name=kata-netmon pid=31069 sandbox=01ddfa442db99b3c143c2fce90d72e3a7969495bf0ad8b2bbdab7ad01e894c7c source=netmon
Sep 29 21:55:24 localhost.localdomain kata-netmon[31069]: time="2018-09-29T09:55:24.325858635-04:00" level=debug msg="Routes converted" routes="[]"
Sep 29 21:55:24 localhost.localdomain kata-netmon[31069]: time="2018-09-29T09:55:24.326094887-04:00" level=debug msg="Running runtime command" command="&{/root/go/src/github.com/kata-containers/runtime/kata-runtime [/root/go/src/github.com/kata-containers/runtime/kata-runtime kata-network update-routes 01ddfa442db99b3c143c2fce90d72e3a7969495bf0ad8b2bbdab7ad01e894c7c /var/run/kata-containers/netmon/sbs/01ddfa442db99b3c143c2fce90d72e3a7969495bf0ad8b2bbdab7ad01e894c7c/shared.json] []  <nil> <nil> <nil> [] <nil> <nil> <nil> <nil> <nil> false [] [] [] [] <nil> <nil>}" name=kata-netmon pid=31069 sandbox=01ddfa442db99b3c143c2fce90d72e3a7969495bf0ad8b2bbdab7ad01e894c7c source=netmon
```
 But as container not started, container id mapping has not been set up. Get error here https://github.com/kata-containers/runtime/blob/a786643d0b3c0195deeb6ef5d4c2a161009a80aa/cli/oci.go#L76-L85
I will dig more.

**Comment by sboeuf** [comment]
Hi @miaoyq, your configuration looks fine to me, and I am not sure the issue comes from `kata-netmon` here.
First thing, I have opened the package [kata-static-1.3](https://github.com/kata-containers/runtime/releases/download/1.3.0/kata-static-1.3.0-x86_64.tar.xz) and I could find `kata-netmon` inside `./opt/kata/libexec/kata-containers/kata-netmon`, so please use the binary from there.
Second thing, make sure you have the appropriate image with the right `kata-agent`, otherwise it could not be compatible.

**Comment by egernst** [comment]
Any updates here @miaoyq ?

**Comment by miaoyq** [comment]
@egernst I've found the problem, that's because I used the docker version(v12.06) too old, it worked well after changing the docker to v18.06.

**Comment by miaoyq** [comment]
I will close the issue.
