### ISSUE TITLE
Kata support mount&umount host directory dynamically in running state

### ISSUE THREAD

**Issue by bekars** [kata-containers/runtime#808]
## TARGET

To support mount&umount host directory(on block device) dynamically into kata container when kata container is in running state.

There is a similar implementation in docker: [docker-mount-dynamic-volumes] (https://jpetazzo.github.io/2015/01/13/docker-mount-dynamic-volumes/), hoping to achieve similar functionality in kata.

In a scenario such as FaaS, you can start some kata containers in advance, and then mount the function directory to be run as needed, thus increasing the startup speed of the FaaS container.

## Implementation in docker

1. Enter the container namespace to mount the host block device to a temporary directory - /tmpmnt;
2. Mount the host's directory to the directory in the container by mount bind;
3. Umount the temporary directory(/tmpmnt) of the container;

Refer to the implementation command:

```
$ docker-enter $CONTAINER_ID -- mknod --mode 0600 /dev/block-mount $DEV_major $DEV_minor
$ docker-enter $CONTAINER_ID -- mkdir /tmpmnt
$ docker-enter $CONTAINER_ID -- mount /dev/block-mount /tmpmnt
$ docker-enter $CONTAINER_ID -- mkdir -p /runtime
$ docker-enter $CONTAINER_ID -- mount -o bind /tmpmnt/runtime /runtime
$ docker-enter $CONTAINER_ID -- umount /tmpmnt
$ docker-enter $CONTAINER_ID -- rm -rf /tmpmnt
```

## Perspective of this feature from start time comparison

| startup time(ms)\container | Docker(runc) | KATA |
| --- | --- | --- |
| Start Container runtime | 526ms | 1501ms |
| Pre-Boot Container + docker cp runtime(100MB) | 441ms | 463ms |
| Pre-boot container + dynamic mount runtime | 155ms | ??? |

It can be seen that by pre-booting the container and then dynamically mounting the host‘s directory, the startup speed of the FaaS is greatly optimized.

so we hope dynamic mount directory working under pre-boot mode can help to optimize the startup time in FaaS scenario.

**Comment by jodh-intel** [comment]
Hi @bekars - thanks for raising! If I'm understanding this correctly, you are interested in a new feature that would be specific to the Kata runtime to allow block devices to be added to a running container. If so, we could handle that by adding a new Kata-specific sub-command like:

```
$ kata-runtime kata-storage [container] [add | remove | list | ...]
```

That would allow you to create a container in the normal way, and then do something like the following:

```
$ sudo kata-runtime kata-storage "$cid" add /dev/block-mount:/runtime
```

That `add` verb would work something like `docker run -v ${host_blockdev_path}:${container_path}` but would of course be setting up the mount after the container was started.

I'm not quite clear on the table you've added though - are you saying you would like containers to use block devices but want to defer mounting them to minimise boot time for a particular scenario?

/cc @bergwolf, @sboeuf, @amshinde, @egernst, @mcastelino.

**Comment by sboeuf** [comment]
@bekars 
IIUC, we want to support the hotplug of a storage device here. We already support device hotplug `AddDevice()` from the virtcontainers API, and the only thing we would need for this use case would be to add a very similar function `AddStorage()` using most of the code already there. From the agent, we already have all the code to handle the mount of a device being passed through the VM, so this should not  require any change IMO. The remaining part being (as mentioned by @jodh-intel) the addition of a new CLI command, which should follow the same model used for network hotplug.

As @jodh-intel, I'm not clear on the rationale behind this performance comparison table.

Adding @WeiZhang555 to the discussion as he implemented `AddDevice()` and should be able to provide some good feedback here.

**Comment by zhiminghufighting** [comment]
@jodh-intel  Per my understanding, bekars hope to mount host directory into kata container such as:
docker run -v host_directory:kata_directory;
you list the sub-command such as:
sudo kata-runtime kata-storage "$cid" add /dev/block-mount:/runtime
it only includes mounting the block device into kata, the better way is to include mounting directory into kata.
thanks for your inputs!

**Comment by bekars** [comment]
@jodh-intel 
We want to mount a host directory in a running kata container. Like @zhiminghufighting said.

I think the right step should be:

`$ sudo kata-runtime kata-storage "$cid" add /dev/block-mount:/runtime`
`$ sudo kata-runtime exec "$cid" mount -o bind /runtime/codedir:/codedir`
`$ sudo kata-runtime kata-storage "$cid" remove /runtime`

I hope only the /codedir directory to be visible in the container, but not the contents of other directories on /dev/block-mount.

What I want to explain in the table is that in the case of pre-starting the container, the mount is the fastest, followed by docker cp.

@WeiZhang555 

In this design I want to make the container runtime environment start up faster, so we have to pre-start the container and then mount the corresponding function code when we need to do the computation, so that we can process the incoming request faster. The container is destroyed after the function finished running. I think start up faster is a generic feature here.

Thanks for your reply.

@sboeuf @WeiZhang555 @zhiminghufighting

**Comment by jodh-intel** [comment]
> I hope only the /codedir directory to be visible in the container, but not the contents of other directories on /dev/block-mount.

If you only want the container to access `/codedir`, we'd need something like a `kata-storage bind` command:

```
$ sudo kata-runtime kata-storage "$cid" add /dev/block-mount:/runtime
$ sudo kata-runtime kata-storage bind "$cid" /runtime/codedir:/codedir
$ sudo kata-runtime kata-storage "$cid" remove /runtime
```

That way, all `kata-storage` operations would happen in the guests root namespace context, but the `bind` would then effectively "share" the `/runtime/codedir/` resource into the container namespace. The `$cid` parameters in the `add` and `remove` commands above would simply be used to determine the correct sandbox (VM) that the container was running inside of.

**Comment by mcastelino** [comment]
> `$ sudo kata-runtime exec "$cid" mount -o bind /runtime/codedir:/codedir`

Will the mount command actually work without additional permission?

**Comment by bergwolf** [comment]
Since we are considering to add our own subcommand, let's not depend on the OCI spec and just do:
1. `sudo kata-runtime storage add -s "$sandboxid" -c "$cid" -v <source-device>:<guest-dir>` and upon success it prints a new volume id to identifies the <source-device, guest-dir> mapping.
2. `sudo kata-runtime storage remove -s "$sandboxid" -c "$cid" "$volume-id"`. It unmounts the corresponding mount point from the guest and unplugs the device if it is not used by other volumes. 

Above works if the source-device is owned by a single container.

However, since @bekars said `I hope only the /codedir directory to be visible in the container, but not the contents of other directories on /dev/block-mount.`, I'm not sure `kata-runtime storage` subcommand is even needed. If @bekars can do the following:
1. start container with `docker run -v /runtime:/guest-dir`
2. mount `/dev/block-mount` to `/host-dir` on the host
3. bind mount `/host-dir/codedir` to `/runtime/codedir` on the host

Then the container can access its code dir at `/guest-dir/codedir`. And it seems to me that the requested `prestart+dynamic mount runtime` is implemented. WDYT @bekars ?

**Comment by bekars** [comment]
@bergwolf 
Thanks for your reply, it is a very cool idea. I have tested it. The mount bind directory which on the host can be accessed in the kata container. I will do some detailed tests later.

**Comment by zhiminghufighting** [comment]
@bekars does bergwolf's idea solve your questions and requirement?

**Comment by caoruidong** [comment]
Yes. Mount propagation can also help.

**Comment by bekars** [comment]
@zhiminghufighting  
it is worked for us now.

**Comment by zhiminghufighting** [comment]
@mcastelino per my understanding, kata use 9p to share three files from host to sandbox. if i use such cmd to mount host volume with mount_tag to guest(mount -t 9p -o trans=virtio kataShared /host/share:/guest/share -oversion=9p2000.L) , it will report "mount: permission deny", is it related with you mentioned "additional permission"? 
Thanks a lot!

**Comment by zhiminghufighting** [comment]
@bekars do you implement any stress test in your production environment about the solution of bergwolf? thanks!
