### ISSUE TITLE
I/O: enable setting of cache modes on IO devices

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#810]
# Description of problem

Presently kata/virtcontainers/govmm hard wires (or rather, does not wire at all) the cache mode for any disk mounts, and thus uses whatever the system defaults are (which generally means the QEMU defaults for the type of IO device afaict, but for many that I believe is writeback).

That is probably mostly fine as is, but:
- we should probably clearly document it
- we should probably allow the user to configure it (possibly as a single global type, or possibly on a per-type basis, such as 9p and block types)
- we should probably discuss if leaving the kata default as the QEMU default is the right thing to do for Kata. This came to my mind from doing some IO testing, where I realised we currently make use of the host side page cache, which felt like a duplication and possible inefficiency. I believe some VM vendors out there suggest cache=none to be used.

For ref, there is a thread and a little hack I made over here 
https://github.com/kata-containers/tests/issues/560#issuecomment-415038847

My gut feeling is that we should allow user configuration, but leave the default as the default (of QEMU), as how that interacts can depend on the guest kernel and workload.

/cc @jon @dargh for domain knowledge input
/cc @amshinde @mcastelino for other thoughts etc.

**Comment by mcastelino** [comment]
@grahamwhaley we should also set it up properly for the scsi-disk. Today we cache at both ends in the case of scsi-disk

```
scsi-disk.write-cache=OnOffAuto
```

**Comment by grahamwhaley** [comment]
@mcastelino - right - cache at both ends was what got me thinking about this in the first place - seeing that when I ran a direct-IO test in the container, under some circumstances I still got the pagecache-bandwidth level of results (from the host cache).
Do you have an opinion what the 'right' setup is? It may be different for different mount types. I will moot:

1) for block mount devices (devicemapper, scsi-disk), we cache only in the guest, and disable host side cacheing by default
2) for 9p, we do not cache in the guest (by design, as I believe 9p cacheing in the guest comes with its own sync problems), so we should cache at the host (which is what I believe we get by default for 9p today).

**Comment by mcastelino** [comment]
@grahamwhaley IMO and I am not an expert here. We should disable the caching on the host side (i.e. in QEMU device side). Within the guest the application typically makes the choice of using or bypassing the page cache. And using this method honors the guest's request. So the user/application gets the right behavior.

Also normally QEMU lets you control caching for write (and not always for read) as in the case of scsi-disk. 
But that is fine as it does not have any downside.

**Comment by grahamwhaley** [comment]
I agree - if we believe that the guest stack is modern, sane, and 'doing the right thing'(tm) wrt direct and flushing, then disabling the host side cache I think should be our default. But, we do also want to add the ability for the user to over-ride/configure this in the config file if they need.
I'll see if I get to this - might not be in the next few days. If anybody else wants to leap on this, please note here and we can assign the Issue.
Useful deck from our friend @stefanha [here](https://events.static.linuxfound.org/slides/2011/linuxcon-japan/lcj2011_hajnoczi.pdf). May be from 2011, but still reads relevant.
