### ISSUE TITLE
Get VM container real metric

### ISSUE THREAD

**Issue by Ace-Tang** [kata-containers/runtime#822]
# Description of problem

I am working on some container metric things, found that docker/pouch can not get right kata container metric informations. because if we use runc container, docker can get cpu/memory/pid/blkio infomation from cgroup and proc/stats on the host, but for kata, since it is a vm, we can not get information from host, if we want to get right things, we should get the file inside vm.

Here I think about a simple and crude way to get this information. Get file through exec command, and resolve the data in the pouch side, filling container metric with this thing. 

I am not get better idea for how to get metric in kata container, so I want to ask for some help here, thanks.

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by bergwolf** [comment]
Does `kata-runtime events` subcommand satisfy your needs? https://github.com/kata-containers/runtime/blob/master/cli/events.go#L119. Please try to expand the same interface if you see any missing pieces.

**Comment by Ace-Tang** [comment]
This is really gooood !

**Comment by jshachm** [comment]
Glad that helps you ^ ^ @Ace-Tang

**Comment by Ace-Tang** [comment]
thanks for @jshachm , now seems still can't get real metric through containerd. I have paste the reason on containerd issue https://github.com/containerd/containerd/issues/2722, could you offer more help.
/cc @lifupan , since you are implement the shim v2 api now, I think you can offer some help. Thank.

**Comment by crosbymichael** [comment]
The v2 runtime that the kata should would implement has a custom proto.Any for metrics types.  It is up to the shim to provide metrics how they see fit.  It shouldn't be an issue.

https://github.com/containerd/containerd/blob/master/runtime/v2/task/shim.proto#L33

**Comment by Ace-Tang** [comment]
Thanks for all yours help, I think https://github.com/kata-containers/runtime/pull/572 can satisfy my need, I will do more test on this.

**Comment by Ace-Tang** [comment]
I do some test with the container shim v2 API feature, seems good to run, and I can get kata real metric then, what is this pr's status now ?

It is weird I can not leave a comment under that PR, so I reopen this issue.
