### ISSUE TITLE
Hotplug GPU vfio device into qemu vm failed

### ISSUE THREAD

**Issue by woshijpf** [kata-containers/runtime#850]
# Description of problem

I have a GPU device in host and I use vfio to passthrough this GPU into kata-container's VM, however it does not work.

kata-runtime version: 
```bash
kata-runtime  : 1.3.0
   commit   : a786643d0b3c0195deeb6ef5d4c2a161009a80aa
   OCI specs: 1.0.1
```

qemu version: QEMU emulator version 2.8.1

# Expected result

hotplug GPU vfio deivce into VM success and doesn't have the errors in kata-proxy log.

# Actual result

I get the following error in kata-proxy logs:
```
# journalctl -t kata-proxy
...
[    7.589853] pci 0000:01:02.0: [10de:1bb3] type 00 class 0x030200
[    7.590223] pci 0000:01:02.0: reg 0x10: [mem 0x00000000-0x00ffffff]
[    7.590599] pci 0000:01:02.0: reg 0x14: [mem 0x00000000-0x0fffffff 64bit pref]
[    7.590994] pci 0000:01:02.0: reg 0x1c: [mem 0x00000000-0x01ffffff 64bit pref]
[    7.592150] pci 0000:01:02.0: BAR 1: no space for [mem size 0x10000000 64bit pref]
[    7.592386] pci 0000:01:02.0: BAR 1: failed to assign [mem size 0x10000000 64bit pref]
[    7.592569] pci 0000:01:02.0: BAR 3: no space for [mem size 0x02000000 64bit pref]
[    7.592752] pci 0000:01:02.0: BAR 3: failed to assign [mem size 0x02000000 64bit pref]
[    7.592937] pci 0000:01:02.0: BAR 0: no space for [mem size 0x01000000]
[    7.593241] pci 0000:01:02.0: BAR 0: failed to assign [mem size 0x01000000]
```

p.s: I have plug block device use `virtio-blk`  driver successfully.

**Comment by sboeuf** [comment]
Hi @woshijpf, please could you try with this [flag](https://github.com/kata-containers/runtime/blob/master/cli/config/configuration.toml.in#L153) enabled?
This allows VFIO devices to be hotplugged directly to the main bus, which has more space for PCI holes.

**Comment by woshijpf** [comment]
@sboeuf Thanks！I enable `hotplug_vfio_on_root_bus = true` this flag and GPU vfio device hotpulg into VM successfully.
