### ISSUE TITLE
Add xurls to versions database

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#854]
Add the [`xurls`](https://mvdan.cc/xurls/cmd/xurls) utility to the versions database to avoid the need to use a very new version of golang (in the stable branches).

For a summary of the time we've burnt on fixing xurls, see https://github.com/kata-containers/kata-containers/issues/32.

**Comment by caoruidong** [comment]
So can we close this？

**Comment by grahamwhaley** [comment]
I think we can - it is over at https://github.com/kata-containers/tests/blob/master/versions.yaml#L41 and merged already.
OK @jodh-intel ?

**Comment by jodh-intel** [comment]
Yep - this was fixed on https://github.com/kata-containers/tests/pull/856.
