### ISSUE TITLE
Network：the network added via hotplug is not available when machine=q35

### ISSUE THREAD

**Issue by miaoyq** [kata-containers/runtime#861]
# Description of problem

I set `machine_type = q35`, and created a kata container.
When I attached a veth to the container, found the veth was unavailable, 

@sboeuf 

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by grahamwhaley** [comment]
I believe there are different PCI(e) hotplug features between q35 and 'pc' - iirc, q35 mayb e PCI, not PCIe, and thus not have hotplug. /cc @devimc who did the original looking into this iirc.

**Comment by sboeuf** [comment]
@miaoyq you should be able (relying on latest agent and latest runtime) to hotplug some additional interfaces when using `q35`. But in case of `q35`, the roo bus is not directly hotpluggable, which means that if you use `hotplug_vfio_on_root_bus = true` from `configuration.toml`, this won't work.

**Comment by miaoyq** [comment]
@sboeuf  Sorry for my delay, you're right :+1: 
I set `hotplug_vfio_on_root_bus = true` and `machine_type = q35`, it works well. Thanks.

@devimc Yes, SHPC have been enabled. Thanks for reminder. :-)

**Comment by miaoyq** [comment]
I will close this issue.

**Comment by miaoyq** [comment]
@grahamwhaley There are instructions actually in `configuration.toml`. It would be better to have an explanation in the document I think. :-)
