### ISSUE TITLE
Test failures running as non-root

### ISSUE THREAD

**Issue by jodh-intel** [kata-containers/runtime#863]
```
$ go test github.com/kata-containers/runtime/virtcontainers -run "^TestStatsContainerFailing$" -v
=== RUN   TestStatsContainerFailing
--- FAIL: TestStatsContainerFailing (0.00s)
    api_test.go:1911: open /sys/fs/cgroup/systemd/kata/7f49d00d-1995-4156-8c79-5f5ab24ce138/cgroup.procs: permission denied
FAIL
FAIL    github.com/kata-containers/runtime/virtcontainers       0.008s
$ echo $?
1
```

The following tests are failing when run as non-`root`:

```
TestCreateContainerFailingNoSandbox
TestCreateContainerSuccessful
TestCreateSandboxNoopAgentSuccessful
TestDeleteContainerFailingNoContainer
TestDeleteContainerSuccessful
TestDeleteSandboxNoopAgentSuccessful
TestEnterContainerFailingContNotStarted
TestEnterContainerFailingNoContainer
TestEnterContainerNoopAgentSuccessful
TestKillContainerFromContReadySuccessful
TestListSandboxSuccessful
TestPauseThenResumeSandboxNoopAgentSuccessful
TestRunSandboxNoopAgentSuccessful
TestStartContainerFailingNoContainer
TestStartContainerFailingSandboxNotStarted
TestStartContainerNoopAgentSuccessful
TestStartSandboxNoopAgentSuccessful
TestStatsContainerFailing
TestStatusContainerFailing
TestStatusContainerStateReady
TestStatusContainerStateRunning
TestStatusContainerSuccessful
TestStatusPodSandboxFailingFetchSandboxState
TestStatusSandboxFailingFetchSandboxConfig
TestStatusSandboxSuccessfulStateReady
TestStatusSandboxSuccessfulStateRunning
TestStopContainerFailingNoContainer
TestStopContainerNoopAgentSuccessful
TestStopSandboxNoopAgentSuccessful
```

This seems to have been caused by #734 landing. The fix is to modify the tests above so they all start with:

```go
if os.Geteuid() != 0 {
    t.Skip(testDisabledNeedRoot)    
}
```

/cc @WeiZhang555

**Comment by jodh-intel** [comment]
@chavafg - The CI is correctly running the unit tests as a non-`root` and `root` user so any idea why this issue didn't get caught in the CI?

**Comment by WeiZhang555** [comment]
@jodh-intel Same question, why this isn't caught in CI? I see all CI cases passed in PR #734

**Comment by chavafg** [comment]
@jodh-intel @WeiZhang555, I see in the logs that the tests above are only running for `root user`. Are these tests from virtcontainers? I remember we run virtcontainers tests only with root user, but don't remember the reason.

here we are skipping virtcontainers tests when running with non-root user: https://github.com/kata-containers/tests/blob/master/.ci/go-test.sh#L184

**Comment by sboeuf** [comment]
Well I have the same thoughts you all got.
- First, why the CI didn't catch that in the first place? I think this is the most concerning issue as this means we might not properly test each PR.
- This current PR makes sense IMO, as the introduction of cgroups makes a lot of tests depend on the creation/destruction of cgroups, and you need to be root for that. Two questions to follow up on this:
  - Is there any way to create some cgroups without being root? Would it work to simply add some capabilities?
  - Maybe we could introduce some no-op cgroups implementation, which would prevent from the need of using a root user, as we would not create cgroups for real in those cases.
