### ISSUE TITLE
error not propagating back to crio and container left in unknown state 

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#87]
Opening issue to track original from: https://github.com/containers/virtcontainers/issues/623

**Comment by egernst** [comment]
Last comment from @jodh-intel:

This looks like a bug in crio. If you force an error running the runtime standalone...

https://github.com/clearcontainers/runtime/wiki/Running-standalone
... you get the expected:
```
$ sudo cc-runtime run --bundle "$bundle" baz >stdout 2>stderr
$ cat stdout
$ cat stderr
ERROR received from VM agent, control msg received : Process could not be started: container_linux.go:296: starting container process caused "exec: \"blablab\": executable file not found in $PATH"
```

The problem appears to be here....

https://github.com/kubernetes-incubator/cri-o/blob/master/oci/oci.go#L314
... and here:

https://github.com/kubernetes-incubator/cri-o/blob/master/utils/utils.go#L33..L41
meaning the runtimes error message goes to the system journal. That appears to be happening, but the journal entries make it appear the error is coming from the crio daemon itself, which is clearly incorrect.

**Comment by egernst** [comment]
cc/ @sboeuf @jodh-intel

**Comment by egernst** [comment]
@jodh-intel  My apologies if I'm mistaken, but I think there are actually two issues here, and the CRI-O bug you're bringing up deals with the appropriate error message propagation.  I'm concerned still that the container is being reported as in an unknown state, and that removal of the container fails, leaving the system in a pretty bad state.

/cc @mrunalp

**Comment by egernst** [comment]
cc/ @chenxumsft

**Comment by jodh-intel** [comment]
crio seems to take some convincing to behave, but...

```
$ sudo crictl --runtime-endpoint /var/run/crio/crio.sock pull busybox
Image is update to date for docker.io/library/busybox@sha256:c7b0a24019b0e6eda714ec0fa137ad42bc44a754d9cea17d14fba3a80ccc1ee4
$ sudo crictl runp ./sandbox_config.json  
2ec767f337bfeef6d7e70eb789e4f94ecdcd712c55b136a8e4216d3d877626b8
$ sudo crictl create 2ec767f337bfeef6d7e70eb789e4f94ecdcd712c55b136a8e4216d3d877626b8 container_bad.json sandbox_config.json  
FATA[0000] Creating container failed: rpc error: code = Unknown desc = container create failed: rpc error: code = Internal desc = Could not run process: container_linux.go:296: starting container process caused "exec: \"blablab\": executable file not found in $PATH"
$ echo $?
1
$ for component in runtime shim proxy; do sudo journalctl -q -o cat -a -t "kata-${component}" > "./kata-${component}.log"; done
$ grep blablab *.log
kata-runtime.log:time="2018-03-28T16:23:06.716063478+01:00" level=error msg="rpc error: code = Internal desc = Could not run process: container_linux.go:296: starting container process caused \"exec: \\\"blablab\\\": executable file not found in $PATH\"" command=create name=kata-runtime pid=23176 source=runtime
```

**Comment by chenxumsft** [comment]
is there a way to remove the pod/VM? mainly the left-over VM consumes ~130MB memory, and our code has retry logic to remove and re-create the faulted container, which would soon eats up all the memory of the host since the removal operation won't succeed. 
`$ sudo crictl stop a81f2b93b5465
a81f2b93b5465
$ sudo crictl rm a81f2b93b5465
FATA[0000] Removing the container failed: rpc error: code = Unknown desc = failed to delete container a81f2b93b54656a76d598ddb83baa56a73102640a641714fe2b949be4336fa1d: `/usr/local/bin/cc-runtime delete --force a81f2b93b54656a76d598ddb83baa56a73102640a641714fe2b949be4336fa1d` failed: open /var/lib/virtcontainers/pods/be4082cc91d12d41640358557ee5f0668fda08cb6fe6bfe63c3cf6d58500a995/a81f2b93b54656a76d598ddb83baa56a73102640a641714fe2b949be4336fa1d/config.json: no such file or directory
  (exit status 1)`

**Comment by egernst** [comment]
@jodh-intel -- the failure issue that @chenxumsft is seeing is specific to Clear Containers 3.0, actually.  

While the failure still exists, it is in a different point in time (ie, at container creation time versus container start). This is because Kata's agent matches runc behavior closer relative to Clear Containers'.

I talked with @sboeuf on this this morning, and we have a pretty good handle on the issue.  We're looking to see if we properly update the container state if CRIO will be able to clean up appropriately.  Assigning this to @sboeuf at this point...
