### ISSUE TITLE
kata-runtime and docker-runc Running simultaneously

### ISSUE THREAD

**Issue by free2k** [kata-containers/runtime#873]
# Description of problem

Can the docker-runc container and the kata-runtime virtual machine exist at the same time? ? Create containers or create virtual machines

**Comment by grahamwhaley** [comment]
Hi @free2k Yes, absolutely. You can have multiple OCI compatible runtimes installed at the same time, and choose which to use at runtime. For instance, in `docker` you use the `--runtime=xxx` to choose which runtime to execute the chosen container with.
In k8s you make the runtime choice through the config file, at present by choosing which 'trust level' you have in the container workload I believe. Somebody else may elucidate details for k8s.

**Comment by free2k** [comment]
@grahamwhaley Thank you for your answer.
When docker is running, I configure --default-runtime=kata-runtime and --default-runtime=docker-runc to control the runtime. However, the container I created in docker-runc cannot be controlled in the docker started by the kata-runtime configuration, it will throw an exception.
```
Docker start d67f3226fb3c
Error response from daemon: Unknown runtime specified docker-runc
Error: failed to start containers: d67f3226fb3c
```
D67f3226fb3c is a runc container, not a kata virtual machine. I want to have both a container and a virtual machine.

**Comment by free2k** [comment]
@jshachm Thank you, solved it with your method.

**Comment by egernst** [comment]
Ok to close this issue?

**Comment by free2k** [comment]
@egernst Yes, this issue can be closed.
