### ISSUE TITLE
mount blockdevices in the guest VM

### ISSUE THREAD

**Issue by zklei** [kata-containers/runtime#881]
# Description of problem
When we use `docker run -v /dev/sdb:/mnt/data ` to run a container, It will passing `/dev/sdb/` through as blockdevice `/mnt/data`. 

# Expected result
Usually, What we want is to mount the block device as a directory in container, Or we're going to choose --device to pass this blockdevice.

**Comment by WeiZhang555** [comment]
Duplicate of #571
