### ISSUE TITLE
Make failed because of yq

### ISSUE THREAD

**Issue by caoruidong** [kata-containers/runtime#889]
# Description of problem
Run "make" in the runtime directory, then error out

# Expected result
make successfully

# Actual result
```
[root@localhost runtime]# make
usage: yq [-h] [--yaml-output] [--width WIDTH] [--version]
          jq_filter [files [files ...]]
yq: error: argument files: can't open 'languages.golang.version': [Errno 2] No such file or directory: 'languages.golang.version'
golang.mk:12: *** "ERROR: cannot determine minimum golang version".  Stop.
```
In golang.mk, we have
https://github.com/kata-containers/runtime/blob/d895cd0f2dec7cbabfda95846543314565acc70a/golang.mk#L9-L13

If I change the cmd, it works
```
[root@localhost runtime]# yq -r .languages.golang.version versions.yaml
1.10.4
```
Maybe I'm not familiar with yq's grammar. cc @grahamwhaley

**Comment by grahamwhaley** [comment]
@caoruidong - let's check which `yq` you have installed? We have used https://github.com/mikefarah/yq so far afaik. Maybe you have managed to get a different `yq` that has a slightly different syntax - I think there is more than one program called `yq` out there.
Having said that, maybe the addition of the `.` works for more versions of `yq` - if so, then we can add it :-)

**Comment by caoruidong** [comment]
Oh, Got it! I use https://github.com/kislyuk/yq :sweat_smile:  Thank you!

**Comment by umarcor** [comment]
I did need to:

``` bash
go get gopkg.in/mikefarah/yq.v1
mv /go/bin/yq.v1 /go/bin/yq
```
