### ISSUE TITLE
docker update doubt with PR https://github.com/kata-containers/runtime/pull/734

### ISSUE THREAD

**Issue by liangxianlong** [kata-containers/runtime#901]
# I have a few questions about "docker update" with the PR #734 :
(1) When I execute "docker run -ti --cpu-quota 60000 --cpu-period 100000 busybox /bin/sh", the container id is "cf3e2d7be1f9ad7f8e7cdd0bc09045363df6a08b02d88e6c81d18e3b5737e414"
We can see the following results in the host directory and virtual machine directory:
cat cpu.cfs_quota_us
60000
cat cpu.cfs_period_us
100000
(2) But when I execute "docker update --cpu-quota 50000 --cpu-period 200000 cf3e2d7be1f9ad7f8e7cdd0bc09045363df6a08b02d88e6c81d18e3b5737e414", the value on the host has not changed:
Cat cpu.cfs_quota_us
60000
Cat cpu.cfs_period_us
100000
However, the value on the virtual machine is updated.
Question 1
I want to know if "docker update --cpu-quota 50000 --cpu-period " will have the same effect as "docker run -ti --cpu-quota 60000 --cpu-period 100000" in the future?
Question 2
If the answer to question 1 is "yes", then is it related to cpu and cpuset?
Question 3
On the host, should we use diretory "/sys/fs/cgroup/cpu/kata/${vm-name}" instead "/sys/fs/cgroup/cpu/kata/${containerid}"?
@WeiZhang555 @bergwolf @liwei @jbryce @gnawux

**Comment by caoruidong** [comment]
Thanks for raising. You can reference an issue or PR by "#"+its number in github comment

**Comment by liangxianlong** [comment]
> Thanks for raising. You can reference an issue or PR by "#"+its number in github comment

thanks,how do you think this issue?

**Comment by caoruidong** [comment]
Sorry, I'm not sure about this. Maybe applied in the guest.

**Comment by liangxianlong** [comment]
> Sorry, I'm not sure about this. Maybe applied in the guest.

thanks! If it applied in the guest, we don't need to merge #734 . So,it also confused me.

**Comment by caoruidong** [comment]
> > Sorry, I'm not sure about this. Maybe applied in the guest.
> 
> thanks! If it applied in the guest, we don't need to merge #734 . So,it also confused me.

Just a guess! Host cgroup is useful for controlling container in a fine granularity

**Comment by egernst** [comment]
Hey @liangxianlong  - the PR is for helping constrain QEMU on the *host*.  The requested handling of containers using docker update is for updating the cgroups within the guest. Or... what was the question?

**Comment by liangxianlong** [comment]
> Hey @liangxianlong - the PR is for helping constrain QEMU on the _host_. The requested handling of containers using docker update is for updating the cgroups within the guest. Or... what was the question?
Do you mean that if one want realize a comman "vpcupin" in libvirt,he/she should use "docker run --cpuset-cpus 6"?
