### ISSUE TITLE
error while doing a ping in a container with macvlan network on CentOS

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#905]
These are the steps to reproduce:
```
1. $ docker network create -d macvlan macvlan1
2. $docker run -d --runtime=kata-runtime --network=macvlan --name=containerA debian sh -c "tail -f /dev/null"
3. $ip_address=$(docker inspect --format "{{.NetworkSettings.Networks.macvlan1.IPAddress}}"  containerA)
4. $ docker run --runtime=kata-runtime  --network=macvlan --name=containerB debian  sh -c "ping -c 5  ${ip_address}"
   PING 172.20.0.2 (172.20.0.2) 56(84) bytes of data.
   From 172.20.0.3 icmp_seq=1 Destination Host Unreachable
   From 172.20.0.3 icmp_seq=2 Destination Host Unreachable
   From 172.20.0.3 icmp_seq=3 Destination Host Unreachable
   From 172.20.0.3 icmp_seq=4 Destination Host Unreachable
   From 172.20.0.3 icmp_seq=5 Destination Host Unreachable
```

**Comment by amshinde** [comment]
@GabyCT Looks like macvlan requires kernel 3.9 or greater. Lets skip this test for Centos or we could do this
```
modprobe macvlan
lsmod | grep macvlan
```
If the result of the `grep` is empty, lets skip.

**Comment by GabyCT** [comment]
@amshinde , yes that is the problem, I am skipping these tests https://github.com/kata-containers/tests/pull/900

**Comment by JK1991scmy** [comment]
@amshinde @GabyCT my centos has macvlan module,this error also occurred.Whether centos does not support this feature？

**Comment by GabyCT** [comment]
The same error is happening on RHEL and from what I can see the kernel version is similar to centos
Linux rhelgaby 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by amshinde** [comment]
@GabyCT If you are able to create a macvlan network driver with docker, it means that the kernel supports it. 
If not, docker would have given you an error at the network create step itself.
There is something else going on, do you have a centos/rhel machine that you have setup that I can try this on?

**Comment by amshinde** [comment]
@GabyCT Took a look at this. I was able to ping between the containers, if I change the internetwork model in our configuration.toml to `tcfilter` (https://github.com/kata-containers/runtime/blob/master/cli/config/configuration-qemu.toml.in#L316), so this looks like a case of `macvtap` internetworking model not working with macvlan driver on a older kernel.

Can you run the tests by explicitly setting the internetwork model here.
We should be using the right model transparently here for older kernels, perhaps default to `tcfilter` for macvlan as well (as we do for ipvlan today).

cc @mcastelino

**Comment by mcastelino** [comment]
@amshinde can you check if the macvlan interfaces are setup in bridge mode and not VEPA

**Comment by amshinde** [comment]
@mcastelino The macvlan interfaces are in bridge mode.
Here is what I see on a rhel machine:
```
# ip -d link show  eth0
599: eth0@if591: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 12:df:d8:bc:51:d0 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0 
    macvlan mode bridge addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
[root@red75gaby network]# ip -d link show tap0_kata
21061: tap0_kata@eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN mode DEFAULT group default qlen 1500
    link/ether 02:42:ac:13:00:03 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    macvtap mode bridge addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535 
```

For runc on RHEL:
```
# ip -d link show eth0
594: eth0@if591: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether 02:42:ac:13:00:04 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0 
    macvlan mode bridge addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```

And here is what I see on my laptop running ubuntu with kata:
```
# ip -d link show eth0
199: eth0@if197: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether 06:70:48:ba:53:12 brd ff:ff:ff:ff:ff:ff link-netnsid 0 promiscuity 0 
    macvlan  mode bridge addrgenmode eui64 
$ ip -d link show tap0_kata
60229: tap0_kata@if197: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1500
    link/ether 02:42:ac:12:00:03 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    macvtap  mode bridge addrgenmode eui64 
```

**Comment by amshinde** [comment]
Looking at the actual dummy interface created by the docker macvlan driver on which the macvlan are based of:
```
ip -d link show dm-882979dbaf05
601: dm-882979dbaf05: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether ee:f0:de:39:40:50 brd ff:ff:ff:ff:ff:ff promiscuity 0 
    dummy addrgenmode eui64 numtxqueues 1 numrxqueues 1 gso_max_size 65536 gso_max_segs 65535
```
On ubuntu: 
```
sudo ip -d link show dm-77259930028d
197: dm-77259930028d: <BROADCAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc noqueue state UNKNOWN mode DEFAULT group default 
    link/ether aa:7e:f8:35:66:55 brd ff:ff:ff:ff:ff:ff promiscuity 1 
    dummy addrgenmode eui64 
```
