### ISSUE TITLE
error in running ipvlan in CentOS

### ISSUE THREAD

**Issue by GabyCT** [kata-containers/runtime#906]
It is not possible to run the ipvlan tests (https://github.com/kata-containers/tests/blob/master/integration/network/ipvlan/ipvlan_driver.bats)  on CentOS as we are getting the following error
```
Error response from daemon: kernel version failed to meet the minimum ipvlan kernel requirement of 4.2, found 3.10.0
```

**Comment by amshinde** [comment]
Yeah looks like you need kernel 4.2 for ipvlan. Lets skip ipvlan test for Centos.

**Comment by GabyCT** [comment]
@amshinde , yes that is the problem, I am skipping these tests kata-containers/tests#900
