### ISSUE TITLE
utils: Implement a safe RemoveAll()

### ISSUE THREAD

**Issue by sboeuf** [kata-containers/runtime#912]
There are many places in the code where we call into `os.RemoveAll(path)` without checking the validity of this path. By validity, I mean that we should make sure the path is:
- not empty
- compliant with Linux paths format
- not `*`, `/`, `/dev`, etc...

We should implement our own `RemoveAll()` function that would be a simple wrapper around `os.RemoveAll()`, this way it would be pretty easy to replace in the code and it would be transparent for developers to use it.

**Comment by jodh-intel** [comment]
Agreed. We already have precedent for doing something like that for `os.Exit()`:

- https://github.com/kata-containers/runtime/blob/master/cli/exit.go

Once we've implemented the custom function, we should refactor the CI test below to ensure `os.RemoveAll()` isn't called from non-test code:

- https://github.com/kata-containers/runtime/blob/master/.ci/go-no-os-exit.sh

**Comment by jingxiaolu** [comment]
Hi, @sboeuf this is good idea~

I think we should also check whether the sub-dir is mounted by other dirs, just like moby doing in `EnsureRemoveAll()`
- https://github.com/moby/moby/blob/master/pkg/system/rm.go
