### ISSUE TITLE
golang version requirements for OBS packaging

### ISSUE THREAD

**Issue by marcov** [kata-containers/runtime#923]
I was having a look at the golang required to build kata on OBS:

https://github.com/kata-containers/packaging/blob/e5a2f4aa4569eb6609a3644a9b4229b0b1ad8548/obs-packaging/gen_versions_txt.sh#L42-43

- There's a `golang_version=1.10.2` hardcoded
- Once [this PR](https://github.comkata-containers/runtime/pull/917) is merged, we need to "use" it to skip golang version check for the runtime, since `yq` is not available in OBS projects and can't be downloaded during build.
- What about using `languages.golang.version` instead of `languages.golang.meta.newest-version`?This would make things easier when we will be packaging using the golang version provided by distributions (I am working on this), as the "newest" version may not be available.

**Comment by marcov** [comment]
I'll follow up with a PR, and I'd like a feedback about the 2nd bullet point (@grahamwhaley, @jodh-intel).

**Comment by marcov** [comment]
sorry this was meant to be opened in packaging repo

**Comment by grahamwhaley** [comment]
/me waits for the packaging Issue to open....
in the meantime - yeah, err, that hardwired 1.10.2 looks wonky to me... it fetches 'latest', and then overwrites it with the hard wired value, does it not? @jcvenegas (who may not be online for a couple of days btw)

I'm not sure if we should go with `version` or `newest-version`. I would actually vote `newest`, as then we may get benefits of newer optimisations etc. Given some distros only package versions of golang that are older than the one we require (iirc, Ubuntu for instance is the obvious candidate)... we are (probably) going to have to install our own golang version to do a build anyway, somewhere - so I would have thought then we'd go with `newest-version`.

**Comment by marcov** [comment]
Please continue here and sorry again :)
https://github.com/kata-containers/packaging/issues/242

**Comment by caoruidong** [comment]
Beta "Transfer this issue" looks good. But I can't find packing repo :sweat_smile:
