### ISSUE TITLE
sharedPidNs didn't work 

### ISSUE THREAD

**Issue by lifupan** [kata-containers/runtime#930]
# Description of problem
there is a bug in virtcontainers/kata-agent.go and in kata agent for dealing with "sharedPidNs", which will complained error as below:
Could not run process: container_linux.go:348: starting container process caused "process_linux.go:301: running exec setns process for init caused "exit status 40""

# Expected result

(replace this text with an explanation of what you thought would happen)

# Actual result

(replace this text with details of what actually happened)

---

(replace this text with the output of the `kata-collect-data.sh` script, after
you have reviewed its content to ensure it does not contain any private
information).

**Comment by amshinde** [comment]
@lifupan Can you provide more details for this, and when you are seeing this bug.
We have a test for checking pidns is shared correctly:
https://github.com/kata-containers/tests/blob/master/integration/kubernetes/k8s-pid-ns.bats

**Comment by bergwolf** [comment]
https://github.com/kata-containers/agent/pull/678 should fix this one.
