### ISSUE TITLE
virtcontainers: endianess issue

### ISSUE THREAD

**Issue by alicefr** [kata-containers/runtime#947]
In the [utils_linux.go](https://github.com/kata-containers/runtime/blob/c2eea35b183ffc2365f9117105029f70479ee9e8/virtcontainers/utils/utils_linux.go#L56) there is an endianess bug. I'm testing the `kata-runtime` on s390x (big endian) with `vsock` and the function [ioctlFunc](https://github.com/kata-containers/runtime/blob/c2eea35b183ffc2365f9117105029f70479ee9e8/virtcontainers/utils/utils_linux.go#L75) always returned EINVAL(errno=22). I tried to reproduce the issue with these small golang programs:
test32.go:
```golang 
package main

import (
        "fmt"
        "os"
        "syscall"
        "unsafe"

        "golang.org/x/sys/unix"
)

// from <linux/vhost.h>
// VHOST_VSOCK_SET_GUEST_CID = _IOW(VHOST_VIRTIO, 0x60, __u64)
const ioctlVhostVsockSetGuestCid = 0x4008AF60

type argsType uint32

func ioctl(fd uintptr, request int, arg1 argsType) error {
        if _, _, errno := unix.Syscall(
                unix.SYS_IOCTL,
                fd,
                uintptr(request),
                uintptr(unsafe.Pointer(&arg1)),
        ); errno != 0 {
                return os.NewSyscallError("ioctl", fmt.Errorf("%d", int(errno)))
        }

        return nil
}

func main() {
        var cid argsType = 0x4

        vsockFd, err := os.OpenFile("/dev/vhost-vsock", syscall.O_RDWR, 0666)
        if err != nil {
                fmt.Println("ERROR:")
        }

        if err := ioctl(vsockFd.Fd(), ioctlVhostVsockSetGuestCid, cid); err == nil {
                fmt.Printf("SUCCESS\n")
        } else {
                fmt.Printf("err:%s vsockFd=%d cid=%x \n", err, vsockFd.Fd(), cid)
        }

        vsockFd.Close()
}
```
and test64.go
```golang
package main

import (
        "fmt"
        "os"
        "syscall"
        "unsafe"

        "golang.org/x/sys/unix"
)

// from <linux/vhost.h>
// VHOST_VSOCK_SET_GUEST_CID = _IOW(VHOST_VIRTIO, 0x60, __u64)
const ioctlVhostVsockSetGuestCid = 0x4008AF60

type argsType uint64

func ioctl(fd uintptr, request int, arg1 argsType) error {
        if _, _, errno := unix.Syscall(
                unix.SYS_IOCTL,
                fd,
                uintptr(request),
                uintptr(unsafe.Pointer(&arg1)),
        ); errno != 0 {
                return os.NewSyscallError("ioctl", fmt.Errorf("%d", int(errno)))
        }

        return nil
}

func main() {
        var cid argsType = 0x4

        vsockFd, err := os.OpenFile("/dev/vhost-vsock", syscall.O_RDWR, 0666)
        if err != nil {
                fmt.Println("ERROR:")
        }

        if err := ioctl(vsockFd.Fd(), ioctlVhostVsockSetGuestCid, cid); err == nil {
                fmt.Printf("SUCCESS\n")
        } else {
                fmt.Printf("err:%s vsockFd=%d cid=%x \n", err, vsockFd.Fd(), cid)
        }

        vsockFd.Close()
}
```
As you probably noticed the single difference between the 2 files is the:
```golang
type argsType
```
On s390x:
```sh
$ sudo go run test32.go 
err:ioctl: 22 vsockFd=3 cid=4
$ sudo go run test64.go 
SUCCESS
```
on x86_64
```sh
$ sudo go run test32.go
SUCCESS
$ sudo go run test64.go
SUCCESS
```
In the kernel the cid for vsock is u64 (see https://github.com/torvalds/linux/blob/ef78e5ec9214376c5cb989f5da70b02d0c117b66/drivers/vhost/vsock.c#L664). Up to now only the first 32 bits are used as you can see from the [comment](https://github.com/torvalds/linux/blob/ef78e5ec9214376c5cb989f5da70b02d0c117b66/drivers/vhost/vsock.c#L621). However, if the args is a `unit32`, that provokes an endianess issue. 

There are 2 possibilites:
1- Change the args type in [ioctlFunc](https://github.com/kata-containers/runtime/blob/c2eea35b183ffc2365f9117105029f70479ee9e8/virtcontainers/utils/utils_linux.go#L27) from `uint32` to `uint64`
2- Change all the CID vsock from `unit32` to `uint64`. That requires also to change the type in [govmm](https://github.com/intel/govmm/blob/60a5f7ca7fd9a200028dfa903f934f3c1bec0be4/qemu/qemu.go#L1017)

**Comment by sboeuf** [comment]
@alicefr thanks for this detailed explanation!
>There are 2 possibilites:
1- Change the args type in ioctlFunc from uint32 to uint64
2- Change all the CID vsock from unit32 to uint64. That requires also to change the type in govmm

I would say that we want to fix the issue properly, and that means we should fix both `1` and `2` IMO. Because the kernel uses u64 for vsock's CID, I think we should do the same in our code.

So you could start with `1`, which would fix the issue, and later implement `2` in order to have a fully compliant code.

**Comment by alicefr** [comment]
@sboeuf I agree, it could also avoid future bug. I don't know if the ioctl in utils_linux in the only place where the issue apprears
