### ISSUE TITLE
ci: tests repo path is hard wired and not over-rideable

### ISSUE THREAD

**Issue by grahamwhaley** [kata-containers/runtime#95]
In [lib.sh](https://github.com/kata-containers/runtime/blob/master/.ci/lib.sh#L6), the path (url) to the tests repo is hard wired, and not over-rideable:
```
export tests_repo="github.com/kata-containers/tests"
```

This makes it very hard to develop and test new functionality in a tests repo clone/branch, as the call out from the tests repo to the repo under test (in this case the runtime), then switches back to using files from the main tests repo (and not the ones in development)...
Proposal is to change to:
```
export tests_repo="${tests_repo:-github.com/kata-containers/tests}"
```

Which will then pick up any overwride setting of `tests_repo` that has come from higher up the chain (we already have that functionality in the [tests repo](https://github.com/kata-containers/tests/blob/master/.ci/jenkins_job_build.sh#L16) itself for instance, but it is not trickling down to the other repos).

If folks agree, then we should do this in all repos (and/or come up with another way to share a lib.sh across all repos, which may not be ideal either).

**Comment by jodh-intel** [comment]
I had a crazy idea that we could add a submodule to each repo for CI scripts. But clearly I need to go and have a cuppa and a biccy to clear my head! :smile:
