### ISSUE TITLE
Ask about version selection of QEMU.

### ISSUE THREAD

**Issue by clarklee92** [kata-containers/runtime#959]
# Description of problem
In official tarball there is the <qemu-system-x86_64> offered;
In linux distributions there is the <qemu-lite-x86_64> offered;
In `packaging` rep there is a static build of qemu which downloaded from "https://github.com/qemu/capstone.git";
And there is also NEMU version can be used.
We intend to put kata on online ENV. Please give some suggestion.Thanks a lot.

**Comment by grahamwhaley** [comment]
Hi @clarklee92 - each of the different options will give you a different performance profile and set of features - if you can elaborate on your requirements and priorities then that might help us help you choose.
@egernst @gnawux et. al. - maybe we can put together a table with the above QEMU versions and their pro/cons and add it to the [UserGuide section](https://github.com/kata-containers/documentation/wiki/UserGuide#qemu-versions) ?

**Comment by clarklee92** [comment]
Thank you very much. We have tested these versions on kubernetes cluster(vistual machine based and nested for kata).  `qemu-lite-x86_64`  consumed much less memory and cpu than `qemu-system-x86_64` and nemu. We want to utilize kata as  secure container  with k8s. First we considered the stability of cluster features and then the less consumption and good performance.
I prefer `qemu-lite-x86_64` , could you please tell me  why it was discarded for the tarball?

**Comment by bergwolf** [comment]
@clarklee92 I don't think there is strong reasoning for not shipping `qemu-lite-x86_64` in the tarball. It just the very first commit doing qemu static build tried to fetch `assets.hypervisor.qemu.url` from https://github.com/kata-containers/runtime/blob/master/versions.yaml

May be we should just unify with obs and also put qemu-lite there? @jodh-intel @grahamwhaley @jcvenegas  WDYT?

**Comment by jodh-intel** [comment]
@bergwolf - agreed - it does seem odd that we:

- Only provide the static binary on https://github.com/kata-containers/runtime/releases.
- Provide the non-static binaries (`qemu-lite` and `qemu-vanilla`) in OBS packages
 (https://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/stable-1.3/Fedora_28/x86_64/ for example).

Any thoughts on this @marcov?

**Comment by devimc** [comment]
we cannot just release the qemu static binary, we also need the firmwares, since they are loaded when a device is hot-plugged

**Comment by marcov** [comment]
My view:
- w.r.t. OBS, qemu should be kept dynamically linked, statically linking is not usually allowed and e.g. it's marked as rpm lint warning or even worse can generate a build error.
- (Moving forward) qemu-vanilla should NOT be packaged on OBS, unless there's a strong reason not to use the official qemu shipped by the distributions.

**Comment by devimc** [comment]
@marcov 

> (Moving forward) qemu-vanilla should NOT be packaged on OBS, unless there's a strong reason not to use the official qemu shipped by the distributions.

Some distros don't support 9p, also might be qemu is broken in some distributions, see https://github.com/kata-containers/runtime/issues/969

**Comment by marcov** [comment]
@devimc 
I see, then qemu should be set as requirement only for those distros not having 9p enabled. As for the broken qemu, that should be fixed on their side :)
