### ISSUE TITLE
create-sandbox: do we ever expect more than one container?

### ISSUE THREAD

**Issue by egernst** [kata-containers/runtime#961]
doing some static review, I notice in [createSandboxFromConfig](https://github.com/kata-containers/runtime/blob/master/virtcontainers/api.go#L65) we [call create containers](https://github.com/kata-containers/runtime/blob/master/virtcontainers/api.go#L120).

AFAIU, if we are creating a sandbox, the only container that should be expected from a "create" call is the pause container.  Can someone clarify if this is an incorrect assumption?

We may want to consider just calling the simpler (and very common in code flow) function [CreateContainer](https://github.com/kata-containers/runtime/blob/master/virtcontainers/sandbox.go#L1274) from sandbox.go.  

Another side comment - can we agree we shouldn't add any more functions with the name createContainer - we have a enough right now, right?  :)

**Comment by egernst** [comment]
@bergwolf @sboeuf - PTAL and help clarify?

**Comment by bergwolf** [comment]
I guess the main reason is we have containers listed in the sandbox config? For hyperd, we are able to get all container configs when creating the sandbox but we still choose to create an empty sandbox and insert all containers to it thereafter.

I think we can do the same here and simply remove `createcontainers` from `createSandboxFromConfig`, and then change the API callers (cli and shimv2 atm) to call `CreateContainer` after calling `CreateSandbox` etc.

**Comment by sboeuf** [comment]
@egernst 
>AFAIU, if we are creating a sandbox, the only container that should be expected from a "create" call is the pause container. Can someone clarify if this is an incorrect assumption?

The reason why we introduced such logic was to ensure the API would let the caller provide a `SandboxConfig` with one or more containers, and those containers would be created at the same time  the sandbox is being created, which makes sense IMO.

Now, from a kata-runtime (CLI) perspective, we want to call into `CreateContainer()`, we could definitely do that by not doing any modification to the API. The only thing we would need is to submit a patch to the CLI, making sure we're not creating any `ContainerConfig` as part of the `SandboxConfig`, and after the call to `CreateSandbox` returns, we would call into `CreateContainer`. Does that help?

**Comment by bergwolf** [comment]
@sboeuf The purpose is to make `CreateSandbox` API possible to implement for some hypervisors (i.e., firecracker) that do not support hotplug. We need to change the API flow from `create sandbox -> start vm -> create container -> start container` to `create sandbox -> create container -> start vm & container`. As for CLI, there will be a emulated `Created` state where no VM is created at all.
