### ISSUE TITLE
Is Qemu-3.0.0 supposed to work with kata? 

### ISSUE THREAD

**Issue by avekceeb** [kata-containers/runtime#969]
# Description of problem
Hi,
I didn't find any mention of this is 'not supported' or something about 3.0.0 particulary.
Could you, please, comment on that?
 
Tried Fedora rpms from http://download.opensuse.org/repositories/home:/katacontainers:/releases:/x86_64:/master/Fedora_28/
Works fine with default qemu-lite, but when set kata toml with qemu-3.0.0 (from fedora's repo)
qemu process gets SIGABORT (6) on docker kill vm:
```
docker run --runtime kata-runtime -d -P --name vm nginx
docker kill vm 
```

# Actual result
Core was generated by `/usr/bin/qemu-system-x86_64 -name sandbox-7ca90427d28f0a26e2aae401c98958425e507'.
Program terminated with signal SIGABRT, Aborted.
#0  0x00007f3ce934853f in ?? ()
[Current thread is 1 (LWP 3162)]

## Proxy logs

Recent proxy problems found in system journal:
```
time="2018-12-03T17:03:08.748797326+03:00" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/c3731c0d78d9d427318c53df1852d23f9074c6fc24df8f3f9a6e85c41b365331/kata.sock: use of closed network connection" name=kata-proxy pid=2788 sandbox=c3731c0d78d9d427318c53df1852d23f9074c6fc24df8f3f9a6e85c41b365331 source=proxy
time="2018-12-03T17:08:13.852221292+03:00" level=fatal msg="failed to handle exit signal" error="close unix @->/run/vc/vm/7ca90427d28f0a26e2aae401c98958425e5076f263fa1b42d744fcf2ece75b4f/kata.sock: use of closed network connection" name=kata-proxy pid=3168 sandbox=7ca90427d28f0a26e2aae401c98958425e5076f263fa1b42d744fcf2ece75b4f source=proxy
```

qemu-system-x86-3.0.0-1.fc29.x86_64
kata-shim-1.4.0+git.b02868b-9.1.x86_64
ipxe-roms-qemu-20170710-5.git0600d3ae.fc29.noarch
qemu-ui-curses-3.0.0-1.fc29.x86_64
qemu-vanilla-bin-2.11.2+git.0982a56a55-13.1.x86_64
qemu-block-nfs-3.0.0-1.fc29.x86_64
qemu-lite-data-2.11.0+git.f886228056-13.1.x86_64
qemu-block-dmg-3.0.0-1.fc29.x86_64
qemu-guest-agent-3.0.0-1.fc29.x86_64
qemu-audio-pa-3.0.0-1.fc29.x86_64
qemu-img-3.0.0-1.fc29.x86_64
qemu-block-iscsi-3.0.0-1.fc29.x86_64
qemu-lite-2.11.0+git.f886228056-13.1.x86_64
kata-ksm-throttler-1.4.0.git+1212de2-12.1.x86_64
qemu-kvm-3.0.0-1.fc29.x86_64
qemu-block-curl-3.0.0-1.fc29.x86_64
qemu-system-x86-core-3.0.0-1.fc29.x86_64
qemu-vanilla-data-2.11.2+git.0982a56a55-13.1.x86_64
kata-proxy-bin-1.4.0+git.e1856c2-11.1.x86_64
qemu-audio-oss-3.0.0-1.fc29.x86_64
qemu-block-rbd-3.0.0-1.fc29.x86_64
qemu-vanilla-2.11.2+git.0982a56a55-13.1.x86_64
kata-runtime-1.4.0+git.21f0059-15.1.x86_64
qemu-ui-sdl-3.0.0-1.fc29.x86_64
qemu-block-gluster-3.0.0-1.fc29.x86_64
qemu-lite-bin-2.11.0+git.f886228056-13.1.x86_64
kata-linux-container-4.14.67.17-11.1.x86_64
qemu-audio-sdl-3.0.0-1.fc29.x86_64
qemu-common-3.0.0-1.fc29.x86_64
kata-containers-image-1.4.0-10.1.x86_64
qemu-audio-alsa-3.0.0-1.fc29.x86_64
libvirt-daemon-driver-qemu-4.7.0-1.fc29.x86_64
qemu-ui-gtk-3.0.0-1.fc29.x86_64
kata-proxy-1.4.0+git.e1856c2-11.1.x86_64
kata-shim-bin-1.4.0+git.b02868b-9.1.x86_64
qemu-block-ssh-3.0.0-1.fc29.x86_64

**Comment by devimc** [comment]
@avekceeb thanks for raising this, we'll take a look asap :sweat_smile:

**Comment by devimc** [comment]
Hi @avekceeb 

I tried with qemu tip (https://github.com/qemu/qemu) with next configuration 

```
$ ./configure --disable-bluez --disable-brlapi --disable-docs --disable-curses --disable-gtk --disable-opengl --disable-sdl --disable-spice --disable-vte --disable-vnc --disable-vnc-jpeg --disable-vnc-png --disable-vnc-sasl --disable-fdt --disable-glusterfs --disable-libiscsi --disable-libnfs --disable-libssh2 --disable-bzip2 --disable-lzo --disable-snappy --disable-seccomp --disable-tpm --disable-slirp --disable-libusb --disable-usb-redir --disable-tcg --disable-uuid --disable-debug-tcg --disable-tcg-interpreter --disable-qom-cast-debug --disable-tcmalloc --disable-curl --disable-rdma --disable-tools --disable-xen --disable-linux-aio --enable-kvm --enable-vhost-net --enable-rbd --enable-virtfs --enable-attr --enable-cap-ng --target-list=x86_64-softmmu --extra-cflags=" -O3 -fno-semantic-interposition -falign-functions=32 -D_FORTIFY_SOURCE=2 -fPIE" --extra-ldflags=" -pie -z noexecstack -z relro -z now" --prefix=/opt/qemu --libdir=/opt/qemu/lib/qemu-lite --libexecdir=/opt/qemu/libexec/qemu-lite --datadir=/opt/qemu/share/qemu-lite
```

```
$ docker run -dti --runtime=kata-runtime debian bash
$ ps aux | grep qemu
root     17443 13.7  1.1 3270408 187148 ?      Sl   11:00   0:01 /opt/qemu/bin/qemu-system-x86_64 -name sandbox-a6a7d2a855a9c3253f4c94a6f4be52a43ce8dee44486570dfed8775895eadce5 -uuid 53e4ef81-ab6b-428a-abd5-072dafe3299d -machine pc,accel=kvm,kernel_irqchip,nvdimm -cpu host -qmp unix:/run/vc/vm/a6a7d2a855a9c3253f4c94a6f4be52a43ce8dee44486570dfed8775895eadce5/qmp.sock,server,nowait -m 2048M,slots=10,maxmem=16940M -device pci-bridge,bus=pci.0,id=pci-bridge-0,chassis_nr=1,shpc=on,addr=2,romfile= -device virtio-serial-pci,id=serial0,romfile= -device virtconsole,chardev=charconsole0,id=console0 -chardev socket,id=charconsole0,path=/run/vc/vm/a6a7d2a855a9c3253f4c94a6f4be52a43ce8dee44486570dfed8775895eadce5/console.sock,server,nowait -device nvdimm,id=nv0,memdev=mem0 -object memory-backend-file,id=mem0,mem-path=/home/juliomon/go/src/github.com/kata-containers/osbuilder/kata-containers.img,size=134217728 -device virtio-scsi-pci,id=scsi0,romfile= -object rng-random,id=rng0,filename=/dev/urandom -device virtio-rng,rng=rng0,romfile= -device virtserialport,chardev=charch0,id=channel0,name=agent.channel.0 -chardev socket,id=charch0,path=/run/vc/vm/a6a7d2a855a9c3253f4c94a6f4be52a43ce8dee44486570dfed8775895eadce5/kata.sock,server,nowait -device virtio-9p-pci,fsdev=extra-9p-kataShared,mount_tag=kataShared,romfile= -fsdev local,id=extra-9p-kataShared,path=/run/kata-containers/shared/sandboxes/a6a7d2a855a9c3253f4c94a6f4be52a43ce8dee44486570dfed8775895eadce5,security_model=none -netdev tap,id=network-0,vhost=on,vhostfds=3,fds=4 -device driver=virtio-net-pci,netdev=network-0,mac=02:42:ac:11:00:02,mq=on,vectors=4,romfile= -global kvm-pit.lost_tick_policy=discard -vga none -no-user-config -nodefaults -nographic -daemonize -kernel /usr/share/kata-containers/vmlinuz-4.14.67.container -append tsc=reliable no_timer_check rcupdate.rcu_expedited=1 i8042.direct=1 i8042.dumbkbd=1 i8042.nopnp=1 i8042.noaux=1 noreplace-smp reboot=k console=hvc0 console=hvc1 iommu=off cryptomgr.notests net.ifnames=0 pci=lastbus=0 root=/dev/pmem0p1 rootflags=dax,data=ordered,errors=remount-ro rw rootfstype=ext4 debug systemd.show_status=true systemd.log_level=debug panic=1 nr_cpus=8 init=/usr/lib/systemd/systemd systemd.unit=kata-containers.target systemd.mask=systemd-networkd.service systemd.mask=systemd-networkd.socket agent.log=debug -smp 1,cores=1,threads=1,sockets=1,maxcpus=8
```

probably this is a problem with fedora package, could you confirm that qemu tip works for you?

**Comment by avekceeb** [comment]
Thank you!
Indeed, current qemu git don't produce this error:
/opt/qemu/bin/qemu-system-x86_64 -version
QEMU emulator version 3.0.93 (v3.1.0-rc3-12-g933cc4bb34)
... while this one from official rpm does:
/usr/bin/qemu-system-x86_64 -version
QEMU emulator version 3.0.0 (qemu-3.0.0-1.fc29)
```
docker kill vm # this happens on killing
ls -l /var/spool/abrt
drwxr-x---. 3 root abrt 4096 Dec  4 13:23 ccpp-2018-12-04-13:23:42.968856-15412
```
cgroups: unable to remove paths /sys/fs/cgroup/systemd/kata/8ec520150cb7595c38839792d34c356435898e34f6dcc765c3e3266633960d67, and so on ... and so on...

So, most probably, this is not Kata's problem.
But, anyway, why SIGABRT was sent?
I assume that is was sent by Kata. Is it kinda 'last resort' measure when vm's status is 'unknown'?

Thanks!

**Comment by devimc** [comment]
@avekceeb 
> Indeed, current qemu git don't produce this error:

thanks

> I assume that it was sent by Kata. Is it kinda 'last resort' measure when vm's status is 'unknown'?

nop, kata uses qmp quit or SIGKILL, never SIGABRT

**Comment by avekceeb** [comment]
OK, Thank you.
Smth has been broken b/w qemu 3.0 and 3.1-rc...
Closing.
