### ISSUE TITLE
[RFC] bump supported qemu version

### ISSUE THREAD

**Issue by bergwolf** [kata-containers/runtime#993]
QEMU has released v3.0.0 and v2.12.1 yet we are still sticking with `2.11.0`. I'm wondering if/when we are going to bump supported qemu version. FWIW, the new releases includes many features and improvements. For details, please see https://wiki.qemu.org/ChangeLog/2.12 and https://wiki.qemu.org/ChangeLog/3.0.

**Comment by grahamwhaley** [comment]
we should definitely.... **test** 3.0.0 ;-) first...

**Comment by bergwolf** [comment]
Agreed @sboeuf and @grahamwhaley. We definitely need to test and validate before really bumping. Let's target at `3.0.0`.
